// Azure-Lily FC layer wrapper (single dsp_mac, serial N-output schedule)
// Generated by gen_azurelily_fc_wrapper.py — K=512, N=128
//
// CLB activation LUT: yes (saturation absorbed inside dsp_mac accum)
// Architecture: pure 4-wide int_sop_4 dsp_mac (Phase 6A canonical).
//
// Cycle model (per AL FC inference at this K, N):
//   feed_load     = PACKED_K = 128 cycles  (S_LOAD: write input SRAM)
//   compute_total = N * (PACKED_K + 3) = 128 * 131 = 16768 cycles
//                   per-output: 2 SRAM-prime + PACKED_K dsp valid + 1 out_valid latch
//   output_drain  = N = 128 cycles                (S_OUTPUT: stream data_out)
//   reduction+act = 0 cycles                       (none, sequential accum in dsp_mac)

`timescale 1ns / 1ps

module azurelily_fc_512_128 #(
    parameter DATA_WIDTH = 40
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid,
    input  wire                    ready_n,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg  [DATA_WIDTH-1:0]   data_out,
    output wire                    ready,
    output reg                     valid_n
);
    localparam K_INPUT  = 512;
    localparam N_OUTPUT = 128;
    localparam EPW      = 4;
    localparam PACKED_K = 128;

    // ---------------- Input SRAM ----------------
    reg  [7:0] i_w_addr;
    reg  [7:0] i_r_addr;
    wire                    i_w_en;
    wire [DATA_WIDTH-1:0]   i_sram_out;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(129))
        i_sram (.clk(clk), .rst(rst), .w_en(i_w_en),
                .r_addr(i_r_addr), .w_addr(i_w_addr),
                .sram_data_in(data_in), .sram_data_out(i_sram_out));

    // ---------------- Weight BRAM ----------------
    // Pre-loaded by TB hierarchical writes; w_en tied off in module.
    reg  [14:0] w_w_addr;  // unused at runtime, present for hier init
    reg  [14:0] w_r_addr;
    wire [DATA_WIDTH-1:0]   w_bram_out;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(16385))
        w_bram (.clk(clk), .rst(rst), .w_en(1'b0),
                .r_addr(w_r_addr), .w_addr(w_w_addr),
                .sram_data_in({DATA_WIDTH{1'b0}}), .sram_data_out(w_bram_out));

    // ---------------- Output SRAM ----------------
    reg  [7:0] o_w_addr;
    reg  [7:0] o_r_addr;
    reg                     o_w_en;
    wire [DATA_WIDTH-1:0]   dsp_data_out;
    wire                    dsp_out_valid;
    wire [DATA_WIDTH-1:0]   o_sram_out;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(129))
        o_sram (.clk(clk), .rst(rst), .w_en(o_w_en),
                .r_addr(o_r_addr), .w_addr(o_w_addr),
                .sram_data_in(dsp_data_out), .sram_data_out(o_sram_out));

    // ---------------- FSM ----------------
    localparam S_IDLE    = 3'd0;
    localparam S_LOAD    = 3'd1;
    localparam S_COMPUTE = 3'd2;
    localparam S_OUTPUT  = 3'd3;
    localparam S_DONE    = 3'd4;
    reg [2:0] state;
    reg [7:0] mac_count;   // 0..PACKED_K+1 within current output
    reg [7:0] out_count;   // current output index 0..N-1

    // dsp_mac valid gated to mac_count in [2, PACKED_K+1] (2-cyc SRAM prime)
    wire dsp_valid_gate = (state == S_COMPUTE)
                        && (mac_count >= 2)
                        && (mac_count <= PACKED_K + 1);
    assign i_w_en = (state == S_LOAD) && valid;

    dsp_mac #(.DATA_WIDTH(DATA_WIDTH), .K(PACKED_K)) dsp_inst (
        .clk(clk), .rst(rst),
        .valid(dsp_valid_gate),
        .ready_n(1'b0),
        .data_a(i_sram_out),
        .data_b(w_bram_out),
        .data_out(dsp_data_out),
        .ready(),
        .valid_n(dsp_out_valid)
    );

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state     <= S_IDLE;
            i_w_addr  <= 0;
            i_r_addr  <= 0;
            w_w_addr  <= 0;
            w_r_addr  <= 0;
            o_w_addr  <= 0;
            o_r_addr  <= 0;
            o_w_en    <= 0;
            mac_count <= 0;
            out_count <= 0;
            data_out  <= 0;
            valid_n   <= 0;
        end else begin
            o_w_en  <= 0;
            valid_n <= 0;
            case (state)
                S_IDLE: if (valid) state <= S_LOAD;
                S_LOAD: begin
                    if (valid) begin
                        if (i_w_addr == PACKED_K - 1) begin
                            state     <= S_COMPUTE;
                            i_w_addr  <= 0;
                            mac_count <= 0;
                            out_count <= 0;
                            i_r_addr  <= 0;
                            w_r_addr  <= 0;
                        end else begin
                            i_w_addr <= i_w_addr + 1;
                        end
                    end
                end
                S_COMPUTE: begin
                    if (mac_count < PACKED_K + 2) begin
                        // Set SRAM read addresses one cycle ahead so sram_out
                        // is settled when dsp_valid_gate samples it.
                        i_r_addr  <= mac_count;
                        w_r_addr  <= out_count * PACKED_K + mac_count;
                        mac_count <= mac_count + 1;
                    end
                    if (dsp_out_valid) begin
                        // dsp_mac just produced one accumulated result.
                        o_w_en   <= 1;
                        o_w_addr <= out_count;
                        if (out_count == N_OUTPUT - 1) begin
                            state     <= S_OUTPUT;
                            out_count <= 0;
                            o_r_addr  <= 0;
                            mac_count <= 0;
                        end else begin
                            out_count <= out_count + 1;
                            mac_count <= 0;  // reset for next output
                            i_r_addr  <= 0;
                        end
                    end
                end
                S_OUTPUT: begin
                    // Drain output SRAM, one int8-saturated value per cycle.
                    if (!ready_n) begin
                        data_out <= o_sram_out;
                        valid_n  <= 1;
                        if (o_r_addr == N_OUTPUT - 1) begin
                            state <= S_DONE;
                        end else begin
                            o_r_addr <= o_r_addr + 1;
                        end
                    end
                end
                S_DONE: begin
                    valid_n <= 0;
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    assign ready = (state == S_IDLE) || (state == S_LOAD);

endmodule
