"""Generate Azure-Lily FC wrappers using parallel-output dsp_macs (streaming).

The Azure-Lily FC architecture for AH-track verification (post-streaming refactor):

    valid in stream  ──► Input SRAM (depth PACKED_K, lockstep write/read)
                              │
                              │ broadcast a packed K-word per cycle
                              ▼
                  ┌──────────────────────────────────────────┐
                  │  N parallel dsp_mac instances            │
                  │  (each holds 1 output column's K-words)  │
                  │  All fire on the same input stream;      │
                  │  Each has its own weight slice from a    │
                  │  shared w_bram (depth = N*PACKED_K).     │
                  └──────────────────────────────────────────┘
                              │
                              │ N int8 output bytes/row, all latched
                              │ in the same cycle (PACKED_K +3 latency)
                              ▼
                       Output FIFO ─► drain stream (1 byte/cyc)

Streaming model (matches sim's gemm_dsp(M=N_tokens, K, N) at N parallel DSPs):
    - Compute steady-state: 1 row per PACKED_K cycles.
    - Drain steady-state: 1 row per N cycles (1 byte/cyc).
    - Per-row bottleneck: max(PACKED_K, N) cycles.
    - For M streamed rows: M × max(PACKED_K, N) + initial fill (PACKED_K + 3) +
      tail drain (N) cycles.

Backward compatibility (T1 single-row case):
    - Hierarchical preload paths are preserved:
        * dut.i_sram.mem[0..PACKED_K-1]
        * dut.w_bram.mem[0..N*PACKED_K-1]
        * dut.g_out[i].dsp_inst (per-output dsp_mac instance)
    - The unified S_STREAM state handles single-row T1 mode by transitioning
      to S_DONE once the lone row's drain completes.

Generated module name: ``azurelily_fc_<K>_<N>``.

Stage model (per row, parallel-output):
  feed       : input load from data_in stream → input SRAM (PACKED_K cyc)
  compute    : (PACKED_K + 3) cyc latency for FIRST row
               (2 SRAM-prime + PACKED_K dsp.valid + 1 latch).
               Subsequent rows are pipelined every PACKED_K cyc.
  output     : N cycles per row (drain output FIFO 1 int8/cyc)
  reduction  : 0 (no reduction tree)
  activation : 0 (saturation absorbed inside dsp_mac accum)

Resource cost vs. previous one-shot (3 dsp_macs total Q/K/V):
  N dsp_mac instances per arm × 3 arms = 3N total.
  For attention head (K=128, N=64): 192 dsp_macs total.

Usage:
    python gen_azurelily_fc_wrapper.py --K 512 --N 128 \\
           --output-dir fc_verification/rtl/azurelily/
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

EPW_DSP = 4   # 4 int8 pairs per dsp_mac cycle (pure int_sop_4)
EPW_OUT = 5   # 5 int8 bytes packed per output valid_n cycle (matches downstream q_buf EPW)
DATA_WIDTH = 40


def gen_azurelily_fc_wrapper(K: int, N: int, output_dir: Path) -> Path:
    PACKED_K = math.ceil(K / EPW_DSP)
    PACKED_N = math.ceil(N / EPW_OUT)  # output drain takes PACKED_N cyc per row (5 bytes/cyc packed)
    module_name = f"azurelily_fc_{K}_{N}"

    # Address widths.
    i_addr_w = max(1, math.ceil(math.log2(PACKED_K + 1)))
    w_addr_w = max(1, math.ceil(math.log2(N * PACKED_K + 1)))
    o_addr_w = max(1, math.ceil(math.log2(N + 1)))
    mac_count_w = max(1, math.ceil(math.log2(PACKED_K + 4)))
    drain_idx_w = max(1, math.ceil(math.log2(PACKED_N + 1)))
    # FIFO depth for streaming: drain rate (PACKED_N cyc/row) <= compute
    # rate (PACKED_K cyc/row) for D_HEAD <= EPW_OUT * PACKED_K (always true
    # for our configs).  So drain catches up immediately, and at most one
    # row is in flight in the FIFO.  Use FIFO_ROWS=4 for slack against
    # off-by-one timing.
    FIFO_ROWS = 4  # row buffer depth

    rtl = f"""// Azure-Lily FC layer wrapper — streaming + N-parallel-output dsp_macs
// Generated by gen_azurelily_fc_wrapper.py — K={K}, N={N}
//
// CLB activation LUT: yes (saturation absorbed inside dsp_mac accum)
// Architecture: N parallel dsp_macs (Phase 6A canonical pure 4-wide int_sop_4),
//               unified S_STREAM with overlapping compute/drain.
//
// Streaming cycle model (per AL FC at this K, N):
//   feed_load     = PACKED_K = {PACKED_K} cycles  (S_LOAD_FIRST: fill row 0)
//   compute       = PACKED_K + 3 = {PACKED_K + 3} cycles latency for first row
//                   (2 SRAM-prime + PACKED_K dsp.valid + 1 latch).
//                   Subsequent rows pipelined every PACKED_K cyc.
//   output_drain  = PACKED_N = ceil(N/{EPW_OUT}) = {PACKED_N} cycles per row
//                   (each valid_n cycle emits {EPW_OUT} packed int8 bytes
//                    in data_out[39:0]).
//   reduction+act = 0 cycles
//
// Streaming throughput: per-row = max(PACKED_K, PACKED_N) cycles.
//   For M streamed rows: M × max(PACKED_K, PACKED_N) + (PACKED_K + 3) startup
//   + tail drain = (M-1) × max(PACKED_K, PACKED_N) + (PACKED_K + 3) +
//   PACKED_N total cyc.

`timescale 1ns / 1ps

module {module_name} #(
    parameter DATA_WIDTH = {DATA_WIDTH}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid,
    input  wire                    ready_n,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg  [DATA_WIDTH-1:0]   data_out,
    output wire                    ready,
    output reg                     valid_n
);
    localparam K_INPUT  = {K};
    localparam N_OUTPUT = {N};
    localparam EPW      = {EPW_DSP};
    localparam PACKED_K = {PACKED_K};
    localparam EPW_O    = {EPW_OUT};      // output packing rate (5 bytes/cyc)
    localparam PACKED_N = {PACKED_N};     // ceil(N/EPW_O) packed words/row drained
    localparam FIFO_ROWS = {FIFO_ROWS};

    // ---------------- Input SRAM (single buffer, depth PACKED_K + 1) ----------------
    // For T1 single-row: TB hierarchically preloads i_sram.mem[0..PACKED_K-1]
    //   and forces state directly into S_COMPUTE.
    // For streaming: input bytes are cycled into mem[0..PACKED_K-1] in
    //   lockstep with the dsp read cadence (i_w_addr matches mac_count
    //   modulo PACKED_K).  The 1-cycle SRAM-read delay ensures dsp reads
    //   the previous row's byte before the new row's overwrite commits.
    reg  [{i_addr_w - 1}:0] i_w_addr;
    reg  [{i_addr_w - 1}:0] i_r_addr;
    wire                    i_w_en;
    wire [DATA_WIDTH-1:0]   i_sram_out;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH({PACKED_K + 1}))
        i_sram (.clk(clk), .rst(rst), .w_en(i_w_en),
                .r_addr(i_r_addr), .w_addr(i_w_addr),
                .sram_data_in(data_in), .sram_data_out(i_sram_out));

    // ---------------- Weight BRAM ----------------
    // Single sram instance with depth = N * PACKED_K.  Preloaded by TB
    // hierarchical writes (dut.w_bram.mem[output_idx*PACKED_K + k]).
    // Each dsp_mac instance reads its own slice via combinational
    // hierarchical references (w_bram.mem[oi*PACKED_K + i_r_addr]).
    reg  [{w_addr_w - 1}:0] w_w_addr;  // unused at runtime (hier preload only)
    reg  [{w_addr_w - 1}:0] w_r_addr;  // unused at runtime
    wire [DATA_WIDTH-1:0]   w_bram_out_unused;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH({N * PACKED_K + 1}))
        w_bram (.clk(clk), .rst(rst), .w_en(1'b0),
                .r_addr(w_r_addr), .w_addr(w_w_addr),
                .sram_data_in({{DATA_WIDTH{{1'b0}}}}), .sram_data_out(w_bram_out_unused));

    // ---------------- Output FIFO (FIFO_ROWS × N entries) ----------------
    // Stores latched rows pending serial drain.  Rows flow into the FIFO
    // from dsp_macs (parallel write at end of each compute window) and
    // exit serially (1 byte/cycle from data_out).  Depth FIFO_ROWS=2 is
    // sufficient because the head/TB gates new compute when the FIFO is
    // full, and at most 1 row is being drained at any time.
    reg  [DATA_WIDTH-1:0] o_mem [0:FIFO_ROWS*{N} + 1];
    reg  [{drain_idx_w - 1}:0] o_r_pkidx;     // current packed-EPW_O index 0..PACKED_N-1
    reg  [2:0]              o_drain_row;      // 0..FIFO_ROWS-1 row being drained
    reg  [2:0]              o_compute_row;    // 0..FIFO_ROWS-1 row to write next
    reg  [2:0]              o_count;          // 0..FIFO_ROWS rows in flight

    // ---------------- Per-output dsp_mac generate-loop ----------------
    // N parallel dsp_mac instances; each handles 1 output column.
    // All share the same input stream (i_sram_out) and the same dsp valid
    // gate.  Weight inputs are sliced from w_bram.mem combinationally.
    wire [DATA_WIDTH-1:0] dsp_data_out [0:{N - 1}];
    wire                  dsp_out_valid_arr [0:{N - 1}];
    wire dsp_valid_gate;

    genvar oi;
    generate
        for (oi = 0; oi < {N}; oi = oi + 1) begin : g_out
            wire [DATA_WIDTH-1:0] w_slice;
            // Combinational read from w_bram's named memory.  iverilog
            // accepts hierarchical reads from a child module's reg array.
            assign w_slice = w_bram.mem[oi * PACKED_K + i_r_addr];
            dsp_mac #(.DATA_WIDTH(DATA_WIDTH), .K(PACKED_K)) dsp_inst (
                .clk(clk), .rst(rst),
                .valid(dsp_valid_gate),
                .ready_n(1'b0),
                .data_a(i_sram_out),
                .data_b(w_slice),
                .data_out(dsp_data_out[oi]),
                .ready(),
                .valid_n(dsp_out_valid_arr[oi])
            );
        end
    endgenerate

    // ---------------- FSM ----------------
    localparam S_IDLE         = 3'd0;
    localparam S_LOAD_FIRST   = 3'd1;
    localparam S_COMPUTE      = 3'd2;  // unified compute + drain (streaming)
    localparam S_DONE         = 3'd3;
    reg [2:0] state;
    reg [{mac_count_w - 1}:0] mac_count;   // 0..PACKED_K+1 within current row's compute
    reg                       drain_active;  // 1 when a row's drain is in progress
    reg                       started;       // 1 after first dsp_out_valid (compute fired)
    // When `i_sram_preloaded` is set, the current row's full byte set is
    // already present in i_sram (T1 mode after force, or after S_LOAD_FIRST
    // completes the first row).  Then mac_count can advance unconditionally
    // through the K+2 cycles of compute.  For streaming, this flag is set
    // when a complete row's bytes have been written and cleared on row latch.
    reg                       i_sram_full;

    // dsp valid: gated for the 2-cycle SRAM prime at the very start of
    // S_COMPUTE (mac_count<2).  Once gating fires, dsp_macs run continuously
    // — they internally count mac_count modulo K and auto-fire on each row.
    //
    // For T1 mode (single-row, valid=0 throughout compute), dsp_valid_gate
    // must NOT depend on `valid` — i_sram is pre-loaded and dsp_macs
    // consume it without new input.  For streaming mode, the FSM advances
    // mac_count regardless of valid, but the head guarantees `valid` stays
    // high while data is flowing (back-pressure handled at the head's
    // `q_fc_ready` interface).  Here dsp_valid_gate is purely position-
    // gated within the row (mac_count window).
    assign dsp_valid_gate = (state == S_COMPUTE)
                          && (mac_count >= 2)
                          && (mac_count <= PACKED_K + 1);

    // i_sram is written when the head supplies new bytes (`valid=1`).
    // i_w_addr cycles 0..PACKED_K-1.  Streaming relies on the head to
    // pace input at the FC's compute rate (PACKED_K cyc/row); the FC's
    // drain is faster (PACKED_N ≤ PACKED_K when D_HEAD ≤ EPW_O × PACKED_K),
    // so the FIFO never overflows.
    wire fifo_has_room = (o_count < FIFO_ROWS[2:0]);  // observable, but
                                                       // not used to gate i_w_en.
    assign i_w_en = ((state == S_LOAD_FIRST) ||
                     (state == S_COMPUTE)) && valid;

    integer oi_idx;
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state            <= S_IDLE;
            i_w_addr         <= 0;
            i_r_addr         <= 0;
            w_w_addr         <= 0;
            w_r_addr         <= 0;
            mac_count        <= 0;
            data_out         <= 0;
            valid_n          <= 0;
            drain_active     <= 0;
            started          <= 0;
            o_r_pkidx        <= 0;
            o_drain_row      <= 0;
            o_compute_row    <= 0;
            o_count          <= 0;
            for (oi_idx = 0; oi_idx <= FIFO_ROWS*{N}; oi_idx = oi_idx + 1)
                o_mem[oi_idx] <= 0;
        end else begin
            valid_n <= 0;
            case (state)
                S_IDLE: begin
                    if (valid) begin
                        state    <= S_LOAD_FIRST;
                        i_w_addr <= 1;          // wrote mem[0] this cycle
                        i_r_addr <= 0;
                    end
                end
                S_LOAD_FIRST: begin
                    if (valid) begin
                        if (i_w_addr == PACKED_K - 1) begin
                            state            <= S_COMPUTE;
                            i_w_addr         <= 0;
                            mac_count        <= 0;
                            i_r_addr         <= 0;
                        end else begin
                            i_w_addr <= i_w_addr + 1;
                        end
                    end
                end
                S_COMPUTE: begin
                    // ── Input load ──
                    // Write next row's bytes to i_sram[i_w_addr] when the
                    // head supplies valid input.  In T1 mode (preloaded
                    // i_sram), valid=0 and i_w_en stays low (no overwrite).
                    if (i_w_en) begin
                        if (i_w_addr == PACKED_K - 1) begin
                            i_w_addr <= 0;
                        end else begin
                            i_w_addr <= i_w_addr + 1;
                        end
                    end

                    // ── dsp read cadence ──
                    // mac_count cycles 0..PACKED_K+1 (with 2-cyc SRAM prime).
                    // Advances unconditionally for the first 2 cycles of a
                    // row (SRAM prime — works both in T1 with preloaded
                    // i_sram and in streaming after first row done) and
                    // when valid=1 mid-row (streaming, fresh data arriving).
                    // For T1, valid=0 and i_sram is full → mac_count
                    // advances unconditionally.
                    if (mac_count < PACKED_K + 2) begin
                        i_r_addr  <= mac_count;
                        mac_count <= mac_count + 1;
                    end else if (valid) begin
                        // Resume after idling: head has new bytes, restart.
                        mac_count <= 0;
                        i_r_addr  <= 0;
                    end

                    // ── Capture latched outputs ──
                    if (dsp_out_valid_arr[0]) begin
                        // Write all N outputs into the FIFO row at
                        // o_compute_row.
                        for (oi_idx = 0; oi_idx < {N}; oi_idx = oi_idx + 1) begin
                            o_mem[o_compute_row * {N} + oi_idx] <= dsp_data_out[oi_idx];
                        end
                        o_compute_row <= (o_compute_row == FIFO_ROWS - 1) ? 0
                                                                          : o_compute_row + 1;
                        o_count       <= o_count + 1;
                        started       <= 1;
                        // Reset mac_count/i_r_addr for next row when more
                        // streaming input is coming (`valid=1`).  In T1
                        // mode (`valid=0`), leave mac_count frozen so
                        // dsp_macs idle.
                        if (valid) begin
                            mac_count <= 0;
                            i_r_addr  <= 0;
                        end
                    end

                    // ── Drain (concurrent with compute) ──
                    // Drain EPW_O packed int8 bytes per cycle: per cycle
                    // assemble {{o_mem[base+4], o_mem[base+3], ...,
                    // o_mem[base]}} (low byte first) into data_out[39:0].
                    // base = o_drain_row * N + o_r_pkidx * EPW_O.
                    // PACKED_N cycles per row.  Final word may have
                    // fewer than EPW_O valid bytes (zero-padded).
                    if (!drain_active && o_count > 0) begin
                        drain_active <= 1;
                        o_r_pkidx    <= 0;
                    end
                    if (drain_active && !ready_n) begin : drain_emit
                        reg [DATA_WIDTH-1:0] packed_word;
                        integer base_b;
                        integer slot;
                        base_b = o_drain_row * {N} + o_r_pkidx * EPW_O;
                        packed_word = {{DATA_WIDTH{{1'b0}}}};
                        for (slot = 0; slot < EPW_O; slot = slot + 1) begin
                            if ((base_b + slot) < ((o_drain_row + 1) * {N})) begin
                                packed_word[slot*8 +: 8] = o_mem[base_b + slot][7:0];
                            end
                        end
                        data_out <= packed_word;
                        valid_n  <= 1;
                        if (o_r_pkidx == PACKED_N - 1) begin
                            // Done draining this row; advance.
                            drain_active <= 0;
                            o_r_pkidx    <= 0;
                            o_drain_row  <= (o_drain_row == FIFO_ROWS - 1) ? 0
                                                                           : o_drain_row + 1;
                            o_count      <= o_count - 1;
                        end else begin
                            o_r_pkidx <= o_r_pkidx + 1;
                        end
                    end

                    // ── Termination ──
                    // No premature termination here.  Stay in S_COMPUTE so
                    // the latch + drain logic continues to run for any
                    // in-flight rows.  Termination is performed in S_DONE
                    // when valid drops AND all rows have fully drained.
                    if (started && !valid && o_count == 0 && !drain_active
                        && mac_count >= PACKED_K + 2) begin
                        // dsp_macs idle (mac_count frozen), no rows pending
                        // in FIFO, no drain in progress, and no new input
                        // → safe to halt.
                        state <= S_DONE;
                    end
                end
                S_DONE: begin
                    // Continue draining any rows that latched after the
                    // S_DONE transition (race with dsp_macs producing a
                    // late dsp_out_valid).  Use the same drain path.
                    if (dsp_out_valid_arr[0]) begin
                        for (oi_idx = 0; oi_idx < {N}; oi_idx = oi_idx + 1) begin
                            o_mem[o_compute_row * {N} + oi_idx] <= dsp_data_out[oi_idx];
                        end
                        o_compute_row <= (o_compute_row == FIFO_ROWS - 1) ? 0
                                                                          : o_compute_row + 1;
                        o_count <= o_count + 1;
                    end
                    if (!drain_active && o_count > 0) begin
                        drain_active <= 1;
                        o_r_pkidx    <= 0;
                    end
                    if (drain_active && !ready_n) begin : drain_emit_done
                        reg [DATA_WIDTH-1:0] packed_word;
                        integer base_b;
                        integer slot;
                        base_b = o_drain_row * {N} + o_r_pkidx * EPW_O;
                        packed_word = {{DATA_WIDTH{{1'b0}}}};
                        for (slot = 0; slot < EPW_O; slot = slot + 1) begin
                            if ((base_b + slot) < ((o_drain_row + 1) * {N})) begin
                                packed_word[slot*8 +: 8] = o_mem[base_b + slot][7:0];
                            end
                        end
                        data_out <= packed_word;
                        valid_n  <= 1;
                        if (o_r_pkidx == PACKED_N - 1) begin
                            drain_active <= 0;
                            o_r_pkidx    <= 0;
                            o_drain_row  <= (o_drain_row == FIFO_ROWS - 1) ? 0
                                                                           : o_drain_row + 1;
                            o_count      <= o_count - 1;
                        end else begin
                            o_r_pkidx <= o_r_pkidx + 1;
                        end
                    end
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    assign ready = (state == S_IDLE) || (state == S_LOAD_FIRST) ||
                   (state == S_COMPUTE && fifo_has_room);

endmodule
"""

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{module_name}.v"
    out_path.write_text(rtl)

    feed_cyc = PACKED_K
    compute_cyc = PACKED_K + 3
    output_cyc = PACKED_N  # packed drain (EPW_OUT bytes/cyc)
    total = feed_cyc + compute_cyc + output_cyc
    steady = max(PACKED_K, PACKED_N)
    print(f"  Generated {module_name}.v "
          f"(K={K}, N={N}, PACKED_K={PACKED_K}, PACKED_N={PACKED_N}, "
          f"feed={feed_cyc}, compute={compute_cyc}, output={output_cyc}, "
          f"total_single_row={total} cyc, "
          f"streaming_steady=max(PACKED_K, PACKED_N)={steady} cyc/row)")
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Azure-Lily FC (parallel-output dsp_mac) wrappers for AH-track verification"
    )
    parser.add_argument("--K", type=int, required=True, help="Input dim")
    parser.add_argument("--N", type=int, required=True, help="Output dim")
    parser.add_argument("--output-dir", type=Path, default=Path("."),
                        help="Output directory (default: cwd)")
    args = parser.parse_args()
    gen_azurelily_fc_wrapper(args.K, args.N, args.output_dir)
