#!/usr/bin/env python3
"""Generate P-replica GEMM wrapper for Round 2 DSP+CLB replacement sweep.

Instantiates P copies of the single-replica fc_top module (generated by
gen_gemv_wrappers.py) with broadcast data_in and round-robin output collection.

Usage:
    python gen_gemm_wrapper.py --rows 512 --cols 128 --K 2048 --N 256 --P 5 \
        --output-dir ../dse/rtl/
"""

import argparse
import math
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

# Import the single-replica generator internals
from gen_gemv_wrappers import (
    _gen_fc_top,
    _gen_fc_layer,
    _gen_activation_lut_module,
    _get_supporting_modules,
)


def _gen_gemm_top(p: int, data_width: int = 40) -> str:
    """Generate the gemm_top module that wraps P copies of fc_top."""
    sel_width = max(1, math.ceil(math.log2(p))) if p > 1 else 1
    lines = []

    lines.append(f"module gemm_top #(")
    lines.append(f"    parameter DATA_WIDTH = {data_width},")
    lines.append(f"    parameter P = {p}")
    lines.append(f")(")
    lines.append(f"    input wire clk,")
    lines.append(f"    input wire rst,")
    lines.append(f"    input wire valid,")
    lines.append(f"    input wire ready_n,")
    lines.append(f"    input wire [DATA_WIDTH-1:0] data_in,")
    lines.append(f"    output wire [DATA_WIDTH-1:0] data_out,")
    lines.append(f"    output wire ready,")
    lines.append(f"    output wire valid_n")
    lines.append(f");")
    lines.append(f"")

    # Per-replica signals
    lines.append(f"    // Per-replica signals")
    for i in range(p):
        lines.append(f"    wire [DATA_WIDTH-1:0] rep{i}_data_out;")
        lines.append(f"    wire rep{i}_ready, rep{i}_valid_n;")
        lines.append(f"    reg  rep{i}_valid;")
    lines.append(f"")

    # Input distribution FSM
    lines.append(f"    // Input distribution: round-robin valid to replicas")
    lines.append(f"    reg [{sel_width}-1:0] in_sel;")
    lines.append(f"    always @(posedge clk or posedge rst) begin")
    lines.append(f"        if (rst)")
    lines.append(f"            in_sel <= 0;")
    lines.append(f"        else if (valid)")
    if p > 1:
        lines.append(f"            in_sel <= (in_sel == {sel_width}'d{p - 1}) ? "
                     f"0 : in_sel + 1;")
    else:
        lines.append(f"            in_sel <= 0;")
    lines.append(f"    end")
    lines.append(f"")

    # Demux valid signal
    lines.append(f"    // Demux valid to selected replica")
    lines.append(f"    always @(*) begin")
    for i in range(p):
        lines.append(f"        rep{i}_valid = 1'b0;")
    lines.append(f"        case (in_sel)")
    for i in range(p):
        lines.append(f"            {sel_width}'d{i}: rep{i}_valid = valid;")
    lines.append(f"            default: ;")
    lines.append(f"        endcase")
    lines.append(f"    end")
    lines.append(f"")

    # Instantiate P copies of fc_top — broadcast data_in
    lines.append(f"    // P replica instances of fc_top")
    for i in range(p):
        lines.append(f"    fc_top #(.DATA_WIDTH(DATA_WIDTH)) replica_{i} (")
        lines.append(f"        .clk(clk),")
        lines.append(f"        .rst(rst),")
        lines.append(f"        .valid(rep{i}_valid),")
        lines.append(f"        .ready_n(1'b1),")
        lines.append(f"        .data_in(data_in),")
        lines.append(f"        .data_out(rep{i}_data_out),")
        lines.append(f"        .ready(rep{i}_ready),")
        lines.append(f"        .valid_n(rep{i}_valid_n)")
        lines.append(f"    );")
        lines.append(f"")

    # Output collection: round-robin mux
    lines.append(f"    // Output collection: round-robin from replicas")
    lines.append(f"    reg [{sel_width}-1:0] out_sel;")
    lines.append(f"    always @(posedge clk or posedge rst) begin")
    lines.append(f"        if (rst)")
    lines.append(f"            out_sel <= 0;")
    if p > 1:
        lines.append(f"        else if (|{{" +
                     ", ".join(f"rep{i}_valid_n" for i in range(p)) +
                     f"}})")
        lines.append(f"            out_sel <= (out_sel == {sel_width}'d{p - 1}) ? "
                     f"0 : out_sel + 1;")
    lines.append(f"    end")
    lines.append(f"")

    # Output mux
    lines.append(f"    // Output data mux")
    lines.append(f"    reg [DATA_WIDTH-1:0] data_out_mux;")
    lines.append(f"    reg valid_n_mux;")
    lines.append(f"    always @(*) begin")
    lines.append(f"        data_out_mux = {data_width}'d0;")
    lines.append(f"        valid_n_mux = 1'b0;")
    lines.append(f"        case (out_sel)")
    for i in range(p):
        lines.append(f"            {sel_width}'d{i}: begin")
        lines.append(f"                data_out_mux = rep{i}_data_out;")
        lines.append(f"                valid_n_mux = rep{i}_valid_n;")
        lines.append(f"            end")
    lines.append(f"            default: ;")
    lines.append(f"        endcase")
    lines.append(f"    end")
    lines.append(f"")

    lines.append(f"    assign data_out = data_out_mux;")
    lines.append(f"    assign valid_n = valid_n_mux;")
    # Ready when any replica is ready to accept
    ready_expr = " | ".join(f"rep{i}_ready" for i in range(p))
    lines.append(f"    assign ready = {ready_expr};")
    lines.append(f"")
    lines.append(f"endmodule")

    return "\n".join(lines)


def gen_gemm_wrapper(k: int, n: int, rows: int, cols: int,
                     p: int, output_dir: str,
                     data_width: int = 40) -> Path:
    """Generate P-replica GEMM wrapper around fc_top.

    Returns path to the generated .v file.
    """
    v = math.ceil(k / rows)
    h = math.ceil(n / cols)
    total_dpes = p * v * h
    depth = max(512, k)
    addr_width = math.ceil(math.log2(depth)) if depth > 1 else 1
    acam_eligible = (v == 1)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"gemm_{k}_{n}_{rows}x{cols}_P{p}.v"
    out_path = out_dir / filename

    parts = []

    # Header
    parts.append(f"// Auto-generated GEMM P-replica wrapper")
    parts.append(f"// Workload: K={k}, N={n}, P={p} replicas")
    parts.append(f"// Crossbar: {rows}x{cols}")
    parts.append(f"// Per-replica: V={v}, H={h}, DPEs={v * h}")
    parts.append(f"// Total DPEs: {total_dpes}")
    parts.append(f"// ACAM eligible (V=1): {'yes' if acam_eligible else 'no'}")
    parts.append(f"// Generated by gen_gemm_wrapper.py")
    parts.append(f"")

    # gemm_top (new top-level)
    parts.append(f"// =====================================================")
    parts.append(f"// gemm_top — P-replica wrapper ({p} copies of fc_top)")
    parts.append(f"// =====================================================")
    parts.append(_gen_gemm_top(p, data_width))
    parts.append(f"")

    # fc_top module (single replica, reused P times)
    parts.append(f"// =====================================================")
    parts.append(f"// fc_top — single replica (instantiated {p} times)")
    parts.append(f"// =====================================================")
    parts.append(_gen_fc_top(v, h, k, n, rows, cols, depth, addr_width,
                             data_width))
    parts.append(f"")

    # fc_layer module (only if not V=1 H=1)
    if not (v == 1 and h == 1):
        parts.append(f"// =====================================================")
        parts.append(f"// fc_layer — DPE stacking + reduction + activation")
        parts.append(f"// =====================================================")
        parts.append(_gen_fc_layer(v, h, k, n, rows, cols, depth, addr_width,
                                   data_width))
        parts.append(f"")

    # activation_lut module (only if V > 1)
    if v > 1:
        parts.append(f"// =====================================================")
        parts.append(f"// activation_lut — piecewise-linear tanh approximation")
        parts.append(f"// =====================================================")
        parts.append(_gen_activation_lut_module())
        parts.append(f"")

    # Supporting modules
    parts.append(f"// =====================================================")
    parts.append(f"// Supporting modules (from gemv_1_channel.v)")
    parts.append(f"// =====================================================")
    parts.append(_get_supporting_modules())
    parts.append(f"")

    out_path.write_text("\n".join(parts))
    print(f"  Generated {filename} (K={k}, N={n}, P={p}, "
          f"V={v}, H={h}, total_DPEs={total_dpes})")
    return out_path


# ── CLI ───────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate P-replica GEMM wrapper for Round 2 DSE"
    )
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument("--cols", type=int, required=True)
    parser.add_argument("--K", type=int, required=True, help="Input dimension")
    parser.add_argument("--N", type=int, required=True, help="Output dimension")
    parser.add_argument("--P", type=int, required=True, help="Number of replicas")
    parser.add_argument("--output-dir", type=str, default=".",
                        help="Output directory")

    args = parser.parse_args()
    gen_gemm_wrapper(args.K, args.N, args.rows, args.cols, args.P,
                     args.output_dir)
