#!/usr/bin/env python3
"""Generator for BERT-Tiny DPE-independent CLB modules.

Generates three pure-CLB Verilog modules that have no dependency on DPE config (R, C):
  1. residual_add  — element-wise add of two tensors
  2. embedding_add — 3-way element-wise add (token + position + segment)
  3. layernorm     — per-token LayerNorm with mean, variance, rsqrt LUT, normalize

All modules follow the project's valid/ready handshake convention and include
an inline sram module for standalone synthesis.

Usage:
    python nl_dpe/gen_bert_clb_modules.py [--out_dir dse/rtl/bert_tiny]
"""

import argparse
import math
from pathlib import Path


# ---------------------------------------------------------------------------
# Shared: inline SRAM module (from attention_head_1_channel.v:1489-1518)
# ---------------------------------------------------------------------------
def _sram_module():
    return """\
module sram #(
    parameter N_CHANNELS = 1,
    parameter DATA_WIDTH = 40 * N_CHANNELS,
    parameter DEPTH      = 512
)(
    input  wire                       clk,
    input  wire                       w_en,
    input  wire                       rst,
    input  wire [$clog2(DEPTH)-1:0]   r_addr,
    input  wire [$clog2(DEPTH)-1:0]   w_addr,
    input  wire [DATA_WIDTH-1:0]      sram_data_in,
    output reg  [DATA_WIDTH-1:0]      sram_data_out
);
    reg [DATA_WIDTH-1:0] mem [DEPTH-1:0];

    always @(posedge clk) begin
        if (rst)
            sram_data_out <= {DATA_WIDTH{1'b0}};
        else
            sram_data_out <= mem[r_addr];
    end

    always @(posedge clk) begin
        if (w_en)
            mem[w_addr] <= sram_data_in;
    end
endmodule
"""


# ---------------------------------------------------------------------------
# Module 1: residual_add
# ---------------------------------------------------------------------------
def gen_residual_add(depth=128, data_width=40):
    """Element-wise add of two seq_len*d_model streams.

    FSM: S_LOAD (buffer first operand into SRAM) -> S_ADD (stream second, add, output).
    """
    addr_w = max(1, math.ceil(math.log2(depth)))
    return f"""\
// Auto-generated residual_add module
// Element-wise add of two tensors (DEPTH={depth} elements)
// Pure CLB: 1 SRAM + 1 adder + 2-state FSM
// Generated by gen_bert_clb_modules.py

module residual_add #(
    parameter DATA_WIDTH = {data_width},
    parameter DEPTH      = {depth}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid,
    input  wire                    ready_n,
    input  wire [DATA_WIDTH-1:0]  data_in,
    output reg  [DATA_WIDTH-1:0]  data_out,
    output wire                    ready,
    output wire                    valid_n
);

    localparam ADDR_WIDTH = {addr_w};

    // FSM
    localparam S_IDLE = 2'd0;
    localparam S_LOAD = 2'd1;
    localparam S_ADD  = 2'd2;

    reg [1:0] state, next_state;

    // SRAM for first operand
    reg                      sram_w_en;
    reg  [ADDR_WIDTH-1:0]    sram_w_addr;
    reg  [ADDR_WIDTH-1:0]    sram_r_addr;
    wire [DATA_WIDTH-1:0]    sram_out;

    sram #(
        .N_CHANNELS(1),
        .DATA_WIDTH(DATA_WIDTH),
        .DEPTH(DEPTH)
    ) buf_a (
        .clk(clk),
        .rst(rst),
        .w_en(sram_w_en),
        .r_addr(sram_r_addr),
        .w_addr(sram_w_addr),
        .sram_data_in(data_in),
        .sram_data_out(sram_out)
    );

    // Registered add result (1-cycle latency from SRAM read)
    reg                      add_valid;
    reg  [ADDR_WIDTH-1:0]    add_addr;

    // FSM transitions
    always @(posedge clk or posedge rst) begin
        if (rst)
            state <= S_IDLE;
        else
            state <= next_state;
    end

    always @* begin
        next_state = state;
        case (state)
            S_IDLE: if (valid)                        next_state = S_LOAD;
            S_LOAD: if (sram_w_addr == DEPTH - 1)     next_state = S_ADD;
            S_ADD:  if (add_addr == DEPTH - 1 && add_valid) next_state = S_IDLE;
            default:                                   next_state = S_IDLE;
        endcase
    end

    // Datapath
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            sram_w_en   <= 1'b0;
            sram_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
            sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
            add_valid   <= 1'b0;
            add_addr    <= {{ADDR_WIDTH{{1'b0}}}};
            data_out    <= {{DATA_WIDTH{{1'b0}}}};
        end else begin
            case (state)
                S_IDLE: begin
                    sram_w_en   <= 1'b0;
                    sram_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    add_valid   <= 1'b0;
                    add_addr    <= {{ADDR_WIDTH{{1'b0}}}};
                    if (valid) begin
                        sram_w_en   <= 1'b1;
                        sram_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                S_LOAD: begin
                    sram_w_en <= valid;
                    if (valid) begin
                        sram_w_addr <= sram_w_addr + 1'b1;
                    end
                    if (sram_w_addr == DEPTH - 1) begin
                        // Transition: start reading from addr 0
                        sram_w_en   <= 1'b0;
                        sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                S_ADD: begin
                    sram_w_en <= 1'b0;
                    // Pipeline: SRAM read (cycle N) -> add + output (cycle N+1)
                    if (valid) begin
                        sram_r_addr <= sram_r_addr + 1'b1;
                    end
                    // Registered add: sram_out is available 1 cycle after r_addr
                    add_valid <= valid;
                    if (add_valid)
                        add_addr <= add_addr + 1'b1;
                    data_out <= $signed(sram_out) + $signed(data_in);
                end

                default: begin
                    sram_w_en <= 1'b0;
                    add_valid <= 1'b0;
                end
            endcase
        end
    end

    assign ready   = (state == S_LOAD && valid) || (state == S_ADD && valid) || (state == S_IDLE);
    assign valid_n = ~add_valid;

endmodule

{_sram_module()}
"""


# ---------------------------------------------------------------------------
# Module 2: embedding_add
# ---------------------------------------------------------------------------
def gen_embedding_add(depth=128, data_width=40):
    """3-way element-wise add: token + position + segment embeddings.

    FSM: S_LOAD_TOK -> S_LOAD_POS -> S_ADD (stream segment, read tok+pos, 2-stage add).
    """
    addr_w = max(1, math.ceil(math.log2(depth)))
    return f"""\
// Auto-generated embedding_add module
// 3-way element-wise add: token + position + segment (DEPTH={depth} elements)
// Pure CLB: 2 SRAMs + 2 adders + 3-state FSM
// Generated by gen_bert_clb_modules.py

module embedding_add #(
    parameter DATA_WIDTH = {data_width},
    parameter DEPTH      = {depth}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid,
    input  wire                    ready_n,
    input  wire [DATA_WIDTH-1:0]  data_in,
    output reg  [DATA_WIDTH-1:0]  data_out,
    output wire                    ready,
    output wire                    valid_n
);

    localparam ADDR_WIDTH = {addr_w};

    // FSM
    localparam S_IDLE     = 2'd0;
    localparam S_LOAD_TOK = 2'd1;
    localparam S_LOAD_POS = 2'd2;
    localparam S_ADD      = 2'd3;

    reg [1:0] state, next_state;

    // Token SRAM
    reg                      tok_w_en;
    reg  [ADDR_WIDTH-1:0]    tok_w_addr, tok_r_addr;
    wire [DATA_WIDTH-1:0]    tok_out;

    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(DEPTH)) sram_tok (
        .clk(clk), .rst(rst), .w_en(tok_w_en),
        .r_addr(tok_r_addr), .w_addr(tok_w_addr),
        .sram_data_in(data_in), .sram_data_out(tok_out)
    );

    // Position SRAM
    reg                      pos_w_en;
    reg  [ADDR_WIDTH-1:0]    pos_w_addr, pos_r_addr;
    wire [DATA_WIDTH-1:0]    pos_out;

    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(DEPTH)) sram_pos (
        .clk(clk), .rst(rst), .w_en(pos_w_en),
        .r_addr(pos_r_addr), .w_addr(pos_w_addr),
        .sram_data_in(data_in), .sram_data_out(pos_out)
    );

    // Pipeline registers
    reg                      pipe1_valid;
    reg  [DATA_WIDTH-1:0]    pipe1_seg;        // segment value delayed 1 cycle
    reg  [DATA_WIDTH-1:0]    pipe1_tok_pos;    // tok + pos (stage 1)
    reg                      pipe2_valid;
    reg  [ADDR_WIDTH-1:0]    out_addr;

    // FSM transitions
    always @(posedge clk or posedge rst) begin
        if (rst)
            state <= S_IDLE;
        else
            state <= next_state;
    end

    always @* begin
        next_state = state;
        case (state)
            S_IDLE:     if (valid)                        next_state = S_LOAD_TOK;
            S_LOAD_TOK: if (tok_w_addr == DEPTH - 1)      next_state = S_LOAD_POS;
            S_LOAD_POS: if (pos_w_addr == DEPTH - 1)      next_state = S_ADD;
            S_ADD:      if (out_addr == DEPTH - 1 && pipe2_valid) next_state = S_IDLE;
            default:                                       next_state = S_IDLE;
        endcase
    end

    // Datapath
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            tok_w_en    <= 1'b0;
            tok_w_addr  <= {{ADDR_WIDTH{{1'b0}}}};
            tok_r_addr  <= {{ADDR_WIDTH{{1'b0}}}};
            pos_w_en    <= 1'b0;
            pos_w_addr  <= {{ADDR_WIDTH{{1'b0}}}};
            pos_r_addr  <= {{ADDR_WIDTH{{1'b0}}}};
            pipe1_valid <= 1'b0;
            pipe1_seg   <= {{DATA_WIDTH{{1'b0}}}};
            pipe1_tok_pos <= {{DATA_WIDTH{{1'b0}}}};
            pipe2_valid <= 1'b0;
            out_addr    <= {{ADDR_WIDTH{{1'b0}}}};
            data_out    <= {{DATA_WIDTH{{1'b0}}}};
        end else begin
            case (state)
                S_IDLE: begin
                    tok_w_en   <= 1'b0;
                    tok_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    pos_w_en   <= 1'b0;
                    pos_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    tok_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    pos_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    pipe1_valid <= 1'b0;
                    pipe2_valid <= 1'b0;
                    out_addr    <= {{ADDR_WIDTH{{1'b0}}}};
                    if (valid) begin
                        tok_w_en   <= 1'b1;
                        tok_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                S_LOAD_TOK: begin
                    tok_w_en <= valid;
                    if (valid)
                        tok_w_addr <= tok_w_addr + 1'b1;
                    pos_w_en <= 1'b0;
                    if (tok_w_addr == DEPTH - 1) begin
                        tok_w_en   <= 1'b0;
                        pos_w_en   <= 1'b1;
                        pos_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                S_LOAD_POS: begin
                    tok_w_en <= 1'b0;
                    pos_w_en <= valid;
                    if (valid)
                        pos_w_addr <= pos_w_addr + 1'b1;
                    if (pos_w_addr == DEPTH - 1) begin
                        pos_w_en   <= 1'b0;
                        tok_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                        pos_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                S_ADD: begin
                    tok_w_en <= 1'b0;
                    pos_w_en <= 1'b0;
                    // Cycle 0: drive r_addr, capture segment
                    if (valid) begin
                        tok_r_addr <= tok_r_addr + 1'b1;
                        pos_r_addr <= pos_r_addr + 1'b1;
                    end
                    // Cycle 1: SRAM outputs valid, compute tok + pos
                    pipe1_valid   <= valid;
                    pipe1_seg     <= data_in;
                    pipe1_tok_pos <= $signed(tok_out) + $signed(pos_out);
                    // Cycle 2: add segment
                    pipe2_valid <= pipe1_valid;
                    data_out    <= $signed(pipe1_tok_pos) + $signed(pipe1_seg);
                    if (pipe2_valid)
                        out_addr <= out_addr + 1'b1;
                end

                default: begin
                    tok_w_en    <= 1'b0;
                    pos_w_en    <= 1'b0;
                    pipe1_valid <= 1'b0;
                    pipe2_valid <= 1'b0;
                end
            endcase
        end
    end

    assign ready   = (state == S_LOAD_TOK) || (state == S_LOAD_POS) || (state == S_ADD) || (state == S_IDLE);
    assign valid_n = ~pipe2_valid;

endmodule

{_sram_module()}
"""


# ---------------------------------------------------------------------------
# Module 3: layernorm
# ---------------------------------------------------------------------------
def gen_layernorm(d_model=128, data_width=40):
    """Per-token LayerNorm: y = (x - mean) * rsqrt(var) * gamma + beta.

    5-stage FSM per token: LOAD -> MEAN -> VARIANCE -> RSQRT -> NORMALIZE.
    SRAM read 3 times (mean accumulation, variance accumulation, normalize output).

    Multiplications use explicit 'multiply' DSP primitive (27x27) to prevent
    VTR from mapping wide multiplies to DPE hard blocks.
    """
    addr_w = max(1, math.ceil(math.log2(d_model)))
    log2_d = int(math.log2(d_model))  # for divide-by-d_model via right shift
    acc_w = 2 * data_width
    # DSP multiply width: 27x27 -> 54 (largest fixed-point mode in arch)
    mult_w = 27
    prod_w = 2 * mult_w  # 54

    # Build rsqrt LUT entries (priority encoder, DATA_WIDTH bits)
    rsqrt_entries = []
    for i in range(data_width):
        msb_pos = data_width - 1 - i
        shift = msb_pos // 2
        rsqrt_approx = 1 << (data_width - 1 - shift)
        pattern = "0" * i + "1" + "?" * (data_width - 1 - i)
        rsqrt_entries.append((pattern, rsqrt_approx))

    rsqrt_cases = ""
    for pattern, val in rsqrt_entries:
        rsqrt_cases += f"            {data_width}'b{pattern}: rsqrt_val = {data_width}'d{val};\n"

    return f"""\
// Auto-generated layernorm module
// Per-token LayerNorm over D_MODEL={d_model} elements
// Pure CLB + DSP: 1 SRAM + accumulator + 2x explicit DSP multiply (27x27) + rsqrt LUT
// FSM: LOAD -> MEAN -> VARIANCE -> RSQRT -> NORMALIZE (repeats per token)
// Multiplies use explicit 'multiply' primitive to force DSP mapping (not DPE).
// Generated by gen_bert_clb_modules.py

module layernorm #(
    parameter DATA_WIDTH = {data_width},
    parameter D_MODEL    = {d_model}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid,
    input  wire                    ready_n,
    input  wire [DATA_WIDTH-1:0]  data_in,
    output reg  [DATA_WIDTH-1:0]  data_out,
    output wire                    ready,
    output wire                    valid_n
);

    localparam ADDR_WIDTH = {addr_w};
    localparam ACC_WIDTH  = {acc_w};
    localparam LOG2_D     = {log2_d};
    localparam MULT_W     = {mult_w};
    localparam PROD_W     = {prod_w};

    // FSM states
    localparam S_IDLE      = 3'd0;
    localparam S_LOAD      = 3'd1;
    localparam S_MEAN      = 3'd2;
    localparam S_VARIANCE  = 3'd3;
    localparam S_RSQRT     = 3'd4;
    localparam S_NORMALIZE = 3'd5;
    localparam S_DRAIN     = 3'd6;

    reg [2:0] state, next_state;

    // SRAM: stores one token (d_model elements), read 3 times
    reg                      sram_w_en;
    reg  [ADDR_WIDTH-1:0]    sram_w_addr, sram_r_addr;
    wire [DATA_WIDTH-1:0]    sram_out;

    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(D_MODEL)) token_buf (
        .clk(clk), .rst(rst), .w_en(sram_w_en),
        .r_addr(sram_r_addr), .w_addr(sram_w_addr),
        .sram_data_in(data_in), .sram_data_out(sram_out)
    );

    // Accumulator (reused for mean and variance)
    reg signed [ACC_WIDTH-1:0] accumulator;

    // Computed statistics (held for one token)
    reg signed [DATA_WIDTH-1:0] mean_val;
    reg        [DATA_WIDTH-1:0] rsqrt_val_reg;

    // Counters
    reg [ADDR_WIDTH-1:0] elem_count;

    // ========================================================================
    // Explicit DSP multiply primitives (27x27 -> 54)
    // Prevents VTR from mapping wide multiplies to DPE hard blocks.
    // Two multipliers: var_mult (diff²) and norm_mult (diff * rsqrt)
    // ========================================================================

    // Variance multiplier: diff * diff (truncated to 27 bits)
    reg  [MULT_W-1:0] var_mult_a, var_mult_b;
    wire [PROD_W-1:0] var_mult_out;

    multiply var_dsp (
        .a(var_mult_a),
        .b(var_mult_b),
        .out(var_mult_out)
    );

    // Normalize multiplier: diff * rsqrt_val (truncated to 27 bits)
    reg  [MULT_W-1:0] norm_mult_a, norm_mult_b;
    wire [PROD_W-1:0] norm_mult_out;

    multiply norm_dsp (
        .a(norm_mult_a),
        .b(norm_mult_b),
        .out(norm_mult_out)
    );

    // Normalize pipeline registers
    reg signed [DATA_WIDTH-1:0]  norm_pipe1_diff;
    reg                           norm_pipe1_valid;
    reg signed [PROD_W-1:0]      norm_pipe2_product;
    reg                           norm_pipe2_valid;
    reg                           norm_pipe3_valid;
    reg [1:0]                     drain_count;

    // rsqrt LUT (priority encoder — same pattern as reciprocal in attention_head)
    reg [DATA_WIDTH-1:0] rsqrt_val;
    wire [DATA_WIDTH-1:0] var_upper = accumulator[ACC_WIDTH-1:DATA_WIDTH];

    always @* begin
        casez (var_upper)
{rsqrt_cases}            default: rsqrt_val = {{DATA_WIDTH{{1'b1}}}};
        endcase
    end

    // FSM transitions
    always @(posedge clk or posedge rst) begin
        if (rst)
            state <= S_IDLE;
        else
            state <= next_state;
    end

    always @* begin
        next_state = state;
        case (state)
            S_IDLE:      if (valid)                           next_state = S_LOAD;
            S_LOAD:      if (sram_w_addr == D_MODEL - 1)      next_state = S_MEAN;
            S_MEAN:      if (elem_count == D_MODEL - 1)        next_state = S_VARIANCE;
            S_VARIANCE:  if (elem_count == D_MODEL - 1)        next_state = S_RSQRT;
            S_RSQRT:                                           next_state = S_NORMALIZE;
            S_NORMALIZE: if (elem_count == D_MODEL - 1)        next_state = S_DRAIN;
            S_DRAIN:     if (drain_count == 2'd2)              next_state = S_IDLE;
            default:                                           next_state = S_IDLE;
        endcase
    end

    // Datapath
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            sram_w_en       <= 1'b0;
            sram_w_addr     <= {{ADDR_WIDTH{{1'b0}}}};
            sram_r_addr     <= {{ADDR_WIDTH{{1'b0}}}};
            accumulator     <= {{ACC_WIDTH{{1'b0}}}};
            mean_val        <= {{DATA_WIDTH{{1'b0}}}};
            rsqrt_val_reg   <= {{DATA_WIDTH{{1'b0}}}};
            elem_count      <= {{ADDR_WIDTH{{1'b0}}}};
            var_mult_a      <= {{MULT_W{{1'b0}}}};
            var_mult_b      <= {{MULT_W{{1'b0}}}};
            norm_mult_a     <= {{MULT_W{{1'b0}}}};
            norm_mult_b     <= {{MULT_W{{1'b0}}}};
            norm_pipe1_diff  <= {{DATA_WIDTH{{1'b0}}}};
            norm_pipe1_valid <= 1'b0;
            norm_pipe2_product <= {{PROD_W{{1'b0}}}};
            norm_pipe2_valid <= 1'b0;
            norm_pipe3_valid <= 1'b0;
            drain_count      <= 2'd0;
            data_out         <= {{DATA_WIDTH{{1'b0}}}};
        end else begin
            case (state)
                // ---- IDLE: reset for next token ----
                S_IDLE: begin
                    sram_w_en    <= 1'b0;
                    sram_w_addr  <= {{ADDR_WIDTH{{1'b0}}}};
                    sram_r_addr  <= {{ADDR_WIDTH{{1'b0}}}};
                    accumulator  <= {{ACC_WIDTH{{1'b0}}}};
                    elem_count   <= {{ADDR_WIDTH{{1'b0}}}};
                    norm_pipe1_valid <= 1'b0;
                    norm_pipe2_valid <= 1'b0;
                    norm_pipe3_valid <= 1'b0;
                    drain_count  <= 2'd0;
                    if (valid) begin
                        sram_w_en   <= 1'b1;
                        sram_w_addr <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                // ---- LOAD: stream d_model elements into SRAM ----
                S_LOAD: begin
                    sram_w_en <= valid;
                    if (valid)
                        sram_w_addr <= sram_w_addr + 1'b1;
                    if (sram_w_addr == D_MODEL - 1) begin
                        sram_w_en   <= 1'b0;
                        sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                        accumulator <= {{ACC_WIDTH{{1'b0}}}};
                        elem_count  <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                // ---- MEAN: accumulate sum, then right-shift to get mean ----
                S_MEAN: begin
                    sram_w_en <= 1'b0;
                    sram_r_addr <= sram_r_addr + 1'b1;
                    accumulator <= accumulator + {{{{(ACC_WIDTH-DATA_WIDTH){{sram_out[DATA_WIDTH-1]}}}}, sram_out}};
                    elem_count  <= elem_count + 1'b1;
                    if (elem_count == D_MODEL - 1) begin
                        mean_val    <= accumulator[DATA_WIDTH-1+LOG2_D:LOG2_D];
                        accumulator <= {{ACC_WIDTH{{1'b0}}}};
                        sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                        elem_count  <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                // ---- VARIANCE: accumulate (x - mean)^2 via DSP multiply ----
                S_VARIANCE: begin
                    sram_r_addr <= sram_r_addr + 1'b1;
                    elem_count  <= elem_count + 1'b1;
                    begin : var_block
                        reg signed [DATA_WIDTH-1:0] diff;
                        diff = $signed(sram_out) - $signed(mean_val);
                        // Truncate diff to MULT_W bits for DSP multiply
                        var_mult_a <= diff[MULT_W-1:0];
                        var_mult_b <= diff[MULT_W-1:0];
                    end
                    // Accumulate DSP product (var_mult_out is combinational)
                    accumulator <= accumulator + {{{{(ACC_WIDTH-PROD_W){{var_mult_out[PROD_W-1]}}}}, var_mult_out}};
                    if (elem_count == D_MODEL - 1) begin
                        sram_r_addr <= {{ADDR_WIDTH{{1'b0}}}};
                        elem_count  <= {{ADDR_WIDTH{{1'b0}}}};
                    end
                end

                // ---- RSQRT: lookup rsqrt(variance) in 1 cycle ----
                S_RSQRT: begin
                    rsqrt_val_reg <= rsqrt_val;
                    sram_r_addr   <= {{ADDR_WIDTH{{1'b0}}}};
                    elem_count    <= {{ADDR_WIDTH{{1'b0}}}};
                end

                // ---- NORMALIZE: y = (x - mean) * rsqrt_val via DSP multiply ----
                S_NORMALIZE: begin
                    sram_r_addr <= sram_r_addr + 1'b1;
                    elem_count  <= elem_count + 1'b1;

                    // Pipeline stage 1: diff = x - mean, feed DSP
                    norm_pipe1_diff  <= $signed(sram_out) - $signed(mean_val);
                    norm_pipe1_valid <= 1'b1;
                    norm_mult_a      <= norm_pipe1_diff[MULT_W-1:0];
                    norm_mult_b      <= rsqrt_val_reg[MULT_W-1:0];

                    // Pipeline stage 2: capture DSP product
                    norm_pipe2_product <= norm_mult_out;
                    norm_pipe2_valid   <= norm_pipe1_valid;

                    // Pipeline stage 3: truncate to DATA_WIDTH and output
                    data_out         <= norm_pipe2_product[PROD_W-2:PROD_W-1-DATA_WIDTH];
                    norm_pipe3_valid <= norm_pipe2_valid;

                    if (elem_count == D_MODEL - 1) begin
                        norm_pipe1_valid <= 1'b0;
                    end
                end

                // ---- DRAIN: flush pipeline (2 extra cycles) ----
                S_DRAIN: begin
                    drain_count <= drain_count + 1'b1;
                    // Stage 2
                    norm_mult_a      <= norm_pipe1_diff[MULT_W-1:0];
                    norm_mult_b      <= rsqrt_val_reg[MULT_W-1:0];
                    norm_pipe2_product <= norm_mult_out;
                    norm_pipe2_valid   <= norm_pipe1_valid;
                    norm_pipe1_valid   <= 1'b0;
                    // Stage 3
                    data_out         <= norm_pipe2_product[PROD_W-2:PROD_W-1-DATA_WIDTH];
                    norm_pipe3_valid <= norm_pipe2_valid;
                    if (drain_count == 2'd2)
                        norm_pipe3_valid <= 1'b0;
                end

                default: begin
                    sram_w_en        <= 1'b0;
                    norm_pipe1_valid <= 1'b0;
                    norm_pipe2_valid <= 1'b0;
                    norm_pipe3_valid <= 1'b0;
                end
            endcase
        end
    end

    assign ready   = (state == S_LOAD) || (state == S_IDLE);
    assign valid_n = ~norm_pipe3_valid;

endmodule

{_sram_module()}
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Generate BERT-Tiny CLB modules")
    parser.add_argument("--out_dir", type=str, default="dse/rtl/bert_tiny",
                        help="Output directory for generated Verilog files")
    parser.add_argument("--d_model", type=int, default=128,
                        help="Model hidden dimension (default: 128)")
    parser.add_argument("--data_width", type=int, default=40,
                        help="Data bus width (default: 40)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate all three modules
    modules = {
        "residual_add.v": gen_residual_add(depth=args.d_model, data_width=args.data_width),
        "embedding_add.v": gen_embedding_add(depth=args.d_model, data_width=args.data_width),
        "layernorm.v": gen_layernorm(d_model=args.d_model, data_width=args.data_width),
    }

    for fname, verilog in modules.items():
        path = out_dir / fname
        path.write_text(verilog)
        print(f"Generated {path} ({len(verilog)} bytes)")


if __name__ == "__main__":
    main()
