#!/usr/bin/env python3
"""Generate VTR-compatible Verilog wrapper files for GEMV and FC layers.

GEMV mode (default): generates bare GEMV wrappers by string-substituting
K/N/ROWS/COLS in gemv_1_channel.v.

FC mode (--fc): uses Python-generates-Verilog approach to emit concrete
Verilog with explicit DPE instantiations, adder trees, and activation
for arbitrary (V,H) tilings needed by the DSE sweep.

Usage:
    python gen_gemv_wrappers.py                          # generate all 5 GEMV shapes
    python gen_gemv_wrappers.py --run-vtr                # generate + run VTR for all shapes
    python gen_gemv_wrappers.py --fc --rows 256 --cols 256 --output-dir ../dse/rtl/
"""

import argparse
import math
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
GEMV_SRC = SCRIPT_DIR / "gemv_1_channel.v"

# 5 GEMV shapes from paper_questions.md
# Naming: gemv_{M}_{K}_{N} where M=1 (single vector), K=input dim, N=output dim
SHAPES = {
    "1_64_64":     (64,   64),
    "1_512_128":   (512,  128),
    "1_2048_256":  (2048, 256),
    "1_256_512":   (256,  512),
    "1_512_512":   (512,  512),
}

# 5 FC workloads for DSE
FC_WORKLOADS = {
    "fc_64_64":    (64,   64),
    "fc_512_128":  (512,  128),
    "fc_2048_256": (2048, 256),
    "fc_256_512":  (256,  512),
    "fc_512_512":  (512,  512),
}


def gen_wrapper(name: str, k: int, n: int, rows: int = 256, cols: int = 256) -> Path:
    """Generate a self-contained .v wrapper for a specific GEMV shape."""
    # Read the full gemv source
    src = GEMV_SRC.read_text()

    # Replace the default parameters in the top-level gemv module
    # Original: parameter K = 64, ... parameter N = 64, ...
    modified = src.replace(
        "parameter K = 64,           // Input dimension (rows of W)",
        f"parameter K = {k},           // Input dimension (rows of W)",
    ).replace(
        "parameter N = 64,           // Output dimension (cols of W)",
        f"parameter N = {n},           // Output dimension (cols of W)",
    ).replace(
        "parameter ROWS = 256,       // Crossbar rows (Q1 sweep: 128, 256, 512)",
        f"parameter ROWS = {rows},       // Crossbar rows (Q1 sweep: 128, 256, 512)",
    ).replace(
        "parameter COLS = 256,       // Crossbar cols (Q1 sweep: 128, 256, 512)",
        f"parameter COLS = {cols},       // Crossbar cols (Q1 sweep: 128, 256, 512)",
    )

    # Compute expected DPE count
    v = math.ceil(k / rows)
    h = math.ceil(n / cols)
    dpes = v * h

    header = f"""// Auto-generated GEMV wrapper: {name} (K={k}, N={n})
// Crossbar: {rows}x{cols}, Tiling: V={v} H={h}, DPEs={dpes}
// Generated by gen_gemv_wrappers.py
"""

    out_path = SCRIPT_DIR / f"gemv_{name}.v"
    out_path.write_text(header + modified)
    print(f"  Generated {out_path.name} (K={k}, N={n}, V={v}, H={h}, DPEs={dpes})")
    return out_path


# ---------------------------------------------------------------------------
# Supporting module extraction from gemv_1_channel.v
# ---------------------------------------------------------------------------
def _extract_modules(src_text: str) -> dict:
    """Extract module definitions from Verilog source, keyed by module name.

    Returns dict mapping module_name -> full text (from 'module ...' to
    'endmodule' inclusive).
    """
    modules = {}
    lines = src_text.splitlines(keepends=True)
    current_name = None
    current_lines = []
    for line in lines:
        m = re.match(r'^module\s+(\w+)', line)
        if m:
            current_name = m.group(1)
            current_lines = [line]
        elif current_name is not None:
            current_lines.append(line)
            if re.match(r'^endmodule', line):
                modules[current_name] = "".join(current_lines)
                current_name = None
                current_lines = []
    return modules


def _get_supporting_modules() -> str:
    """Return concatenated text for supporting modules extracted from
    gemv_1_channel.v.
    """
    src = GEMV_SRC.read_text()
    all_mods = _extract_modules(src)

    needed = [
        "conv_layer_single_dpe",
        "conv_controller",
        "sram",
        "global_controller",
        "controller_scalable",
        "xbar_ip_module",
    ]
    parts = []
    for name in needed:
        if name in all_mods:
            parts.append(all_mods[name])
        else:
            print(f"  WARNING: module '{name}' not found in {GEMV_SRC.name}")
    result = "\n\n".join(parts)
    # Fix $clog2(1)=0 issue: controller_scalable uses $clog2(N_DPE_V) which
    # produces 0-width vectors when N_DPE_V=1. Patch to minimum width of 1.
    result = result.replace(
        "localparam N_DPE_SEL_V = $clog2(N_DPE_V);",
        "localparam N_DPE_SEL_V = (N_DPE_V > 1) ? $clog2(N_DPE_V) : 1;"
    )
    return result


# ---------------------------------------------------------------------------
# FC Verilog generation (Python-generates-Verilog)
# ---------------------------------------------------------------------------

def _gen_activation_lut_module() -> str:
    """Generate the activation_lut module definition (piecewise-linear tanh)."""
    return """\
module activation_lut #(
    parameter DATA_WIDTH = 40
)(
    input wire clk,
    input wire [DATA_WIDTH-1:0] data_in,
    output reg [DATA_WIDTH-1:0] data_out
);
    // Saturation to int8 range [-128, 127]
    always @(posedge clk) begin
        if ($signed(data_in) > $signed(127))
            data_out <= 127;
        else if ($signed(data_in) < $signed(-128))
            data_out <= -128;
        else
            data_out <= data_in;
    end
endmodule"""


def _gen_adder_tree(v: int, input_prefix: str, output_name: str,
                    data_width: int = 40, wire_prefix: str = "") -> str:
    """Generate a binary adder tree reducing *v* inputs to one output.

    *input_prefix* is the wire name prefix; inputs are
    ``{input_prefix}_0`` ... ``{input_prefix}_{v-1}``.
    *wire_prefix* is prepended to all internal wire names to avoid
    collisions when multiple adder trees exist in the same module (H>1).

    Returns wire declarations + assign statements as a single string block.
    """
    if v == 1:
        return f"    assign {output_name} = {input_prefix}_0;\n"

    pfx = f"{wire_prefix}_" if wire_prefix else ""
    lines = []
    current_names = [f"{input_prefix}_{i}" for i in range(v)]
    current_width = data_width
    level = 0

    while len(current_names) > 1:
        next_names = []
        next_width = current_width + 1
        pairs = len(current_names) // 2
        odd = len(current_names) % 2

        for p in range(pairs):
            a = current_names[2 * p]
            b = current_names[2 * p + 1]
            sname = f"{pfx}sum_L{level}_{p}"
            lines.append(f"    wire signed [{next_width - 1}:0] {sname};")
            lines.append(
                f"    assign {sname} = $signed({a}) + $signed({b});"
            )
            next_names.append(sname)

        if odd:
            last = current_names[-1]
            pname = f"{pfx}pass_L{level}"
            lines.append(f"    wire signed [{next_width - 1}:0] {pname};")
            # Sign-extend: replicate MSB. Avoid $signed()[bit] which Parmys rejects.
            lines.append(
                f"    assign {pname} = {{{{{last}[{current_width - 1}]}}, {last}}};"
            )
            next_names.append(pname)

        current_names = next_names
        current_width = next_width
        level += 1

    # Truncate the final sum back to DATA_WIDTH
    final = current_names[0]
    lines.append(f"    // Truncate adder tree result to {data_width} bits")
    lines.append(f"    assign {output_name} = {final}[{data_width - 1}:0];")
    return "\n".join(lines) + "\n"


def _gen_fc_layer_v1_h1(k: int, n: int, rows: int, cols: int,
                         depth: int, addr_width: int,
                         data_width: int = 40) -> str:
    """V=1 H=1 — reuse conv_layer_single_dpe directly.  fc_layer is not
    needed; fc_top instantiates conv_layer_single_dpe."""
    return ""  # No separate fc_layer module needed


def _gen_fc_layer(v: int, h: int, k: int, n: int, rows: int, cols: int,
                  depth: int, addr_width: int,
                  data_width: int = 40,
                  module_name: str = "fc_layer",
                  conversion: str = "acam",
                  dpe_data_width: int = 40,
                  elems_per_word: int = 5) -> str:
    """Generate the fc_layer module for arbitrary (V, H) tiling.

    The fc_layer contains:
      - 1 sram + 1 controller_scalable driving all DPEs
      - V*H dpe instantiations
      - Per-column adder tree (V inputs -> 1 output) if V > 1
      - Per-column activation_lut:
          ACAM: only if V > 1 (ACAM handles activation when V=1)
          ADC:  always (ADC gives raw output, no ACAM)
      - Horizontal concatenation of column outputs

    conversion: "acam" or "adc"
    dpe_data_width: DPE data_in/data_out pin width (16 or 40)
    """
    needs_clb_activation = (conversion == "adc") or (v > 1)
    total_dpes = v * h
    lines = []

    lines.append(f"module {module_name} #(")
    lines.append(f"    parameter DATA_WIDTH = {data_width}")
    lines.append(f")(")
    lines.append(f"    input wire clk,")
    lines.append(f"    input wire rst,")
    lines.append(f"    input wire valid,")
    lines.append(f"    input wire ready_n,")
    lines.append(f"    input wire [DATA_WIDTH-1:0] data_in,")
    lines.append(f"    output wire [DATA_WIDTH-1:0] data_out,")
    lines.append(f"    output wire ready,")
    lines.append(f"    output wire valid_n")
    lines.append(f");")
    lines.append(f"")
    lines.append(f"    localparam V = {v};")
    lines.append(f"    localparam H = {h};")
    lines.append(f"    localparam DEPTH = {depth};")
    lines.append(f"    localparam ADDR_WIDTH = {addr_width};")
    lines.append(f"")

    # ── Input demux: route packed words to correct row SRAM (V>1) ──────
    # Input arrives as a stream of packed words (elems_per_word int8s each).
    # First ceil(R/epw) words go to row 0, next ceil(R/epw) to row 1, etc.
    if v > 1:
        total_packed_words = math.ceil(k / elems_per_word)
        pw_bits = max(1, math.ceil(math.log2(total_packed_words)) if total_packed_words > 1 else 1)
        lines.append(f"    // Input demux: route packed words to per-row SRAMs")
        lines.append(f"    // ({elems_per_word} int8/word, {total_packed_words} words total)")
        lines.append(f"    reg [{pw_bits}-1:0] input_word_count;")
        lines.append(f"    always @(posedge clk or posedge rst) begin")
        lines.append(f"        if (rst) input_word_count <= 0;")
        lines.append(f"        else if (valid) input_word_count <= input_word_count + 1;")
        lines.append(f"    end")
        for row_i in range(v):
            lo = math.ceil(row_i * rows / elems_per_word)
            hi = math.ceil(min((row_i + 1) * rows, k) / elems_per_word) - 1
            lines.append(f"    wire valid_r{row_i} = valid && "
                         f"(input_word_count >= {lo}) && (input_word_count <= {hi});")
        lines.append(f"")

    # ── Per-row SRAM + Controller + DPEs (parallel loading) ──────────
    # Each vertical DPE row has its own SRAM and controller_scalable(N_DPE_V=1).
    # All rows load in parallel. This matches the nn/ simulator assumption.
    clog2_h = max(1, math.ceil(math.log2(h))) if h > 1 else 1

    for row in range(v):
        kw_row = min(k, rows) if row < v - 1 else k - row * rows  # elements for this tile
        packed_kw_row = math.ceil(kw_row / elems_per_word)  # packed word count
        sram_depth_row = max(512 // elems_per_word, packed_kw_row) + 1
        addr_width_row = max(1, math.ceil(math.log2(sram_depth_row)) if sram_depth_row > 1 else 1)

        lines.append(f"    // ── Row {row}: SRAM + controller + {h} DPEs "
                     f"(K_row={kw_row}, packed={packed_kw_row} words) ──")

        # Per-row wires
        lines.append(f"    wire [{dpe_data_width}-1:0] sram_data_out_r{row};")
        lines.append(f"    wire [{addr_width_row}-1:0] read_addr_r{row}, write_addr_r{row};")
        lines.append(f"    wire w_en_r{row}, w_buf_en_r{row};")
        lines.append(f"    wire [1:0] nl_dpe_control_r{row};")
        lines.append(f"    wire shift_add_control_r{row}, shift_add_bypass_r{row};")
        lines.append(f"    wire load_output_reg_r{row}, load_input_reg_r{row};")
        lines.append(f"    wire MSB_SA_Ready_r{row}, dpe_done_r{row};")
        lines.append(f"    wire shift_add_done_r{row}, shift_add_bypass_ctrl_r{row};")
        lines.append(f"    wire dpe_accum_done_r{row}, dpe_accum_ready_r{row};")
        lines.append(f"    wire ready_r{row}, valid_n_r{row};")
        lines.append(f"    wire [{h}-1:0] reg_empty_r{row};")
        if h > 1:
            lines.append(f"    wire [{clog2_h}-1:0] dpe_sel_h_r{row};")
        lines.append(f"")

        # SRAM (packed: DATA_WIDTH=dpe_data_width, each word holds elems_per_word int8s)
        lines.append(f"    sram #(.N_CHANNELS(1), .DEPTH({sram_depth_row}), "
                     f".DATA_WIDTH({dpe_data_width})) sram_r{row} (")
        lines.append(f"        .clk(clk), .rst(rst), .w_en(w_en_r{row}),")
        lines.append(f"        .r_addr(read_addr_r{row}), .w_addr(write_addr_r{row}),")
        lines.append(f"        .sram_data_in(data_in), .sram_data_out(sram_data_out_r{row})")
        lines.append(f"    );")
        lines.append(f"")

        # Controller (N_DPE_V=1: this controller drives one row of H DPEs)
        # KERNEL_WIDTH = packed word count (not element count)
        lines.append(f"    controller_scalable #(")
        lines.append(f"        .N_CHANNELS(1), .N_BRAM_R(1), .N_BRAM_W(1),")
        lines.append(f"        .N_DPE_V(1), .N_DPE_H({h}),")
        lines.append(f"        .ADDR_WIDTH({addr_width_row}), .N_KERNELS(1),")
        lines.append(f"        .KERNEL_WIDTH({packed_kw_row}), .KERNEL_HEIGHT(1),")
        lines.append(f"        .W(1), .H(1), .S(1)")
        lines.append(f"    ) ctrl_r{row} (")
        lines.append(f"        .clk(clk), .rst(rst),")
        lines.append(f"        .MSB_SA_Ready(MSB_SA_Ready_r{row}),")
        valid_sig = f"valid_r{row}" if v > 1 else "valid"
        lines.append(f"        .valid({valid_sig}), .ready_n(ready_n),")
        lines.append(f"        .dpe_done(dpe_done_r{row}),")
        lines.append(f"        .reg_full(reg_full_c0_r{row}),")  # N_DPE_V=1 → use first column's reg_full
        lines.append(f"        .reg_empty(reg_empty_r{row}),")
        lines.append(f"        .shift_add_done(shift_add_done_r{row}),")
        lines.append(f"        .shift_add_bypass_ctrl(shift_add_bypass_ctrl_r{row}),")
        lines.append(f"        .dpe_accum_done(dpe_accum_done_r{row}),")
        lines.append(f"        .read_address(read_addr_r{row}),")
        lines.append(f"        .write_address(write_addr_r{row}),")
        lines.append(f"        .w_en_dec(w_en_r{row}),")
        lines.append(f"        .w_buf_en(w_buf_en_r{row}),")
        lines.append(f"        .nl_dpe_control(nl_dpe_control_r{row}),")
        lines.append(f"        .shift_add_control(shift_add_control_r{row}),")
        lines.append(f"        .shift_add_bypass(shift_add_bypass_r{row}),")
        lines.append(f"        .load_output_reg(load_output_reg_r{row}),")
        lines.append(f"        .load_input_reg(load_input_reg_r{row}),")
        lines.append(f"        .dpe_sel(),")  # unused (N_DPE_V=1)
        lines.append(f"        .dpe_sel_h({f'dpe_sel_h_r{row}' if h > 1 else ''}),")
        lines.append(f"        .ready(ready_r{row}),")
        lines.append(f"        .valid_n(valid_n_r{row}),")
        lines.append(f"        .dpe_accum_ready(dpe_accum_ready_r{row})")
        lines.append(f"    );")
        re_bits = ", ".join("1'b0" for _ in range(h))
        lines.append(f"    assign reg_empty_r{row} = {{{re_bits}}};")
        lines.append(f"    assign dpe_accum_done_r{row} = dpe_done_r{row};")
        lines.append(f"")

        # DPE instances for this row (H columns)
        for col in range(h):
            lines.append(f"    wire [{dpe_data_width}-1:0] dpe_out_c{col}_r{row};")
            lines.append(f"    wire dpe_done_c{col}_r{row};")
            lines.append(f"    wire reg_full_c{col}_r{row};")
            lines.append(f"    wire shift_add_done_c{col}_r{row};")
            lines.append(f"    wire shift_add_bypass_ctrl_c{col}_r{row};")
            lines.append(f"    wire MSB_SA_Ready_c{col}_r{row};")
            lines.append(f"    dpe dpe_c{col}_r{row} (")
            lines.append(f"        .clk(clk), .reset(rst),")
            lines.append(f"        .data_in(sram_data_out_r{row}),")  # per-row SRAM
            lines.append(f"        .nl_dpe_control(nl_dpe_control_r{row}),")
            lines.append(f"        .shift_add_control(shift_add_control_r{row}),")
            lines.append(f"        .w_buf_en(w_buf_en_r{row}),")  # scalar (N_DPE_V=1)
            lines.append(f"        .shift_add_bypass(shift_add_bypass_r{row}),")
            lines.append(f"        .load_output_reg(load_output_reg_r{row}),")
            lines.append(f"        .load_input_reg(load_input_reg_r{row}),")
            lines.append(f"        .MSB_SA_Ready(MSB_SA_Ready_c{col}_r{row}),")
            lines.append(f"        .data_out(dpe_out_c{col}_r{row}),")
            lines.append(f"        .dpe_done(dpe_done_c{col}_r{row}),")
            lines.append(f"        .reg_full(reg_full_c{col}_r{row}),")
            lines.append(f"        .shift_add_done(shift_add_done_c{col}_r{row}),")
            lines.append(f"        .shift_add_bypass_ctrl(shift_add_bypass_ctrl_c{col}_r{row})")
            lines.append(f"    );")
            lines.append(f"")

        # Per-row aggregate signals
        done_r = " | ".join(f"dpe_done_c{c}_r{row}" for c in range(h))
        lines.append(f"    assign dpe_done_r{row} = {done_r};")
        sad_r = " & ".join(f"shift_add_done_c{c}_r{row}" for c in range(h))
        lines.append(f"    assign shift_add_done_r{row} = {sad_r};")
        sabp_r = " & ".join(f"shift_add_bypass_ctrl_c{c}_r{row}" for c in range(h))
        lines.append(f"    assign shift_add_bypass_ctrl_r{row} = {sabp_r};")
        msa_r = " & ".join(f"MSB_SA_Ready_c{c}_r{row}" for c in range(h))
        lines.append(f"    assign MSB_SA_Ready_r{row} = {msa_r};")
        lines.append(f"")

    # Global aggregate: ready when ALL rows are ready, valid when ALL rows valid
    lines.append(f"    // Global control: AND ready across rows, AND valid")
    lines.append(f"    assign ready = {' & '.join(f'ready_r{r}' for r in range(v))};")
    lines.append(f"    assign valid_n = {' & '.join(f'valid_n_r{r}' for r in range(v))};")
    # Global dpe_sel_h: use row 0's controller (all rows have identical H-sequencing)
    if h > 1:
        lines.append(f"    wire [{clog2_h}-1:0] dpe_sel_h;")
        lines.append(f"    assign dpe_sel_h = dpe_sel_h_r0;")
    lines.append(f"")

    # Per-column reduction (adder tree + activation if V > 1)
    col_result_wires = []
    for col in range(h):
        if v > 1:
            # Adder tree for this column
            tree_input_prefix = f"col{col}_dpe"
            tree_output = f"col{col}_sum"
            lines.append(f"    // Column {col} adder tree (V={v})")
            # Alias DPE outputs to tree input names (sign-extend if dpe_data_width < DATA_WIDTH)
            for r in range(v):
                lines.append(f"    wire signed [DATA_WIDTH-1:0] {tree_input_prefix}_{r};")
                if dpe_data_width < data_width:
                    pad = data_width - dpe_data_width
                    lines.append(f"    assign {tree_input_prefix}_{r} = "
                                 f"{{{{{pad}{{dpe_out_c{col}_r{r}[{dpe_data_width-1}]}}}}, "
                                 f"dpe_out_c{col}_r{r}}};")
                else:
                    lines.append(f"    assign {tree_input_prefix}_{r} = dpe_out_c{col}_r{r};")
            # Registered streaming reduction (pipelined with DPE serial output)
            lines.append(f"    reg signed [DATA_WIDTH-1:0] {tree_output}_reg;")
            if v == 2:
                # V=2: single registered add
                lines.append(f"    always @(posedge clk) begin")
                lines.append(f"        {tree_output}_reg <= $signed({tree_input_prefix}_0) "
                             f"+ $signed({tree_input_prefix}_1);")
                lines.append(f"    end")
            else:
                # V>2: cascaded registered adds (log2(V) stages)
                # Level 0: pairwise add with register
                prev_names = [f"{tree_input_prefix}_{r}" for r in range(v)]
                level = 0
                while len(prev_names) > 1:
                    next_names = []
                    lines.append(f"    // Reduction level {level}")
                    for p in range(len(prev_names) // 2):
                        sname = f"col{col}_reduc_L{level}_{p}"
                        lines.append(f"    reg signed [DATA_WIDTH-1:0] {sname};")
                        lines.append(f"    always @(posedge clk) "
                                     f"{sname} <= $signed({prev_names[2*p]}) "
                                     f"+ $signed({prev_names[2*p+1]});")
                        next_names.append(sname)
                    if len(prev_names) % 2:
                        # Odd element: register and pass through
                        sname = f"col{col}_reduc_L{level}_pass"
                        lines.append(f"    reg signed [DATA_WIDTH-1:0] {sname};")
                        lines.append(f"    always @(posedge clk) "
                                     f"{sname} <= $signed({prev_names[-1]});")
                        next_names.append(sname)
                    prev_names = next_names
                    level += 1
                # Final result → registered output
                lines.append(f"    always @(posedge clk) "
                             f"{tree_output}_reg <= {prev_names[0]};")
            lines.append(f"")
            # Activation LUT reads from registered reduction output
            act_out = f"col{col}_act"
            lines.append(f"    wire [DATA_WIDTH-1:0] {act_out};")
            lines.append(f"    activation_lut #(.DATA_WIDTH(DATA_WIDTH)) act_c{col} (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .data_in({tree_output}_reg),")
            lines.append(f"        .data_out({act_out})")
            lines.append(f"    );")
            lines.append(f"")
            col_result_wires.append(act_out)
        else:
            # V=1: no adder tree needed
            if needs_clb_activation:
                # Azure-Lily (ADC): still needs CLB activation even at V=1
                # Sign-extend DPE output from dpe_data_width to DATA_WIDTH
                act_in = f"col{col}_dpe_ext"
                if dpe_data_width < data_width:
                    pad = data_width - dpe_data_width
                    lines.append(f"    wire [DATA_WIDTH-1:0] {act_in};")
                    lines.append(f"    assign {act_in} = "
                                 f"{{{{{pad}{{dpe_out_c{col}_r0[{dpe_data_width-1}]}}}}, "
                                 f"dpe_out_c{col}_r0}};")
                else:
                    lines.append(f"    wire [DATA_WIDTH-1:0] {act_in};")
                    lines.append(f"    assign {act_in} = dpe_out_c{col}_r0;")
                act_out = f"col{col}_act"
                lines.append(f"    wire [DATA_WIDTH-1:0] {act_out};")
                lines.append(f"    activation_lut #(.DATA_WIDTH(DATA_WIDTH)) act_c{col} (")
                lines.append(f"        .clk(clk),")
                lines.append(f"        .data_in({act_in}),")
                lines.append(f"        .data_out({act_out})")
                lines.append(f"    );")
                lines.append(f"")
                col_result_wires.append(act_out)
            else:
                # NL-DPE (ACAM): activation handled by ACAM inside DPE
                # Sign-extend DPE output for downstream
                if dpe_data_width < data_width:
                    ext_wire = f"col{col}_dpe_ext"
                    pad = data_width - dpe_data_width
                    lines.append(f"    wire [DATA_WIDTH-1:0] {ext_wire};")
                    lines.append(f"    assign {ext_wire} = "
                                 f"{{{{{pad}{{dpe_out_c{col}_r0[{dpe_data_width-1}]}}}}, "
                                 f"dpe_out_c{col}_r0}};")
                    col_result_wires.append(ext_wire)
                else:
                    col_result_wires.append(f"dpe_out_c{col}_r0")

    # Horizontal concatenation / output selection
    if h == 1:
        lines.append(f"    assign data_out = {col_result_wires[0]};")
    else:
        # Round-robin or mux across columns using dpe_sel_h
        lines.append(f"    // Horizontal output mux ({h} columns)")
        lines.append(f"    reg [DATA_WIDTH-1:0] data_out_mux;")
        lines.append(f"    always @(*) begin")
        lines.append(f"        case (dpe_sel_h)")
        for col in range(h):
            lines.append(f"            {clog2_h}'d{col}: data_out_mux = {col_result_wires[col]};")
        lines.append(f"            default: data_out_mux = {data_width}'d0;")
        lines.append(f"        endcase")
        lines.append(f"    end")
        lines.append(f"    assign data_out = data_out_mux;")
    lines.append(f"")

    lines.append(f"endmodule")
    return "\n".join(lines)


def _gen_fc_top(v: int, h: int, k: int, n: int, rows: int, cols: int,
                depth: int, addr_width: int,
                data_width: int = 40,
                conversion: str = "acam",
                dpe_data_width: int = 40,
                elems_per_word: int = 5) -> str:
    """Generate the fc_top module (top-level wrapper).

    conversion: "acam" or "adc". Controls CLB activation LUT.
    dpe_data_width: DPE data_in/data_out pin width (16 or 40).
    elems_per_word: int8 elements packed per SRAM word (dpe_data_width // 8).
    """
    needs_clb_activation = (conversion == "adc") or (v > 1)
    lines = []
    lines.append(f"module fc_top #(")
    lines.append(f"    parameter DATA_WIDTH = {data_width}")
    lines.append(f")(")
    lines.append(f"    input wire clk,")
    lines.append(f"    input wire rst,")
    lines.append(f"    input wire valid,")
    lines.append(f"    input wire ready_n,")
    lines.append(f"    input wire [DATA_WIDTH-1:0] data_in,")
    lines.append(f"    output wire [DATA_WIDTH-1:0] data_out,")
    lines.append(f"    output wire ready,")
    lines.append(f"    output wire valid_n")
    lines.append(f");")
    lines.append(f"")
    lines.append(f"    localparam V = {v};")
    lines.append(f"    localparam H = {h};")
    lines.append(f"    localparam DEPTH = {depth};")
    lines.append(f"    localparam ADDR_WIDTH = {addr_width};")
    lines.append(f"")
    lines.append(f"    // Internal signals for global controller")
    lines.append(f"    wire valid_g_in, valid_g_out, ready_g_in, ready_g_out;")
    lines.append(f"    wire [DATA_WIDTH-1:0] data_out_layer;")
    lines.append(f"    wire [DATA_WIDTH-1:0] global_sram_data_in;")
    lines.append(f"    reg [7:0] read_address, write_address;")
    lines.append(f"")

    # FC layer instantiation
    dpe_dw = dpe_data_width

    if v == 1 and h == 1:
        # Packed KERNEL_WIDTH: controller loops over packed words, not elements
        packed_kw = math.ceil(k / elems_per_word)

        if needs_clb_activation:
            # Azure-Lily V=1 H=1: DPE + CLB activation LUT
            lines.append(f"    // V=1, H=1: conv_layer_single_dpe + CLB activation (ADC, no ACAM)")
            lines.append(f"    // Packed: {elems_per_word} int8/word, {packed_kw} words for K={k}")
            lines.append(f"    wire [DATA_WIDTH-1:0] dpe_raw_out;")
            lines.append(f"    conv_layer_single_dpe #(")
            lines.append(f"        .N_CHANNELS(1),")
            lines.append(f"        .ADDR_WIDTH(ADDR_WIDTH),")
            lines.append(f"        .N_KERNELS(1),")
            lines.append(f"        .KERNEL_WIDTH({packed_kw}),")
            lines.append(f"        .KERNEL_HEIGHT(1),")
            lines.append(f"        .W(1),")
            lines.append(f"        .H(1),")
            lines.append(f"        .S(1),")
            lines.append(f"        .DEPTH({depth}),")
            lines.append(f"        .DATA_WIDTH({dpe_dw})")
            lines.append(f"    ) fc_layer_inst (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .rst(rst),")
            lines.append(f"        .valid(valid_g_out),")
            lines.append(f"        .ready_n(ready_g_out),")
            lines.append(f"        .data_in(data_in),")
            lines.append(f"        .data_out(dpe_raw_out),")
            lines.append(f"        .ready(ready_g_in),")
            lines.append(f"        .valid_n(valid_g_in)")
            lines.append(f"    );")
            lines.append(f"    activation_lut #(.DATA_WIDTH(DATA_WIDTH)) act_inst (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .data_in(dpe_raw_out),")
            lines.append(f"        .data_out(data_out_layer)")
            lines.append(f"    );")
        else:
            # NL-DPE V=1 H=1: DPE with ACAM handles activation
            lines.append(f"    // V=1, H=1: conv_layer_single_dpe (ACAM handles activation)")
            lines.append(f"    // Packed: {elems_per_word} int8/word, {packed_kw} words for K={k}")
            lines.append(f"    conv_layer_single_dpe #(")
            lines.append(f"        .N_CHANNELS(1),")
            lines.append(f"        .ADDR_WIDTH(ADDR_WIDTH),")
            lines.append(f"        .N_KERNELS(1),")
            lines.append(f"        .KERNEL_WIDTH({packed_kw}),")
            lines.append(f"        .KERNEL_HEIGHT(1),")
            lines.append(f"        .W(1),")
            lines.append(f"        .H(1),")
            lines.append(f"        .S(1),")
            lines.append(f"        .DEPTH({depth}),")
            lines.append(f"        .DATA_WIDTH({dpe_dw})")
            lines.append(f"    ) fc_layer_inst (")
            lines.append(f"        .clk(clk),")
            lines.append(f"        .rst(rst),")
            lines.append(f"        .valid(valid_g_out),")
            lines.append(f"        .ready_n(ready_g_out),")
            lines.append(f"        .data_in(data_in),")
            lines.append(f"        .data_out(data_out_layer),")
            lines.append(f"        .ready(ready_g_in),")
            lines.append(f"        .valid_n(valid_g_in)")
            lines.append(f"    );")
    else:
        lines.append(f"    // FC layer: V={v}, H={h}")
        lines.append(f"    fc_layer #(")
        lines.append(f"        .DATA_WIDTH(DATA_WIDTH)")
        lines.append(f"    ) fc_layer_inst (")
        lines.append(f"        .clk(clk),")
        lines.append(f"        .rst(rst),")
        lines.append(f"        .valid(valid_g_out),")
        lines.append(f"        .ready_n(ready_g_out),")
        lines.append(f"        .data_in(data_in),")
        lines.append(f"        .data_out(data_out_layer),")
        lines.append(f"        .ready(ready_g_in),")
        lines.append(f"        .valid_n(valid_g_in)")
        lines.append(f"    );")
    lines.append(f"")

    # Global controller
    lines.append(f"    // Global controller")
    lines.append(f"    global_controller #(")
    lines.append(f"        .N_Layers(1)")
    lines.append(f"    ) g_ctrl_inst (")
    lines.append(f"        .clk(clk),")
    lines.append(f"        .rst(rst),")
    lines.append(f"        .ready_L1(ready_g_in),")
    lines.append(f"        .valid_Ln(valid_g_in),")
    lines.append(f"        .valid(valid),")
    lines.append(f"        .ready(ready),")
    lines.append(f"        .valid_L1(valid_g_out),")
    lines.append(f"        .ready_Ln(ready_g_out)")
    lines.append(f"    );")
    lines.append(f"")

    # Global output SRAM buffer
    # Output SRAM depth: enough for packed output words + margin
    out_sram_depth = max(16, math.ceil(n / elems_per_word) + 2)
    lines.append(f"    // Output SRAM buffer (packed: {elems_per_word} cols/word)")
    lines.append(f"    sram #(")
    lines.append(f"        .N_CHANNELS(1),")
    lines.append(f"        .DATA_WIDTH(DATA_WIDTH),")
    lines.append(f"        .DEPTH({out_sram_depth})")
    lines.append(f"    ) global_sram_inst (")
    lines.append(f"        .clk(clk),")
    lines.append(f"        .rst(rst),")
    lines.append(f"        .w_en(valid_g_in),")
    lines.append(f"        .r_addr(read_address),")
    lines.append(f"        .w_addr(write_address),")
    lines.append(f"        .sram_data_in(data_out_layer),")
    lines.append(f"        .sram_data_out(global_sram_data_in)")
    lines.append(f"    );")
    lines.append(f"")

    # Address counter logic
    lines.append(f"    always @(posedge clk or posedge rst) begin")
    lines.append(f"        if (rst) begin")
    lines.append(f"            read_address <= 0;")
    lines.append(f"            write_address <= 16;")
    lines.append(f"        end else begin")
    lines.append(f"            if (ready_g_out)")
    lines.append(f"                read_address <= read_address + 1;")
    lines.append(f"            if (valid_g_out)")
    lines.append(f"                write_address <= write_address + 1;")
    lines.append(f"        end")
    lines.append(f"    end")
    lines.append(f"")

    # Output connections
    lines.append(f"    assign data_out = global_sram_data_in;")
    lines.append(f"    assign ready = ready_g_in;")
    lines.append(f"    assign valid_n = valid_g_in;")
    lines.append(f"")
    lines.append(f"endmodule")
    return "\n".join(lines)


def gen_fc_wrapper(k: int, n: int, rows: int, cols: int,
                   output_dir: str,
                   conversion: str = "acam",
                   dpe_data_width: int = 40) -> Path:
    """Generate a self-contained FC+activation .v file for a (K,N) workload
    mapped onto (rows x cols) crossbars.

    conversion: "acam" or "adc".
      - acam: ACAM handles activation when V=1 (no CLB LUT needed).
      - adc:  ADC gives raw output; CLB activation LUT always needed.

    dpe_data_width: DPE hard block data_in/data_out width (16 or 40 bits).
      Controls BRAM↔DPE transfer bandwidth.

    Returns the path to the generated file.
    """
    v = math.ceil(k / rows)
    h = math.ceil(n / cols)
    total_dpes = v * h
    data_width = dpe_data_width  # external port matches DPE bus width
    # Packed transfers: floor(dpe_data_width / 8) int8 elements per SRAM word
    elems_per_word = dpe_data_width // 8  # 2 for 16-bit, 5 for 40-bit
    # SRAM depth in packed words (not individual elements)
    packed_k = math.ceil(k / elems_per_word)
    depth = max(512 // elems_per_word, packed_k) + 1
    addr_width = math.ceil(math.log2(depth)) if depth > 1 else 1
    acam_eligible = (v == 1) and (conversion == "acam")
    needs_clb_activation = (conversion == "adc") or (v > 1)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"fc_{k}_{n}_{rows}x{cols}_{conversion}_dw{dpe_data_width}.v"
    out_path = out_dir / filename

    parts = []

    # Header comment
    parts.append(f"// Auto-generated FC+activation wrapper")
    parts.append(f"// Workload: K={k}, N={n}")
    parts.append(f"// Crossbar: {rows}x{cols}")
    parts.append(f"// Conversion: {conversion}, DPE DATA_WIDTH: {dpe_data_width}")
    parts.append(f"// Tiling: V={v}, H={h}, DPEs={total_dpes}")
    parts.append(f"// ACAM eligible (V=1 + ACAM): {'yes' if acam_eligible else 'no'}")
    parts.append(f"// CLB activation LUT: {'yes' if needs_clb_activation else 'no (ACAM)'}")
    parts.append(f"// Generated by gen_gemv_wrappers.py --fc")
    parts.append(f"")

    # fc_top module
    parts.append(f"// =====================================================")
    parts.append(f"// fc_top — top-level module")
    parts.append(f"// =====================================================")
    parts.append(_gen_fc_top(v, h, k, n, rows, cols, depth, addr_width,
                             data_width, conversion=conversion,
                             dpe_data_width=dpe_data_width,
                             elems_per_word=elems_per_word))
    parts.append(f"")

    # fc_layer module (only if not V=1 H=1)
    if not (v == 1 and h == 1):
        parts.append(f"// =====================================================")
        parts.append(f"// fc_layer — DPE stacking + reduction + activation")
        parts.append(f"// =====================================================")
        parts.append(_gen_fc_layer(v, h, k, n, rows, cols, depth, addr_width,
                                   data_width, conversion=conversion,
                                   dpe_data_width=dpe_data_width,
                                   elems_per_word=elems_per_word))
        parts.append(f"")

    # activation_lut module (needed for Azure-Lily always, NL-DPE only when V>1)
    if needs_clb_activation:
        parts.append(f"// =====================================================")
        parts.append(f"// activation_lut — piecewise-linear tanh approximation")
        parts.append(f"// =====================================================")
        parts.append(_gen_activation_lut_module())
        parts.append(f"")

    # Supporting modules extracted from gemv_1_channel.v
    parts.append(f"// =====================================================")
    parts.append(f"// Supporting modules (from gemv_1_channel.v)")
    parts.append(f"// =====================================================")
    parts.append(_get_supporting_modules())
    parts.append(f"")

    out_path.write_text("\n".join(parts))
    print(f"  Generated {filename} (K={k}, N={n}, V={v}, H={h}, "
          f"DPEs={total_dpes}, conv={conversion}, dpe_dw={dpe_data_width}, "
          f"ACAM={'yes' if acam_eligible else 'no'}, "
          f"CLB_act={'yes' if needs_clb_activation else 'no'})")
    return out_path


def main():
    parser = argparse.ArgumentParser(
        description="Generate GEMV/FC VTR wrapper files"
    )
    parser.add_argument("--run-vtr", action="store_true",
                        help="Also run VTR synthesis for all generated shapes")
    parser.add_argument("--arch", default="nl_dpe_22nm_auto.xml",
                        help="Architecture XML (default: nl_dpe_22nm_auto.xml)")
    parser.add_argument("--rows", type=int, default=256,
                        help="Crossbar rows (default: 256)")
    parser.add_argument("--cols", type=int, default=256,
                        help="Crossbar cols (default: 256)")
    parser.add_argument("--fc", action="store_true",
                        help="Generate FC+activation wrappers instead of GEMV")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory for generated files "
                             "(default: script dir for GEMV, required for FC)")
    args = parser.parse_args()

    if args.fc:
        # FC mode
        out_dir = args.output_dir if args.output_dir else str(SCRIPT_DIR)
        print(f"Generating FC+activation wrappers "
              f"({args.rows}x{args.cols} crossbar) -> {out_dir}")
        for name, (k, n) in FC_WORKLOADS.items():
            gen_fc_wrapper(k, n, args.rows, args.cols, out_dir)
    else:
        # GEMV mode (original behavior)
        print(f"Generating GEMV wrappers ({args.rows}x{args.cols} crossbar):")
        wrappers = []
        for name, (k, n) in SHAPES.items():
            path = gen_wrapper(name, k, n, args.rows, args.cols)
            wrappers.append(path)

        if args.run_vtr:
            print(f"\nRunning VTR synthesis...")
            designs = " ".join(f"gemv_{name}.v" for name in SHAPES)
            cmd = (f"python {SCRIPT_DIR / 'run_vtr.py'} "
                   f"--arch {args.arch} --design {designs}")
            print(f"  {cmd}")
            os.chdir(SCRIPT_DIR)
            subprocess.run(cmd.split(), check=False)


if __name__ == "__main__":
    main()
