#!/usr/bin/env python3
"""
DSP-MAC behavior model generator (FIDELITY_METHODOLOGY.md §3, §4, §5).

Reads `azurelily/IMC/configs/azure_lily.json` and emits a Verilog file
into `fc_verification/rtl/dsp_mac.v`.

The DSP-MAC primitive is the AL DIMM lane: one ``int_sop_4`` hard block
running at DSP_WIDTH int8 MACs/cycle. The simulator side is in
`azurelily/IMC/peripherals/fpga_fabric.py:gemm_dsp` (per-pass
DPE-axiom):

    L = ceil(K_INPUT * 8 / dpe_buf_width)
    C = max(1, ceil(K_INPUT / DSP_WIDTH))
    O = max(1, ceil(precision_bits / dpe_buf_width))     # 1 byte drain

Per pass: feed K_INPUT bytes, accumulate K_INPUT int8 products at
DSP_WIDTH MAC/cycle, drain 1 int8 result. Same handshake/FSM as the DPE
behavior model so a unified TB harness works.

Pipeline model (FIDELITY_METHODOLOGY.md §4, Task #87 Phase 1
faithful FSM): single-buffered drain-load overlap,
    T(M)     = T_fill + (M-1) * T_steady
    T_fill   = L + C + O + 2     (+2 for LOAD→COMPUTE and COMPUTE→OUTPUT)
    T_steady = max(L, C, O)
Three parallel sub-FSMs (LOAD / COMPUTE / OUTPUT) operate concurrently
with a queue of pending MAC results between LOAD->COMPUTE and
COMPUTE->OUTPUT stages.  Wake-up signals between stages are queue
indices NBA-advanced by the producer; the consumer reads the updated
n_pending_* combinational count one cycle later (the +1 per handoff).
See fc_verification/rtl/dpe_*.v for full design narrative — dsp_mac
mirrors that structure with a 1-element accumulator per pass instead
of an N-column VMM result.

Default K_INPUT is set from the AL crossbar's NUM_COLS so the module
compiles standalone; TBs override via Verilog parameter passing
(``dsp_mac #(.K_INPUT(64)) dut (...);``).

Usage:
    python nl_dpe/gen_dsp_mac.py
    python nl_dpe/gen_dsp_mac.py --config azurelily/IMC/configs/azure_lily.json
"""
import argparse
import json
import math
import os
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_CFG = os.path.join(REPO, "azurelily/IMC/configs/azure_lily.json")
OUT_DIR = os.path.join(REPO, "fc_verification/rtl")

# DSP_WIDTH is a hard-block constant (int_sop_4 = 4 int8 MAC/cycle).
# Mirrors `DSP_WDITH` in azurelily/IMC/peripherals/fpga_fabric.py.
DSP_WIDTH_CONST = 4


def _import_imc_core():
    imc_root = os.path.join(REPO, "azurelily", "IMC")
    if imc_root not in sys.path:
        sys.path.insert(0, imc_root)
    from imc_core.config import Config  # noqa: WPS433
    return Config


def derive_dsp_params(cfg_path, K_default):
    """Return canonical RTL params for the DSP-MAC primitive.

    K_default is the K_INPUT default baked as the parameter default
    (TBs override per-instance). The compute formula below is the same
    one the simulator uses in `gemm_dsp` — single source of truth per
    FIDELITY_METHODOLOGY.md §3.
    """
    Config = _import_imc_core()
    cfg = Config(cfg_path)

    BUF = int(cfg.dpe_buf_width)
    PREC = int(getattr(cfg, "n_in", 8))
    DSP_WIDTH = DSP_WIDTH_CONST

    L = math.ceil(K_default * PREC / BUF)
    C = max(1, math.ceil(K_default / DSP_WIDTH))
    O = max(1, math.ceil(PREC / BUF))

    return {
        "BUF": BUF,
        "PREC": PREC,
        "DSP_WIDTH": DSP_WIDTH,
        "K_default": int(K_default),
        "L_default": int(L),
        "C_default": int(C),
        "O_default": int(O),
        # T_fill includes +2 FSM register-propagation overhead (Task #87).
        "T_fill_default": int(L + C + O + 2),
    }


def emit_dsp_mac_verilog(params):
    BUF = params["BUF"]
    PREC = params["PREC"]
    DSP_WIDTH = params["DSP_WIDTH"]
    K_default = params["K_default"]

    lines = []
    a = lines.append
    a("// dsp_mac.v -- behavioral DSP-MAC lane model with single-buffered drain-load overlap.")
    a("// Generated by nl_dpe/gen_dsp_mac.py from azure_lily.json.")
    a("//")
    a("// AL DIMM lane: one int_sop_4 hard block (DSP_WIDTH int8 MACs/cycle),")
    a("// matching FIDELITY_METHODOLOGY.md §3 + §5 + the simulator's gemm_dsp")
    a("// formula in azurelily/IMC/peripherals/fpga_fabric.py.")
    a("//")
    a("// Per pass:")
    a("//   LOAD    L = ceil(K_INPUT * PRECISION_BITS / DPE_BUF_WIDTH)")
    a("//   COMPUTE C = max(1, ceil(K_INPUT / DSP_WIDTH))")
    a("//   OUTPUT  O = max(1, ceil(PRECISION_BITS / DPE_BUF_WIDTH))")
    a("//")
    a(f"// Default-parameter values (K_INPUT={K_default}):")
    a(f"//   L = {params['L_default']}, C = {params['C_default']}, O = {params['O_default']}")
    a(f"//   T_fill = L + C + O + 2 = {params['T_fill_default']}  (Task #87)")
    a("//")
    a("// Pipeline model (FIDELITY_METHODOLOGY.md §4, Task #87 Phase 1):")
    a("//   T(M)     = T_fill + (M-1) * T_steady")
    a("//   T_fill   = L + C + O + 2     (+2 = LOAD→COMPUTE + COMPUTE→OUTPUT)")
    a("//   T_steady = max(L, C, O)")
    a("// Three parallel sub-FSMs (LOAD / COMPUTE / OUTPUT) operate concurrently")
    a("// with a queue of pending MAC results between LOAD->COMPUTE and")
    a("// COMPUTE->OUTPUT stages.  Wake-up signals are queue indices NBA-")
    a("// advanced by the producer; consumer reads them one cycle later.")
    a("// See dpe_*.v for full design narrative — dsp_mac mirrors that")
    a("// structure with a 1-element accumulator per pass instead of an")
    a("// N-column VMM result.")
    a("//")
    a("// Weights are loaded by the TB through hierarchical force:")
    a("//     dut.weight[k] = <int8>;     (no weight_wen port).")
    a("")
    a("module dsp_mac #(")
    a(f"    parameter K_INPUT        = {K_default},  // input vector length per pass")
    a(f"    parameter DPE_BUF_WIDTH  = {BUF},")
    a(f"    parameter PRECISION_BITS = {PREC},")
    a(f"    parameter DSP_WIDTH      = {DSP_WIDTH}")
    a(")(")
    a("    input  wire                       clk,")
    a("    input  wire                       reset,")
    a("    input  wire [DPE_BUF_WIDTH-1:0]   data_in,")
    a("    input  wire [1:0]                 nl_dpe_control,")
    a("    input  wire                       shift_add_control,")
    a("    input  wire                       w_buf_en,")
    a("    input  wire                       shift_add_bypass,")
    a("    input  wire                       load_output_reg,")
    a("    input  wire                       load_input_reg,")
    a("    output reg                        MSB_SA_Ready,")
    a("    output reg  [DPE_BUF_WIDTH-1:0]   data_out,")
    a("    output reg                        dpe_done,")
    a("    output reg                        reg_full,")
    a("    output reg                        shift_add_done,")
    a("    output reg                        shift_add_bypass_ctrl")
    a(");")
    a("")
    a("    wire _unused_aux = shift_add_control | shift_add_bypass |")
    a("                       load_output_reg   | load_input_reg;")
    a("")
    a("    // Derived per-pass cycle counters")
    a("    localparam ELEMS_PER_STROBE = DPE_BUF_WIDTH / 8;")
    a("    localparam LOAD_CYCLES  = (K_INPUT * PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;")
    a("    // K MACs at DSP_WIDTH per cycle on the int_sop_4 hard block.")
    a("    localparam COMPUTE_CYCLES = (K_INPUT + DSP_WIDTH - 1) / DSP_WIDTH;")
    a("    // One int8 result drains in ceil(PRECISION_BITS / DPE_BUF_WIDTH) cycles (>= 1).")
    a("    localparam OUTPUT_CYCLES_RAW = (PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;")
    a("    localparam OUTPUT_CYCLES = (OUTPUT_CYCLES_RAW < 1) ? 1 : OUTPUT_CYCLES_RAW;")
    a("")
    a("    // Ring buffer queue depth.")
    a("    localparam QDEPTH = 4;")
    a("")
    a("    // Single-column weight + input buffer; per-pass MAC result queue.")
    a("    reg signed [7:0]  weight       [0:K_INPUT-1];")
    a("    reg signed [7:0]  input_buffer [0:K_INPUT-1];")
    a("    reg signed [31:0] mac_queue    [0:QDEPTH-1];")
    a("    // Legacy alias: `mac_result` reflects the most recently fired MAC")
    a("    // result so TBs (e.g., tb_dsp_mac.v) hierarchically reading")
    a("    // dut.mac_result observe the same value as before.")
    a("    reg signed [31:0] mac_result;")
    a("")
    a("    // ── LOAD sub-FSM ────────────────────────────────────────────────────")
    a("    reg [15:0] load_count;")
    a("    reg [15:0] load_cycle_idx;")
    a("    reg [3:0]  q_load_tail;")
    a("")
    a("    // ── COMPUTE sub-FSM ─────────────────────────────────────────────────")
    a("    reg        compute_busy;")
    a("    reg [15:0] compute_cycle;")
    a("    reg [3:0]  q_compute_head;")
    a("")
    a("    // ── OUTPUT sub-FSM ──────────────────────────────────────────────────")
    a("    reg        output_busy;")
    a("    reg [15:0] output_col_idx;")
    a("    reg [3:0]  q_output_head;")
    a("")
    a("    wire [3:0] n_pending_compute = (q_load_tail >= q_compute_head) ?")
    a("                                    (q_load_tail - q_compute_head) :")
    a("                                    (QDEPTH[3:0] + q_load_tail - q_compute_head);")
    a("    wire [3:0] n_pending_output  = (q_compute_head >= q_output_head) ?")
    a("                                    (q_compute_head - q_output_head) :")
    a("                                    (QDEPTH[3:0] + q_compute_head - q_output_head);")
    a("")
    a("    // Legacy state encoding (combinational, priority OUTPUT > COMPUTE > LOAD > IDLE).")
    a("    localparam S_IDLE      = 3'd0;")
    a("    localparam S_LOAD      = 3'd1;")
    a("    localparam S_COMPUTE   = 3'd3;")
    a("    localparam S_OUTPUT    = 3'd4;")
    a("    wire [2:0] state = output_busy ? S_OUTPUT :")
    a("                       compute_busy ? S_COMPUTE :")
    a("                       (w_buf_en || load_cycle_idx != 0) ? S_LOAD : S_IDLE;")
    a("")
    a("    integer wi, wq;")
    a("    initial begin")
    a("        for (wi = 0; wi < K_INPUT; wi = wi + 1) begin")
    a("            weight[wi]       = 0;")
    a("            input_buffer[wi] = 0;")
    a("        end")
    a("        for (wq = 0; wq < QDEPTH; wq = wq + 1) begin")
    a("            mac_queue[wq] = 0;")
    a("        end")
    a("        mac_result = 0;")
    a("    end")
    a("")
    a("    integer k, b;")
    a("")
    a("    always @(posedge clk or posedge reset) begin")
    a("        if (reset) begin")
    a("            load_count       <= 0;")
    a("            load_cycle_idx  <= 0;")
    a("            q_load_tail      <= 0;")
    a("            compute_busy     <= 0;")
    a("            compute_cycle    <= 0;")
    a("            q_compute_head   <= 0;")
    a("            output_busy      <= 0;")
    a("            output_col_idx   <= 0;")
    a("            q_output_head    <= 0;")
    a("            data_out         <= 0;")
    a("            dpe_done         <= 0;")
    a("            reg_full         <= 0;")
    a("            MSB_SA_Ready     <= 1;")
    a("            shift_add_done   <= 1;")
    a("            shift_add_bypass_ctrl <= 1;")
    a("            mac_result       <= 0;")
    a("        end else begin")
    a("            // ── LOAD sub-FSM ────────────────────────────────────────────")
    a("            if (w_buf_en) begin")
    a("                if (load_cycle_idx == LOAD_CYCLES - 1) begin")
    a("                    // Last strobe of pass: write final EPS bytes BLOCKING.")
    a("                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin")
    a("                        if (load_count + b < K_INPUT)")
    a("                            input_buffer[load_count + b] = data_in[b*8 +: 8];")
    a("                    end")
    a("                    // Fire MAC into mac_queue[q_load_tail].")
    a("                    mac_queue[q_load_tail] = 0;")
    a("                    for (k = 0; k < K_INPUT; k = k + 1) begin")
    a("                        mac_queue[q_load_tail] = mac_queue[q_load_tail] +")
    a("                            input_buffer[k] * weight[k];")
    a("                    end")
    a("                    mac_result      <= mac_queue[q_load_tail];  // legacy alias")
    a("                    load_count      <= 0;")
    a("                    load_cycle_idx <= 0;")
    a("                    q_load_tail     <= (q_load_tail + 1) % QDEPTH;")
    a("                end else begin")
    a("                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin")
    a("                        if (load_count + b < K_INPUT)")
    a("                            input_buffer[load_count + b] <= data_in[b*8 +: 8];")
    a("                    end")
    a("                    load_count      <= load_count + ELEMS_PER_STROBE;")
    a("                    load_cycle_idx <= load_cycle_idx + 1;")
    a("                end")
    a("            end")
    a("")
    a("            // ── COMPUTE sub-FSM (Task #87 Phase 1: NBA-wake on queue) ──")
    a("            if (compute_busy) begin")
    a("                if (compute_cycle + 1 >= COMPUTE_CYCLES) begin")
    a("                    compute_busy     <= 0;")
    a("                    compute_cycle    <= 0;")
    a("                    q_compute_head   <= (q_compute_head + 1) % QDEPTH;")
    a("                    MSB_SA_Ready     <= 1;")
    a("                    shift_add_done   <= 1;")
    a("                end else begin")
    a("                    compute_cycle <= compute_cycle + 1;")
    a("                end")
    a("            end else begin")
    a("                // Wake one cycle after LOAD's last strobe: q_load_tail's")
    a("                // NBA must commit before n_pending_compute>0 is observable.")
    a("                if (n_pending_compute > 0) begin")
    a("                    compute_busy     <= 1;")
    a("                    compute_cycle    <= 0;")
    a("                    MSB_SA_Ready     <= 0;")
    a("                    shift_add_done   <= 0;")
    a("                end")
    a("            end")
    a("")
    a("            // ── OUTPUT sub-FSM (Task #87 Phase 1: NBA-wake on queue) ───")
    a("            if (output_busy) begin")
    a("                // Drive data_out: the MAC result is a single int8 byte;")
    a("                // OCYC is typically 1 (since BUF >= PRECISION_BITS = 8).")
    a("                // For OCYC > 1, subsequent strobes drive zeros (the TB")
    a("                // latches on cycle 0).")
    a("                data_out <= 0;")
    a("                if (output_col_idx == 0) begin")
    a("                    data_out[7:0] <= mac_queue[q_output_head][7:0];")
    a("                end")
    a("                if (output_col_idx + 1 >= OUTPUT_CYCLES) begin")
    a("                    q_output_head  <= (q_output_head + 1) % QDEPTH;")
    a("                    output_col_idx <= 0;")
    a("                    // Chain when COMPUTE has already advanced past the")
    a("                    // current OUTPUT pass.")
    a("                    if (n_pending_output > 1) begin")
    a("                        output_busy <= 1;")
    a("                    end else begin")
    a("                        output_busy <= 0;")
    a("                    end")
    a("                end else begin")
    a("                    output_col_idx <= output_col_idx + 1;")
    a("                end")
    a("            end else begin")
    a("                // Wake one cycle after COMPUTE done.")
    a("                if (n_pending_output > 0) begin")
    a("                    output_busy    <= 1;")
    a("                    output_col_idx <= 0;")
    a("                end")
    a("            end")
    a("")
    a("            if (output_busy)")
    a("                dpe_done <= 1;")
    a("            else")
    a("                dpe_done <= 0;")
    a("")
    a("            if (compute_busy || output_busy)")
    a("                reg_full <= 1;")
    a("            else")
    a("                reg_full <= 0;")
    a("        end")
    a("    end")
    a("")
    a("endmodule")
    a("")
    return "\n".join(lines)


def main(argv=None):
    p = argparse.ArgumentParser(description="DSP-MAC behavior model generator")
    p.add_argument("--config", default=DEFAULT_CFG,
                   help="Azure-Lily config path (default: azurelily/IMC/configs/azure_lily.json)")
    p.add_argument("--k-default", type=int, default=64,
                   help="Default K_INPUT (TBs override per-instance). 64 matches "
                        "attention head N=128 d=64 K=64.")
    args = p.parse_args(argv)

    params = derive_dsp_params(args.config, args.k_default)
    src = emit_dsp_mac_verilog(params)
    os.makedirs(OUT_DIR, exist_ok=True)
    out_path = os.path.join(OUT_DIR, "dsp_mac.v")
    with open(out_path, "w") as fh:
        fh.write(src)
    print(f"[gen_dsp_mac] wrote {out_path}")
    print(f"               BUF={params['BUF']} PREC={params['PREC']} "
          f"DSP_WIDTH={params['DSP_WIDTH']} K_default={params['K_default']} "
          f"L={params['L_default']} C={params['C_default']} "
          f"O={params['O_default']} T_fill={params['T_fill_default']}")


if __name__ == "__main__":
    main()
