#!/usr/bin/env python3
"""Generate P-replica attention head wrapper for Round 2 attention DSE.

Instantiates P copies of the attention_head module (generated by
gen_attention_wrapper.py) with broadcast data_in and round-robin output.

Usage:
    python gen_attention_gemm_wrapper.py --rows 512 --cols 128 --P 3 \
        --output-dir ../dse/rtl/
"""

import argparse
import math
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

from gen_attention_wrapper import (
    _gen_attention_top,
    _gen_dimm_score_matrix,
    _gen_softmax_dpe,
    _gen_dimm_weighted_sum,
    N_DIMM_STAGES,
)
from gen_gemv_wrappers import (
    _gen_fc_layer,
    _gen_activation_lut_module,
    _get_supporting_modules,
)


def _gen_attn_gemm_top(p: int, data_width: int = 40) -> str:
    """Generate attn_gemm_top: P copies of attention_head with round-robin I/O."""
    sel_width = max(1, math.ceil(math.log2(p))) if p > 1 else 1
    lines = []

    lines.append(f"module attn_gemm_top #(")
    lines.append(f"    parameter DATA_WIDTH = {data_width},")
    lines.append(f"    parameter P = {p}")
    lines.append(f")(")
    lines.append(f"    input wire clk, input wire rst,")
    lines.append(f"    input wire valid, input wire ready_n,")
    lines.append(f"    input wire [DATA_WIDTH-1:0] data_in,")
    lines.append(f"    output wire [DATA_WIDTH-1:0] data_out,")
    lines.append(f"    output wire ready, output wire valid_n")
    lines.append(f");")
    lines.append(f"")

    # Per-replica signals
    for i in range(p):
        lines.append(f"    wire [DATA_WIDTH-1:0] rep{i}_data_out;")
        lines.append(f"    wire rep{i}_ready, rep{i}_valid_n;")
        lines.append(f"    reg  rep{i}_valid;")
    lines.append(f"")

    # Input distribution
    lines.append(f"    reg [{sel_width}-1:0] in_sel;")
    lines.append(f"    always @(posedge clk or posedge rst) begin")
    lines.append(f"        if (rst) in_sel <= 0;")
    lines.append(f"        else if (valid)")
    if p > 1:
        lines.append(f"            in_sel <= (in_sel == {sel_width}'d{p-1}) ? 0 : in_sel + 1;")
    else:
        lines.append(f"            in_sel <= 0;")
    lines.append(f"    end")
    lines.append(f"")

    # Demux valid
    lines.append(f"    always @(*) begin")
    for i in range(p):
        lines.append(f"        rep{i}_valid = 1'b0;")
    lines.append(f"        case (in_sel)")
    for i in range(p):
        lines.append(f"            {sel_width}'d{i}: rep{i}_valid = valid;")
    lines.append(f"            default: ;")
    lines.append(f"        endcase")
    lines.append(f"    end")
    lines.append(f"")

    # Instantiate P attention_head replicas
    for i in range(p):
        lines.append(f"    attention_head #(.DATA_WIDTH(DATA_WIDTH)) replica_{i} (")
        lines.append(f"        .clk(clk), .rst(rst),")
        lines.append(f"        .valid(rep{i}_valid), .ready_n(1'b1),")
        lines.append(f"        .data_in(data_in), .data_out(rep{i}_data_out),")
        lines.append(f"        .ready(rep{i}_ready), .valid_n(rep{i}_valid_n)")
        lines.append(f"    );")
        lines.append(f"")

    # Output collection
    lines.append(f"    reg [{sel_width}-1:0] out_sel;")
    lines.append(f"    always @(posedge clk or posedge rst) begin")
    lines.append(f"        if (rst) out_sel <= 0;")
    if p > 1:
        lines.append(f"        else if (|{{{', '.join(f'rep{i}_valid_n' for i in range(p))}}}) ")
        lines.append(f"            out_sel <= (out_sel == {sel_width}'d{p-1}) ? 0 : out_sel + 1;")
    lines.append(f"    end")
    lines.append(f"")

    # Output mux
    lines.append(f"    reg [DATA_WIDTH-1:0] data_out_mux;")
    lines.append(f"    reg valid_n_mux;")
    lines.append(f"    always @(*) begin")
    lines.append(f"        data_out_mux = 0; valid_n_mux = 0;")
    lines.append(f"        case (out_sel)")
    for i in range(p):
        lines.append(f"            {sel_width}'d{i}: begin data_out_mux = rep{i}_data_out; valid_n_mux = rep{i}_valid_n; end")
    lines.append(f"            default: ;")
    lines.append(f"        endcase")
    lines.append(f"    end")
    lines.append(f"    assign data_out = data_out_mux;")
    lines.append(f"    assign valid_n = valid_n_mux;")
    lines.append(f"    assign ready = {' | '.join(f'rep{i}_ready' for i in range(p))};")
    lines.append(f"endmodule")
    return "\n".join(lines)


def gen_attention_gemm_wrapper(n_seq: int, d_head: int,
                                rows: int, cols: int, p: int,
                                output_dir: str,
                                data_width: int = 40) -> Path:
    """Generate P-replica attention wrapper."""
    v = math.ceil(d_head / rows)
    h = math.ceil(d_head / cols)
    h_dimm = math.ceil(max(d_head, n_seq) / cols)
    dpes_per_rep = (3 * v + 4) * h
    total_dpes = p * dpes_per_rep

    depth = 256 if (v == 1 and h == 1) else max(512, d_head)
    addr_width = max(8, math.ceil(math.log2(depth)) if depth > 1 else 1)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"attn_gemm_{rows}x{cols}_P{p}.v"
    out_path = out_dir / filename

    parts = []
    parts.append(f"// Auto-generated P-replica attention head wrapper")
    parts.append(f"// Crossbar: {rows}x{cols}, P={p} replicas")
    parts.append(f"// Per-replica: V={v}, H={h}, H_dimm={h_dimm}, DPEs={dpes_per_rep}")
    parts.append(f"// Total DPEs: {total_dpes} = {p} × {dpes_per_rep}")
    parts.append(f"// N={n_seq}, d={d_head}")
    parts.append(f"")

    # attn_gemm_top
    parts.append(_gen_attn_gemm_top(p, data_width))
    parts.append(f"")

    # attention_head (single replica, reused P times)
    parts.append(f"// === attention_head (single replica) ===")
    parts.append(_gen_attention_top(v, h, n_seq, d_head, rows, cols,
                                     depth, addr_width, data_width))
    parts.append(f"")

    # fc_layer for projections (if H>1)
    if not (v == 1 and h == 1):
        parts.append(f"// === fc_layer for projections ({v}x{h}) ===")
        parts.append(_gen_fc_layer(v, h, d_head, d_head, rows, cols,
                                    depth, addr_width, data_width))
        parts.append(f"")

    if v > 1:
        parts.append(_gen_activation_lut_module())
        parts.append(f"")

    # DIMM modules
    parts.append(f"// === DIMM modules ===")
    parts.append(_gen_dimm_score_matrix(n_seq, d_head, h_dimm, depth, addr_width, data_width))
    parts.append(f"")
    parts.append(_gen_softmax_dpe(n_seq, d_head, h_dimm, depth, addr_width, data_width))
    parts.append(f"")
    parts.append(_gen_dimm_weighted_sum(n_seq, d_head, h_dimm, depth, addr_width, data_width))
    parts.append(f"")

    # Supporting modules
    parts.append(f"// === Supporting modules ===")
    parts.append(_get_supporting_modules())

    out_path.write_text("\n".join(parts))
    print(f"  Generated {filename} (P={p}, DPEs/rep={dpes_per_rep}, total_DPEs={total_dpes})")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Generate P-replica attention wrapper")
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument("--cols", type=int, required=True)
    parser.add_argument("--P", type=int, required=True)
    parser.add_argument("--n-seq", type=int, default=128)
    parser.add_argument("--d-head", type=int, default=128)
    parser.add_argument("--output-dir", type=str, required=True)
    args = parser.parse_args()
    gen_attention_gemm_wrapper(args.n_seq, args.d_head, args.rows, args.cols,
                                args.P, args.output_dir)


if __name__ == "__main__":
    main()
