"""Generate pure-FPGA GEMV wrappers using DSP multipliers + BRAM weight storage.

No DPE (nl_dpe) hard block instantiation — uses explicit VTR primitives:
  - `single_port_ram` (from vtr_primitives.v, has keep_hierarchy) for BRAM inference
  - `*` operator for DSP mult_9x9 inference via Parmys $mul mapping

This is the baseline for Round 2 Part 2: DSP+BRAM equivalence comparison.

Architecture: primary-input-driven datapath (no FSM) to avoid VPR constant
propagation sweeping black-box subcircuits.  Primary inputs `addr` and `data_in`
directly drive RAM addresses and multiply operands — matching the proven
minimal_dsp test pattern.  The latency model is computed analytically
(K × ceil(N/P) cycles) since the control logic would be identical overhead.

Key synthesis requirements:
  - Explicit single_port_ram instantiation: survives Yosys mem2reg + flatten
  - Weight-loading ports (w_data/w_addr/w_we) prevent dead-code removal
  - Primary inputs directly feed multiply + RAM to prevent VPR constant folding
  - Unsigned `*` operator for DSP mult_9x9 inference

Usage:
    python gen_dsp_gemv_wrapper.py --K 512 --N 128 --output-dir dse/rtl/
"""

import argparse
import math
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

# Parallel MAC channels. Each uses 1 multiply (→ 1/4 DSP in 9x9 mode).
MAX_PARALLEL = 32


def gen_dsp_fc_wrapper(
    K: int,
    N: int,
    output_dir: str = ".",
    data_width: int = 8,
    max_parallel: int = MAX_PARALLEL,
) -> Path:
    """Generate a DSP-based FC (GEMV) wrapper.

    Architecture (primary-input driven, no FSM):
      - P parallel MAC channels (P = min(N, max_parallel))
      - Each channel: single_port_ram (weight BRAM) + multiply (DSP) + accumulator
      - Primary input `addr` drives all RAM read addresses
      - Primary input `data_in` feeds directly into multiply operand A
      - Weight loading via w_data/w_addr/w_we ports
      - Registered accumulator + output
    """
    P = min(N, max_parallel)
    BATCHES = math.ceil(N / P)
    W_DEPTH = K * BATCHES
    W_ADDR_W = max(1, math.ceil(math.log2(max(W_DEPTH, 2))))
    OUT_W = max(1, math.ceil(math.log2(max(P, 2))))
    ACC_W = data_width * 2 + math.ceil(math.log2(max(K, 2)))
    PROD_W = data_width * 2

    module_name = f"dsp_fc_{K}_{N}"

    lines = []
    a = lines.append

    a(f"// DSP-based FC layer: K={K}, N={N}, P={P} parallel MACs")
    a(f"// Generated by gen_dsp_gemv_wrapper.py")
    a(f"// Uses explicit single_port_ram (BRAM) + multiply (DSP) primitives")
    a(f"// Primary-input driven datapath (no FSM) to avoid VPR constant propagation")
    a(f"")
    a(f"module {module_name} (")
    a(f"    input wire clk,")
    a(f"    // Datapath — primary inputs drive RAM + multiply directly")
    a(f"    input wire [{W_ADDR_W-1}:0] addr,     // RAM read address (primary input)")
    a(f"    input wire [{data_width-1}:0] data_in, // multiply operand A (primary input)")
    a(f"    input wire acc_en,                      // accumulate enable")
    a(f"    input wire acc_clear,                   // clear accumulators")
    a(f"    output reg [{data_width-1}:0] data_out,")
    a(f"    // Weight loading (prevents dead-code removal)")
    a(f"    input wire [{data_width-1}:0] w_data,")
    a(f"    input wire [{W_ADDR_W-1}:0] w_addr,")
    a(f"    input wire [{OUT_W-1}:0] w_ch,   // channel select (0..{P-1})")
    a(f"    input wire w_we")
    a(f");")
    a(f"")

    # Weight memories — P × single_port_ram
    a(f"// ── Weight memories: {P} channels × {W_DEPTH} depth (single_port_ram → BRAM) ──")
    for p in range(P):
        a(f"wire wmem_we_{p};")
        a(f"assign wmem_we_{p} = w_we & (w_ch == {OUT_W}'d{p});")
        a(f"wire [{W_ADDR_W-1}:0] wmem_addr_{p};")
        a(f"assign wmem_addr_{p} = wmem_we_{p} ? w_addr : addr;")
        a(f"wire [{data_width-1}:0] w_val_{p};")
        a(f"single_port_ram #(.ADDR_WIDTH({W_ADDR_W}), .DATA_WIDTH({data_width})) w_mem_{p} (")
        a(f"    .clk(clk), .addr(wmem_addr_{p}), .data(w_data), .we(wmem_we_{p}), .out(w_val_{p})")
        a(f");")
        a(f"")

    # Multipliers — use * operator (Parmys maps $mul → DSP)
    a(f"// ── Multipliers: {data_width}×{data_width} → {PROD_W} (DSP mult_9x9) ──")
    for p in range(P):
        a(f"wire [{PROD_W-1}:0] prod_{p};")
        a(f"assign prod_{p} = data_in * w_val_{p};")
    a(f"")

    # Accumulators
    a(f"// ── Accumulators ──")
    for p in range(P):
        a(f"reg signed [{ACC_W-1}:0] acc_{p};")
    a(f"")

    a(f"always @(posedge clk) begin")
    a(f"    if (acc_clear) begin")
    for p in range(P):
        a(f"        acc_{p} <= {ACC_W}'d0;")
    a(f"    end else if (acc_en) begin")
    for p in range(P):
        a(f"        acc_{p} <= acc_{p} + {{{{({ACC_W}-{PROD_W}){{prod_{p}[{PROD_W-1}]}}}}, prod_{p}}};")
    a(f"    end")
    a(f"end")
    a(f"")

    # Output mux — select one accumulator based on addr lower bits
    a(f"// ── Output: saturate selected accumulator to int8 ──")
    a(f"reg signed [{ACC_W-1}:0] sel_acc;")
    a(f"always @(*) begin")
    a(f"    case (addr[{OUT_W-1}:0])")
    for p in range(P):
        a(f"    {OUT_W}'d{p}: sel_acc = acc_{p};")
    a(f"    default: sel_acc = {ACC_W}'d0;")
    a(f"    endcase")
    a(f"end")
    a(f"")
    a(f"always @(posedge clk)")
    a(f"    data_out <= (sel_acc > {ACC_W}'sd127) ? {data_width}'d127 :")
    a(f"               (sel_acc < -{ACC_W}'sd128) ? -{data_width}'sd128 :")
    a(f"               sel_acc[{data_width-1}:0];")
    a(f"")
    a(f"endmodule")

    # Write output
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{module_name}.v"
    out_path.write_text("\n".join(lines) + "\n")

    latency_cycles = K * BATCHES + P  # K*batches compute + P output
    print(f"  Generated {module_name}.v (K={K}, N={N}, P={P}, "
          f"batches={BATCHES}, latency={latency_cycles} cycles, "
          f"DSPs~{math.ceil(P/4)}, BRAMs~{P})")
    return out_path


# ── CLI ───────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate DSP-based FC (GEMV) wrappers for VTR"
    )
    parser.add_argument("--K", type=int, required=True, help="Input dimension")
    parser.add_argument("--N", type=int, required=True, help="Output dimension")
    parser.add_argument("--output-dir", type=str, default=".", help="Output directory")
    parser.add_argument("--max-parallel", type=int, default=MAX_PARALLEL,
                        help=f"Max parallel MAC channels (default: {MAX_PARALLEL})")
    args = parser.parse_args()
    gen_dsp_fc_wrapper(args.K, args.N, output_dir=args.output_dir,
                       max_parallel=args.max_parallel)
