"""Generate Azure-Lily attention-head top RTL matching the IMC simulator's
``attention_model`` definition (no output projection).

Composition (W=16 DIMM lanes, N=128 tokens, d_head=64, K=128, EPW_DSP=4):

    data_in_x ─► outer FSM that re-resets fc_q/k/v 128 times to push N tokens
              ├─► fc_q_inst : azurelily_fc_128_64  ─► valid_n stream (1 int8/cyc)
              ├─► fc_k_inst : azurelily_fc_128_64
              └─► fc_v_inst : azurelily_fc_128_64
                                    │
                  pack5_buffer x 3 ─┤  (5 int8/cyc → packed 40-bit, EPW=5)
                                    ▼
                          q_buffer / k_buffer / v_buffer (SRAM, depth = N⌈d/5⌉ + 1)
                                    │
                                    ▼
                       azurelily_dimm_top (W=16, fires once over full Q/K/V)
                                    │
                                    ▼
                          [data_out, valid_n]   (no O projection — matches sim
                                                  attention_model which stops at mac_sv)

Format mismatch resolved here:
    - AL FC emits unpacked 1 int8 / cycle (low byte of 40-bit data_out).
    - AL DIMM threshold uses EPW=5 (q_w_addr >= 13 == ⌈64/5⌉).  This is a
      pre-existing inconsistency in the AL DIMM generator (dsp_mac internally
      reads 4 int8 lanes), but downstream RTL must match the threshold.
    - pack5_buffer accumulates 5 consecutive bytes into one 40-bit packed
      word and emits one packed write per 5 valid_in cycles.

Generator usage:
    python3 gen_azurelily_attn_head_top.py --output-dir fc_verification/rtl/

Compile smoke test:
    iverilog -o /tmp/smoke \\
        fc_verification/rtl/azurelily_attn_head_d64_c128.v \\
        fc_verification/rtl/azurelily_dimm_top_d64_c128.v \\
        fc_verification/rtl/azurelily/azurelily_fc_128_64.v
    (Do NOT pass azurelily_fc_stubs.v — duplicate dsp_mac/sram defs collide
     with the inline ones in azurelily_dimm_top_d64_c128.v.)
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path


def gen_azurelily_attn_head_top(
    d_model: int = 128,
    d_head: int = 64,
    n_seq: int = 128,
    w_lanes: int = 16,
    data_width: int = 40,
    epw_pack: int = 5,
    output_dir: Path = Path("."),
) -> Path:
    """Emit fc_verification/rtl/azurelily_attn_head_d64_c128.v.

    Args:
        d_model:    input token dim (K of Q/K/V projection FC)            [128]
        d_head:     output head dim (N of Q/K/V projection FC)            [64]
        n_seq:      sequence length (number of tokens to push through)    [128]
        w_lanes:    DIMM parallel lane count                              [16]
        data_width: packed word width                                     [40]
        epw_pack:   packing rate (int8 per packed word) for buffer SRAMs  [5]
        output_dir: directory to write RTL into.
    """
    EPW_DSP = 4                              # FC int_sop_4 lane count
    PACKED_K = math.ceil(d_model / EPW_DSP)  # FC input SRAM depth = 32
    PACKED_D = math.ceil(d_head / epw_pack)  # 13
    BUF_DEPTH = n_seq * PACKED_D + 1         # 128*13 + 1 = 1665

    fc_module = f"azurelily_fc_{d_model}_{d_head}"
    top_name = f"azurelily_attn_head_d{d_head}_c{d_model}"

    # Address widths
    pack_cnt_w = max(1, math.ceil(math.log2(epw_pack + 1)))       # 0..EPW
    buf_addr_w = max(1, math.ceil(math.log2(BUF_DEPTH + 1)))      # ~12 bits
    tok_cnt_w = max(1, math.ceil(math.log2(n_seq + 1)))           # ~8 bits
    feed_cnt_w = max(1, math.ceil(math.log2(PACKED_K + 2)))       # ~6 bits
    out_cnt_w = max(1, math.ceil(math.log2(d_head + 1)))          # ~7 bits

    rtl = f"""// Azure-Lily Attention Head Top — matches IMC attention_model (no O proj)
// Generated by gen_azurelily_attn_head_top.py
//   d_model={d_model}, d_head={d_head}, N_SEQ={n_seq}, W={w_lanes}, EPW_DSP={EPW_DSP}
//
// Architecture (mirrors azurelily/models/attention.py attention_model):
//   N tokens × (Q/K/V projection FC) → pack5_buffer → Q/K/V SRAM buffers
//   → azurelily_dimm_top (W=16 lanes, single fire over full N×d Q/K/V) → out
//
// NO output projection — sim's attention_model stops at mac_sv.
//
// Composition:
//   - 3 × azurelily_fc_128_64       (Q/K/V proj, fired N={n_seq} times each)
//   - 3 × pack5_buffer              (Q/K/V unpacked→packed converters)
//   - 3 × sram (Q/K/V buffer)       (depth = N⌈d_head/5⌉ + 1 = {BUF_DEPTH})
//   - 1 × azurelily_dimm_top        (W={w_lanes} lanes, fires once)
//
// Outer FSM (state names + transitions):
//   S_IDLE          : await valid_x → S_LOAD_TOKEN
//   S_LOAD_TOKEN    : forward {PACKED_K} packed input words/token to FC.valid
//                     → S_WAIT_FC after PACKED_K cycles
//   S_WAIT_FC       : assert FC valid quiet; collect FC valid_n stream into
//                     pack5_buffer (handled combinationally from FC valid_n)
//                     → S_FC_DRAIN once FC has emitted d_head valid_n bytes
//   S_FC_DRAIN      : safety drain so packer flushes; → S_INTER_TOKEN_RST
//   S_INTER_TOKEN_RST: pulse fc_rst high one cycle to reset FC FSMs; advance
//                     token_count.  → S_LOAD_TOKEN if more tokens; else S_DIMM_FIRE
//   S_DIMM_FIRE     : DIMM auto-fires once thresholds met (handled inside
//                     azurelily_dimm_top); we just gate ready_x = 0 here.
//   S_DRAIN         : DIMM emits valid_n stream → output port.
//
// Format note: AL DIMM's S_LOAD threshold uses EPW=5 (q_w_addr >= 13,
// k_w_addr/v_w_addr >= 1664).  This is a pre-existing inconsistency in
// gen_dimm_azurelily_top.py vs dsp_mac (which reads EPW=4 lanes) — DO NOT
// FIX HERE.  pack5_buffer matches the EPW=5 threshold semantics.

`timescale 1ns / 1ps

module {top_name} #(
    parameter DATA_WIDTH = {data_width},
    parameter D_MODEL    = {d_model},
    parameter D_HEAD     = {d_head},
    parameter N_SEQ      = {n_seq},
    parameter W          = {w_lanes}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);
    localparam PACKED_K  = {PACKED_K};   // FC input packed words per token
    localparam PACKED_D  = {PACKED_D};   // packed Q/K/V words per token (EPW=5)
    localparam BUF_DEPTH = {BUF_DEPTH};  // total packed Q/K/V words across N tokens

    // ───────── outer FSM state encoding ─────────
    localparam S_IDLE             = 4'd0;
    localparam S_LOAD_TOKEN       = 4'd1;
    localparam S_WAIT_FC          = 4'd2;
    localparam S_FC_DRAIN         = 4'd3;
    localparam S_INTER_TOKEN_RST  = 4'd4;
    localparam S_DIMM_FIRE        = 4'd5;
    localparam S_DRAIN            = 4'd6;
    reg [3:0] state;

    reg [{tok_cnt_w - 1}:0] token_count;
    reg [{feed_cnt_w - 1}:0] feed_count;     // 0..PACKED_K within current token feed
    reg [{out_cnt_w - 1}:0]  fc_byte_count;  // 0..D_HEAD within current FC token output
    reg                      fc_rst_pulse;   // one-cycle reset to FC arms

    wire fc_rst = rst | fc_rst_pulse;

    // ───────── valid + data into FCs ─────────
    wire fc_valid_in = (state == S_LOAD_TOKEN);
    wire [DATA_WIDTH-1:0] fc_data_in = data_in_x;

    // FC outputs (1 int8 in low byte of 40-bit valid_n word)
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    {fc_module} fc_q_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(q_fc_out), .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    {fc_module} fc_k_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(k_fc_out), .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    {fc_module} fc_v_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(v_fc_out), .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ───────── pack5_buffer x 3 (Q/K/V) ─────────
    // Each takes 1 int8/cycle (FC valid_n), emits one packed 40-bit word
    // every {epw_pack} valid_in cycles to its Q/K/V buffer SRAM.
    wire q_buf_w_en, k_buf_w_en, v_buf_w_en;
    wire [{buf_addr_w - 1}:0] q_buf_w_addr, k_buf_w_addr, v_buf_w_addr;
    wire [DATA_WIDTH-1:0]     q_buf_w_data, k_buf_w_data, v_buf_w_data;

    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W({buf_addr_w}), .EPW({epw_pack}))
        q_packer (.clk(clk), .rst(rst),
                  .valid_in(q_fc_valid_n), .data_in(q_fc_out),
                  .w_en(q_buf_w_en), .w_addr(q_buf_w_addr),
                  .sram_data_in(q_buf_w_data));
    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W({buf_addr_w}), .EPW({epw_pack}))
        k_packer (.clk(clk), .rst(rst),
                  .valid_in(k_fc_valid_n), .data_in(k_fc_out),
                  .w_en(k_buf_w_en), .w_addr(k_buf_w_addr),
                  .sram_data_in(k_buf_w_data));
    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W({buf_addr_w}), .EPW({epw_pack}))
        v_packer (.clk(clk), .rst(rst),
                  .valid_in(v_fc_valid_n), .data_in(v_fc_out),
                  .w_en(v_buf_w_en), .w_addr(v_buf_w_addr),
                  .sram_data_in(v_buf_w_data));

    // ───────── Q/K/V buffer SRAMs ─────────
    // Read side: streamed out as DIMM input during S_DIMM_FIRE.
    reg [{buf_addr_w - 1}:0] q_buf_r_addr, k_buf_r_addr, v_buf_r_addr;
    wire [DATA_WIDTH-1:0]    q_buf_r_data, k_buf_r_data, v_buf_r_data;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        q_buf (.clk(clk), .rst(rst), .w_en(q_buf_w_en),
               .r_addr(q_buf_r_addr), .w_addr(q_buf_w_addr),
               .sram_data_in(q_buf_w_data), .sram_data_out(q_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        k_buf (.clk(clk), .rst(rst), .w_en(k_buf_w_en),
               .r_addr(k_buf_r_addr), .w_addr(k_buf_w_addr),
               .sram_data_in(k_buf_w_data), .sram_data_out(k_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        v_buf (.clk(clk), .rst(rst), .w_en(v_buf_w_en),
               .r_addr(v_buf_r_addr), .w_addr(v_buf_w_addr),
               .sram_data_in(v_buf_w_data), .sram_data_out(v_buf_r_data));

    // ───────── DIMM inputs (replay buffered Q/K/V into DIMM stream) ─────────
    reg [{buf_addr_w - 1}:0] dimm_replay_count;
    wire dimm_replay_active = (state == S_DIMM_FIRE);
    wire dimm_valid_q = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);
    wire dimm_valid_k = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);
    wire dimm_valid_v = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);

    // ───────── DIMM (W=16 lanes, mac_qk + clb_softmax + mac_sv) ─────────
    wire [DATA_WIDTH-1:0] dimm_out;
    wire dimm_valid_n_w;
    azurelily_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH)
    ) dimm_inst (
        .clk(clk), .rst(rst),
        .valid_q(dimm_valid_q), .valid_k(dimm_valid_k), .valid_v(dimm_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_r_data), .data_in_k(k_buf_r_data), .data_in_v(v_buf_r_data),
        .data_out(dimm_out),
        .ready_q(), .ready_k(), .ready_v(),
        .valid_n(dimm_valid_n_w)
    );

    // ───────── outer FSM body ─────────
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state             <= S_IDLE;
            token_count       <= 0;
            feed_count        <= 0;
            fc_byte_count     <= 0;
            fc_rst_pulse      <= 1'b0;
            dimm_replay_count <= 0;
            q_buf_r_addr      <= 0;
            k_buf_r_addr      <= 0;
            v_buf_r_addr      <= 0;
        end else begin
            fc_rst_pulse <= 1'b0;  // default; pulsed in S_INTER_TOKEN_RST
            case (state)
                S_IDLE: begin
                    if (valid_x) begin
                        state         <= S_LOAD_TOKEN;
                        token_count   <= 0;
                        feed_count    <= 0;
                        fc_byte_count <= 0;
                    end
                end
                S_LOAD_TOKEN: begin
                    // FC.S_LOAD samples valid for PACKED_K cycles to fill input SRAM.
                    if (feed_count == PACKED_K - 1) begin
                        state      <= S_WAIT_FC;
                        feed_count <= 0;
                    end else begin
                        feed_count <= feed_count + 1;
                    end
                end
                S_WAIT_FC: begin
                    // FC enters S_COMPUTE → S_OUTPUT, emits D_HEAD valid_n bytes.
                    // Packers absorb the stream automatically.
                    if (q_fc_valid_n) begin
                        if (fc_byte_count == D_HEAD - 1) begin
                            state         <= S_FC_DRAIN;
                            fc_byte_count <= 0;
                        end else begin
                            fc_byte_count <= fc_byte_count + 1;
                        end
                    end
                end
                S_FC_DRAIN: begin
                    // One-cycle settle so the last packer write commits.
                    state <= S_INTER_TOKEN_RST;
                end
                S_INTER_TOKEN_RST: begin
                    // Pulse FC reset so the FC arms can accept the next token.
                    fc_rst_pulse <= 1'b1;
                    if (token_count == N_SEQ - 1) begin
                        state             <= S_DIMM_FIRE;
                        token_count       <= 0;
                        dimm_replay_count <= 0;
                        q_buf_r_addr      <= 0;
                        k_buf_r_addr      <= 0;
                        v_buf_r_addr      <= 0;
                    end else begin
                        state       <= S_LOAD_TOKEN;
                        token_count <= token_count + 1;
                        feed_count  <= 0;
                    end
                end
                S_DIMM_FIRE: begin
                    // Stream packed Q/K/V buffer into DIMM (q/k/v_w_addr inside
                    // DIMM increments while valid_q/k/v are high).
                    if (dimm_replay_count < BUF_DEPTH - 1) begin
                        q_buf_r_addr      <= dimm_replay_count;
                        k_buf_r_addr      <= dimm_replay_count;
                        v_buf_r_addr      <= dimm_replay_count;
                        dimm_replay_count <= dimm_replay_count + 1;
                    end else begin
                        state <= S_DRAIN;
                    end
                end
                S_DRAIN: begin
                    // Hold here; DIMM internally drives valid_n through W lanes.
                    // Top exits to S_IDLE only via top-level rst (one-shot run).
                    state <= S_DRAIN;
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ───────── outputs ─────────
    assign data_out = dimm_out;
    assign valid_n  = dimm_valid_n_w;
    assign ready_x  = (state == S_IDLE) || (state == S_LOAD_TOKEN);

endmodule

// ════ pack5_buffer ════
//
// Accumulates {epw_pack} consecutive int8 bytes (low byte of data_in[39:0]) into
// a packed 40-bit word, emitting one packed write to the buffer SRAM every
// {epw_pack} valid_in cycles.  Bytes are placed in increasing-byte order:
//
//   word[ 7: 0] = byte 0 (first input)
//   word[15: 8] = byte 1
//   word[23:16] = byte 2
//   word[31:24] = byte 3
//   word[39:32] = byte 4 (last input)
//
// The packer is purely a write-side helper: it drives w_en, w_addr, sram_data_in.
// It does NOT own the SRAM (the parent instantiates the buffer SRAM).
//
// Reset semantics: rst clears the partial register, w_addr, and pack_count.

module pack5_buffer #(
    parameter DATA_WIDTH = {data_width},
    parameter ADDR_W     = {buf_addr_w},
    parameter EPW        = {epw_pack}
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_in,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg                     w_en,
    output reg  [ADDR_W-1:0]       w_addr,
    output reg  [DATA_WIDTH-1:0]   sram_data_in
);
    reg [{pack_cnt_w - 1}:0] pack_count;       // 0..EPW-1
    reg [DATA_WIDTH-1:0]     pack_reg;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            pack_count   <= 0;
            pack_reg     <= 0;
            w_en         <= 0;
            w_addr       <= 0;
            sram_data_in <= 0;
        end else begin
            w_en <= 0;  // default; raised exactly when we emit a packed word
            if (valid_in) begin
                // Insert low byte of data_in into byte-position pack_count.
                case (pack_count)
                    {pack_cnt_w}'d0: pack_reg[ 7: 0] <= data_in[7:0];
                    {pack_cnt_w}'d1: pack_reg[15: 8] <= data_in[7:0];
                    {pack_cnt_w}'d2: pack_reg[23:16] <= data_in[7:0];
                    {pack_cnt_w}'d3: pack_reg[31:24] <= data_in[7:0];
                    {pack_cnt_w}'d4: pack_reg[39:32] <= data_in[7:0];
                    default: ;
                endcase

                if (pack_count == EPW - 1) begin
                    // Emit packed word: assemble combinationally so the
                    // commit happens the same cycle as the 5th byte arrives.
                    sram_data_in <= {{ data_in[7:0],
                                       pack_reg[31:24],
                                       pack_reg[23:16],
                                       pack_reg[15: 8],
                                       pack_reg[ 7: 0] }};
                    w_en         <= 1;
                    pack_count   <= 0;
                    if (w_addr != {{ADDR_W{{1'b1}}}}) w_addr <= w_addr + 1;
                end else begin
                    pack_count <= pack_count + 1;
                end
            end
        end
    end
endmodule
"""

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{top_name}.v"
    out_path.write_text(rtl)
    print(f"  Generated {top_name}.v "
          f"(d_model={d_model}, d_head={d_head}, N_SEQ={n_seq}, W={w_lanes}, "
          f"BUF_DEPTH={BUF_DEPTH}, PACKED_K={PACKED_K}, PACKED_D={PACKED_D})")
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Azure-Lily attention head top RTL "
                    "(matches IMC attention_model — no O projection)"
    )
    parser.add_argument("--d-model", type=int, default=128,
                        help="Input token dim (FC K)  [128]")
    parser.add_argument("--d-head", type=int, default=64,
                        help="Per-head output dim (FC N)  [64]")
    parser.add_argument("--n-seq", type=int, default=128,
                        help="Sequence length (number of tokens)  [128]")
    parser.add_argument("--w-lanes", type=int, default=16,
                        help="DIMM parallel lane count  [16]")
    parser.add_argument("--data-width", type=int, default=40,
                        help="Packed word width  [40]")
    parser.add_argument("--epw-pack", type=int, default=5,
                        help="Buffer packing rate (int8/word)  [5]")
    parser.add_argument("--output-dir", type=Path,
                        default=Path("fc_verification/rtl/"),
                        help="Output directory")
    args = parser.parse_args()
    gen_azurelily_attn_head_top(
        d_model=args.d_model, d_head=args.d_head, n_seq=args.n_seq,
        w_lanes=args.w_lanes, data_width=args.data_width,
        epw_pack=args.epw_pack, output_dir=args.output_dir,
    )
