#!/usr/bin/env python3
"""Generate the NL-DPE attention-head top RTL (no output projection).

Composition matches the IMC simulator's `attention_model` definition:

    [valid_x, data_in_x] ──► fc_top_qkv_streaming ×3 (Q/K/V projections)
                                 │     │     │
                                 ▼     ▼     ▼
                              q_buf  k_buf  v_buf  (sram, depth = N×PACKED_NQ+1)
                                 │     │     │
                                 └─────┴─────┘
                                       ▼
                              nldpe_dimm_top (W=16 lanes, 1 fire)
                                       ▼
                                [data_out, valid_n]

For N=128 input tokens of d_model=128, the FCs run as streaming
ping-pong pairs (2 DPEs per arm, dpe_a/dpe_b), absorbing one packed
input word per cycle and producing one packed output word per cycle
in steady state. Total linear-QKV stage cycles ≈ N × PACKED_KQ =
3328 cyc + initial latency, well below the 4000-cyc bound.

The buffered Q/K/V tensors are then replayed into the DIMM top,
which fires once to produce the N × d_head packed attention
output stream.

Locked design parameters:
  d_model = 128
  d_head  = 64
  N_SEQ   = 128
  C       = 128 (crossbar cols)
  W       = 16  (DIMM lanes)
  K_qkt   = 2   (= C / d_head)
  K_sv    = 1
  EPW     = 5   (elements per 40-bit packed word)
  PACKED_KQ = ceil(d_model/EPW) = 26 (input words per FC inference)
  PACKED_NQ = ceil(d_head/EPW)  = 13 (output words per FC inference)

Resource expectation (verified by grep on emitted RTL):
  - 3 × fc_top_qkv_streaming (Q/K/V arms; 2 DPEs each) — instances
                               fc_q_inst, fc_k_inst, fc_v_inst
  - 3 × sram (q/k/v buffers)    — instances q_buffer, k_buffer, v_buffer
  - 1 × nldpe_dimm_top          — instance dimm_inst
  - 0 × fc_top_o (NO output projection; sim's attention_model stops at mac_sv)

Top-level FSM (5 states):
  S_IDLE       → wait for valid_x rising edge
  S_FEED_X     → ready_x=1; pipe X to all 3 FCs for N×PACKED_KQ cycles;
                 capture FC outputs into q/k/v_buffers as their valid_n fire
  S_DRAIN_FC   → wait for in-flight FC outputs to settle (count = N×PACKED_NQ)
  S_FIRE_DIMM  → drive valid_q (14 cycles, 1 query worth), then valid_k (1664
                 cycles, full K tensor), then valid_v (1664 cycles, full V
                 tensor); buffer read-addresses advance accordingly
  S_OUTPUT     → forward DIMM data_out / valid_n to top-level outputs

iverilog smoke-compile target:
  iverilog -o /tmp/smoke fc_verification/rtl/nldpe_attn_head_d64_c128.v   \
                         fc_verification/rtl/nldpe_dimm_top_d64_c128.v    \
                         fc_verification/rtl/nldpe/fc_top_qkv_streaming.v \
                         fc_verification/dpe_stub.v

Usage:
    python3 nl_dpe/gen_nldpe_attn_head_top.py --output-dir fc_verification/rtl/
"""

import argparse
import math
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────
# Locked design constants
# ─────────────────────────────────────────────────────────────────────────
DATA_WIDTH = 40
D_MODEL    = 128
D_HEAD     = 64
N_SEQ      = 128
C          = 128
W_LANES    = 16
EPW        = 5  # elements per 40-bit packed word

PACKED_KQ  = math.ceil(D_MODEL / EPW)  # 26 — input words / FC inference
PACKED_NQ  = math.ceil(D_HEAD  / EPW)  # 13 — output words / FC inference

# DIMM ingest counts (matched against existing nldpe_dimm_top FSM):
DIMM_Q_WORDS = 14                 # score_matrix S_LOAD_Q exits when q_write_addr==13
DIMM_K_WORDS = 1664               # full K tensor (128 keys × 13 packed)
DIMM_V_WORDS = 1664               # full V tensor (128 vals × 13 packed)


def render_top_module(out_path: Path) -> None:
    """Emit the nldpe_attn_head_d64_c128 top module."""

    n_x_input_words   = N_SEQ * PACKED_KQ          # 128 × 26 = 3328
    n_fc_output_words = N_SEQ * PACKED_NQ          # 128 × 13 = 1664
    buffer_depth      = n_fc_output_words + 1      # 1665 (matches DIMM k/v sram depth)

    # Address widths
    aw_in   = max(1, math.ceil(math.log2(n_x_input_words   + 1)))   # 12
    aw_buf  = max(1, math.ceil(math.log2(buffer_depth          )))  # 11
    aw_dimm = max(1, math.ceil(math.log2(max(DIMM_K_WORDS,
                                              DIMM_V_WORDS) + 1)))  # 11

    rtl = []
    rtl.append("// NL-DPE Attention Head Top — Q/K/V projections + buffers + DIMM")
    rtl.append("// AUTO-GENERATED by nl_dpe/gen_nldpe_attn_head_top.py — DO NOT EDIT BY HAND")
    rtl.append("//")
    rtl.append("// Composition (matches IMC sim's attention_model — no output projection):")
    rtl.append("//")
    rtl.append("//   [valid_x, data_in_x] ──► fc_top_qkv_streaming ×3 (Q/K/V; 2 DPEs each)")
    rtl.append("//                                │     │     │")
    rtl.append("//                                ▼     ▼     ▼")
    rtl.append("//                             q_buf k_buf v_buf  (sram)")
    rtl.append("//                                │     │     │")
    rtl.append("//                                └─────┴─────┘")
    rtl.append("//                                      ▼")
    rtl.append("//                             nldpe_dimm_top (W=16 lanes, 1 fire)")
    rtl.append("//                                      ▼")
    rtl.append("//                                [data_out, valid_n]")
    rtl.append("//")
    rtl.append("// Locked parameters (see gen_nldpe_attn_head_top.py for derivation):")
    rtl.append(f"//   d_model={D_MODEL}, d_head={D_HEAD}, N_SEQ={N_SEQ}, C={C}, W={W_LANES}")
    rtl.append(f"//   PACKED_KQ={PACKED_KQ} (input words/inference)")
    rtl.append(f"//   PACKED_NQ={PACKED_NQ} (output words/inference)")
    rtl.append("//")
    rtl.append("// Resource expectation:")
    rtl.append("//   - 3 × fc_top_qkv_streaming (instances: fc_q_inst, fc_k_inst, fc_v_inst;")
    rtl.append("//                               2 DPEs each via ping-pong)")
    rtl.append("//   - 3 × sram                 (instances: q_buffer, k_buffer, v_buffer)")
    rtl.append("//   - 1 × nldpe_dimm_top       (instance:  dimm_inst)")
    rtl.append("//   - 0 × fc_top_o             (NO output projection)")
    rtl.append("//")
    rtl.append("// Module dependencies (compile together with this file):")
    rtl.append("//   - fc_verification/rtl/nldpe_dimm_top_d64_c128.v")
    rtl.append("//   - fc_verification/rtl/nldpe/fc_top_qkv_streaming.v")
    rtl.append("//   - fc_verification/dpe_stub.v")
    rtl.append("")
    rtl.append("`timescale 1ns / 1ps")
    rtl.append("")
    rtl.append("module nldpe_attn_head_d64_c128 #(")
    rtl.append(f"    parameter DATA_WIDTH = {DATA_WIDTH},")
    rtl.append(f"    parameter D_MODEL    = {D_MODEL},")
    rtl.append(f"    parameter D_HEAD     = {D_HEAD},")
    rtl.append(f"    parameter N_SEQ      = {N_SEQ},")
    rtl.append(f"    parameter C          = {C},")
    rtl.append(f"    parameter W          = {W_LANES}")
    rtl.append(")(")
    rtl.append("    input  wire                    clk,")
    rtl.append("    input  wire                    rst,")
    rtl.append("    input  wire                    valid_x,")
    rtl.append("    input  wire [DATA_WIDTH-1:0]   data_in_x,")
    rtl.append("    input  wire                    ready_n,")
    rtl.append("    output wire [DATA_WIDTH-1:0]   data_out,")
    rtl.append("    output wire                    ready_x,")
    rtl.append("    output wire                    valid_n")
    rtl.append(");")
    rtl.append("")
    rtl.append("    // ─── Local constants (must match generator) ────────────────────")
    rtl.append(f"    localparam PACKED_KQ        = {PACKED_KQ}; // ceil(d_model/EPW), in words")
    rtl.append(f"    localparam PACKED_NQ        = {PACKED_NQ}; // ceil(d_head/EPW),  in words")
    rtl.append(f"    localparam N_X_INPUT_WORDS  = {n_x_input_words};   // N × PACKED_KQ")
    rtl.append(f"    localparam N_FC_OUT_WORDS   = {n_fc_output_words}; // N × PACKED_NQ")
    rtl.append(f"    localparam BUFFER_DEPTH     = {buffer_depth};      // N × PACKED_NQ + 1")
    rtl.append(f"    localparam DIMM_Q_WORDS     = {DIMM_Q_WORDS};")
    rtl.append(f"    localparam DIMM_K_WORDS     = {DIMM_K_WORDS};")
    rtl.append(f"    localparam DIMM_V_WORDS     = {DIMM_V_WORDS};")
    rtl.append("")
    rtl.append("    // ─── FSM ───────────────────────────────────────────────────────")
    rtl.append("    // Bug-1 fix (2026-04-25): outer Q-row loop. The DIMM internally")
    rtl.append("    // computes ONE Q row's full attention output (mac_qk + softmax +")
    rtl.append("    // mac_sv across all N keys) per fire. To run a full N×N attention")
    rtl.append("    // head we now loop S_FIRE_DIMM N times, soft-resetting the DIMM")
    rtl.append("    // between iterations and re-driving valid_q (with each Q row read")
    rtl.append("    // from the head's q_buffer) plus valid_k / valid_v (re-loaded from")
    rtl.append("    // the static k/v_buffer; SRAM contents persist through DIMM rst).")
    rtl.append("    localparam S_IDLE        = 4'd0;")
    rtl.append("    localparam S_FEED_X      = 4'd1;")
    rtl.append("    localparam S_DRAIN_FC    = 4'd2;")
    rtl.append("    localparam S_DIMM_RST    = 4'd3;  // hold DIMM in soft rst between Q rows")
    rtl.append("    localparam S_FIRE_DIMM   = 4'd4;  // drive valid_q/k/v for one Q row")
    rtl.append("    localparam S_DIMM_WAIT   = 4'd5;  // wait for DIMM to produce valid_n")
    rtl.append("    localparam S_OUTPUT      = 4'd6;")
    rtl.append("    reg [3:0] state;")
    rtl.append("")
    rtl.append(f"    reg [{aw_in - 1}:0] in_count;       // X words consumed (0..N_X_INPUT_WORDS)")
    rtl.append(f"    reg [{aw_buf - 1}:0] write_addr;    // q/k/v_buffer write address")
    rtl.append(f"    reg [{aw_buf - 1}:0] read_addr;     // q/k/v_buffer read address")
    rtl.append(f"    reg [{aw_dimm - 1}:0] dimm_q_count; // valid_q pulses already issued")
    rtl.append(f"    reg [{aw_dimm - 1}:0] dimm_k_count; // valid_k pulses already issued")
    rtl.append(f"    reg [{aw_dimm - 1}:0] dimm_v_count; // valid_v pulses already issued")
    rtl.append("    reg drive_valid_q, drive_valid_k, drive_valid_v;")
    rtl.append("    // Bug-1 fix: outer-loop Q-row counter and DIMM soft-rst pulse")
    rtl.append("    reg [7:0] q_row_idx;            // 0..N-1 over Q rows")
    rtl.append("    reg [3:0] dimm_rst_count;       // S_DIMM_RST hold counter")
    rtl.append("    reg dimm_soft_rst;              // pulses high during S_DIMM_RST")
    rtl.append("")
    rtl.append("    // ─── Q/K/V projection arms ─────────────────────────────────────")
    rtl.append("    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;")
    rtl.append("    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;")
    rtl.append("    wire q_fc_ready,   k_fc_ready,   v_fc_ready;")
    rtl.append("")
    rtl.append("    wire feed_x_now = (state == S_FEED_X) && valid_x;")
    rtl.append("")
    rtl.append("    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_q_inst (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .valid(feed_x_now), .ready_n(1'b0),")
    rtl.append("        .data_in(data_in_x),")
    rtl.append("        .data_out(q_fc_out),")
    rtl.append("        .ready(q_fc_ready), .valid_n(q_fc_valid_n)")
    rtl.append("    );")
    rtl.append("    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_k_inst (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .valid(feed_x_now), .ready_n(1'b0),")
    rtl.append("        .data_in(data_in_x),")
    rtl.append("        .data_out(k_fc_out),")
    rtl.append("        .ready(k_fc_ready), .valid_n(k_fc_valid_n)")
    rtl.append("    );")
    rtl.append("    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_v_inst (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .valid(feed_x_now), .ready_n(1'b0),")
    rtl.append("        .data_in(data_in_x),")
    rtl.append("        .data_out(v_fc_out),")
    rtl.append("        .ready(v_fc_ready), .valid_n(v_fc_valid_n)")
    rtl.append("    );")
    rtl.append("")
    rtl.append("    // ─── Q/K/V buffers (sram, depth = N × PACKED_NQ + 1) ────────────")
    rtl.append("    // write_addr increments on each FC valid_n; read_addr increments")
    rtl.append("    // when DIMM is driven from the corresponding buffer.")
    rtl.append("    wire [DATA_WIDTH-1:0] q_buf_out, k_buf_out, v_buf_out;")
    rtl.append("")
    rtl.append("    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))")
    rtl.append("    q_buffer (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .w_en(q_fc_valid_n),")
    rtl.append("        .r_addr(read_addr),")
    rtl.append("        .w_addr(write_addr),")
    rtl.append("        .sram_data_in(q_fc_out),")
    rtl.append("        .sram_data_out(q_buf_out)")
    rtl.append("    );")
    rtl.append("    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))")
    rtl.append("    k_buffer (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .w_en(k_fc_valid_n),")
    rtl.append("        .r_addr(read_addr),")
    rtl.append("        .w_addr(write_addr),")
    rtl.append("        .sram_data_in(k_fc_out),")
    rtl.append("        .sram_data_out(k_buf_out)")
    rtl.append("    );")
    rtl.append("    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))")
    rtl.append("    v_buffer (")
    rtl.append("        .clk(clk), .rst(rst),")
    rtl.append("        .w_en(v_fc_valid_n),")
    rtl.append("        .r_addr(read_addr),")
    rtl.append("        .w_addr(write_addr),")
    rtl.append("        .sram_data_in(v_fc_out),")
    rtl.append("        .sram_data_out(v_buf_out)")
    rtl.append("    );")
    rtl.append("")
    rtl.append("    // Track the number of FC valid_n pulses observed (Q is canonical;")
    rtl.append("    // K/V fire in lockstep because all 3 FCs share the same `valid`).")
    rtl.append(f"    reg [{aw_buf - 1}:0] fc_out_count;")
    rtl.append("    always @(posedge clk or posedge rst) begin")
    rtl.append("        if (rst) begin")
    rtl.append("            write_addr   <= 0;")
    rtl.append("            fc_out_count <= 0;")
    rtl.append("        end else if (q_fc_valid_n) begin")
    rtl.append("            write_addr   <= write_addr   + 1;")
    rtl.append("            fc_out_count <= fc_out_count + 1;")
    rtl.append("        end")
    rtl.append("    end")
    rtl.append("")
    rtl.append("    // ─── DIMM instance (re-fired N times via soft rst, Bug-1 fix) ──")
    rtl.append("    // dimm_rst_internal pulses high between Q rows so the DIMM's")
    rtl.append("    // FSM resets to S_LOAD_Q while its k_sram/v_sram contents persist")
    rtl.append("    // (regular SRAMs don't clear on rst). Each iteration reloads K/V")
    rtl.append("    // from the head's static k/v_buffer with the same data — idempotent.")
    rtl.append("    wire [DATA_WIDTH-1:0] dimm_data_out;")
    rtl.append("    wire dimm_valid_n;")
    rtl.append("    wire dimm_ready_q, dimm_ready_k, dimm_ready_v;")
    rtl.append("    wire dimm_rst_internal = rst | dimm_soft_rst;")
    rtl.append("")
    rtl.append("    nldpe_dimm_top #(")
    rtl.append("        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH)")
    rtl.append("    ) dimm_inst (")
    rtl.append("        .clk(clk), .rst(dimm_rst_internal),")
    rtl.append("        .valid_q(drive_valid_q), .valid_k(drive_valid_k), .valid_v(drive_valid_v),")
    rtl.append("        .ready_n(ready_n),")
    rtl.append("        .data_in_q(q_buf_out), .data_in_k(k_buf_out), .data_in_v(v_buf_out),")
    rtl.append("        .data_out(dimm_data_out),")
    rtl.append("        .ready_q(dimm_ready_q), .ready_k(dimm_ready_k), .ready_v(dimm_ready_v),")
    rtl.append("        .valid_n(dimm_valid_n)")
    rtl.append("    );")
    rtl.append("")
    rtl.append("    // ─── Top-level FSM (Bug-1 fix: outer Q-row loop) ───────────────")
    rtl.append("    // For each q_row_idx in [0..N-1]:")
    rtl.append("    //   1. S_DIMM_RST  : pulse dimm_soft_rst for a few cycles so the")
    rtl.append("    //                    DIMM's FSM returns to S_IDLE (k/v_sram persists)")
    rtl.append("    //   2. S_FIRE_DIMM : drive valid_q for DIMM_Q_WORDS, then valid_k for")
    rtl.append("    //                    DIMM_K_WORDS, then valid_v for DIMM_V_WORDS.")
    rtl.append("    //                    Q read address starts at q_row_idx * PACKED_NQ.")
    rtl.append("    //   3. S_DIMM_WAIT : wait for dimm_valid_n to rise (DIMM completed")
    rtl.append("    //                    mac_qk + softmax + mac_sv for this Q row); this")
    rtl.append("    //                    ensures every DPE in the pipeline fires before")
    rtl.append("    //                    we re-rst the DIMM for the next Q row.")
    rtl.append("    //   4. If q_row_idx + 1 < N: increment q_row_idx, go back to S_DIMM_RST.")
    rtl.append("    //      Else: transition to S_OUTPUT (final Q row's outputs drain to top).")
    rtl.append(f"    localparam DIMM_RST_CYCLES = 4'd4;   // hold DIMM in soft rst for 4 cyc")
    rtl.append("    always @(posedge clk or posedge rst) begin")
    rtl.append("        if (rst) begin")
    rtl.append("            state          <= S_IDLE;")
    rtl.append("            in_count       <= 0;")
    rtl.append("            read_addr      <= 0;")
    rtl.append("            dimm_q_count   <= 0;")
    rtl.append("            dimm_k_count   <= 0;")
    rtl.append("            dimm_v_count   <= 0;")
    rtl.append("            drive_valid_q  <= 1'b0;")
    rtl.append("            drive_valid_k  <= 1'b0;")
    rtl.append("            drive_valid_v  <= 1'b0;")
    rtl.append("            q_row_idx      <= 0;")
    rtl.append("            dimm_rst_count <= 0;")
    rtl.append("            dimm_soft_rst  <= 1'b0;")
    rtl.append("        end else begin")
    rtl.append("            case (state)")
    rtl.append("                S_IDLE: begin")
    rtl.append("                    if (valid_x) state <= S_FEED_X;")
    rtl.append("                end")
    rtl.append("                S_FEED_X: begin")
    rtl.append("                    if (valid_x) in_count <= in_count + 1;")
    rtl.append("                    if (in_count + 1 == N_X_INPUT_WORDS) begin")
    rtl.append("                        state <= S_DRAIN_FC;")
    rtl.append("                    end")
    rtl.append("                end")
    rtl.append("                S_DRAIN_FC: begin")
    rtl.append("                    // Wait until all PACKED_NQ × N FC outputs are buffered.")
    rtl.append("                    if (fc_out_count >= N_FC_OUT_WORDS) begin")
    rtl.append("                        // Enter Q-row loop. q_row_idx already 0.")
    rtl.append("                        state         <= S_DIMM_RST;")
    rtl.append("                        dimm_rst_count <= 0;")
    rtl.append("                        dimm_soft_rst  <= 1'b0;  // first iteration: no rst needed,")
    rtl.append("                                                   // DIMM is already at S_IDLE post-rst")
    rtl.append("                    end")
    rtl.append("                end")
    rtl.append("                S_DIMM_RST: begin")
    rtl.append("                    // Pulse dimm_soft_rst high for DIMM_RST_CYCLES cycles")
    rtl.append("                    // (skip on q_row_idx==0 since DIMM was just rst by global)")
    rtl.append("                    if (q_row_idx == 0) begin")
    rtl.append("                        // First iteration: DIMM is fresh from global rst, skip soft rst")
    rtl.append("                        state         <= S_FIRE_DIMM;")
    rtl.append("                        read_addr     <= q_row_idx * PACKED_NQ;")
    rtl.append("                        drive_valid_q <= 1'b1;")
    rtl.append("                        dimm_q_count  <= 0;")
    rtl.append("                        dimm_k_count  <= 0;")
    rtl.append("                        dimm_v_count  <= 0;")
    rtl.append("                        dimm_soft_rst <= 1'b0;")
    rtl.append("                    end else begin")
    rtl.append("                        dimm_soft_rst <= 1'b1;")
    rtl.append("                        dimm_rst_count <= dimm_rst_count + 1;")
    rtl.append("                        if (dimm_rst_count + 1 == DIMM_RST_CYCLES) begin")
    rtl.append("                            dimm_soft_rst  <= 1'b0;")
    rtl.append("                            state          <= S_FIRE_DIMM;")
    rtl.append("                            read_addr      <= q_row_idx * PACKED_NQ;")
    rtl.append("                            drive_valid_q  <= 1'b1;")
    rtl.append("                            dimm_q_count   <= 0;")
    rtl.append("                            dimm_k_count   <= 0;")
    rtl.append("                            dimm_v_count   <= 0;")
    rtl.append("                        end")
    rtl.append("                    end")
    rtl.append("                end")
    rtl.append("                S_FIRE_DIMM: begin")
    rtl.append("                    // Phase A: drive valid_q for DIMM_Q_WORDS cycles (Q row).")
    rtl.append("                    // Phase B: drive valid_k for DIMM_K_WORDS cycles (full K).")
    rtl.append("                    // Phase C: drive valid_v for DIMM_V_WORDS cycles (full V).")
    rtl.append("                    // read_addr advances in lockstep with the active phase.")
    rtl.append("                    if (drive_valid_q) begin")
    rtl.append("                        dimm_q_count <= dimm_q_count + 1;")
    rtl.append("                        read_addr    <= read_addr + 1;")
    rtl.append("                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin")
    rtl.append("                            drive_valid_q <= 1'b0;")
    rtl.append("                            drive_valid_k <= 1'b1;")
    rtl.append("                            read_addr     <= 0;")
    rtl.append("                        end")
    rtl.append("                    end else if (drive_valid_k) begin")
    rtl.append("                        dimm_k_count <= dimm_k_count + 1;")
    rtl.append("                        read_addr    <= read_addr + 1;")
    rtl.append("                        if (dimm_k_count + 1 == DIMM_K_WORDS) begin")
    rtl.append("                            drive_valid_k <= 1'b0;")
    rtl.append("                            drive_valid_v <= 1'b1;")
    rtl.append("                            read_addr     <= 0;")
    rtl.append("                        end")
    rtl.append("                    end else if (drive_valid_v) begin")
    rtl.append("                        dimm_v_count <= dimm_v_count + 1;")
    rtl.append("                        read_addr    <= read_addr + 1;")
    rtl.append("                        if (dimm_v_count + 1 == DIMM_V_WORDS) begin")
    rtl.append("                            drive_valid_v <= 1'b0;")
    rtl.append("                            state         <= S_DIMM_WAIT;")
    rtl.append("                        end")
    rtl.append("                    end")
    rtl.append("                end")
    rtl.append("                S_DIMM_WAIT: begin")
    rtl.append("                    // Wait for DIMM to fully complete this Q row.")
    rtl.append("                    // dimm_valid_n is high once any wsum lane reaches WS_OUTPUT,")
    rtl.append("                    // by which time all DPE pipeline stages have fired.")
    rtl.append("                    if (dimm_valid_n) begin")
    rtl.append("                        if (q_row_idx + 1 == N_SEQ) begin")
    rtl.append("                            // Last Q row complete — drain output to top.")
    rtl.append("                            state <= S_OUTPUT;")
    rtl.append("                        end else begin")
    rtl.append("                            // Move to next Q row: soft-reset DIMM, repeat.")
    rtl.append("                            q_row_idx     <= q_row_idx + 1;")
    rtl.append("                            state         <= S_DIMM_RST;")
    rtl.append("                            dimm_rst_count <= 0;")
    rtl.append("                            dimm_soft_rst  <= 1'b1;")
    rtl.append("                        end")
    rtl.append("                    end")
    rtl.append("                end")
    rtl.append("                S_OUTPUT: begin")
    rtl.append("                    // Pass-through: DIMM internally proceeds through")
    rtl.append("                    // mac_qk → softmax → mac_sv and emits valid_n; the")
    rtl.append("                    // top-level outputs are wired directly below.")
    rtl.append("                end")
    rtl.append("                default: state <= S_IDLE;")
    rtl.append("            endcase")
    rtl.append("        end")
    rtl.append("    end")
    rtl.append("")
    rtl.append("    // ─── Top-level handshake / outputs ─────────────────────────────")
    rtl.append("    // Accept new X words only while feeding the FCs.")
    rtl.append("    assign ready_x  = (state == S_FEED_X) && q_fc_ready && k_fc_ready && v_fc_ready;")
    rtl.append("    assign data_out = dimm_data_out;")
    rtl.append("    assign valid_n  = (state == S_OUTPUT) && dimm_valid_n;")
    rtl.append("")
    rtl.append("endmodule")
    rtl.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(rtl))
    print(f"[gen_nldpe_attn_head_top] wrote {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output-dir", required=True,
                        help="Directory to write nldpe_attn_head_d64_c128.v into.")
    parser.add_argument("--filename", default="nldpe_attn_head_d64_c128.v",
                        help="Output filename (default: nldpe_attn_head_d64_c128.v).")
    args = parser.parse_args()

    out_dir  = Path(args.output_dir).resolve()
    out_path = out_dir / args.filename
    render_top_module(out_path)


if __name__ == "__main__":
    main()
