#!/usr/bin/env python3
"""Emit rtl/softmax_luts.vh: exp and reciprocal ROM functions (AL block).

Fixed-point conventions locked in
docs/superpowers/plans/2026-08-05-softmax-study-implementation.md:

  exp ROM   : E8[u] = min(255, int(255*exp(-u/16.0) + 0.5)),  u = max - x in [0,255]
  recip ROM : R8[0] = 255; R8[i] = min(255, (2*256 + i)//(2*i))   (round-half-up 256/i)

Both tables are S-independent; the S-dependent scaling lives in the
R_SHIFT = $clog2(S) shifts inside softmax_al.v.
"""
import math
from pathlib import Path


def e8(u: int) -> int:
    return min(255, int(255 * math.exp(-u / 16.0) + 0.5))


def r8(i: int) -> int:
    return 255 if i == 0 else min(255, (2 * 256 + i) // (2 * i))


def main() -> None:
    lines = [
        "// AUTO-GENERATED by softmax_study/gen_luts.py -- do not edit by hand.",
        "// exp_lut: E8[u] = min(255, round(255*exp(-u/16))), u = max - x (8b unsigned).",
        "// recip_lut: R8[0]=255; R8[i] = min(255, round_half_up(256/i)).",
        "",
        "function [7:0] exp_lut;",
        "    input [7:0] u;",
        "    begin",
        "        case (u)",
    ]
    lines += [f"            8'd{u}: exp_lut = 8'd{e8(u)};" for u in range(256)]
    lines += [
        "        endcase",
        "    end",
        "endfunction",
        "",
        "function [7:0] recip_lut;",
        "    input [7:0] i;",
        "    begin",
        "        case (i)",
    ]
    lines += [f"            8'd{i}: recip_lut = 8'd{r8(i)};" for i in range(256)]
    lines += [
        "        endcase",
        "    end",
        "endfunction",
        "",
    ]
    out = Path(__file__).parent / "rtl" / "softmax_luts.vh"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
