// tb_dpe_azurelily_faithful.v -- standalone testbench for the FAITHFUL
// Azure-Lily DPE behavior model (fc_verification/rtl/dpe_azurelily_faithful.v).
//
// Test modes selected at compile time via `-DTEST_MODE=N` (1..5).
// Defaults to 1 if not specified. Each mode loads its own weights /
// inputs / expected outputs from .mem files generated by the numpy
// oracle (fc_verification/oracles/azurelily_mac_oracle.py).
//
// Workflow:
//   1. Hierarchical-force weights from t<N>_weights.mem
//   2. Drive LOAD strobes carrying inputs from t<N>_inputs.mem
//   3. Wait for OUTPUT phase, capture data_out
//   4. Compare captured bytes against t<N>_expected.mem (numpy oracle)
//   5. Report measured cycle counts vs the oracle's predicted sim_exp
//      (LCYC + CCYC_oracle + OCYC -- unified Task #98 formula). The
//      +2 NBA-handoff cost surfaces as info-only cycle delta.
//   6. For T3: also MEASURE the CCYC gap explicitly between observed
//      "compute_first_bit_pulse" and "compute_last_bit_pulse" -- shows
//      that the 10-cycle CCYC EMERGES from the 3-stage bit-serial
//      structure (Crossbar + ADC + ShiftAdd, NO ACAM) rather than
//      being asserted as a parameter.
//
// Pass criterion (Task #98): FUNCTIONAL only. Cycle delta (= rtl_obs -
// sim_exp = +2 from NBA handoffs in T_fill) is reported but does NOT
// gate PASS/FAIL.
//
// Test cases (Task #92 spec):
//   T1: Identity W, all-ones X -> output[c]=1 for c<min(R,C).
//   T2: Random int8 W,X -> matches signed MAC, byte-truncated.
//   T3: M=1 identity -> verify CCYC=10 emerges by direct gap
//       measurement (bit_idx_s0/s1/s2 sweeps, compute_last commit).
//   T4: M-sweep M in {1,2,4,8}, identity W -> per-pass functional
//       + measured T(M) = T_fill + (M-1)*T_steady.
//   T5: Random signed inputs (negatives) -> signed 2's complement MAC.
//
// (No T5/T6 exp/log tests -- Azure-Lily has NO ACAM stage. T5 here is
// the signed-input test that was T7 in NL faithful.)

`timescale 1ns / 1ps

`ifndef TEST_MODE
  `define TEST_MODE 1
`endif

// Compile-time geometry (must match test_vectors and the DUT defaults).
`ifndef R_TB
  `define R_TB 512
`endif
`ifndef C_TB
  `define C_TB 128
`endif
`ifndef BUF_TB
  `define BUF_TB 16
`endif
`ifndef PRECISION_TB
  `define PRECISION_TB 8
`endif
`ifndef PIPELINE_DEPTH_TB
  `define PIPELINE_DEPTH_TB 3
`endif
`ifndef ACAM_CYCLES_TB
  `define ACAM_CYCLES_TB 0
`endif

// Where to look for the .mem files; the Makefile passes -DVECT_DIR=".../"
// with a trailing slash. Defaults to the relative path that works when
// the simulator is run from fc_verification/.
`ifndef VECT_DIR
  `define VECT_DIR "oracles/test_vectors_al/"
`endif

module tb_dpe_azurelily_faithful;
    // -- Clock / reset --
    reg clk;
    reg reset;
    initial begin
        clk = 0;
        forever #5 clk = ~clk;   // 100 MHz toy clock
    end

    // -- Stimuli to DUT --
    reg [`BUF_TB-1:0] data_in_full;
    reg               w_buf_en;
    reg [1:0]         nl_dpe_control;
    reg               shift_add_control;
    reg               shift_add_bypass;
    reg               load_output_reg;
    reg               load_input_reg;

    // -- DUT outputs --
    wire               MSB_SA_Ready;
    wire [`BUF_TB-1:0] data_out_full;
    wire               dpe_done;
    wire               reg_full;
    wire               shift_add_done;
    wire               shift_add_bypass_ctrl;

    // -- Localparam (single source of truth, mirrors DUT) --
    localparam R              = `R_TB;
    localparam C              = `C_TB;
    localparam BUF            = `BUF_TB;
    localparam PRECISION      = `PRECISION_TB;
    localparam PIPELINE_DEPTH = `PIPELINE_DEPTH_TB;
    localparam ACAM_CYCLES    = `ACAM_CYCLES_TB;
    localparam EPS            = BUF / 8;
    localparam LCYC           = (R + EPS - 1) / EPS;
    localparam OCYC           = (C + EPS - 1) / EPS;

    // Oracle prediction (DECLARED structural CCYC). The TB MEASURES the
    // actual CCYC from the RTL and compares -- they MUST match.
    //   CCYC = PRECISION + (PIPELINE_DEPTH - 1) + ACAM_CYCLES
    //        = 8 + (3 - 1) + 0 = 10   (Azure-Lily INT8)
    // Compare to NL faithful: 8 + (2 - 1) + 1 = 10. Same number,
    // different physical decomposition (3-stage pipeline vs 2-stage +
    // ACAM read-out).
    localparam CCYC_ORACLE    = PRECISION + (PIPELINE_DEPTH - 1) + ACAM_CYCLES;
    // Task #98 unified sim formula: T_fill = LCYC + CCYC + OCYC (no
    // compensation constants). The RTL pays an extra +2 NBA-handoff
    // cost (LOAD->COMPUTE wake + COMPUTE->OUTPUT wake) -- this surfaces
    // as a constant +2 cycle delta between rtl_obs and sim_exp.
    localparam T_FILL_ORACLE  = LCYC + CCYC_ORACLE + OCYC;
    // Option A1 T_steady: LOAD-pass-(k+1) cannot launch until pass-k
    // COMPUTE has consumed all PRECISION slices. The LOAD-gate enforces
    // this, so per-pass cadence is max(LCYC + PRECISION, CCYC, OCYC).
    // For typical AL configs (LCYC=256, PRECISION=8, CCYC=10, OCYC=64),
    // LCYC + PRECISION = 264 dominates.
    localparam T_STEADY_AB    = ((LCYC + PRECISION) > CCYC_ORACLE) ?
                                (LCYC + PRECISION) : CCYC_ORACLE;
    localparam T_STEADY       = (T_STEADY_AB > OCYC) ? T_STEADY_AB : OCYC;

    // Per-test mode parameters
    localparam TEST_MODE      = `TEST_MODE;
    // M-sweep used in T4 only; other tests use M=1.
    localparam M_T4_MAX       = 8;   // M in {1, 2, 4, 8} -- TB iterates.

    // -- DUT --
    // No ACAM_MODE parameter (AL has no ACAM stage).
    dpe #(
        .KERNEL_WIDTH(R),
        .NUM_COLS(C),
        .DPE_BUF_WIDTH(BUF),
        .PRECISION(PRECISION),
        .PIPELINE_DEPTH(PIPELINE_DEPTH),
        .ACAM_CYCLES(ACAM_CYCLES)
    ) dut (
        .clk(clk), .reset(reset),
        .data_in(data_in_full),
        .nl_dpe_control(nl_dpe_control),
        .shift_add_control(shift_add_control),
        .w_buf_en(w_buf_en),
        .shift_add_bypass(shift_add_bypass),
        .load_output_reg(load_output_reg),
        .load_input_reg(load_input_reg),
        .MSB_SA_Ready(MSB_SA_Ready),
        .data_out(data_out_full),
        .dpe_done(dpe_done),
        .reg_full(reg_full),
        .shift_add_done(shift_add_done),
        .shift_add_bypass_ctrl(shift_add_bypass_ctrl)
    );

    // -- Cycle counter --
    integer cycle_count;
    always @(posedge clk) cycle_count <= cycle_count + 1;
    initial cycle_count = 0;

    integer T_first_load;
    integer T_done_last;
    integer T_compute_first_bit;       // captures compute_first_bit_pulse high
    integer T_compute_last_bit;        // captures compute_last_bit_pulse high
    integer i, j, k, b, mi;
    integer error_count;
    integer load_cycle_idx;
    integer pass_idx;
    integer cap_strobe_idx;
    integer cap_idx;

    // Capture buffers (oversized for M-sweep up to M=8).
    localparam MAX_CAP = M_T4_MAX * (OCYC + 4);
    reg [7:0] captured_bytes [0:MAX_CAP * EPS - 1];
    reg [7:0] expected_bytes [0:1023];          // per-pass expected (T1/T2/T5)

    // Per-test storage loaded from .mem files
    reg [7:0] w_mem [0:R*C - 1];                // row-major weights
    reg [7:0] x_mem [0:R - 1];                  // inputs
    reg [7:0] y_mem [0:C - 1];                  // expected output bytes

    // FSM probe
    wire [2:0] state_now      = dut.state;
    wire       compute_busy_w = dut.compute_busy;
    wire [4:0] bit_idx_s0_w   = dut.bit_idx_s0;
    wire [4:0] bit_idx_s1_w   = dut.bit_idx_s1;
    wire [4:0] bit_idx_s2_w   = dut.bit_idx_s2;

    // T3 specifically tracks bit_idx_s0/s1/s2 advancement.
    reg [9:0] bit_idx_s0_observed;   // bitmap of which values we've seen
    reg [9:0] bit_idx_s1_observed;
    reg [9:0] bit_idx_s2_observed;
    integer   first_compute_cycle;
    integer   last_compute_cycle;

    // Continuous telemetry capture (T3 + T4 use this).
    always @(posedge clk) begin
        // Track first cycle compute_busy high (first bit slice entering).
        if (dut.compute_first_bit_pulse && first_compute_cycle == -1)
            first_compute_cycle <= cycle_count;
        // Track last cycle compute_busy high (= cycle stage 2 commits MSB).
        if (dut.compute_busy)
            last_compute_cycle <= cycle_count;
        // Track last-bit pulse (signals MAC commit).
        if (dut.compute_last_bit_pulse && T_compute_last_bit == -1)
            T_compute_last_bit <= cycle_count;
        // Bit_idx observations (T3): record which bit_idx_s0/s1/s2 values
        // we saw during compute. Useful for verifying 0..PRECISION-1 sweep.
        if (dut.compute_busy && dut.bit_idx_s0 < 10)
            bit_idx_s0_observed[dut.bit_idx_s0] <= 1'b1;
        if (dut.compute_busy && dut.bit_idx_s1 < 10)
            bit_idx_s1_observed[dut.bit_idx_s1] <= 1'b1;
        if (dut.compute_busy && dut.bit_idx_s2 < 10)
            bit_idx_s2_observed[dut.bit_idx_s2] <= 1'b1;
    end

    // Output capture (per-strobe, dpe_done gate).
    always @(posedge clk) begin
        if (dpe_done && cap_strobe_idx < MAX_CAP) begin
            for (b = 0; b < EPS; b = b + 1) begin
                if (cap_strobe_idx * EPS + b < MAX_CAP * EPS)
                    captured_bytes[cap_strobe_idx * EPS + b] <=
                        data_out_full[b*8 +: 8];
            end
            cap_strobe_idx <= cap_strobe_idx + 1;
            T_done_last <= cycle_count;
        end
    end

    // -- Helper task: load test vectors from .mem files --
    task load_test_vectors;
        input [31:0] tm;
        begin
            case (tm)
                1: begin
                    $readmemh({`VECT_DIR, "t1_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t1_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t1_expected.mem"},y_mem);
                end
                2: begin
                    $readmemh({`VECT_DIR, "t2_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t2_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t2_expected.mem"},y_mem);
                end
                3: begin
                    $readmemh({`VECT_DIR, "t3_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t3_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t3_expected.mem"},y_mem);
                end
                4: begin
                    $readmemh({`VECT_DIR, "t4_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t4_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t4_expected.mem"},y_mem);
                end
                5: begin
                    $readmemh({`VECT_DIR, "t5_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t5_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t5_expected.mem"},y_mem);
                end
                default: begin
                    $readmemh({`VECT_DIR, "t1_weights.mem"}, w_mem);
                    $readmemh({`VECT_DIR, "t1_inputs.mem"},  x_mem);
                    $readmemh({`VECT_DIR, "t1_expected.mem"},y_mem);
                end
            endcase
        end
    endtask

    // -- Helper task: hierarchical-force weights into the DUT --
    task force_weights;
        integer ri, ci;
        begin
            for (ri = 0; ri < R; ri = ri + 1)
                for (ci = 0; ci < C; ci = ci + 1)
                    dut.weights[ri][ci] = w_mem[ri * C + ci];
        end
    endtask

    // -- Helper task: drive ONE pass of LOAD strobes --
    // pack_inputs: 1 = use x_mem; 0 = use input override array.
    task drive_load_pass;
        input integer override_pass;     // for T4 per-pass input pattern
        input [7:0]   override_byte;     // T4 uses constant (m+1) byte
        integer li, bi;
        begin
            for (li = 0; li < LCYC; li = li + 1) begin
                data_in_full = {`BUF_TB{1'b0}};
                for (bi = 0; bi < EPS; bi = bi + 1) begin
                    if (li * EPS + bi < R) begin
                        if (override_pass != 0)
                            data_in_full[bi*8 +: 8] = override_byte;
                        else
                            data_in_full[bi*8 +: 8] = x_mem[li * EPS + bi];
                    end
                end
                w_buf_en = 1'b1;
                @(posedge clk); #1;
                if (T_first_load == -1)
                    T_first_load = cycle_count;
            end
            w_buf_en = 1'b0;
            data_in_full = {`BUF_TB{1'b0}};
        end
    endtask

    // -- Helper task: reset + clear capture state --
    task tb_init;
        integer ii;
        begin
            reset             = 1;
            w_buf_en          = 0;
            nl_dpe_control    = 2'b11;     // generic compute-active (DPE ignores)
            shift_add_control = 0;
            shift_add_bypass  = 0;
            load_output_reg   = 0;
            load_input_reg    = 0;
            data_in_full      = {`BUF_TB{1'b0}};
            T_first_load      = -1;
            T_done_last       = -1;
            T_compute_first_bit = -1;
            T_compute_last_bit = -1;
            first_compute_cycle = -1;
            last_compute_cycle  = -1;
            bit_idx_s0_observed = 10'b0;
            bit_idx_s1_observed = 10'b0;
            bit_idx_s2_observed = 10'b0;
            error_count       = 0;
            cap_strobe_idx    = 0;
            for (ii = 0; ii < MAX_CAP * EPS; ii = ii + 1)
                captured_bytes[ii] = 8'h00;
            for (ii = 0; ii < 1024; ii = ii + 1)
                expected_bytes[ii] = 8'h00;
            for (ii = 0; ii < R*C; ii = ii + 1)
                w_mem[ii] = 8'h00;
            for (ii = 0; ii < R; ii = ii + 1)
                x_mem[ii] = 8'h00;
            for (ii = 0; ii < C; ii = ii + 1)
                y_mem[ii] = 8'h00;

            repeat (3) @(posedge clk); #1;
            reset = 0;
            @(posedge clk); #1;
        end
    endtask

    // -- Compare helper: captured_bytes (single pass, OCYC*EPS slots) vs y_mem --
    task compare_pass0_against_y_mem;
        integer ii;
        begin
            for (ii = 0; ii < C; ii = ii + 1) begin
                if (captured_bytes[ii] !== y_mem[ii]) begin
                    if (error_count < 10)
                        $display("[tb_faithful_al] T%0d MISMATCH col=%0d expected=0x%02h got=0x%02h",
                                 TEST_MODE, ii, y_mem[ii], captured_bytes[ii]);
                    error_count = error_count + 1;
                end
            end
        end
    endtask

    // -- Run TEST_MODE 1: identity W, ones X --
    task run_t1;
        integer guard;
        begin
            $display("[tb_faithful_al] T1: identity W, ones X");
            $display("[tb_faithful_al]   expect output[c]=1 for c<min(R,C)");
            tb_init;
            load_test_vectors(1);
            force_weights;

            drive_load_pass(0, 8'd0);   // override_pass=0 -> use x_mem
            guard = 0;
            while (cap_strobe_idx < OCYC && guard < T_FILL_ORACLE * 4) begin
                @(posedge clk); #1;
                guard = guard + 1;
            end
            @(posedge clk); #1;
            compare_pass0_against_y_mem;
            check_cycles(1);
            report_verdict(1);
        end
    endtask

    // -- Run TEST_MODE 2: random int8 W,X --
    task run_t2;
        integer guard;
        begin
            $display("[tb_faithful_al] T2: random int8 W and X");
            $display("[tb_faithful_al]   expect numpy oracle bit-exact match");
            tb_init;
            load_test_vectors(2);
            force_weights;

            drive_load_pass(0, 8'd0);
            guard = 0;
            while (cap_strobe_idx < OCYC && guard < T_FILL_ORACLE * 4) begin
                @(posedge clk); #1;
                guard = guard + 1;
            end
            @(posedge clk); #1;
            compare_pass0_against_y_mem;
            check_cycles(2);
            report_verdict(2);
        end
    endtask

    // -- Run TEST_MODE 3: identity W, ones X -- CYCLE EMERGENCE --
    task run_t3;
        integer guard;
        integer measured_ccyc;
        integer bi;
        reg     bit_idx_ok;
        begin
            $display("[tb_faithful_al] T3: identity W, ones X -- CYCLE EMERGENCE CHECK");
            $display("[tb_faithful_al]   verify bit_idx_s0/s1/s2 sweep 0..PRECISION-1");
            $display("[tb_faithful_al]   verify CCYC = (last_compute_cycle - first_compute_cycle + 1)");
            $display("[tb_faithful_al]   declared CCYC_ORACLE = %0d (PRECISION=%0d + PIPELINE_DEPTH-1=%0d + ACAM_CYCLES=%0d)",
                     CCYC_ORACLE, PRECISION, PIPELINE_DEPTH - 1, ACAM_CYCLES);
            $display("[tb_faithful_al]   AL decomposition: 3-stage pipeline (Crossbar+ADC+ShiftAdd) + NO ACAM");
            $display("[tb_faithful_al]   NL comparison:    2-stage pipeline + 1-cycle ACAM = same CCYC, different physics");
            tb_init;
            load_test_vectors(3);
            force_weights;

            drive_load_pass(0, 8'd0);
            guard = 0;
            while (cap_strobe_idx < OCYC && guard < T_FILL_ORACLE * 4) begin
                @(posedge clk); #1;
                guard = guard + 1;
            end
            @(posedge clk); #1;

            // Functional check
            compare_pass0_against_y_mem;

            // -- Cycle emergence verification --
            // bit_idx_s0 must have swept 0..PRECISION-1 (inclusive).
            // bit_idx_s1 must have swept 0..PRECISION-1.
            // bit_idx_s2 must have swept 0..PRECISION-1.
            bit_idx_ok = 1'b1;
            for (bi = 0; bi < PRECISION; bi = bi + 1) begin
                if (!bit_idx_s0_observed[bi]) begin
                    $display("[tb_faithful_al] T3 ERROR: bit_idx_s0=%0d never observed during compute", bi);
                    error_count = error_count + 1;
                    bit_idx_ok = 1'b0;
                end
                if (!bit_idx_s1_observed[bi]) begin
                    $display("[tb_faithful_al] T3 ERROR: bit_idx_s1=%0d never observed during compute", bi);
                    error_count = error_count + 1;
                    bit_idx_ok = 1'b0;
                end
                if (!bit_idx_s2_observed[bi]) begin
                    $display("[tb_faithful_al] T3 ERROR: bit_idx_s2=%0d never observed during compute", bi);
                    error_count = error_count + 1;
                    bit_idx_ok = 1'b0;
                end
            end
            if (bit_idx_ok)
                $display("[tb_faithful_al] T3   bit_idx_s0/s1/s2 all swept 0..%0d (PRECISION values observed across 3 stages)",
                         PRECISION - 1);

            // MEASURE CCYC: count cycles compute_busy was high.
            // first_compute_cycle = first cycle compute_busy was observed high
            //                       (compute_first_bit_pulse marks this).
            // last_compute_cycle  = last cycle compute_busy was observed high
            //                       (== cycle stage 2 commits MSB; the very
            //                        next cycle has compute_busy=0).
            // Result MUST equal CCYC_ORACLE = PRECISION + (PIPELINE_DEPTH-1)
            // + ACAM_CYCLES.
            //
            // Additionally, T_compute_last_bit records the cycle that the
            // compute_last_bit_pulse was observed -- it should fire on the
            // same cycle as the last compute_busy=1 observation (the MSB
            // subtract cycle), so T_compute_last_bit == last_compute_cycle.
            if (first_compute_cycle == -1 || last_compute_cycle == -1) begin
                $display("[tb_faithful_al] T3 ERROR: never observed compute_busy high");
                error_count = error_count + 1;
            end else begin
                measured_ccyc = last_compute_cycle - first_compute_cycle + 1;
                $display("[tb_faithful_al] T3   first_compute_cycle  = %0d (first cycle compute_busy was high; bit_idx_s0=0 entering Stage 0/Crossbar)",
                         first_compute_cycle);
                $display("[tb_faithful_al] T3   last_compute_cycle   = %0d (last cycle compute_busy was high; Stage 2/ShiftAdd MSB commit)",
                         last_compute_cycle);
                $display("[tb_faithful_al] T3   T_compute_last_bit   = %0d (cycle compute_last_bit_pulse observed)",
                         T_compute_last_bit);
                $display("[tb_faithful_al] T3   MEASURED CCYC        = last_compute_cycle - first_compute_cycle + 1 = %0d",
                         measured_ccyc);
                $display("[tb_faithful_al] T3   DECLARED CCYC_ORACLE = %0d  (= PRECISION + (PIPELINE_DEPTH-1) + ACAM_CYCLES = %0d + %0d + %0d)",
                         CCYC_ORACLE, PRECISION, PIPELINE_DEPTH - 1, ACAM_CYCLES);
                if (measured_ccyc != CCYC_ORACLE) begin
                    $display("[tb_faithful_al] T3 ERROR: measured CCYC=%0d != oracle %0d", measured_ccyc, CCYC_ORACLE);
                    error_count = error_count + 1;
                end else begin
                    $display("[tb_faithful_al] T3   *** CCYC=%0d EMERGED from physical structure (NOT set as parameter) ***",
                             measured_ccyc);
                    $display("[tb_faithful_al] T3   *** Breakdown: PRECISION=%0d cycles of bit-slice entry + (PIPELINE_DEPTH-1)=%0d cycles of pipeline drain (ADC+ShiftAdd) + ACAM_CYCLES=%0d (NO ACAM in AL) ***",
                             PRECISION, PIPELINE_DEPTH - 1, ACAM_CYCLES);
                    $display("[tb_faithful_al] T3   *** Note: same total as NL faithful (8 + 1 + 1 = 10), different physical decomposition ***");
                end
                // Cross-check: T_compute_last_bit should be last_compute_cycle + 1
                // (compute_last_bit_pulse is NBA'd in the same cycle as the
                // MSB subtract, so it is OBSERVED one cycle later -- standard
                // NBA latency between assert and observe).
                if (T_compute_last_bit != last_compute_cycle + 1) begin
                    $display("[tb_faithful_al] T3 WARN: T_compute_last_bit (%0d) != last_compute_cycle+1 (%0d) -- check structural alignment",
                             T_compute_last_bit, last_compute_cycle + 1);
                end
            end

            check_cycles(3);
            report_verdict(3);
        end
    endtask

    // -- Run TEST_MODE 4: M-sweep --
    task run_t4;
        integer m_target;
        integer guard;
        integer mi_local;
        integer si;
        integer T_first_M;
        integer T_last_M;
        integer measured_total;
        integer expected_total;
        integer pass_mismatch;
        begin
            $display("[tb_faithful_al] T4: M-sweep functional + cycle for M in {1,2,4,8}, identity W");
            // Run 4 separate sub-tests, accumulating error_count globally.
            tb_init;
            // We'll re-tb_init for each M; track aggregated errors externally.
            for (mi_local = 0; mi_local < 4; mi_local = mi_local + 1) begin
                case (mi_local)
                    0: m_target = 1;
                    1: m_target = 2;
                    2: m_target = 4;
                    3: m_target = 8;
                    default: m_target = 1;
                endcase
                tb_init;
                load_test_vectors(4);    // identity weights
                force_weights;
                expected_total = T_FILL_ORACLE + (m_target - 1) * T_STEADY;
                T_first_M = -1;
                T_last_M  = -1;
                pass_mismatch = 0;

                // Drive m_target passes of LOAD strobes.
                // For pass m (0-indexed), use constant byte (m+1) as input.
                // Task #99 double-buffer: pass-(k+1)'s LOAD writes the
                // OTHER substrate, so we can drive passes back-to-back
                // with no inter-pass synchronization (no load_safe gate).
                for (pass_idx = 0; pass_idx < m_target; pass_idx = pass_idx + 1) begin
                    drive_load_pass(1, (pass_idx + 1) & 8'hFF);
                end
                if (T_first_M == -1) T_first_M = T_first_load;

                guard = 0;
                while (cap_strobe_idx < m_target * OCYC && guard < expected_total * 4 + 200) begin
                    @(posedge clk); #1;
                    guard = guard + 1;
                end
                @(posedge clk); #1;
                T_last_M = T_done_last;
                measured_total = T_last_M - T_first_M + 1;

                // Per-pass functional check (expected: byte = (m+1) & 0xFF
                // for col < min(R,C); 0 otherwise).
                for (mi = 0; mi < m_target; mi = mi + 1) begin
                    for (si = 0; si < OCYC * EPS; si = si + 1) begin
                        if (si < R && si < C) begin
                            if (captured_bytes[mi * OCYC * EPS + si] !== ((mi + 1) & 8'hFF)) begin
                                if (pass_mismatch < 5)
                                    $display("[tb_faithful_al] T4 M=%0d MISMATCH pass=%0d slot=%0d expected=0x%02h got=0x%02h",
                                             m_target, mi, si, ((mi + 1) & 8'hFF), captured_bytes[mi * OCYC * EPS + si]);
                                pass_mismatch = pass_mismatch + 1;
                                error_count = error_count + 1;
                            end
                        end
                    end
                end

                // Task #98: functional-only PASS; cycle delta reported as info.
                $display("[tb_faithful_al] T4 M=%0d functional=%s cycles=%0d (sim_exp=%0d, T_fill+%0d*T_steady)  delta=%0d",
                         m_target,
                         (pass_mismatch == 0) ? "PASS" : "FAIL",
                         measured_total, expected_total, m_target - 1,
                         measured_total - expected_total);
                $display("[tb_faithful_al] T4 M=%0d cycle delta = rtl_cycles - oracle_cycles = %0d (info-only; NBA handoffs in T_fill)",
                         m_target, measured_total - expected_total);
            end

            report_verdict(4);
        end
    endtask

    // -- Run TEST_MODE 5: signed inputs (negatives) --
    task run_t5;
        integer guard;
        begin
            $display("[tb_faithful_al] T5: random SIGNED int8 X (includes negatives)");
            $display("[tb_faithful_al]   expect signed 2's complement MAC matches numpy oracle");
            tb_init;
            load_test_vectors(5);
            force_weights;

            drive_load_pass(0, 8'd0);
            guard = 0;
            while (cap_strobe_idx < OCYC && guard < T_FILL_ORACLE * 4) begin
                @(posedge clk); #1;
                guard = guard + 1;
            end
            @(posedge clk); #1;
            compare_pass0_against_y_mem;
            check_cycles(5);
            report_verdict(5);
        end
    endtask

    // -- Common cycle-count check (single-pass tests T1/T2/T3/T5) --
    // Task #98: pass criterion is FUNCTIONAL ONLY. Cycle delta = rtl_obs
    // - sim_exp (target +2 from NBA handoffs in T_fill) is reported as
    // info-only; it does NOT increment error_count.
    task check_cycles;
        input [31:0] tm;
        integer total_meas;
        integer delta;
        begin
            if (T_first_load == -1 || T_done_last == -1) begin
                $display("[tb_faithful_al] T%0d ERROR: never sampled T_first_load or T_done_last (load=%0d done=%0d)",
                         tm, T_first_load, T_done_last);
                error_count = error_count + 1;
            end else begin
                total_meas = T_done_last - T_first_load + 1;
                delta = total_meas - T_FILL_ORACLE;
                $display("[tb_faithful_al] T%0d T_first_load=%0d T_done_last=%0d total_cycles=%0d (sim_exp=%0d)",
                         tm, T_first_load, T_done_last, total_meas, T_FILL_ORACLE);
                $display("[tb_faithful_al] T%0d cycle delta = rtl_cycles - oracle_cycles = %0d (info-only; NBA handoffs in T_fill)",
                         tm, delta);
            end
        end
    endtask

    // -- Verdict reporting --
    task report_verdict;
        input [31:0] tm;
        begin
            if (error_count == 0)
                $display("[tb_faithful_al] T%0d PASS", tm);
            else
                $display("[tb_faithful_al] T%0d FAIL (%0d errors)", tm, error_count);
        end
    endtask

    // -- Top-level dispatch --
    initial begin
        $display("[tb_faithful_al] TEST_MODE=%0d  R=%0d C=%0d BUF=%0d EPS=%0d LCYC=%0d OCYC=%0d",
                 TEST_MODE, R, C, BUF, EPS, LCYC, OCYC);
        $display("[tb_faithful_al]   PRECISION=%0d PIPELINE_DEPTH=%0d ACAM_CYCLES=%0d (Azure-Lily: 3-stage, no ACAM)",
                 PRECISION, PIPELINE_DEPTH, ACAM_CYCLES);
        $display("[tb_faithful_al]   CCYC_ORACLE = %0d (declared)  T_FILL_ORACLE = %0d  T_STEADY = %0d",
                 CCYC_ORACLE, T_FILL_ORACLE, T_STEADY);

        case (TEST_MODE)
            1: run_t1;
            2: run_t2;
            3: run_t3;
            4: run_t4;
            5: run_t5;
            default: begin
                $display("[tb_faithful_al] ERROR: unknown TEST_MODE=%0d", TEST_MODE);
                $finish;
            end
        endcase

        $finish;
    end

`ifdef WAVE
    initial begin
        $dumpfile("build/tb_faithful_al.vcd");
        $dumpvars(0, tb_dpe_azurelily_faithful);
    end
`endif

endmodule
