// Azure-Lily Attention Head Top — matches IMC attention_model (no O proj)
// Generated by gen_azurelily_attn_head_top.py
//   d_model=128, d_head=64, N_SEQ=128, W=16, EPW_DSP=4
//
// Architecture (mirrors azurelily/models/attention.py attention_model):
//   N tokens × (Q/K/V projection FC) → pack5_buffer → Q/K/V SRAM buffers
//   → azurelily_dimm_top (W=16 lanes, single fire over full N×d Q/K/V) → out
//
// NO output projection — sim's attention_model stops at mac_sv.
//
// Composition:
//   - 3 × azurelily_fc_128_64       (Q/K/V proj, fired N=128 times each)
//   - 3 × pack5_buffer              (Q/K/V unpacked→packed converters)
//   - 3 × sram (Q/K/V buffer)       (depth = N⌈d_head/5⌉ + 1 = 1665)
//   - 1 × azurelily_dimm_top        (W=16 lanes, fires once)
//
// Outer FSM (state names + transitions):
//   S_IDLE          : await valid_x → S_LOAD_TOKEN
//   S_LOAD_TOKEN    : forward 32 packed input words/token to FC.valid
//                     → S_WAIT_FC after PACKED_K cycles
//   S_WAIT_FC       : assert FC valid quiet; collect FC valid_n stream into
//                     pack5_buffer (handled combinationally from FC valid_n)
//                     → S_FC_DRAIN once FC has emitted d_head valid_n bytes
//   S_FC_DRAIN      : safety drain so packer flushes; → S_INTER_TOKEN_RST
//   S_INTER_TOKEN_RST: pulse fc_rst high one cycle to reset FC FSMs; advance
//                     token_count.  → S_LOAD_TOKEN if more tokens; else S_DIMM_FIRE
//   S_DIMM_FIRE     : DIMM auto-fires once thresholds met (handled inside
//                     azurelily_dimm_top); we just gate ready_x = 0 here.
//   S_DRAIN         : DIMM emits valid_n stream → output port.
//
// Format note: AL DIMM's S_LOAD threshold uses EPW=5 (q_w_addr >= 13,
// k_w_addr/v_w_addr >= 1664).  This is a pre-existing inconsistency in
// gen_dimm_azurelily_top.py vs dsp_mac (which reads EPW=4 lanes) — DO NOT
// FIX HERE.  pack5_buffer matches the EPW=5 threshold semantics.

`timescale 1ns / 1ps

module azurelily_attn_head_d64_c128 #(
    parameter DATA_WIDTH = 40,
    parameter D_MODEL    = 128,
    parameter D_HEAD     = 64,
    parameter N_SEQ      = 128,
    parameter W          = 16
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);
    localparam PACKED_K  = 32;   // FC input packed words per token
    localparam PACKED_D  = 13;   // packed Q/K/V words per token (EPW=5)
    localparam BUF_DEPTH = 1665;  // total packed Q/K/V words across N tokens

    // ───────── outer FSM state encoding ─────────
    localparam S_IDLE             = 4'd0;
    localparam S_LOAD_TOKEN       = 4'd1;
    localparam S_WAIT_FC          = 4'd2;
    localparam S_FC_DRAIN         = 4'd3;
    localparam S_INTER_TOKEN_RST  = 4'd4;
    localparam S_DIMM_FIRE        = 4'd5;
    localparam S_DRAIN            = 4'd6;
    reg [3:0] state;

    reg [7:0] token_count;
    reg [5:0] feed_count;     // 0..PACKED_K within current token feed
    reg [6:0]  fc_byte_count;  // 0..D_HEAD within current FC token output
    reg                      fc_rst_pulse;   // one-cycle reset to FC arms

    wire fc_rst = rst | fc_rst_pulse;

    // ───────── valid + data into FCs ─────────
    wire fc_valid_in = (state == S_LOAD_TOKEN);
    wire [DATA_WIDTH-1:0] fc_data_in = data_in_x;

    // FC outputs (1 int8 in low byte of 40-bit valid_n word)
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    azurelily_fc_128_64 fc_q_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(q_fc_out), .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    azurelily_fc_128_64 fc_k_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(k_fc_out), .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    azurelily_fc_128_64 fc_v_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(v_fc_out), .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ───────── pack5_buffer x 3 (Q/K/V) ─────────
    // Each takes 1 int8/cycle (FC valid_n), emits one packed 40-bit word
    // every 5 valid_in cycles to its Q/K/V buffer SRAM.
    wire q_buf_w_en, k_buf_w_en, v_buf_w_en;
    wire [10:0] q_buf_w_addr, k_buf_w_addr, v_buf_w_addr;
    wire [DATA_WIDTH-1:0]     q_buf_w_data, k_buf_w_data, v_buf_w_data;

    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W(11), .EPW(5))
        q_packer (.clk(clk), .rst(rst),
                  .valid_in(q_fc_valid_n), .data_in(q_fc_out),
                  .w_en(q_buf_w_en), .w_addr(q_buf_w_addr),
                  .sram_data_in(q_buf_w_data));
    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W(11), .EPW(5))
        k_packer (.clk(clk), .rst(rst),
                  .valid_in(k_fc_valid_n), .data_in(k_fc_out),
                  .w_en(k_buf_w_en), .w_addr(k_buf_w_addr),
                  .sram_data_in(k_buf_w_data));
    pack5_buffer #(.DATA_WIDTH(DATA_WIDTH), .ADDR_W(11), .EPW(5))
        v_packer (.clk(clk), .rst(rst),
                  .valid_in(v_fc_valid_n), .data_in(v_fc_out),
                  .w_en(v_buf_w_en), .w_addr(v_buf_w_addr),
                  .sram_data_in(v_buf_w_data));

    // ───────── Q/K/V buffer SRAMs ─────────
    // Read side: streamed out as DIMM input during S_DIMM_FIRE.
    reg [10:0] q_buf_r_addr, k_buf_r_addr, v_buf_r_addr;
    wire [DATA_WIDTH-1:0]    q_buf_r_data, k_buf_r_data, v_buf_r_data;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        q_buf (.clk(clk), .rst(rst), .w_en(q_buf_w_en),
               .r_addr(q_buf_r_addr), .w_addr(q_buf_w_addr),
               .sram_data_in(q_buf_w_data), .sram_data_out(q_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        k_buf (.clk(clk), .rst(rst), .w_en(k_buf_w_en),
               .r_addr(k_buf_r_addr), .w_addr(k_buf_w_addr),
               .sram_data_in(k_buf_w_data), .sram_data_out(k_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        v_buf (.clk(clk), .rst(rst), .w_en(v_buf_w_en),
               .r_addr(v_buf_r_addr), .w_addr(v_buf_w_addr),
               .sram_data_in(v_buf_w_data), .sram_data_out(v_buf_r_data));

    // ───────── DIMM inputs (replay buffered Q/K/V into DIMM stream) ─────────
    reg [10:0] dimm_replay_count;
    wire dimm_replay_active = (state == S_DIMM_FIRE);
    wire dimm_valid_q = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);
    wire dimm_valid_k = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);
    wire dimm_valid_v = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);

    // ───────── DIMM (W=16 lanes, mac_qk + clb_softmax + mac_sv) ─────────
    wire [DATA_WIDTH-1:0] dimm_out;
    wire dimm_valid_n_w;
    azurelily_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH)
    ) dimm_inst (
        .clk(clk), .rst(rst),
        .valid_q(dimm_valid_q), .valid_k(dimm_valid_k), .valid_v(dimm_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_r_data), .data_in_k(k_buf_r_data), .data_in_v(v_buf_r_data),
        .data_out(dimm_out),
        .ready_q(), .ready_k(), .ready_v(),
        .valid_n(dimm_valid_n_w)
    );

    // ───────── outer FSM body ─────────
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state             <= S_IDLE;
            token_count       <= 0;
            feed_count        <= 0;
            fc_byte_count     <= 0;
            fc_rst_pulse      <= 1'b0;
            dimm_replay_count <= 0;
            q_buf_r_addr      <= 0;
            k_buf_r_addr      <= 0;
            v_buf_r_addr      <= 0;
        end else begin
            fc_rst_pulse <= 1'b0;  // default; pulsed in S_INTER_TOKEN_RST
            case (state)
                S_IDLE: begin
                    if (valid_x) begin
                        state         <= S_LOAD_TOKEN;
                        token_count   <= 0;
                        feed_count    <= 0;
                        fc_byte_count <= 0;
                    end
                end
                S_LOAD_TOKEN: begin
                    // BUG 1 FIX: extend the S_LOAD_TOKEN window from PACKED_K
                    // to PACKED_K+2 cycles so the inner FC arms can actually
                    // transition from S_IDLE->S_LOAD->S_COMPUTE.
                    //
                    // Pre-fix trace (PACKED_K=32):
                    //   cycle k=1: head enters S_LOAD_TOKEN (feed_count=0),
                    //              valid=1. FC still in S_IDLE (async rst
                    //              cleared it on k=1 for subsequent tokens
                    //              via fc_rst_pulse, or from global rst for
                    //              token 0). FC transitions S_IDLE->S_LOAD at
                    //              posedge of k=2.
                    //   cycle k=2: FC enters S_LOAD, i_w_addr=0, valid=1.
                    //              Writes mem[0], i_w_addr<=1.
                    //   ...
                    //   cycle k=32: FC i_w_addr=30, valid=1. Writes mem[30],
                    //               i_w_addr<=31. head feed_count was 30
                    //               going into this cycle; commits to 31.
                    //   cycle k=33: head feed_count==PACKED_K-1=31 ->
                    //               transitions to S_WAIT_FC. FC i_w_addr=31,
                    //               BUT valid drops to 0 this cycle, so the
                    //               (i_w_addr==31 && valid) condition never
                    //               fires. FC is stuck in S_LOAD forever.
                    //
                    // Post-fix: head stays in S_LOAD_TOKEN for 2 more cycles
                    // (feed_count 0..PACKED_K+1 = 0..33). At k=34, FC has
                    // i_w_addr=31 and valid=1 -> S_COMPUTE, i_w_addr<=0.
                    // mem[31] also gets written in that same cycle. Only
                    // 1 extra valid cycle is strictly needed for the FSM
                    // transition, but +2 gives one cycle of slack so we
                    // also cover the case where the FC's async-reset from
                    // fc_rst_pulse takes 2 NBA settle cycles to release.
                    if (feed_count == PACKED_K + 1) begin
                        state      <= S_WAIT_FC;
                        feed_count <= 0;
                    end else begin
                        feed_count <= feed_count + 1;
                    end
                end
                S_WAIT_FC: begin
                    // FC enters S_COMPUTE → S_OUTPUT, emits D_HEAD valid_n bytes.
                    // Packers absorb the stream automatically.
                    if (q_fc_valid_n) begin
                        if (fc_byte_count == D_HEAD - 1) begin
                            state         <= S_FC_DRAIN;
                            fc_byte_count <= 0;
                        end else begin
                            fc_byte_count <= fc_byte_count + 1;
                        end
                    end
                end
                S_FC_DRAIN: begin
                    // One-cycle settle so the last packer write commits.
                    state <= S_INTER_TOKEN_RST;
                end
                S_INTER_TOKEN_RST: begin
                    // Pulse FC reset so the FC arms can accept the next token.
                    fc_rst_pulse <= 1'b1;
                    if (token_count == N_SEQ - 1) begin
                        state             <= S_DIMM_FIRE;
                        token_count       <= 0;
                        dimm_replay_count <= 0;
                        q_buf_r_addr      <= 0;
                        k_buf_r_addr      <= 0;
                        v_buf_r_addr      <= 0;
                    end else begin
                        state       <= S_LOAD_TOKEN;
                        token_count <= token_count + 1;
                        feed_count  <= 0;
                    end
                end
                S_DIMM_FIRE: begin
                    // Stream packed Q/K/V buffer into DIMM (q/k/v_w_addr inside
                    // DIMM increments while valid_q/k/v are high).
                    if (dimm_replay_count < BUF_DEPTH - 1) begin
                        q_buf_r_addr      <= dimm_replay_count;
                        k_buf_r_addr      <= dimm_replay_count;
                        v_buf_r_addr      <= dimm_replay_count;
                        dimm_replay_count <= dimm_replay_count + 1;
                    end else begin
                        state <= S_DRAIN;
                    end
                end
                S_DRAIN: begin
                    // Hold here; DIMM internally drives valid_n through W lanes.
                    // Top exits to S_IDLE only via top-level rst (one-shot run).
                    state <= S_DRAIN;
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ───────── outputs ─────────
    assign data_out = dimm_out;
    assign valid_n  = dimm_valid_n_w;
    assign ready_x  = (state == S_IDLE) || (state == S_LOAD_TOKEN);

endmodule

// ════ pack5_buffer ════
//
// Accumulates 5 consecutive int8 bytes (low byte of data_in[39:0]) into
// a packed 40-bit word, emitting one packed write to the buffer SRAM every
// 5 valid_in cycles.  Bytes are placed in increasing-byte order:
//
//   word[ 7: 0] = byte 0 (first input)
//   word[15: 8] = byte 1
//   word[23:16] = byte 2
//   word[31:24] = byte 3
//   word[39:32] = byte 4 (last input)
//
// The packer is purely a write-side helper: it drives w_en, w_addr, sram_data_in.
// It does NOT own the SRAM (the parent instantiates the buffer SRAM).
//
// Reset semantics: rst clears the partial register, w_addr, and pack_count.

module pack5_buffer #(
    parameter DATA_WIDTH = 40,
    parameter ADDR_W     = 11,
    parameter EPW        = 5
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_in,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg                     w_en,
    output reg  [ADDR_W-1:0]       w_addr,
    output reg  [DATA_WIDTH-1:0]   sram_data_in
);
    reg [2:0] pack_count;       // 0..EPW-1
    reg [DATA_WIDTH-1:0]     pack_reg;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            pack_count   <= 0;
            pack_reg     <= 0;
            w_en         <= 0;
            w_addr       <= 0;
            sram_data_in <= 0;
        end else begin
            w_en <= 0;  // default; raised exactly when we emit a packed word
            if (valid_in) begin
                // Insert low byte of data_in into byte-position pack_count.
                case (pack_count)
                    3'd0: pack_reg[ 7: 0] <= data_in[7:0];
                    3'd1: pack_reg[15: 8] <= data_in[7:0];
                    3'd2: pack_reg[23:16] <= data_in[7:0];
                    3'd3: pack_reg[31:24] <= data_in[7:0];
                    3'd4: pack_reg[39:32] <= data_in[7:0];
                    default: ;
                endcase

                if (pack_count == EPW - 1) begin
                    // Emit packed word: assemble combinationally so the
                    // commit happens the same cycle as the 5th byte arrives.
                    sram_data_in <= { data_in[7:0],
                                       pack_reg[31:24],
                                       pack_reg[23:16],
                                       pack_reg[15: 8],
                                       pack_reg[ 7: 0] };
                    w_en         <= 1;
                    pack_count   <= 0;
                    if (w_addr != {ADDR_W{1'b1}}) w_addr <= w_addr + 1;
                end else begin
                    pack_count <= pack_count + 1;
                end
            end
        end
    end
endmodule
