// Azure-Lily Full DIMM Top — W=16, N=128, d=64
// Generated by gen_dimm_azurelily_top.py

// Azure-Lily Full DIMM Top (W=16 parallel lanes)
// Per-DIMM DSPs: 2 matmul stages × 16 lanes = 32
// + 16 × clb_softmax (CLB-based softmax, one per lane)
// dsp_mac: pure int_sop_4 (4 MAC/cycle, no CLB helper)

module azurelily_dimm_top #(
    parameter N = 128,
    parameter D = 64,
    parameter W = 16,
    parameter DATA_WIDTH = 40,
    // AH cycle alignment Steps B-2/B-3 (additive, default off):
    // SCORE_BACK_TO_BACK_MODE — when set, lets the top-level FSM
    // recycle from S_WAIT_QK back to S_FEED_QK on a `score_next_q_row_trigger_i`
    // pulse, enabling back-to-back mac_qk firing across Q rows.
    // WSUM_BACK_TO_BACK_MODE — when set, lets the FSM recycle from
    // S_OUTPUT back to S_FEED_QK on a `wsum_next_q_row_trigger_i` pulse,
    // re-arming the dsp_mac auto-recycle for the next Q row's mac_sv.
    // Default 0 keeps the canonical single-Q-row pipeline; B-5 will
    // override to 1 to enable back-to-back Q-row processing.
    parameter SCORE_BACK_TO_BACK_MODE = 0,
    parameter WSUM_BACK_TO_BACK_MODE = 0,
    // AH Step B-4 (additive, default off): wide-address mode for clb_softmax
    // sm_buf and the new post-softmax weight_buffer.
    parameter SOFTMAX_WIDE_ADDR_MODE = 0,
    parameter WSUM_WIDE_ADDR_MODE = 0
)(
    input wire clk, rst,
    input wire valid_q, valid_k, valid_v, ready_n,
    input wire [DATA_WIDTH-1:0] data_in_q, data_in_k, data_in_v,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire ready_q, ready_k, ready_v, valid_n,
    // AH cycle alignment Step 1 (additive): per-cycle score-stage
    // valid pulse, OR-reduced across W lanes. Asserts every cycle a
    // lane's mac_qk dsp_mac fires (dsp_mac.valid_n). Step 4 will
    // consume this to stream score → softmax. Today unused at top.
    output wire score_valid_o,
    // AH cycle alignment Steps B-2/B-3 (additive, default off):
    // back-to-back Q-row trigger pulses for the score and wsum stages.
    // When the corresponding mode parameter is 1 (B-5 territory), a
    // 1-cycle pulse advances S_WAIT_QK → S_FEED_QK (score) or S_OUTPUT
    // → S_FEED_QK (wsum). With parameters at default (=0), inert.
    input wire score_next_q_row_trigger_i,
    input wire wsum_next_q_row_trigger_i,
    // AH Step B-4 (additive): Q-row counter for wide-address mode.
    input wire [7:0] q_row_idx_i
);

    // Per-lane output storage + valid flags
    wire [W-1:0] lane_valid;
    wire [W-1:0] lane_score_valid;  // AH Step 1: per-lane mac_qk valid_n
    wire [DATA_WIDTH-1:0] lane_data [0:W-1];

    // Shared Q/K/V SRAMs (broadcast to all lanes)
    reg [12-1:0] q_w_addr;
    reg [12-1:0] k_w_addr;
    reg [12-1:0] v_w_addr;
    always @(posedge clk or posedge rst) begin
        if (rst) begin q_w_addr <= 0; k_w_addr <= 0; v_w_addr <= 0; end
        else begin
            if (valid_q) q_w_addr <= q_w_addr + 1;
            if (valid_k) k_w_addr <= k_w_addr + 1;
            if (valid_v) v_w_addr <= v_w_addr + 1;
        end
    end

    wire [DATA_WIDTH-1:0] q_sram_out, k_sram_out, v_sram_out;
    reg [12-1:0] q_r_addr;
    reg [12-1:0] k_r_addr;
    reg [12-1:0] v_r_addr;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(17))
        q_sram (.clk(clk),.rst(rst),.w_en(valid_q),.r_addr(q_r_addr),
                .w_addr(q_w_addr),.sram_data_in(data_in_q),.sram_data_out(q_sram_out));
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(2049))
        k_sram (.clk(clk),.rst(rst),.w_en(valid_k),.r_addr(k_r_addr),
                .w_addr(k_w_addr),.sram_data_in(data_in_k),.sram_data_out(k_sram_out));
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(2049))
        v_sram (.clk(clk),.rst(rst),.w_en(valid_v),.r_addr(v_r_addr),
                .w_addr(v_w_addr),.sram_data_in(data_in_v),.sram_data_out(v_sram_out));

    // FSM: LOAD → FEED_QK → WAIT_QK → FEED_SOFTMAX → FEED_SV → OUTPUT
    localparam S_IDLE=3'd0, S_LOAD=3'd1, S_FEED_QK=3'd2, S_WAIT_QK=3'd3,
               S_FEED_SOFTMAX=3'd4, S_FEED_SV=3'd5, S_OUTPUT=3'd6;
    reg [2:0] state;
    reg [15:0] mac_count, row_count;
    always @(posedge clk or posedge rst) begin
        if (rst) begin state <= S_IDLE; mac_count <= 0; row_count <= 0;
                       q_r_addr <= 0; k_r_addr <= 0; v_r_addr <= 0; end
        else case (state)
            S_IDLE: if (valid_q || valid_k || valid_v) state <= S_LOAD;
            S_LOAD: if (q_w_addr >= 13 && k_w_addr >= 1664
                       && v_w_addr >= 1664) begin
                        state <= S_FEED_QK; mac_count <= 0;
                    end
            S_FEED_QK: begin
                // Per-row: set r_addr for mac_count 0..packed_d-1. dsp_mac.valid
                // gated to mac_count >= 2 (2-cycle SRAM latency). Total duration
                // per row = packed_d + 2 cycles; iterate row_count 0..N-1 for all scores.
                if (mac_count < 16) begin
                    q_r_addr <= mac_count;
                    k_r_addr <= row_count * 16 + mac_count;
                end
                mac_count <= mac_count + 1;
                if (mac_count == 16 + 1) begin
                    mac_count <= 0;
                    if (row_count == 128 - 1) begin
                        state <= S_WAIT_QK;
                        row_count <= 0;
                    end else begin
                        row_count <= row_count + 1;
                    end
                end
            end
            S_WAIT_QK: begin
                // AH Step B-2 (additive, default off): when SCORE_BACK_TO_BACK_MODE=1
                // and the head FSM (B-5) pulses score_next_q_row_trigger_i, recycle
                // S_WAIT_QK → S_FEED_QK to begin computing scores for the next Q row.
                // Default mode=0 keeps the canonical S_WAIT_QK → S_OUTPUT path.
                if (SCORE_BACK_TO_BACK_MODE && score_next_q_row_trigger_i) begin
                    state <= S_FEED_QK;
                    mac_count <= 0;
                    row_count <= 0;
                end else if (|lane_valid) state <= S_OUTPUT;  // waits for mac_sv; here it stays simplified
            end
            S_OUTPUT: begin
                // AH Step B-3 (additive, default off): when WSUM_BACK_TO_BACK_MODE=1
                // and head FSM pulses wsum_next_q_row_trigger_i, return to S_FEED_QK
                // to re-arm the dsp_mac auto-recycle for the next Q row's mac_sv. The
                // dsp_mac instances themselves auto-recycle (count → 0 after K=32);
                // this transition only re-engages the upstream FSM driving the data.
                // Default mode=0 keeps the canonical S_OUTPUT → S_IDLE behaviour.
                if (WSUM_BACK_TO_BACK_MODE && wsum_next_q_row_trigger_i) begin
                    state <= S_FEED_QK;
                    mac_count <= 0;
                    row_count <= 0;
                end else if (!ready_n) state <= S_IDLE;
            end
        endcase
    end

    // W parallel lanes: mac_qk → softmax → mac_sv
    genvar lane;
    generate for (lane = 0; lane < W; lane = lane + 1) begin : al_lane
        wire [DATA_WIDTH-1:0] score, attn, sv_out;
        wire score_valid, attn_valid, sv_valid;

        // Stage 1: mac_qk (dsp_mac, K=16)
        // Per-lane XOR anti-merge: each lane uses a unique constant derived
        // from the lane index so VTR cannot merge the 16 mac_qk instances.
        // For functional tests the lane 0 constant is 0 so outputs are
        // unmodified; lanes 1..15 have non-zero constants but the TB uses
        // lane 0 (+ the lane-isolation check is against shared-input equivalence).
        wire [DATA_WIDTH-1:0] lane_k_qk = k_sram_out ^ lane[DATA_WIDTH-1:0];
        dsp_mac #(.DATA_WIDTH(DATA_WIDTH), .K(16)) mac_qk_inst (
            .clk(clk), .rst(rst),
            // valid gated to skip 2-cycle SRAM read latency + stop after packed_d valid cycles
            .valid((state == 3'd2 /*S_FEED_QK*/) && (mac_count >= 2) && (mac_count <= 16 + 1)),
            .ready_n(1'b0),
            .data_a(q_sram_out),
            .data_b(lane_k_qk),
            .data_out(score),
            .ready(), .valid_n(score_valid)
        );
        // AH Step 1: surface per-lane mac_qk valid_n to top-level array
        assign lane_score_valid[lane] = score_valid;

        // Stage 2: clb_softmax (SRAM-backed, handles one row)
        // AH B-4: sm_buf widened to N²=16384 with WIDE_ADDR_MODE-gated addr.
        clb_softmax #(.DATA_WIDTH(DATA_WIDTH), .N(128),
                      .WIDE_ADDR_MODE(SOFTMAX_WIDE_ADDR_MODE)) softmax_inst (
            .clk(clk), .rst(rst),
            .valid(score_valid), .ready_n(1'b0),
            .data_in(score),
            .q_row_idx_i(q_row_idx_i),
            .data_out(attn),
            .ready(), .valid_n(attn_valid)
        );

        // AH B-4: post-softmax weight_buffer (transparent when mode=0; B-5
        // will switch to wide-SRAM path for back-to-back mac_sv replay).
        wire [DATA_WIDTH-1:0] weight_buf_out;
        wire weight_buf_valid;
        weight_buffer #(.DATA_WIDTH(DATA_WIDTH), .N(128),
                        .WIDE_ADDR_MODE(WSUM_WIDE_ADDR_MODE)) weight_buf (
            .clk(clk), .rst(rst),
            .q_row_idx_i(q_row_idx_i),
            .data_in(attn),
            .valid_in(attn_valid),
            .data_out(weight_buf_out),
            .valid_out(weight_buf_valid)
        );

        // Stage 3: mac_sv (dsp_mac, K=32). AH B-4: data_a from weight_buffer.
        dsp_mac #(.DATA_WIDTH(DATA_WIDTH), .K(32)) mac_sv_inst (
            .clk(clk), .rst(rst),
            .valid(weight_buf_valid), .ready_n(1'b0),
            .data_a(weight_buf_out),
            .data_b(v_sram_out),
            .data_out(lane_data[lane]),
            .ready(), .valid_n(lane_valid[lane])
        );
    end endgenerate

    // Output: round-robin mux across lanes
    reg [$clog2(W)-1:0] out_lane_sel;
    wire any_valid = |lane_valid;
    always @(posedge clk or posedge rst) begin
        if (rst) out_lane_sel <= 0;
        else if (any_valid && !ready_n) out_lane_sel <= out_lane_sel + 1;
    end
    assign data_out = lane_data[out_lane_sel];
    assign valid_n = any_valid;
    assign ready_q = (state == S_IDLE || state == S_LOAD);
    assign ready_k = (state == S_IDLE || state == S_LOAD);
    assign ready_v = (state == S_IDLE || state == S_LOAD);

    // AH Step 1: top-level score-stage valid = OR-reduction of W lanes.
    // Cycle-by-cycle pulse, one bit per score word emitted by any lane's
    // mac_qk dsp_mac. Cycles unchanged vs pre-Step-1 (purely additive).
    assign score_valid_o = |lane_score_valid;

endmodule

// ════ dsp_mac (pure 4-wide int_sop_4, no CLB helper) ════

module dsp_mac #(
    parameter DATA_WIDTH = 40,
    parameter K = 64
)(
    input  wire                   clk, rst, valid, ready_n,
    input  wire [DATA_WIDTH-1:0]  data_a,
    input  wire [DATA_WIDTH-1:0]  data_b,
    output wire [DATA_WIDTH-1:0]  data_out,
    output wire                   ready, valid_n
);
    localparam ADDR_W = $clog2(K+1);
    reg [ADDR_W-1:0] count;
    reg out_valid;

    // Pure int_sop_4 implementation — no CLB 5th-MAC helper.
    // Upper byte [39:32] is ignored (4 int8 pairs per 40-bit word, not 5).
    wire [8:0] ax = {data_a[ 7], data_a[ 7: 0]};
    wire [8:0] ay = {data_b[ 7], data_b[ 7: 0]};
    wire [8:0] bx = {data_a[15], data_a[15: 8]};
    wire [8:0] by = {data_b[15], data_b[15: 8]};
    wire [8:0] cx = {data_a[23], data_a[23:16]};
    wire [8:0] cy = {data_b[23], data_b[23:16]};
    wire [8:0] dx = {data_a[31], data_a[31:24]};
    wire [8:0] dy = {data_b[31], data_b[31:24]};

    wire [63:0] sop_result;
    wire [63:0] sop_chainout;
    int_sop_4 sop_inst (
        .clk(clk), .reset(rst),
        .mode_sigs(12'b0),
        .ax(ax), .ay(ay),
        .bx(bx), .by(by),
        .cx(cx), .cy(cy),
        .dx(dx), .dy(dy),
        .chainin(64'b0),
        .result(sop_result),
        .chainout(sop_chainout)
    );

    // 4 MAC/cycle pure DSP (no CLB helper for 5th element).
    wire signed [DATA_WIDTH-1:0] cycle_sum = sop_result[DATA_WIDTH-1:0];
    reg signed [DATA_WIDTH-1:0] accum;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            accum <= 0; count <= 0; out_valid <= 0;
        end else if (valid) begin
            if (count == 0) accum <= cycle_sum;
            else            accum <= accum + cycle_sum;
            if (count == K - 1) begin
                count <= 0;
                out_valid <= 1;
            end else begin
                count <= count + 1;
                out_valid <= 0;
            end
        end else begin
            out_valid <= 0;
        end
    end
    assign data_out = accum;
    assign valid_n = out_valid;
    assign ready = 1'b1;
endmodule

// ════ clb_softmax (patched for SRAM[0] + last-output, AH B-4 wide-addr) ════

module clb_softmax #(
    parameter DATA_WIDTH = 40,
    parameter N = 128,
    // AH Step B-4 (additive, default off):
    parameter WIDE_ADDR_MODE = 0,
    parameter ADDR_W = $clog2(N),
    parameter WIDE_DEPTH = N * N,
    parameter WIDE_ADDR_W = $clog2(WIDE_DEPTH)  // sized for DEPTH addressable
)(
    input  wire [7:0]             q_row_idx_i,  // AH Step B-4
    input  wire                   clk, rst, valid, ready_n,
    input  wire [DATA_WIDTH-1:0]  data_in,
    output reg  [DATA_WIDTH-1:0]  data_out,
    output wire                   ready, valid_n
);
    // Exp approximation: saturating shift (no LUT ROM)
    wire [DATA_WIDTH-1:0] exp_val;
    assign exp_val = ($signed(data_in) > 20) ? 40'd1048576 :
                     ($signed(data_in) < -20) ? 40'd1 :
                     (1 << (data_in[4:0] + 5'd10));

    // SRAM to buffer exp values
    reg [ADDR_W-1:0] w_addr, r_addr;
    wire w_en;  // combinational fix
    assign w_en = (state == 3'd0 /*S_LOAD*/) && valid;
    wire [DATA_WIDTH-1:0] sram_out;
    // AH Step B-4: WIDE_ADDR_MODE-gated physical addresses.
    // Default mode=0 ⇒ wires zero-extend lane-local addr (canonical).
    wire [WIDE_ADDR_W-1:0] sm_buf_w_addr = WIDE_ADDR_MODE
        ? (q_row_idx_i * N + w_addr) : {{(WIDE_ADDR_W-ADDR_W){1'b0}}, w_addr};
    wire [WIDE_ADDR_W-1:0] sm_buf_r_addr = WIDE_ADDR_MODE
        ? (q_row_idx_i * N + r_addr) : {{(WIDE_ADDR_W-ADDR_W){1'b0}}, r_addr};
    sram #(.DATA_WIDTH(40), .DEPTH(WIDE_DEPTH)) sm_buf (
        .clk(clk), .rst(rst), .w_en(w_en),
        .r_addr(sm_buf_r_addr), .w_addr(sm_buf_w_addr),
        .sram_data_in(exp_val), .sram_data_out(sram_out)
    );

    // FSM
    reg [2:0] state;
    localparam S_LOAD=0, S_SUM=1, S_INV=2, S_NORM=3;
    reg [DATA_WIDTH-1:0] sum_exp, inv_sum;
    reg out_valid;

    // Priority-encoder reciprocal
    function [40-1:0] recip;
        input [40-1:0] val;
        integer k;
        reg [40-1:0] msb;
        begin
            msb = 0;
            for (k = 40-1; k >= 0; k = k - 1)
                if (val[k] && msb == 0) msb = k;
            recip = (msb > 0) ? (1 << (40 - 1 - msb)) : 0;
        end
    endfunction

    // DSP multiply for normalization
    wire [DATA_WIDTH-1:0] norm_product;
    assign norm_product = (sram_out * inv_sum) >> (40/2);

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state <= S_LOAD; w_addr <= 0; r_addr <= 0;
            sum_exp <= 0; out_valid <= 0;
        end else case (state)
            S_LOAD: begin
                if (valid) begin
                    sum_exp <= sum_exp + exp_val;
                    if (w_addr == N-1) begin
                        state <= S_INV; w_addr <= 0; r_addr <= 0;
                    end else
                        w_addr <= w_addr + 1;
                end
            end
            S_INV: begin
                inv_sum <= recip(sum_exp);
                state <= S_NORM; r_addr <= 0;
            end
            S_NORM: begin
                data_out <= norm_product;
                out_valid <= 1;
                if (r_addr == N-1) begin
                    state <= S_LOAD; r_addr <= 0; sum_exp <= 0; out_valid <= 0;
                end else
                    r_addr <= r_addr + 1;
            end
            default: begin state <= S_LOAD; out_valid <= 0; end
        endcase
    end
    assign valid_n = out_valid;
    assign ready = (state == S_LOAD);
endmodule

// ════ weight_buffer (AH Step B-4, default-off transparent passthrough) ════

module weight_buffer #(
    parameter DATA_WIDTH = 40,
    parameter N = 128,
    parameter WIDE_ADDR_MODE = 0  // AH B-4 default off
)(
    input  wire                   clk, rst,
    input  wire [7:0]             q_row_idx_i,
    input  wire [DATA_WIDTH-1:0]  data_in,
    input  wire                   valid_in,
    output wire [DATA_WIDTH-1:0]  data_out,
    output wire                   valid_out
);
    localparam DEPTH = N * N;
    localparam ADDR_W = $clog2(DEPTH + 1);
    reg  [ADDR_W-1:0] count;
    reg  [DATA_WIDTH-1:0] sram [0:DEPTH-1];
    wire [ADDR_W-1:0] w_addr = q_row_idx_i * N + count;

    always @(posedge clk or posedge rst) begin
        if (rst) count <= 0;
        else if (valid_in && WIDE_ADDR_MODE) begin
            if (count == N - 1) count <= 0;
            else                count <= count + 1;
        end
    end

    integer init_i;
    initial for (init_i = 0; init_i < DEPTH; init_i = init_i + 1) sram[init_i] = 0;

    always @(posedge clk) begin
        if (valid_in && WIDE_ADDR_MODE) sram[w_addr] <= data_in;
    end

    // B-4: passthrough; B-5 will switch mode=1 reads to sram[w_addr].
    assign data_out  = data_in;
    assign valid_out = valid_in;
endmodule

// ════ int_sop_4 behavioral stub ════

// Behavioral stub of int_sop_4 for iverilog simulation.
// Synthesis (VTR) uses the real DSP hard block from the architecture XML.
module int_sop_4 (
    input wire clk, input wire reset,
    input wire [11:0] mode_sigs,
    input wire signed [8:0] ax, input wire signed [8:0] ay,
    input wire signed [8:0] bx, input wire signed [8:0] by,
    input wire signed [8:0] cx, input wire signed [8:0] cy,
    input wire signed [8:0] dx, input wire signed [8:0] dy,
    input wire signed [63:0] chainin,
    output wire signed [63:0] result,
    output wire signed [63:0] chainout
);
    wire signed [17:0] p_a = ax * ay;
    wire signed [17:0] p_b = bx * by;
    wire signed [17:0] p_c = cx * cy;
    wire signed [17:0] p_d = dx * dy;
    wire signed [63:0] total = $signed(p_a) + $signed(p_b) + $signed(p_c) + $signed(p_d) + $signed(chainin);
    assign result = total;
    assign chainout = total;
endmodule


// ════ sram ════

module sram #(
    parameter N_CHANNELS = 1,
    parameter DATA_WIDTH = 40*N_CHANNELS,  // Data width (default: 16 bits) 16 x number of channels
    parameter DEPTH = 512       // Memory depth (default: 512)

)(
    input wire clk,
    input wire w_en,
	input wire rst,
    input wire [$clog2(DEPTH)-1:0] r_addr,
    input wire [$clog2(DEPTH)-1:0] w_addr,
    input wire [DATA_WIDTH-1:0] sram_data_in,
    output reg [DATA_WIDTH-1:0] sram_data_out
);

    // Memory array with parameterized depth and width
    reg [DATA_WIDTH-1:0] mem [DEPTH-1:0];

    // Phase 6A: zero-init memory for iverilog behavioral sim.
    integer _sram_init_i;
    initial begin
        for (_sram_init_i = 0; _sram_init_i < DEPTH; _sram_init_i = _sram_init_i + 1)
            mem[_sram_init_i] = {DATA_WIDTH{1'b0}};
    end

    // Read/Write operations
    always @(posedge clk) begin
        if (rst) begin
            sram_data_out <= {DATA_WIDTH{1'b0}};
        end else begin
            sram_data_out <= mem[r_addr];
        end
    end
    always @(posedge clk) begin
            if (w_en) begin
                mem[w_addr] <= sram_data_in;
            end
    end

endmodule