// Azure-Lily Attention Head Top — matches IMC attention_model (no O proj)
// Generated by gen_azurelily_attn_head_top.py
//   d_model=128, d_head=64, N_SEQ=128, W=16, EPW_DSP=4
//
// Architecture (mirrors azurelily/models/attention.py attention_model):
//   N tokens × (Q/K/V projection FC) → pack5_buffer → Q/K/V SRAM buffers
//   → azurelily_dimm_top (W=16 lanes, single fire over full N×d Q/K/V) → out
//
// NO output projection — sim's attention_model stops at mac_sv.
//
// Composition:
//   - 3 × azurelily_fc_128_64       (Q/K/V proj, fired N=128 times each)
//   - 3 × pack5_buffer              (Q/K/V unpacked→packed converters)
//   - 3 × sram (Q/K/V buffer)       (depth = N⌈d_head/5⌉ + 1 = 1665)
//   - 1 × azurelily_dimm_top        (W=16 lanes, fires once)
//
// Outer FSM (Bug-1 fix: outer Q-row loop):
//   S_IDLE          : await valid_x → S_STREAM_TOKENS
//   S_STREAM_TOKENS : hold fc_valid_in=1 continuously; FC processes rows
//                     back-to-back (parallel-output dsp_macs, 1 byte/cyc drain
//                     into pack5_buffer).  Track FC valid_n bytes; once
//                     N_SEQ × D_HEAD bytes have flowed, transition to
//                     S_DIMM_RST.  No fc_rst pulses between tokens.
//   S_DIMM_RST      : pulse dimm_soft_rst for a few cycles so the DIMM's
//                     FSM returns to S_IDLE between Q rows (k/v_sram persists)
//   S_DIMM_FIRE     : drive valid_q/k/v with current Q row + full K/V stream
//                     (replays buffered Q row from q_buf_r_addr starting at
//                     q_row_idx * PACKED_D); DIMM internally iterates 128
//                     K rows in S_FEED_QK for current Q row.
//   S_DIMM_WAIT     : wait for dimm_valid_n (DIMM completed mac_qk + softmax
//                     + mac_sv for this Q row) — ensures all DPE/dsp_mac
//                     stages fired before we re-rst the DIMM for next Q row.
//   S_DRAIN         : DIMM emits valid_n stream → output port (final Q row).
//
// Format note: AL DIMM's S_LOAD threshold uses EPW=5 (q_w_addr >= 13,
// k_w_addr/v_w_addr >= 1664).  This is a pre-existing inconsistency in
// gen_dimm_azurelily_top.py vs dsp_mac (which reads EPW=4 lanes) — DO NOT
// FIX HERE.  pack5_buffer matches the EPW=5 threshold semantics.

`timescale 1ns / 1ps

module azurelily_attn_head_d64_c128 #(
    parameter DATA_WIDTH = 40,
    parameter D_MODEL    = 128,
    parameter D_HEAD     = 64,
    parameter N_SEQ      = 128,
    parameter W          = 16
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);
    localparam PACKED_K  = 32;   // FC input packed words per token
    localparam PACKED_D  = 13;   // packed Q/K/V words per token (EPW=5)
    localparam BUF_DEPTH = 1665;  // total packed Q/K/V words across N tokens
    localparam TOTAL_FC_PULSES = N_SEQ * PACKED_D;  // FC valid_n pulses per arm
                                                    // (each pulse carries EPW_O=5 packed bytes)

    // ───────── outer FSM state encoding (Bug-1 fix: outer Q-row loop) ─────────
    localparam S_IDLE             = 4'd0;
    localparam S_STREAM_TOKENS    = 4'd1;
    localparam S_DIMM_RST         = 4'd2;  // hold DIMM in soft rst between Q rows
    localparam S_DIMM_FIRE        = 4'd5;  // drive valid_q/k/v for current Q row
    localparam S_DIMM_WAIT        = 4'd4;  // wait for DIMM to produce valid_n
    localparam S_DRAIN            = 4'd6;  // pass through DIMM output (final Q row)
    reg [3:0] state;

    // Streaming counters
    reg [7:0] token_count;       // 0..N_SEQ-1 input rows queued
    reg [5:0] feed_count;       // 0..PACKED_K within current input row
    reg [21:0]               fc_out_pulse_count; // 0..TOTAL_FC_PULSES seen on FC valid_n
    // Bug-1 fix: outer-loop Q-row counter and DIMM soft-rst pulse
    reg [7:0] q_row_idx;          // 0..N_SEQ-1 over Q rows
    reg [3:0]                dimm_rst_count;     // S_DIMM_RST hold counter
    reg                      dimm_soft_rst;      // pulses high during S_DIMM_RST

    // No fc_rst pulses between tokens — FC streams all rows continuously
    wire fc_rst = rst;

    // ───────── valid + data into FCs ─────────
    // Stream input bytes across all N_SEQ tokens.  Per token: PACKED_K
    // cycles of valid input followed by 3 cycles of "gap" (valid=0) to
    // match the FC's per-row FSM period (PACKED_K + 3 cycles for compute
    // + latch).  This keeps i_w_addr lockstep with mac_count modulo
    // PACKED_K and prevents row N+1's data from contaminating row N's
    // input SRAM.
    wire fc_valid_in = (state == S_STREAM_TOKENS) && (token_count < N_SEQ)
                       && (feed_count < PACKED_K);
    wire [DATA_WIDTH-1:0] fc_data_in = data_in_x;

    // FC outputs (1 int8 in low byte of 40-bit valid_n word)
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    azurelily_fc_128_64 fc_q_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(q_fc_out), .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    azurelily_fc_128_64 fc_k_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(k_fc_out), .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    azurelily_fc_128_64 fc_v_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(v_fc_out), .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ───────── FC → q/k/v_buf passthrough writes ─────────
    // The post-streaming FC emits packed-5 bytes per valid_n cycle
    // (data_out[39:0] = 5 packed int8 bytes).  This MATCHES q_buf's word
    // format, so we wire the FC's data_out directly to the q_buf write
    // port — no pack5_buffer required.  The write address increments
    // monotonically per FC valid_n pulse.
    reg  [10:0] q_buf_w_addr_r, k_buf_w_addr_r, v_buf_w_addr_r;
    wire q_buf_w_en   = q_fc_valid_n;
    wire k_buf_w_en   = k_fc_valid_n;
    wire v_buf_w_en   = v_fc_valid_n;
    wire [10:0] q_buf_w_addr = q_buf_w_addr_r;
    wire [10:0] k_buf_w_addr = k_buf_w_addr_r;
    wire [10:0] v_buf_w_addr = v_buf_w_addr_r;
    wire [DATA_WIDTH-1:0]     q_buf_w_data = q_fc_out;
    wire [DATA_WIDTH-1:0]     k_buf_w_data = k_fc_out;
    wire [DATA_WIDTH-1:0]     v_buf_w_data = v_fc_out;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            q_buf_w_addr_r <= 0;
            k_buf_w_addr_r <= 0;
            v_buf_w_addr_r <= 0;
        end else begin
            if (q_fc_valid_n) q_buf_w_addr_r <= q_buf_w_addr_r + 1;
            if (k_fc_valid_n) k_buf_w_addr_r <= k_buf_w_addr_r + 1;
            if (v_fc_valid_n) v_buf_w_addr_r <= v_buf_w_addr_r + 1;
        end
    end

    // ───────── Q/K/V buffer SRAMs ─────────
    // Read side: streamed out as DIMM input during S_DIMM_FIRE.
    reg [10:0] q_buf_r_addr, k_buf_r_addr, v_buf_r_addr;
    wire [DATA_WIDTH-1:0]    q_buf_r_data, k_buf_r_data, v_buf_r_data;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        q_buf (.clk(clk), .rst(rst), .w_en(q_buf_w_en),
               .r_addr(q_buf_r_addr), .w_addr(q_buf_w_addr),
               .sram_data_in(q_buf_w_data), .sram_data_out(q_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        k_buf (.clk(clk), .rst(rst), .w_en(k_buf_w_en),
               .r_addr(k_buf_r_addr), .w_addr(k_buf_w_addr),
               .sram_data_in(k_buf_w_data), .sram_data_out(k_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        v_buf (.clk(clk), .rst(rst), .w_en(v_buf_w_en),
               .r_addr(v_buf_r_addr), .w_addr(v_buf_w_addr),
               .sram_data_in(v_buf_w_data), .sram_data_out(v_buf_r_data));

    // ───────── DIMM inputs (replay buffered Q/K/V into DIMM stream) ─────────
    // Bug-1 fix: dimm_replay_count is reused per Q-row iteration. The DIMM is
    // soft-reset between Q rows; on each iteration we drive valid_q only for
    // PACKED_D cycles (one Q row) but valid_k/v for full BUF_DEPTH-1 cycles
    // (re-loading K/V each iteration; SRAM contents idempotent).
    reg [10:0] dimm_replay_count;
    wire dimm_replay_active = (state == S_DIMM_FIRE);
    // Q drives only for the current Q row (PACKED_D packed words = 13).
    wire dimm_valid_q = dimm_replay_active && (dimm_replay_count < PACKED_D);
    // K and V re-stream the full N×PACKED_D buffer for every iteration (1664 cyc).
    wire dimm_valid_k = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);
    wire dimm_valid_v = dimm_replay_active && (dimm_replay_count < BUF_DEPTH - 1);

    // ───────── DIMM (W=16 lanes, mac_qk + clb_softmax + mac_sv) ─────────
    // Bug-1 fix: dimm_rst_internal pulses high between Q rows so the DIMM's
    // FSM resets to S_IDLE while its k_sram/v_sram contents persist (SRAMs
    // don't clear on rst). Each iteration reloads K/V — idempotent (same data
    // to same addresses).
    wire dimm_rst_internal = rst | dimm_soft_rst;
    wire [DATA_WIDTH-1:0] dimm_out;
    wire dimm_valid_n_w;
    // AH Step 1: per-cycle DIMM score-stage valid (mac_qk dsp_mac.valid_n
    // OR-reduced across W lanes). Unused at head level for now; Step 4 will
    // consume it to wire score → softmax streaming directly.
    wire dimm_score_valid_o;  /* unused — Step 1 observation port */
    azurelily_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH)
    ) dimm_inst (
        .clk(clk), .rst(dimm_rst_internal),
        .valid_q(dimm_valid_q), .valid_k(dimm_valid_k), .valid_v(dimm_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_r_data), .data_in_k(k_buf_r_data), .data_in_v(v_buf_r_data),
        .data_out(dimm_out),
        .ready_q(), .ready_k(), .ready_v(),
        .valid_n(dimm_valid_n_w),
        .score_valid_o(dimm_score_valid_o)
    );

    // ───────── outer FSM body (streaming) ─────────
    //
    // Streaming model:
    //   - Hold fc_valid_in=1 across all N_SEQ × PACKED_K input bytes.
    //   - FC's parallel-output dsp_macs auto-fire on the continuous input
    //     stream; FC produces 1 row of D_HEAD outputs every PACKED_K cycles
    //     (steady-state).  drain rate = 1 byte/cyc — bottleneck if D_HEAD >
    //     PACKED_K (true for D_HEAD=64 vs PACKED_K=32; max(32,64)=64 cyc/row).
    //   - feed_count tracks position within current input row (0..PACKED_K-1).
    //   - token_count tracks input rows queued (0..N_SEQ-1).
    //   - fc_out_byte_count tracks FC valid_n pulses (= bytes pushed into
    //     packers) — when it reaches TOTAL_FC_BYTES, all rows have drained.
    //   - Once fc_out_byte_count == TOTAL_FC_BYTES: transition to S_DIMM_FIRE.
    //   - No fc_rst_pulse; FC FSM auto-recycles between rows.
    // Bug-1 fix: outer Q-row loop (matches NL-DPE head's S_DIMM_RST/FIRE/WAIT
    // structure). For each q_row_idx in [0..N-1]:
    //   1. S_DIMM_RST  — pulse dimm_soft_rst for DIMM_RST_CYCLES (skip on first iter).
    //   2. S_DIMM_FIRE — drive valid_q (PACKED_D cyc, current Q row) and valid_k/v
    //                    (BUF_DEPTH-1 cyc, full re-stream); read q_buf_r_addr at
    //                    q_row_idx*PACKED_D + dimm_replay_count.
    //   3. S_DIMM_WAIT — wait for dimm_valid_n_w (DIMM completed mac_qk/softmax/mac_sv).
    //   4. If q_row_idx+1 < N: increment q_row_idx, return to S_DIMM_RST.
    //      Else: transition to S_DRAIN (final Q row's outputs visible at top).
    localparam DIMM_RST_CYCLES = 4'd4;
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state              <= S_IDLE;
            token_count        <= 0;
            feed_count         <= 0;
            fc_out_pulse_count <= 0;
            dimm_replay_count  <= 0;
            q_buf_r_addr       <= 0;
            k_buf_r_addr       <= 0;
            v_buf_r_addr       <= 0;
            q_row_idx          <= 0;
            dimm_rst_count     <= 0;
            dimm_soft_rst      <= 1'b0;
        end else begin
            // Track FC valid_n pulses (each pulse carries EPW_O=5 packed
            // bytes, written directly to q_buf).  All three FC arms produce
            // identical valid_n cadence (same rst, same valid, same shape),
            // so q_fc_valid_n is sufficient.
            if (q_fc_valid_n) begin
                fc_out_pulse_count <= fc_out_pulse_count + 1;
            end
            case (state)
                S_IDLE: begin
                    if (valid_x) begin
                        state              <= S_STREAM_TOKENS;
                        token_count        <= 0;
                        feed_count         <= 0;
                        fc_out_pulse_count <= 0;
                    end
                end
                S_STREAM_TOKENS: begin
                    // Pace input bytes into the FCs at the FC's per-row FSM
                    // period (PACKED_K + 3 cycles).  feed_count cycles
                    // 0..PACKED_K+2; valid=1 for cycles 0..PACKED_K-1 and
                    // valid=0 for cycles PACKED_K..PACKED_K+2 (3-cyc gap).
                    if (token_count < N_SEQ) begin
                        if (feed_count == PACKED_K + 2) begin
                            feed_count  <= 0;
                            token_count <= token_count + 1;
                        end else begin
                            feed_count  <= feed_count + 1;
                        end
                    end
                    // Wait until all FC outputs have been collected and
                    // written to Q/K/V buffer SRAMs.  Each token produces
                    // D_HEAD bytes which the FC drains as PACKED_D=
                    // ceil(D_HEAD/EPW_O) packed words; one valid_n pulse
                    // per packed word.  Total expected pulses = N_SEQ ×
                    // PACKED_D = TOTAL_FC_PULSES.
                    if (fc_out_pulse_count >= TOTAL_FC_PULSES) begin
                        // Enter Q-row loop. q_row_idx already 0.
                        state             <= S_DIMM_RST;
                        dimm_replay_count <= 0;
                        q_buf_r_addr      <= 0;
                        k_buf_r_addr      <= 0;
                        v_buf_r_addr      <= 0;
                        dimm_rst_count    <= 0;
                        dimm_soft_rst     <= 1'b0;  // first iteration: skip soft rst
                    end
                end
                S_DIMM_RST: begin
                    // Pulse dimm_soft_rst for DIMM_RST_CYCLES cycles (skip on
                    // q_row_idx==0; DIMM was just rst by global).
                    if (q_row_idx == 0) begin
                        state             <= S_DIMM_FIRE;
                        dimm_replay_count <= 0;
                        dimm_soft_rst     <= 1'b0;
                    end else begin
                        dimm_soft_rst  <= 1'b1;
                        dimm_rst_count <= dimm_rst_count + 1;
                        if (dimm_rst_count + 1 == DIMM_RST_CYCLES) begin
                            dimm_soft_rst     <= 1'b0;
                            state             <= S_DIMM_FIRE;
                            dimm_replay_count <= 0;
                        end
                    end
                end
                S_DIMM_FIRE: begin
                    // Stream Q (PACKED_D cycles, current Q row from q_buf at
                    // offset q_row_idx*PACKED_D) and K/V (full BUF_DEPTH-1 cyc
                    // re-stream of the static k/v_buf into DIMM's K/V SRAMs).
                    // dimm_valid_q gates valid_q to first PACKED_D cycles only.
                    if (dimm_replay_count < BUF_DEPTH - 1) begin
                        // Q reads current Q row's PACKED_D words; first PACKED_D
                        // cycles use offset q_row_idx*PACKED_D, rest are dontcare
                        // (gated by dimm_valid_q).
                        q_buf_r_addr      <= q_row_idx * PACKED_D + dimm_replay_count;
                        k_buf_r_addr      <= dimm_replay_count;
                        v_buf_r_addr      <= dimm_replay_count;
                        dimm_replay_count <= dimm_replay_count + 1;
                    end else begin
                        // Full K/V loaded; transition to wait for DIMM compute.
                        state <= S_DIMM_WAIT;
                    end
                end
                S_DIMM_WAIT: begin
                    // Wait for DIMM to fully complete this Q row.
                    // dimm_valid_n_w is high once any lane reaches mac_sv output,
                    // by which time mac_qk + softmax + mac_sv have all fired.
                    if (dimm_valid_n_w) begin
                        if (q_row_idx + 1 == N_SEQ) begin
                            // Last Q row complete — drain output to top.
                            state <= S_DRAIN;
                        end else begin
                            // Move to next Q row: soft-reset DIMM, repeat.
                            q_row_idx      <= q_row_idx + 1;
                            state          <= S_DIMM_RST;
                            dimm_rst_count <= 0;
                            dimm_soft_rst  <= 1'b1;
                        end
                    end
                end
                S_DRAIN: begin
                    // Hold here; DIMM internally drives valid_n through W lanes.
                    // Top exits to S_IDLE only via top-level rst (one-shot run).
                    state <= S_DRAIN;
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ───────── outputs ─────────
    assign data_out = dimm_out;
    assign valid_n  = dimm_valid_n_w;
    assign ready_x  = (state == S_IDLE) || (state == S_STREAM_TOKENS);

endmodule

// ════ pack5_buffer ════
//
// Accumulates 5 consecutive int8 bytes (low byte of data_in[39:0]) into
// a packed 40-bit word, emitting one packed write to the buffer SRAM every
// 5 valid_in cycles.  Bytes are placed in increasing-byte order:
//
//   word[ 7: 0] = byte 0 (first input)
//   word[15: 8] = byte 1
//   word[23:16] = byte 2
//   word[31:24] = byte 3
//   word[39:32] = byte 4 (last input)
//
// The packer is purely a write-side helper: it drives w_en, w_addr, sram_data_in.
// It does NOT own the SRAM (the parent instantiates the buffer SRAM).
//
// Reset semantics: rst clears the partial register, w_addr, and pack_count.

module pack5_buffer #(
    parameter DATA_WIDTH = 40,
    parameter ADDR_W     = 11,
    parameter EPW        = 5
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_in,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg                     w_en,
    output reg  [ADDR_W-1:0]       w_addr,
    output reg  [DATA_WIDTH-1:0]   sram_data_in
);
    reg [2:0] pack_count;       // 0..EPW-1
    reg [DATA_WIDTH-1:0]     pack_reg;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            pack_count   <= 0;
            pack_reg     <= 0;
            w_en         <= 0;
            w_addr       <= 0;
            sram_data_in <= 0;
        end else begin
            w_en <= 0;  // default; raised exactly when we emit a packed word
            if (valid_in) begin
                // Insert low byte of data_in into byte-position pack_count.
                case (pack_count)
                    3'd0: pack_reg[ 7: 0] <= data_in[7:0];
                    3'd1: pack_reg[15: 8] <= data_in[7:0];
                    3'd2: pack_reg[23:16] <= data_in[7:0];
                    3'd3: pack_reg[31:24] <= data_in[7:0];
                    3'd4: pack_reg[39:32] <= data_in[7:0];
                    default: ;
                endcase

                if (pack_count == EPW - 1) begin
                    // Emit packed word: assemble combinationally so the
                    // commit happens the same cycle as the 5th byte arrives.
                    sram_data_in <= { data_in[7:0],
                                       pack_reg[31:24],
                                       pack_reg[23:16],
                                       pack_reg[15: 8],
                                       pack_reg[ 7: 0] };
                    w_en         <= 1;
                    pack_count   <= 0;
                    if (w_addr != {ADDR_W{1'b1}}) w_addr <= w_addr + 1;
                end else begin
                    pack_count <= pack_count + 1;
                end
            end
        end
    end
endmodule
