// Azure-Lily Attention Head Top — matches IMC attention_model (no O proj)
// Generated by gen_azurelily_attn_head_top.py
//   d_model=128, d_head=64, N_SEQ=128, W=16, EPW_DSP=4
//
// Architecture (mirrors azurelily/models/attention.py attention_model):
//   N tokens × (Q/K/V projection FC) → pack5_buffer → Q/K/V SRAM buffers
//   → azurelily_dimm_top (W=16 lanes, single fire over full N×d Q/K/V) → out
//
// NO output projection — sim's attention_model stops at mac_sv.
//
// Composition:
//   - 3 × azurelily_fc_128_64       (Q/K/V proj, fired N=128 times each)
//   - 3 × pack5_buffer              (Q/K/V unpacked→packed converters)
//   - 3 × sram (Q/K/V buffer)       (depth = N⌈d_head/5⌉ + 1 = 1665)
//   - 1 × azurelily_dimm_top        (W=16 lanes, fires once)
//
// Outer FSM (AH B-5 finish: K/V amortization + strict-serial cascade):
//   S_IDLE          : await valid_x → S_STREAM_TOKENS
//   S_STREAM_TOKENS : hold fc_valid_in=1 continuously; FC processes rows
//                     back-to-back (parallel-output dsp_macs, 1 byte/cyc drain
//                     into pack5_buffer).  Track FC valid_n pulses; once
//                     N_SEQ × PACKED_D pulses have flowed, transition to
//                     S_LOAD_KV.  No fc_rst pulses between tokens.
//   S_LOAD_KV       : drive valid_q for PACKED_D cycles (Q row 0's 13 packed
//                     words), then valid_k for BUF_DEPTH-1 cycles (full K),
//                     then valid_v for BUF_DEPTH-1 cycles (full V) — ONE-SHOT
//                     ingress (NOT repeated per Q row; DIMM's K/V SRAMs
//                     persist through the full cascade thanks to the AL DIMM
//                     SCORE/WSUM_BACK_TO_BACK_MODE reset semantics, which
//                     reset only Q-side addresses on next_q_row trigger).
//   S_CASCADE       : strict-serial Q-row processing.  For each Q row k=1..N-1:
//                       • Drive valid_q for PACKED_D cycles (Q row k's words,
//                         read from q_buf at offset k * PACKED_D).
//                       • Wait for dimm_wsum_done_o (= Q row k entered AL DIMM
//                         S_OUTPUT/S_WAIT_QK after mac_qk + softmax + mac_sv).
//                       • Fire all 3 next_q_row_trigger pulses simultaneously
//                         to recycle DIMM FSM (AL FSM returns to S_LOAD with
//                         q_w_addr/q_r_addr reset; K/V SRAM contents persist).
//                       • Increment q_row_idx for wide-addr indexing.
//                       • Repeat until q_row_idx == N_SEQ-1, then drain.
//   S_DRAIN_FINAL   : settle margin (PHASE_DRAIN_CYC) for last Q row's mac_sv
//                     to commit out_sram before output drain.
//   S_OUTPUT_DRAIN  : assert valid_n for N_FC_OUT_WORDS cycles (TB-counted).
//   S_OUTPUT_DONE   : terminal.
//
// Format note: AL DIMM's S_LOAD threshold uses EPW=5 (q_w_addr >= 13,
// k_w_addr/v_w_addr >= 1664).  This is a pre-existing inconsistency in
// gen_dimm_azurelily_top.py vs dsp_mac (which reads EPW=4 lanes) — DO NOT
// FIX HERE.  pack5_buffer matches the EPW=5 threshold semantics.

`timescale 1ns / 1ps

module azurelily_attn_head_d64_c128 #(
    parameter DATA_WIDTH = 40,
    parameter D_MODEL    = 128,
    parameter D_HEAD     = 64,
    parameter N_SEQ      = 128,
    parameter W          = 16
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);
    localparam PACKED_K  = 32;   // FC input packed words per token
    localparam PACKED_D  = 13;   // packed Q/K/V words per token (EPW=5)
    localparam BUF_DEPTH = 1665;  // total packed Q/K/V words across N tokens
    localparam TOTAL_FC_PULSES = N_SEQ * PACKED_D;  // FC valid_n pulses per arm
                                                    // (each pulse carries EPW_O=5 packed bytes)
    // AH B-5 finish: AL DIMM ingest counts mirror NL conventions.
    //   DIMM_Q_WORDS = PACKED_D (one Q row's packed words)
    //   DIMM_K_WORDS = BUF_DEPTH-1 (= N × PACKED_D, full K tensor)
    //   DIMM_V_WORDS = BUF_DEPTH-1 (full V tensor)
    localparam DIMM_Q_WORDS    = PACKED_D;
    localparam DIMM_K_WORDS    = BUF_DEPTH - 1;
    localparam DIMM_V_WORDS    = BUF_DEPTH - 1;
    localparam N_FC_OUT_WORDS  = N_SEQ * PACKED_D;  // mirrors NL N×PACKED_NQ drain

    // ───────── outer FSM state encoding (AH B-5 finish: K/V amortization) ─────
    // Strict-serial cascade matching NL head FSM (gen_nldpe_attn_head_top.py).
    // K/V loaded ONCE in S_LOAD_KV (one-shot Q0+K+V load); per Q row the head
    // drives valid_q for PACKED_D cycles + waits for dimm_wsum_done_o + fires
    // next_q_row triggers.
    //
    // State encoding kept aligned with the in-tree TB (tb_azurelily_attn_head_v2.v
    // lines 170-176): S_IDLE=0, S_LOAD_TOKEN=1 (= S_STREAM_TOKENS),
    // S_WAIT_FC=2, S_FC_DRAIN=3, S_INTER_TOKEN_RST=4 (legacy, unused post-B5),
    // S_DIMM_FIRE=5 (entered when FC arms drained — covers K/V load + cascade),
    // S_DRAIN=6 (terminal, stream output).  Multiple internal states map to
    // S_DIMM_FIRE=5 so the TB's T_fc_qkv_done timestamp (head_state==S_DIMM_FIRE)
    // fires at the right cycle (FC drain → DIMM cascade transition).
    localparam S_IDLE             = 4'd0;
    localparam S_STREAM_TOKENS    = 4'd1;  // = S_LOAD_TOKEN in TB
    localparam S_LOAD_KV          = 4'd5;  // = S_DIMM_FIRE in TB
    localparam S_CASCADE          = 4'd7;
    localparam S_DRAIN_FINAL      = 4'd8;
    localparam S_OUTPUT_DRAIN     = 4'd6;  // = S_DRAIN in TB
    localparam S_OUTPUT_DONE      = 4'd9;
    reg [3:0] state;

    // Streaming counters
    reg [7:0] token_count;       // 0..N_SEQ-1 input rows queued
    reg [5:0] feed_count;       // 0..PACKED_K within current input row
    reg [21:0]               fc_out_pulse_count; // 0..TOTAL_FC_PULSES seen on FC valid_n
    // AH B-5 finish: outer-loop Q-row counter (NL parity).
    reg [7:0] q_row_idx;                        // 0..N_SEQ-1 (drives DIMM wide-addr SRAMs)

    // Per-phase ingest counters for S_LOAD_KV / S_CASCADE drives.
    reg [10:0] dimm_q_count;      // valid_q pulses already issued
    reg [10:0] dimm_k_count;      // valid_k pulses already issued
    reg [10:0] dimm_v_count;      // valid_v pulses already issued
    reg drive_valid_q, drive_valid_k, drive_valid_v;

    // Drain margin counters — mirror NL S_DRAIN_FINAL / S_OUTPUT_DRAIN cycles.
    reg [15:0] phase_drain_count;
    reg [15:0] output_drain_count;

    // wsum_done_o is a 1-cycle edge pulse; track total count globally so events
    // fired during S_LOAD_KV (Q row 0 finishes inside DIMM before S_CASCADE entry)
    // aren't missed.
    reg [7:0] ws_done_count;        // cumulative wsum_done_o pulses observed
    reg [7:0] ws_consumed_count;    // wsum_done events consumed by S_CASCADE advance

    // AH B-5 finish: triggers driven combinationally from FSM state below.
    reg score_next_q_row_pulse, softmax_next_q_row_pulse, wsum_next_q_row_pulse;

    // Drain margin: mirror NL PHASE_DRAIN_CYC = 64.
    localparam PHASE_DRAIN_CYC = 16'd64;

    // No fc_rst pulses between tokens — FC streams all rows continuously
    wire fc_rst = rst;

    // ───────── valid + data into FCs ─────────
    // Stream input bytes across all N_SEQ tokens.  Per token: PACKED_K
    // cycles of valid input followed by 3 cycles of "gap" (valid=0) to
    // match the FC's per-row FSM period (PACKED_K + 3 cycles for compute
    // + latch).  This keeps i_w_addr lockstep with mac_count modulo
    // PACKED_K and prevents row N+1's data from contaminating row N's
    // input SRAM.
    wire fc_valid_in = (state == S_STREAM_TOKENS) && (token_count < N_SEQ)
                       && (feed_count < PACKED_K);
    wire [DATA_WIDTH-1:0] fc_data_in = data_in_x;

    // FC outputs (1 int8 in low byte of 40-bit valid_n word)
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    azurelily_fc_128_64 fc_q_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(q_fc_out), .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    azurelily_fc_128_64 fc_k_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(k_fc_out), .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    azurelily_fc_128_64 fc_v_inst (
        .clk(clk), .rst(fc_rst),
        .valid(fc_valid_in), .ready_n(1'b0),
        .data_in(fc_data_in),
        .data_out(v_fc_out), .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ───────── FC → q/k/v_buf passthrough writes ─────────
    // The post-streaming FC emits packed-5 bytes per valid_n cycle
    // (data_out[39:0] = 5 packed int8 bytes).  This MATCHES q_buf's word
    // format, so we wire the FC's data_out directly to the q_buf write
    // port — no pack5_buffer required.  The write address increments
    // monotonically per FC valid_n pulse.
    reg  [10:0] q_buf_w_addr_r, k_buf_w_addr_r, v_buf_w_addr_r;
    wire q_buf_w_en   = q_fc_valid_n;
    wire k_buf_w_en   = k_fc_valid_n;
    wire v_buf_w_en   = v_fc_valid_n;
    wire [10:0] q_buf_w_addr = q_buf_w_addr_r;
    wire [10:0] k_buf_w_addr = k_buf_w_addr_r;
    wire [10:0] v_buf_w_addr = v_buf_w_addr_r;
    wire [DATA_WIDTH-1:0]     q_buf_w_data = q_fc_out;
    wire [DATA_WIDTH-1:0]     k_buf_w_data = k_fc_out;
    wire [DATA_WIDTH-1:0]     v_buf_w_data = v_fc_out;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            q_buf_w_addr_r <= 0;
            k_buf_w_addr_r <= 0;
            v_buf_w_addr_r <= 0;
        end else begin
            if (q_fc_valid_n) q_buf_w_addr_r <= q_buf_w_addr_r + 1;
            if (k_fc_valid_n) k_buf_w_addr_r <= k_buf_w_addr_r + 1;
            if (v_fc_valid_n) v_buf_w_addr_r <= v_buf_w_addr_r + 1;
        end
    end

    // ───────── Q/K/V buffer SRAMs ─────────
    // Read side: streamed out as DIMM input during S_DIMM_FIRE.
    reg [10:0] q_buf_r_addr, k_buf_r_addr, v_buf_r_addr;
    wire [DATA_WIDTH-1:0]    q_buf_r_data, k_buf_r_data, v_buf_r_data;
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        q_buf (.clk(clk), .rst(rst), .w_en(q_buf_w_en),
               .r_addr(q_buf_r_addr), .w_addr(q_buf_w_addr),
               .sram_data_in(q_buf_w_data), .sram_data_out(q_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        k_buf (.clk(clk), .rst(rst), .w_en(k_buf_w_en),
               .r_addr(k_buf_r_addr), .w_addr(k_buf_w_addr),
               .sram_data_in(k_buf_w_data), .sram_data_out(k_buf_r_data));
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUF_DEPTH))
        v_buf (.clk(clk), .rst(rst), .w_en(v_buf_w_en),
               .r_addr(v_buf_r_addr), .w_addr(v_buf_w_addr),
               .sram_data_in(v_buf_w_data), .sram_data_out(v_buf_r_data));

    // ───────── DIMM inputs (NL parity: K/V loaded ONCE in S_LOAD_KV) ─────────
    // AH B-5 finish: The AL DIMM-top's SCORE/WSUM_BACK_TO_BACK_MODE branches
    // (in azurelily_dimm_top_d64_c128.v lines 144-180) reset Q-side SRAM
    // addresses on next_q_row_trigger but PERSIST k_w_addr/v_w_addr — so the
    // K/V SRAM contents remain intact across all 128 Q rows and the head only
    // pays the K/V load cost once. valid_q/k/v are now driven by per-phase
    // one-hot drive_valid_* flags from the FSM (matching NL's pattern).
    wire dimm_valid_q = drive_valid_q;
    wire dimm_valid_k = drive_valid_k;
    wire dimm_valid_v = drive_valid_v;

    // ───────── DIMM (W=16 lanes, mac_qk + clb_softmax + mac_sv) ─────────
    // AH B-5 finish: DIMM is reset once globally with rst; Q-row recycling is
    // driven by next_q_row_trigger pulses (no soft-rst loop). K/V SRAM
    // contents persist throughout the cascade.
    wire [DATA_WIDTH-1:0] dimm_out;
    wire dimm_valid_n_w;
    wire dimm_score_valid_o;        // unused — Step 1 observation port
    wire dimm_score_all_done_o;     // unused at head level (lockstep AL FSM)
    wire dimm_softmax_done_o;       // 1-cycle pulse when ALL W lanes enter S_NORM
    wire dimm_wsum_done_o;          // 1-cycle pulse on first lane mac_sv valid_n
    // q_row_idx drives DIMM wide-addr SRAMs (clb_softmax sm_buf, weight_buffer).
    wire [7:0] dimm_q_row_idx = q_row_idx;

    azurelily_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH),
        // AH B-5 finish: every back-to-back / wide-addr mode is ON. Score/wsum
        // back-to-back triggers cause the AL FSM to recycle to S_LOAD with
        // q-side reset (k/v_w_addr persists), enabling one-shot K/V load.
        .SCORE_BACK_TO_BACK_MODE(1),
        .WSUM_BACK_TO_BACK_MODE(1),
        .SOFTMAX_BACK_TO_BACK_MODE(1),
        .SCORE_WIDE_ADDR_MODE(1),
        .SOFTMAX_WIDE_ADDR_MODE(1),
        .WSUM_WIDE_ADDR_MODE(1)
    ) dimm_inst (
        .clk(clk), .rst(rst),
        .valid_q(dimm_valid_q), .valid_k(dimm_valid_k), .valid_v(dimm_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_r_data), .data_in_k(k_buf_r_data), .data_in_v(v_buf_r_data),
        .data_out(dimm_out),
        .ready_q(), .ready_k(), .ready_v(),
        .valid_n(dimm_valid_n_w),
        .score_valid_o(dimm_score_valid_o),
        .score_all_done_o(dimm_score_all_done_o),
        .softmax_done_o(dimm_softmax_done_o),
        .wsum_done_o(dimm_wsum_done_o),
        .score_next_q_row_trigger_i(score_next_q_row_pulse),
        .wsum_next_q_row_trigger_i(wsum_next_q_row_pulse),
        .softmax_next_q_row_trigger_i(softmax_next_q_row_pulse),
        .q_row_idx_i(dimm_q_row_idx)
    );

    // ───────── Top-level strict-serial cascade FSM (NL parity) ─────────
    //
    // S_LOAD_KV : drive valid_q for DIMM_Q_WORDS=PACKED_D cycles (Q row 0),
    //              valid_k for DIMM_K_WORDS=BUF_DEPTH-1 cycles (full K),
    //              valid_v for DIMM_V_WORDS=BUF_DEPTH-1 cycles (full V).
    //              ONE-SHOT — these SRAMs persist (the AL DIMM-top's
    //              SCORE/WSUM_BACK_TO_BACK_MODE branches reset only
    //              q-side; k/v_w_addr persist across Q rows).
    // S_CASCADE : per Q row k = 0..N-1:
    //              • If q_row_idx > 0: drive valid_q for DIMM_Q_WORDS cycles
    //                (Q row k, read from q_buffer at offset k*PACKED_D).
    //              • Wait for dimm_wsum_done_o (= Q row k mac_sv produced
    //                first valid_n, meaning all 3 stages completed for k).
    //              • Fire all 3 *_next_q_row_trigger pulses in lockstep —
    //                AL DIMM FSM transitions S_WAIT_QK/S_OUTPUT → S_LOAD,
    //                resets q-side addrs, k/v_w_addr persists.
    //              • Increment q_row_idx; advance to compute next Q row.
    //              • After q_row_idx == N-1's wsum_done, transition to
    //                S_DRAIN_FINAL.
    // S_DRAIN_FINAL  : drain margin (PHASE_DRAIN_CYC) for last Q row's mac_sv
    //                  to commit out_sram before draining.
    // S_OUTPUT_DRAIN : assert valid_n for N_FC_OUT_WORDS cycles.
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state              <= S_IDLE;
            token_count        <= 0;
            feed_count         <= 0;
            fc_out_pulse_count <= 0;
            q_buf_r_addr       <= 0;
            k_buf_r_addr       <= 0;
            v_buf_r_addr       <= 0;
            q_row_idx          <= 0;
            dimm_q_count       <= 0;
            dimm_k_count       <= 0;
            dimm_v_count       <= 0;
            drive_valid_q      <= 1'b0;
            drive_valid_k      <= 1'b0;
            drive_valid_v      <= 1'b0;
            ws_done_count      <= 0;
            ws_consumed_count  <= 0;
            phase_drain_count  <= 0;
            output_drain_count <= 0;
        end else begin
            // Default: pulses low; states below override for one cycle.
            score_next_q_row_pulse   <= 1'b0;
            softmax_next_q_row_pulse <= 1'b0;
            wsum_next_q_row_pulse    <= 1'b0;

            // Track FC valid_n pulses.
            if (q_fc_valid_n) begin
                fc_out_pulse_count <= fc_out_pulse_count + 1;
            end

            // Track wsum_done_o pulses globally (independent of FSM state).
            // Allows S_CASCADE to consume events that fired during S_LOAD_KV
            // (e.g. Q row 0's wsum finishes mid-K/V load).
            if (dimm_wsum_done_o) ws_done_count <= ws_done_count + 1;

            case (state)
                S_IDLE: begin
                    if (valid_x) begin
                        state              <= S_STREAM_TOKENS;
                        token_count        <= 0;
                        feed_count         <= 0;
                        fc_out_pulse_count <= 0;
                    end
                end
                S_STREAM_TOKENS: begin
                    // Pace input bytes into the FCs at the FC's per-row FSM
                    // period (PACKED_K + 3 cycles).
                    if (token_count < N_SEQ) begin
                        if (feed_count == PACKED_K + 2) begin
                            feed_count  <= 0;
                            token_count <= token_count + 1;
                        end else begin
                            feed_count  <= feed_count + 1;
                        end
                    end
                    if (fc_out_pulse_count >= TOTAL_FC_PULSES) begin
                        // FC arms have drained; load Q row 0 + full K + full V.
                        state         <= S_LOAD_KV;
                        q_buf_r_addr  <= 0;       // Q row 0 starts at offset 0
                        k_buf_r_addr  <= 0;
                        v_buf_r_addr  <= 0;
                        dimm_q_count  <= 0;
                        dimm_k_count  <= 0;
                        dimm_v_count  <= 0;
                        drive_valid_q <= 1'b1;    // begin valid_q (Q row 0)
                        q_row_idx     <= 0;
                    end
                end
                S_LOAD_KV: begin
                    // Phase A: drive valid_q for DIMM_Q_WORDS cycles (Q row 0).
                    // Phase B: drive valid_k for DIMM_K_WORDS cycles (full K).
                    // Phase C: drive valid_v for DIMM_V_WORDS cycles (full V).
                    // After V completes, transition to S_CASCADE.
                    if (drive_valid_q) begin
                        dimm_q_count <= dimm_q_count + 1;
                        q_buf_r_addr <= q_buf_r_addr + 1;
                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin
                            drive_valid_q <= 1'b0;
                            drive_valid_k <= 1'b1;
                            k_buf_r_addr  <= 0;
                        end
                    end else if (drive_valid_k) begin
                        dimm_k_count <= dimm_k_count + 1;
                        k_buf_r_addr <= k_buf_r_addr + 1;
                        if (dimm_k_count + 1 == DIMM_K_WORDS) begin
                            drive_valid_k <= 1'b0;
                            drive_valid_v <= 1'b1;
                            v_buf_r_addr  <= 0;
                        end
                    end else if (drive_valid_v) begin
                        dimm_v_count <= dimm_v_count + 1;
                        v_buf_r_addr <= v_buf_r_addr + 1;
                        if (dimm_v_count + 1 == DIMM_V_WORDS) begin
                            drive_valid_v <= 1'b0;
                            // Q row 0 is being processed inside DIMM; advance to
                            // S_CASCADE FSM that handles all N Q rows.
                            state         <= S_CASCADE;
                            q_row_idx     <= 0;
                            phase_drain_count <= 0;
                        end
                    end
                end
                S_CASCADE: begin
                    // Drive valid_q for current Q row (k > 0). For k = 0,
                    // valid_q already fired in S_LOAD_KV.
                    if (drive_valid_q) begin
                        dimm_q_count <= dimm_q_count + 1;
                        q_buf_r_addr <= q_buf_r_addr + 1;
                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin
                            drive_valid_q <= 1'b0;
                        end
                    end
                    // Use cumulative ws_done_count (vs ws_consumed_count) so
                    // events that fired before S_CASCADE entry aren't lost.
                    // When a fresh wsum_done arrived (count > consumed) and we're
                    // not still driving valid_q for the current Q row, advance.
                    if (ws_done_count > ws_consumed_count && !drive_valid_q) begin
                        if (q_row_idx + 1 < N_SEQ) begin
                            // Advance to next Q row. Fire all 3 triggers in
                            // lockstep — AL DIMM FSM returns to S_LOAD with
                            // q-side reset; k/v_w_addr persist.
                            score_next_q_row_pulse   <= 1'b1;
                            softmax_next_q_row_pulse <= 1'b1;
                            wsum_next_q_row_pulse    <= 1'b1;
                            ws_consumed_count <= ws_consumed_count + 1;
                            q_row_idx     <= q_row_idx + 1;
                            // Drive valid_q for next Q row (k+1).
                            drive_valid_q <= 1'b1;
                            dimm_q_count  <= 0;
                            // Read addr starts at next Q row's word 0 in q_buffer.
                            q_buf_r_addr  <= (q_row_idx + 1) * PACKED_D;
                        end else begin
                            // Last Q row done — no more triggers; advance to drain.
                            ws_consumed_count <= ws_consumed_count + 1;
                            state             <= S_DRAIN_FINAL;
                            phase_drain_count <= 0;
                        end
                    end
                end
                S_DRAIN_FINAL: begin
                    phase_drain_count <= phase_drain_count + 1;
                    if (phase_drain_count + 1 == PHASE_DRAIN_CYC) begin
                        state              <= S_OUTPUT_DRAIN;
                        output_drain_count <= 0;
                    end
                end
                S_OUTPUT_DRAIN: begin
                    // Stream all N × PACKED_D packed outputs to top-level valid_n.
                    output_drain_count <= output_drain_count + 1;
                    if (output_drain_count + 1 == N_FC_OUT_WORDS)
                        state <= S_OUTPUT_DONE;
                end
                S_OUTPUT_DONE: begin
                    // Terminal — held forever (top-level has no rst path back).
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ───────── outputs ─────────
    // Accept new X words only while feeding the FCs.
    assign ready_x  = (state == S_IDLE) || (state == S_STREAM_TOKENS);
    assign data_out = dimm_out;
    // valid_n asserts during S_OUTPUT_DRAIN for exactly N_FC_OUT_WORDS cycles.
    assign valid_n  = (state == S_OUTPUT_DRAIN);

endmodule

// ════ pack5_buffer ════
//
// Accumulates 5 consecutive int8 bytes (low byte of data_in[39:0]) into
// a packed 40-bit word, emitting one packed write to the buffer SRAM every
// 5 valid_in cycles.  Bytes are placed in increasing-byte order:
//
//   word[ 7: 0] = byte 0 (first input)
//   word[15: 8] = byte 1
//   word[23:16] = byte 2
//   word[31:24] = byte 3
//   word[39:32] = byte 4 (last input)
//
// The packer is purely a write-side helper: it drives w_en, w_addr, sram_data_in.
// It does NOT own the SRAM (the parent instantiates the buffer SRAM).
//
// Reset semantics: rst clears the partial register, w_addr, and pack_count.

module pack5_buffer #(
    parameter DATA_WIDTH = 40,
    parameter ADDR_W     = 11,
    parameter EPW        = 5
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_in,
    input  wire [DATA_WIDTH-1:0]   data_in,
    output reg                     w_en,
    output reg  [ADDR_W-1:0]       w_addr,
    output reg  [DATA_WIDTH-1:0]   sram_data_in
);
    reg [2:0] pack_count;       // 0..EPW-1
    reg [DATA_WIDTH-1:0]     pack_reg;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            pack_count   <= 0;
            pack_reg     <= 0;
            w_en         <= 0;
            w_addr       <= 0;
            sram_data_in <= 0;
        end else begin
            w_en <= 0;  // default; raised exactly when we emit a packed word
            if (valid_in) begin
                // Insert low byte of data_in into byte-position pack_count.
                case (pack_count)
                    3'd0: pack_reg[ 7: 0] <= data_in[7:0];
                    3'd1: pack_reg[15: 8] <= data_in[7:0];
                    3'd2: pack_reg[23:16] <= data_in[7:0];
                    3'd3: pack_reg[31:24] <= data_in[7:0];
                    3'd4: pack_reg[39:32] <= data_in[7:0];
                    default: ;
                endcase

                if (pack_count == EPW - 1) begin
                    // Emit packed word: assemble combinationally so the
                    // commit happens the same cycle as the 5th byte arrives.
                    sram_data_in <= { data_in[7:0],
                                       pack_reg[31:24],
                                       pack_reg[23:16],
                                       pack_reg[15: 8],
                                       pack_reg[ 7: 0] };
                    w_en         <= 1;
                    pack_count   <= 0;
                    if (w_addr != {ADDR_W{1'b1}}) w_addr <= w_addr + 1;
                end else begin
                    pack_count <= pack_count + 1;
                end
            end
        end
    end
endmodule
