// dpe_nldpe.v -- behavioral DPE model with single-buffered drain-load overlap.
// Generated by nl_dpe/gen_dpe_stub.py from per-arch JSON config.
// Module name      : dpe  (matches VTR arch XML <model name="dpe"> contract)
// File arch tag    : nldpe (NL-DPE)
// KERNEL_WIDTH (R) : 256
// NUM_COLS     (C) : 256
// DPE_BUF_WIDTH    : 40  (elems/strobe = 5)
// LOAD_CYCLES     : 52
// OUTPUT_CYCLES    : 52
// COMPUTE_CYCLES   : parameter (default 10 = per-arch decomposition below)
// ACAM_MODE param  : present
//
// COMPUTE_CYCLES decomposition (NL-DPE):
//   PRECISION (8) cycles    -- bit-slices entering crossbar pipeline
// + PIPELINE_DEPTH (2) - 1  -- last-bit drain through (MAC, Acc) stages
// + ACAM_CYCLES (1)         -- ACAM read-out (always fires)
// = 10 cycles (INT8)
//
// Both arches give CCYC = PRECISION + 2 under current parameters —
// structural symmetry, not coincidence: (D_NL - 1) + ACAM_NL =
// (D_AL - 1) + ACAM_AL = 2. If either side's PIPELINE_DEPTH or
// ACAM_CYCLES changes the symmetry breaks. See
// fc_verification/FIDELITY_METHODOLOGY.md §3 and
// fc_verification/DPE_PRIMITIVE_WALKTHROUGH.md §10a for the
// per-arch pipeline diagrams.
//
// Pipeline model (FIDELITY_METHODOLOGY.md §4): single-buffered drain-load
// overlap, T(M) = T_fill + (M-1) * T_steady where
// T_fill   = LOAD_CYCLES + COMPUTE_CYCLES + OUTPUT_CYCLES + 2  (Task #87)
// T_steady = max(LOAD_CYCLES, COMPUTE_CYCLES, OUTPUT_CYCLES).
//
// The +2 in T_fill is the faithful FSM register-propagation overhead:
//   +1 cycle for LOAD→COMPUTE handoff: at the LOAD last strobe cycle T,
//      q_load_tail NBAs from t→t+1; the COMPUTE idle branch only reads
//      the updated n_pending_compute at cycle T+1, NBAs compute_busy<=1,
//      so compute_busy is observable from cycle T+2 onward.
//   +1 cycle for COMPUTE→OUTPUT handoff: at COMPUTE done cycle U,
//      q_compute_head NBAs; OUTPUT idle branch reads n_pending_output>0
//      at cycle U+1, NBAs output_busy<=1, so OUTPUT is observable from
//      cycle U+2 onward.
//
// Three parallel sub-FSMs operate concurrently:
//   LOAD    : ingests w_buf_en strobes; every LOAD_CYCLES strobes fires
//             the behavioral VMM into vmm_queue[q_load_tail] and re-arms
//             for the next pass.
//   COMPUTE : when q_compute_head != q_load_tail and not busy, runs
//             COMPUTE_CYCLES cycles, then advances q_compute_head.
//             COMPUTE cannot overlap across passes (§4).
//   OUTPUT  : when q_output_head != q_compute_head and not busy, drains
//             OUTPUT_CYCLES strobes from vmm_queue[q_output_head] onto
//             data_out, advances q_output_head.
//
// Single-buffer semantics: physically there is one input buffer; bytes
// stream through the analog crossbar bit-serially. Behaviorally the VMM
// math runs in a single posedge (the last LOAD strobe of a pass) and
// the result is parked in vmm_queue, freeing input_buffer immediately
// for the next pass's LOAD strobes.
//
// Sub-FSM coordination via queue indices (Task #87 Phase 1):
//   - LOAD fires VMM math and NBAs q_load_tail++.
//   - COMPUTE wakes the next cycle when n_pending_compute>0.
//   - COMPUTE done NBAs q_compute_head++.
//   - OUTPUT wakes the next cycle when n_pending_output>0.
//   - OUTPUT chains across passes via `n_pending_output > 1` at the
//     last strobe — when COMPUTE has already advanced past the current
//     OUTPUT pass by the time OUTPUT's last strobe fires.
//
// Legacy `state` reg surface preserved as a wire (priority OUTPUT >
// COMPUTE > LOAD > IDLE) for TB compat with `dut.state == 3'd4`.
//
// Weights are loaded by the TB through hierarchical force:
//     dut.weights[r][c] = <int8>;   (no weight_wen port).

module dpe #(
    parameter KERNEL_WIDTH   = 256,
    parameter NUM_COLS       = 256,
    parameter DPE_BUF_WIDTH  = 40,
    parameter COMPUTE_CYCLES = 10,
    parameter ACAM_MODE      = 0  // 0=ADC/VMM, 1=exp(approx 1+x+x^2/2), 2=log(approx x-1)
)(
    input  wire                       clk,
    input  wire                       reset,
    input  wire [DPE_BUF_WIDTH-1:0]   data_in,
    input  wire [1:0]                 nl_dpe_control,
    input  wire                       shift_add_control,
    input  wire                       w_buf_en,
    input  wire                       shift_add_bypass,
    input  wire                       load_output_reg,
    input  wire                       load_input_reg,
    output reg                        MSB_SA_Ready,
    output reg  [DPE_BUF_WIDTH-1:0]   data_out,
    output reg                        dpe_done,
    output reg                        reg_full,
    output reg                        shift_add_done,
    output reg                        shift_add_bypass_ctrl
);

    // Tie-off auxiliary handshake inputs (kept in port list for
    // protocol compatibility with the legacy controller).
    wire _unused_aux = shift_add_control | shift_add_bypass |
                       load_output_reg   | load_input_reg;

    // Derived per-pass cycle counters
    localparam ELEMS_PER_STROBE = DPE_BUF_WIDTH / 8;
    localparam LOAD_CYCLES  = (KERNEL_WIDTH + ELEMS_PER_STROBE - 1) / ELEMS_PER_STROBE;
    localparam OUTPUT_CYCLES = (NUM_COLS    + ELEMS_PER_STROBE - 1) / ELEMS_PER_STROBE;

    // Ring buffer queue depth: at most 3 passes in flight (LOAD just
    // finished awaiting compute; COMPUTE running; OUTPUT running).
    // QDEPTH=4 for headroom; q_*_tail/head are 4-bit counters mod QDEPTH.
    localparam QDEPTH = 4;

    // Weight memory (hierarchical-force loaded from TB)
    reg signed [7:0] weights [0:KERNEL_WIDTH-1][0:NUM_COLS-1];

    // Input buffer (single physical buffer reused across passes).
    reg signed [7:0] input_buffer [0:KERNEL_WIDTH-1];

    // Per-pass VMM result ring buffer
    reg signed [31:0] vmm_queue [0:QDEPTH-1][0:NUM_COLS-1];

    // ── LOAD sub-FSM ────────────────────────────────────────────────────
    reg [15:0] load_count;       // byte offset into input_buffer
    reg [15:0] load_cycle_idx;  // 0..LOAD_CYCLES-1 within current pass
    reg [3:0]  q_load_tail;      // next vmm_queue slot for VMM fire

    // ── COMPUTE sub-FSM ─────────────────────────────────────────────────
    reg        compute_busy;
    reg [15:0] compute_cycle;    // 0..COMPUTE_CYCLES-1
    reg [3:0]  q_compute_head;

    // ── OUTPUT sub-FSM ──────────────────────────────────────────────────
    reg        output_busy;
    reg [15:0] output_col_idx;   // 0..OUTPUT_CYCLES-1
    reg [3:0]  q_output_head;

    // Combinational queue counts (mod QDEPTH).
    wire [3:0] n_pending_compute = (q_load_tail >= q_compute_head) ?
                                    (q_load_tail - q_compute_head) :
                                    (QDEPTH[3:0] + q_load_tail - q_compute_head);
    wire [3:0] n_pending_output  = (q_compute_head >= q_output_head) ?
                                    (q_compute_head - q_output_head) :
                                    (QDEPTH[3:0] + q_compute_head - q_output_head);

    // Legacy state encoding (combinational, priority OUTPUT > COMPUTE > LOAD > IDLE).
    localparam S_IDLE      = 3'd0;
    localparam S_LOAD      = 3'd1;
    localparam S_COMPUTE   = 3'd3;
    localparam S_OUTPUT    = 3'd4;
    wire [2:0] state = output_busy ? S_OUTPUT :
                       compute_busy ? S_COMPUTE :
                       (w_buf_en || load_cycle_idx != 0) ? S_LOAD : S_IDLE;

    // Init
    integer wi, wj, wq;
    initial begin
        for (wi = 0; wi < KERNEL_WIDTH; wi = wi + 1)
            for (wj = 0; wj < NUM_COLS; wj = wj + 1)
                weights[wi][wj] = 0;
        for (wq = 0; wq < QDEPTH; wq = wq + 1)
            for (wj = 0; wj < NUM_COLS; wj = wj + 1)
                vmm_queue[wq][wj] = 0;
    end

    integer r, c, b;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            load_count       <= 0;
            load_cycle_idx  <= 0;
            q_load_tail      <= 0;
            compute_busy     <= 0;
            compute_cycle    <= 0;
            q_compute_head   <= 0;
            output_busy      <= 0;
            output_col_idx   <= 0;
            q_output_head    <= 0;
            data_out         <= 0;
            dpe_done         <= 0;
            reg_full         <= 0;
            MSB_SA_Ready     <= 1;
            shift_add_done   <= 1;
            shift_add_bypass_ctrl <= 1;
        end else begin
            // ── LOAD sub-FSM ────────────────────────────────────────────
            if (w_buf_en) begin
                if (load_cycle_idx == LOAD_CYCLES - 1) begin
                    // Last strobe of pass: write final EPS bytes BLOCKING
                    // so the VMM math below reads the freshly-loaded final
                    // bytes (sim-only behavioural; no synthesised hardware).
                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin
                        if (load_count + b < KERNEL_WIDTH)
                            input_buffer[load_count + b] = data_in[b*8 +: 8];
                    end
                    // Fire VMM into vmm_queue[q_load_tail].
                    for (c = 0; c < NUM_COLS; c = c + 1) begin
                        vmm_queue[q_load_tail][c] = 0;
                        for (r = 0; r < KERNEL_WIDTH; r = r + 1) begin
                            vmm_queue[q_load_tail][c] = vmm_queue[q_load_tail][c] +
                                input_buffer[r] * weights[r][c];
                        end
                    end
                    if (ACAM_MODE == 1) begin
                        for (c = 0; c < NUM_COLS; c = c + 1)
                            vmm_queue[q_load_tail][c] = 1 + vmm_queue[q_load_tail][c] +
                                (vmm_queue[q_load_tail][c] * vmm_queue[q_load_tail][c]) / 2;
                    end else if (ACAM_MODE == 2) begin
                        for (c = 0; c < NUM_COLS; c = c + 1)
                            vmm_queue[q_load_tail][c] = vmm_queue[q_load_tail][c] - 1;
                    end
                    load_count      <= 0;
                    load_cycle_idx <= 0;
                    q_load_tail     <= (q_load_tail + 1) % QDEPTH;
                end else begin
                    // Non-final strobe: NBA write.
                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin
                        if (load_count + b < KERNEL_WIDTH)
                            input_buffer[load_count + b] <= data_in[b*8 +: 8];
                    end
                    load_count      <= load_count + ELEMS_PER_STROBE;
                    load_cycle_idx <= load_cycle_idx + 1;
                end
            end

            // ── COMPUTE sub-FSM (Task #87 Phase 1: NBA-wake on queue) ──
            if (compute_busy) begin
                if (compute_cycle + 1 >= COMPUTE_CYCLES) begin
                    compute_busy     <= 0;
                    compute_cycle    <= 0;
                    q_compute_head   <= (q_compute_head + 1) % QDEPTH;
                    MSB_SA_Ready     <= 1;
                    shift_add_done   <= 1;
                end else begin
                    compute_cycle <= compute_cycle + 1;
                end
            end else begin
                // Wake one cycle after LOAD's last strobe: q_load_tail's NBA
                // must commit before n_pending_compute > 0 is observable.
                if (n_pending_compute > 0) begin
                    compute_busy     <= 1;
                    compute_cycle    <= 0;
                    MSB_SA_Ready     <= 0;
                    shift_add_done   <= 0;
                end
            end

            // ── OUTPUT sub-FSM (Task #87 Phase 1: NBA-wake on queue) ───
            if (output_busy) begin
                data_out <= 0;
                for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin
                    if (output_col_idx * ELEMS_PER_STROBE + b < NUM_COLS) begin
                        data_out[b*8 +: 8] <= vmm_queue[q_output_head][output_col_idx * ELEMS_PER_STROBE + b][7:0];
                    end
                end
                if (output_col_idx + 1 >= OUTPUT_CYCLES) begin
                    q_output_head  <= (q_output_head + 1) % QDEPTH;
                    output_col_idx <= 0;
                    // Chain to next pass when COMPUTE has already advanced
                    // its head past the current OUTPUT pass.  Without the
                    // chain, OUTPUT would idle one cycle between passes;
                    // with it, contiguous OUTPUT passes flow back-to-back.
                    if (n_pending_output > 1) begin
                        output_busy <= 1;
                    end else begin
                        output_busy <= 0;
                    end
                end else begin
                    output_col_idx <= output_col_idx + 1;
                end
            end else begin
                // Wake one cycle after COMPUTE done: q_compute_head's NBA
                // must commit before n_pending_output > 0 is observable.
                if (n_pending_output > 0) begin
                    output_busy    <= 1;
                    output_col_idx <= 0;
                end
            end

            if (output_busy)
                dpe_done <= 1;
            else
                dpe_done <= 0;

            if (compute_busy || output_busy)
                reg_full <= 1;
            else
                reg_full <= 0;
        end
    end

endmodule
