// dsp_mac.v -- behavioral DSP-MAC lane model
// Generated by nl_dpe/gen_dsp_mac.py from azure_lily.json.
//
// AL DIMM lane: one int_sop_4 hard block (DSP_WIDTH int8 MACs/cycle),
// matching FIDELITY_METHODOLOGY.md §3 + §5 + the simulator's gemm_dsp
// formula in azurelily/IMC/peripherals/fpga_fabric.py.
//
// Per pass:
//   LOAD    L = ceil(K_INPUT * PRECISION_BITS / DPE_BUF_WIDTH)
//   COMPUTE C = max(1, ceil(K_INPUT / DSP_WIDTH))
//   OUTPUT  O = max(1, ceil(PRECISION_BITS / DPE_BUF_WIDTH))
//
// Default-parameter values (K_INPUT=64):
//   L = 32
//   C = 16
//   O = 1
//   T_fill = L + C + O = 49
//
// FSM: S_IDLE -> S_LOAD -> S_WAIT_EXEC -> S_COMPUTE -> S_OUTPUT -> S_DRAIN.
// Behavioral single-clock MAC at S_WAIT_EXEC fire-time:
//   mac_result = sum_k input_buffer[k] * weight[k]
// Weights are loaded by the TB through hierarchical force:
//     dut.weight[k] = <int8>;     (no weight_wen port).
//
// Handshake mirrors dpe_stub_*.v so the unified test harness applies.

module dsp_mac #(
    parameter K_INPUT        = 64,  // input vector length per pass
    parameter DPE_BUF_WIDTH  = 16,
    parameter PRECISION_BITS = 8,
    parameter DSP_WIDTH      = 4
)(
    input  wire                       clk,
    input  wire                       reset,
    input  wire [DPE_BUF_WIDTH-1:0]   data_in,
    input  wire [1:0]                 nl_dpe_control,
    input  wire                       shift_add_control,
    input  wire                       w_buf_en,
    input  wire                       shift_add_bypass,
    input  wire                       load_output_reg,
    input  wire                       load_input_reg,
    output reg                        MSB_SA_Ready,
    output reg  [DPE_BUF_WIDTH-1:0]   data_out,
    output reg                        dpe_done,
    output reg                        reg_full,
    output reg                        shift_add_done,
    output reg                        shift_add_bypass_ctrl
);

    wire _unused_aux = shift_add_control | shift_add_bypass |
                       load_output_reg   | load_input_reg;

    // Derived per-pass cycle counters
    localparam ELEMS_PER_STROBE = DPE_BUF_WIDTH / 8;
    localparam LOAD_STROBES  = (K_INPUT * PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;
    // K MACs at DSP_WIDTH per cycle on the int_sop_4 hard block.
    localparam COMPUTE_CYCLES = (K_INPUT + DSP_WIDTH - 1) / DSP_WIDTH;
    // One int8 result drains in ceil(PRECISION_BITS / DPE_BUF_WIDTH) cycles (>= 1).
    localparam OUTPUT_CYCLES_RAW = (PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;
    localparam OUTPUT_CYCLES = (OUTPUT_CYCLES_RAW < 1) ? 1 : OUTPUT_CYCLES_RAW;

    // Single-column weight + accumulator (one output element per pass)
    reg signed [7:0]  weight       [0:K_INPUT-1];
    reg signed [7:0]  input_buffer [0:K_INPUT-1];
    reg signed [31:0] mac_result;

    reg [15:0] load_count;
    reg [15:0] strobe_count;
    reg [15:0] output_col_idx;
    reg [15:0] compute_cycle_cnt;

    integer wi;
    initial begin
        for (wi = 0; wi < K_INPUT; wi = wi + 1) begin
            weight[wi]       = 0;
            input_buffer[wi] = 0;
        end
        mac_result = 0;
    end

    // FSM state encoding (mirrors dpe_stub_*.v)
    localparam S_IDLE      = 3'd0;
    localparam S_LOAD      = 3'd1;
    localparam S_WAIT_EXEC = 3'd2;
    localparam S_COMPUTE   = 3'd3;
    localparam S_OUTPUT    = 3'd4;
    localparam S_DRAIN     = 3'd5;
    reg [2:0] state;

    integer k, b;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            state <= S_IDLE;
            load_count <= 0;
            strobe_count <= 0;
            data_out <= 0;
            dpe_done <= 0;
            reg_full <= 0;
            MSB_SA_Ready <= 1;
            shift_add_done <= 1;
            shift_add_bypass_ctrl <= 1;
            compute_cycle_cnt <= 0;
            output_col_idx <= 0;
            mac_result <= 0;
        end else begin
            dpe_done <= 0;
            case (state)
                S_IDLE: begin
                    reg_full <= 0;
                    MSB_SA_Ready <= 1;
                    shift_add_done <= 1;
                    load_count <= 0;
                    strobe_count <= 0;
                    compute_cycle_cnt <= 0;
                    output_col_idx <= 0;
                    if (w_buf_en) begin
                        for (b = 0; b < ELEMS_PER_STROBE; b = b + 1)
                            if (b < K_INPUT)
                                input_buffer[b] <= data_in[b*8 +: 8];
                        load_count <= (ELEMS_PER_STROBE < K_INPUT) ?
                                       ELEMS_PER_STROBE : K_INPUT;
                        strobe_count <= 1;
                        if (1 >= LOAD_STROBES) begin
                            reg_full <= 1;
                            MSB_SA_Ready <= 0;
                            shift_add_done <= 0;
                            state <= S_WAIT_EXEC;
                        end else begin
                            state <= S_LOAD;
                        end
                    end
                end
                S_LOAD: begin
                    if (w_buf_en) begin
                        if (strobe_count + 1 >= LOAD_STROBES) begin
                            // Last LOAD strobe — write input_buffer with
                            // BLOCKING assignment so the MAC below reads the
                            // freshly-loaded final bytes (sim-only behavioural).
                            // Then fire MAC combinationally so T_fill = L+C+O.
                            for (b = 0; b < ELEMS_PER_STROBE; b = b + 1)
                                if (load_count + b < K_INPUT)
                                    input_buffer[load_count + b] = data_in[b*8 +: 8];
                            load_count <= load_count + ELEMS_PER_STROBE;
                            strobe_count <= strobe_count + 1;
                            reg_full <= 1;
                            MSB_SA_Ready <= 0;
                            shift_add_done <= 0;
                            if (nl_dpe_control == 2'b11) begin
                                mac_result = 0;
                                for (k = 0; k < K_INPUT; k = k + 1) begin
                                    mac_result = mac_result +
                                        input_buffer[k] * weight[k];
                                end
                                compute_cycle_cnt <= 0;
                                output_col_idx <= 0;
                                state <= S_COMPUTE;
                            end else begin
                                state <= S_WAIT_EXEC;
                            end
                        end else begin
                            // Non-final LOAD strobe — NBA semantics.
                            for (b = 0; b < ELEMS_PER_STROBE; b = b + 1)
                                if (load_count + b < K_INPUT)
                                    input_buffer[load_count + b] <= data_in[b*8 +: 8];
                            load_count <= load_count + ELEMS_PER_STROBE;
                            strobe_count <= strobe_count + 1;
                        end
                    end
                end
                S_WAIT_EXEC: begin
                    if (nl_dpe_control == 2'b11) begin
                        // Single-clock behavioral MAC accumulation
                        mac_result = 0;
                        for (k = 0; k < K_INPUT; k = k + 1) begin
                            mac_result = mac_result +
                                input_buffer[k] * weight[k];
                        end
                        compute_cycle_cnt <= 0;
                        output_col_idx <= 0;
                        state <= S_COMPUTE;
                    end
                end
                S_COMPUTE: begin
                    compute_cycle_cnt <= compute_cycle_cnt + 1;
                    if (compute_cycle_cnt >= COMPUTE_CYCLES - 1) begin
                        MSB_SA_Ready <= 1;
                        shift_add_done <= 1;
                        output_col_idx <= 0;
                        state <= S_OUTPUT;
                    end
                end
                S_OUTPUT: begin
                    dpe_done <= 1;
                    data_out <= 0;
                    // Drain the 1-byte MAC result on cycle 0; subsequent
                    // OUTPUT cycles (rare: only when DPE_BUF_WIDTH < 8)
                    // pad zeros — the TB latches on cycle 0.
                    if (output_col_idx == 0)
                        data_out[7:0] <= mac_result[7:0];
                    if (output_col_idx < OUTPUT_CYCLES - 1) begin
                        output_col_idx <= output_col_idx + 1;
                    end else begin
                        state <= S_DRAIN;
                    end
                end
                S_DRAIN: begin
                    dpe_done <= 0;
                    reg_full <= 0;
                    load_count <= 0;
                    strobe_count <= 0;
                    output_col_idx <= 0;
                    MSB_SA_Ready <= 1;
                    shift_add_done <= 1;
                    state <= S_IDLE;
                end
                default: state <= S_IDLE;
            endcase
        end
    end

endmodule
