// dsp_mac.v -- behavioral DSP-MAC lane model with single-buffered drain-load overlap.
// Generated by nl_dpe/gen_dsp_mac.py from azure_lily.json.
//
// AL DIMM lane: one int_sop_4 hard block (DSP_WIDTH int8 MACs/cycle),
// matching FIDELITY_METHODOLOGY.md §3 + §5 + the simulator's gemm_dsp
// formula in azurelily/IMC/peripherals/fpga_fabric.py.
//
// Per pass:
//   LOAD    L = ceil(K_INPUT * PRECISION_BITS / DPE_BUF_WIDTH)
//   COMPUTE C = max(1, ceil(K_INPUT / DSP_WIDTH))
//   OUTPUT  O = max(1, ceil(PRECISION_BITS / DPE_BUF_WIDTH))
//
// Default-parameter values (K_INPUT=64):
//   L = 32, C = 16, O = 1
//   T_fill = L + C + O + 2 = 51  (Task #87)
//
// Pipeline model (FIDELITY_METHODOLOGY.md §4, Task #87 Phase 1):
//   T(M)     = T_fill + (M-1) * T_steady
//   T_fill   = L + C + O + 2     (+2 = LOAD→COMPUTE + COMPUTE→OUTPUT)
//   T_steady = max(L, C, O)
// Three parallel sub-FSMs (LOAD / COMPUTE / OUTPUT) operate concurrently
// with a queue of pending MAC results between LOAD->COMPUTE and
// COMPUTE->OUTPUT stages.  Wake-up signals are queue indices NBA-
// advanced by the producer; consumer reads them one cycle later.
// See dpe_*.v for full design narrative — dsp_mac mirrors that
// structure with a 1-element accumulator per pass instead of an
// N-column VMM result.
//
// Weights are loaded by the TB through hierarchical force:
//     dut.weight[k] = <int8>;     (no weight_wen port).

module dsp_mac #(
    parameter K_INPUT        = 64,  // input vector length per pass
    parameter DPE_BUF_WIDTH  = 16,
    parameter PRECISION_BITS = 8,
    parameter DSP_WIDTH      = 4
)(
    input  wire                       clk,
    input  wire                       reset,
    input  wire [DPE_BUF_WIDTH-1:0]   data_in,
    input  wire [1:0]                 nl_dpe_control,
    input  wire                       shift_add_control,
    input  wire                       w_buf_en,
    input  wire                       shift_add_bypass,
    input  wire                       load_output_reg,
    input  wire                       load_input_reg,
    output reg                        MSB_SA_Ready,
    output reg  [DPE_BUF_WIDTH-1:0]   data_out,
    output reg                        dpe_done,
    output reg                        reg_full,
    output reg                        shift_add_done,
    output reg                        shift_add_bypass_ctrl
);

    wire _unused_aux = shift_add_control | shift_add_bypass |
                       load_output_reg   | load_input_reg;

    // Derived per-pass cycle counters
    localparam ELEMS_PER_STROBE = DPE_BUF_WIDTH / 8;
    localparam LOAD_CYCLES  = (K_INPUT * PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;
    // K MACs at DSP_WIDTH per cycle on the int_sop_4 hard block.
    localparam COMPUTE_CYCLES = (K_INPUT + DSP_WIDTH - 1) / DSP_WIDTH;
    // One int8 result drains in ceil(PRECISION_BITS / DPE_BUF_WIDTH) cycles (>= 1).
    localparam OUTPUT_CYCLES_RAW = (PRECISION_BITS + DPE_BUF_WIDTH - 1) / DPE_BUF_WIDTH;
    localparam OUTPUT_CYCLES = (OUTPUT_CYCLES_RAW < 1) ? 1 : OUTPUT_CYCLES_RAW;

    // Ring buffer queue depth.
    localparam QDEPTH = 4;

    // Single-column weight + input buffer; per-pass MAC result queue.
    reg signed [7:0]  weight       [0:K_INPUT-1];
    reg signed [7:0]  input_buffer [0:K_INPUT-1];
    reg signed [31:0] mac_queue    [0:QDEPTH-1];
    // Legacy alias: `mac_result` reflects the most recently fired MAC
    // result so TBs (e.g., tb_dsp_mac.v) hierarchically reading
    // dut.mac_result observe the same value as before.
    reg signed [31:0] mac_result;

    // ── LOAD sub-FSM ────────────────────────────────────────────────────
    reg [15:0] load_count;
    reg [15:0] load_cycle_idx;
    reg [3:0]  q_load_tail;

    // ── COMPUTE sub-FSM ─────────────────────────────────────────────────
    reg        compute_busy;
    reg [15:0] compute_cycle;
    reg [3:0]  q_compute_head;

    // ── OUTPUT sub-FSM ──────────────────────────────────────────────────
    reg        output_busy;
    reg [15:0] output_col_idx;
    reg [3:0]  q_output_head;

    wire [3:0] n_pending_compute = (q_load_tail >= q_compute_head) ?
                                    (q_load_tail - q_compute_head) :
                                    (QDEPTH[3:0] + q_load_tail - q_compute_head);
    wire [3:0] n_pending_output  = (q_compute_head >= q_output_head) ?
                                    (q_compute_head - q_output_head) :
                                    (QDEPTH[3:0] + q_compute_head - q_output_head);

    // Legacy state encoding (combinational, priority OUTPUT > COMPUTE > LOAD > IDLE).
    localparam S_IDLE      = 3'd0;
    localparam S_LOAD      = 3'd1;
    localparam S_COMPUTE   = 3'd3;
    localparam S_OUTPUT    = 3'd4;
    wire [2:0] state = output_busy ? S_OUTPUT :
                       compute_busy ? S_COMPUTE :
                       (w_buf_en || load_cycle_idx != 0) ? S_LOAD : S_IDLE;

    integer wi, wq;
    initial begin
        for (wi = 0; wi < K_INPUT; wi = wi + 1) begin
            weight[wi]       = 0;
            input_buffer[wi] = 0;
        end
        for (wq = 0; wq < QDEPTH; wq = wq + 1) begin
            mac_queue[wq] = 0;
        end
        mac_result = 0;
    end

    integer k, b;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            load_count       <= 0;
            load_cycle_idx  <= 0;
            q_load_tail      <= 0;
            compute_busy     <= 0;
            compute_cycle    <= 0;
            q_compute_head   <= 0;
            output_busy      <= 0;
            output_col_idx   <= 0;
            q_output_head    <= 0;
            data_out         <= 0;
            dpe_done         <= 0;
            reg_full         <= 0;
            MSB_SA_Ready     <= 1;
            shift_add_done   <= 1;
            shift_add_bypass_ctrl <= 1;
            mac_result       <= 0;
        end else begin
            // ── LOAD sub-FSM ────────────────────────────────────────────
            if (w_buf_en) begin
                if (load_cycle_idx == LOAD_CYCLES - 1) begin
                    // Last strobe of pass: write final EPS bytes BLOCKING.
                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin
                        if (load_count + b < K_INPUT)
                            input_buffer[load_count + b] = data_in[b*8 +: 8];
                    end
                    // Fire MAC into mac_queue[q_load_tail].
                    mac_queue[q_load_tail] = 0;
                    for (k = 0; k < K_INPUT; k = k + 1) begin
                        mac_queue[q_load_tail] = mac_queue[q_load_tail] +
                            input_buffer[k] * weight[k];
                    end
                    mac_result      <= mac_queue[q_load_tail];  // legacy alias
                    load_count      <= 0;
                    load_cycle_idx <= 0;
                    q_load_tail     <= (q_load_tail + 1) % QDEPTH;
                end else begin
                    for (b = 0; b < ELEMS_PER_STROBE; b = b + 1) begin
                        if (load_count + b < K_INPUT)
                            input_buffer[load_count + b] <= data_in[b*8 +: 8];
                    end
                    load_count      <= load_count + ELEMS_PER_STROBE;
                    load_cycle_idx <= load_cycle_idx + 1;
                end
            end

            // ── COMPUTE sub-FSM (Task #87 Phase 1: NBA-wake on queue) ──
            if (compute_busy) begin
                if (compute_cycle + 1 >= COMPUTE_CYCLES) begin
                    compute_busy     <= 0;
                    compute_cycle    <= 0;
                    q_compute_head   <= (q_compute_head + 1) % QDEPTH;
                    MSB_SA_Ready     <= 1;
                    shift_add_done   <= 1;
                end else begin
                    compute_cycle <= compute_cycle + 1;
                end
            end else begin
                // Wake one cycle after LOAD's last strobe: q_load_tail's
                // NBA must commit before n_pending_compute>0 is observable.
                if (n_pending_compute > 0) begin
                    compute_busy     <= 1;
                    compute_cycle    <= 0;
                    MSB_SA_Ready     <= 0;
                    shift_add_done   <= 0;
                end
            end

            // ── OUTPUT sub-FSM (Task #87 Phase 1: NBA-wake on queue) ───
            if (output_busy) begin
                // Drive data_out: the MAC result is a single int8 byte;
                // OCYC is typically 1 (since BUF >= PRECISION_BITS = 8).
                // For OCYC > 1, subsequent strobes drive zeros (the TB
                // latches on cycle 0).
                data_out <= 0;
                if (output_col_idx == 0) begin
                    data_out[7:0] <= mac_queue[q_output_head][7:0];
                end
                if (output_col_idx + 1 >= OUTPUT_CYCLES) begin
                    q_output_head  <= (q_output_head + 1) % QDEPTH;
                    output_col_idx <= 0;
                    // Chain when COMPUTE has already advanced past the
                    // current OUTPUT pass.
                    if (n_pending_output > 1) begin
                        output_busy <= 1;
                    end else begin
                        output_busy <= 0;
                    end
                end else begin
                    output_col_idx <= output_col_idx + 1;
                end
            end else begin
                // Wake one cycle after COMPUTE done.
                if (n_pending_output > 0) begin
                    output_busy    <= 1;
                    output_col_idx <= 0;
                end
            end

            if (output_busy)
                dpe_done <= 1;
            else
                dpe_done <= 0;

            if (compute_busy || output_busy)
                reg_full <= 1;
            else
                reg_full <= 0;
        end
    end

endmodule
