// NL-DPE Attention Head Top — Q/K/V projections + buffers + DIMM
// AUTO-GENERATED by nl_dpe/gen_nldpe_attn_head_top.py — DO NOT EDIT BY HAND
//
// Composition (matches IMC sim's attention_model — no output projection):
//
//   [valid_x, data_in_x] ──► fc_top_qkv_streaming ×3 (Q/K/V; 2 DPEs each)
//                                │     │     │
//                                ▼     ▼     ▼
//                             q_buf k_buf v_buf  (sram)
//                                │     │     │
//                                └─────┴─────┘
//                                      ▼
//                             nldpe_dimm_top (W=16 lanes, B-5 strict serial)
//                                      ▼
//                                [data_out, valid_n]
//
// Locked parameters (see gen_nldpe_attn_head_top.py for derivation):
//   d_model=128, d_head=64, N_SEQ=128, C=128, W=16
//   PACKED_KQ=26 (input words/inference)
//   PACKED_NQ=13 (output words/inference)
//
// Resource expectation:
//   - 3 × fc_top_qkv_streaming (instances: fc_q_inst, fc_k_inst, fc_v_inst;
//                               2 DPEs each via ping-pong)
//   - 3 × sram                 (instances: q_buffer, k_buffer, v_buffer)
//   - 1 × nldpe_dimm_top       (instance:  dimm_inst)
//   - 0 × fc_top_o             (NO output projection)
//
// AH Step B-5 (this file): strict-serial 3-stage cascade per Q row.
// All 4 DIMM-top mode parameters (SCORE/SOFTMAX/WSUM_BACK_TO_BACK_MODE,
// *_WIDE_ADDR_MODE) are turned ON. K/V SRAMs are loaded ONCE; the score/softmax/
// wsum FSMs auto-recycle through Q rows on a unified next_q_row_trigger that
// fires when wsum_done_o pulses (= Q row k fully completed all 3 stages).
//
// Module dependencies (compile together with this file):
//   - fc_verification/rtl/nldpe_dimm_top_d64_c128.v
//   - fc_verification/rtl/nldpe/fc_top_qkv_streaming.v
//   - fc_verification/dpe_stub.v

`timescale 1ns / 1ps

module nldpe_attn_head_d64_c128 #(
    parameter DATA_WIDTH = 40,
    parameter D_MODEL    = 128,
    parameter D_HEAD     = 64,
    parameter N_SEQ      = 128,
    parameter C          = 128,
    parameter W          = 16
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);

    // ─── Local constants (must match generator) ────────────────────
    localparam PACKED_KQ        = 26; // ceil(d_model/EPW), in words
    localparam PACKED_NQ        = 13; // ceil(d_head/EPW),  in words
    localparam N_X_INPUT_WORDS  = 3328;   // N × PACKED_KQ
    localparam N_FC_OUT_WORDS   = 1664; // N × PACKED_NQ
    localparam BUFFER_DEPTH     = 1665;      // N × PACKED_NQ + 1
    localparam DIMM_Q_WORDS     = 14;
    localparam DIMM_K_WORDS     = 1664;
    localparam DIMM_V_WORDS     = 1664;

    // ─── FSM (Architecture B, AH Step B-5) ─────────────────────────
    // Strict serial cascade: each Q row goes through score → softmax → wsum
    // before the next Q row starts.  K/V SRAMs are loaded ONCE in S_LOAD_KV.
    // Per Q row, the head waits for wsum_done_o (= Q row k entered WS_OUTPUT)
    // and then fires all 3 *_next_q_row_trigger pulses simultaneously.
    localparam S_IDLE         = 4'd0;
    localparam S_FEED_X       = 4'd1;
    localparam S_DRAIN_FC     = 4'd2;
    localparam S_LOAD_KV      = 4'd3;  // one-shot Q0+K+V load
    localparam S_CASCADE      = 4'd4;  // serial per-Q-row cascade × N
    localparam S_DRAIN_FINAL  = 4'd5;  // settle after last Q row
    localparam S_OUTPUT_DRAIN = 4'd6;  // stream N×PACKED_NQ to valid_n
    localparam S_OUTPUT_DONE  = 4'd7;  // terminal
    reg [3:0] state;

    reg [11:0] in_count;       // X words consumed (0..N_X_INPUT_WORDS)
    reg [10:0] write_addr;    // q/k/v_buffer write address
    reg [10:0] read_addr;     // q/k/v_buffer read address
    reg [10:0] dimm_q_count; // valid_q pulses already issued
    reg [10:0] dimm_k_count; // valid_k pulses already issued
    reg [10:0] dimm_v_count; // valid_v pulses already issued
    reg drive_valid_q, drive_valid_k, drive_valid_v;
    reg [7:0] q_row_idx;            // 0..N-1, drives DIMM wide-addr SRAMs
    // wsum_done_o is a 1-cycle edge pulse; track total count globally so events
    // that fire during S_LOAD_KV (when Q row 0 finishes inside the DIMM before
    // S_CASCADE entry) aren't missed.  Same idea for sm_done_count.
    reg [7:0] ws_done_count;        // cumulative wsum_done_o pulses observed
    reg [7:0] ws_consumed_count;    // wsum_done events consumed by S_CASCADE advance
    reg [10:0] phase_drain_count;  // drain margin counter
    reg [10:0] output_drain_count; // S_OUTPUT_DRAIN ticks 0..N_FC_OUT_WORDS

    // Triggers driven combinationally from FSM state below.
    reg score_next_q_row_pulse, softmax_next_q_row_pulse, wsum_next_q_row_pulse;

    // Drain margin: accommodates the small NBA-edge lag between trigger pulse
    // and FSM commit cycle (typically 1-3 cycles).
    localparam PHASE_DRAIN_CYC = 16'd64;   // post-trigger settle window

    // ─── Q/K/V projection arms ─────────────────────────────────────
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    wire feed_x_now = (state == S_FEED_X) && valid_x;

    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_q_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(q_fc_out),
        .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_k_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(k_fc_out),
        .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_v_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(v_fc_out),
        .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ─── Q/K/V buffers (sram, depth = N × PACKED_NQ + 1) ────────────
    wire [DATA_WIDTH-1:0] q_buf_out, k_buf_out, v_buf_out;

    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    q_buffer (
        .clk(clk), .rst(rst),
        .w_en(q_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(q_fc_out),
        .sram_data_out(q_buf_out)
    );
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    k_buffer (
        .clk(clk), .rst(rst),
        .w_en(k_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(k_fc_out),
        .sram_data_out(k_buf_out)
    );
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    v_buffer (
        .clk(clk), .rst(rst),
        .w_en(v_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(v_fc_out),
        .sram_data_out(v_buf_out)
    );

    // Track the number of FC valid_n pulses observed.
    reg [10:0] fc_out_count;
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            write_addr   <= 0;
            fc_out_count <= 0;
        end else if (q_fc_valid_n) begin
            write_addr   <= write_addr   + 1;
            fc_out_count <= fc_out_count + 1;
        end
    end

    // ─── DIMM instance (Architecture B: all back-to-back modes ON) ─
    wire [DATA_WIDTH-1:0] dimm_data_out;
    wire dimm_valid_n;
    wire dimm_ready_q, dimm_ready_k, dimm_ready_v;
    wire dimm_score_valid_o;
    wire dimm_score_all_done_o;
    wire dimm_softmax_done_o;
    wire dimm_wsum_done_o;

    nldpe_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH),
        // AH Step B-5: activate every back-to-back / wide-addr mode.
        .SCORE_BACK_TO_BACK_MODE(1),
        .SOFTMAX_BACK_TO_BACK_MODE(1),
        .WSUM_BACK_TO_BACK_MODE(1),
        .SCORE_WIDE_ADDR_MODE(1),
        .SOFTMAX_WIDE_ADDR_MODE(1),
        .WSUM_WIDE_ADDR_MODE(1)
    ) dimm_inst (
        .clk(clk), .rst(rst),
        .valid_q(drive_valid_q), .valid_k(drive_valid_k), .valid_v(drive_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_out), .data_in_k(k_buf_out), .data_in_v(v_buf_out),
        .data_out(dimm_data_out),
        .ready_q(dimm_ready_q), .ready_k(dimm_ready_k), .ready_v(dimm_ready_v),
        .valid_n(dimm_valid_n),
        .score_valid_o(dimm_score_valid_o),
        .score_all_done_o(dimm_score_all_done_o),
        .softmax_done_o(dimm_softmax_done_o),
        .wsum_done_o(dimm_wsum_done_o),
        .score_next_q_row_trigger_i(score_next_q_row_pulse),
        .softmax_next_q_row_trigger_i(softmax_next_q_row_pulse),
        .wsum_next_q_row_trigger_i(wsum_next_q_row_pulse),
        .q_row_idx_i(q_row_idx)
    );

    // ─── Top-level strict-serial cascade FSM ───────────────────────
    // S_LOAD_KV : drive valid_q (14 cyc, Q row 0), valid_k (1664 cyc, full K),
    //              valid_v (1664 cyc, full V). One-shot — these SRAMs persist.
    // S_CASCADE : per Q row k = 0..N-1:
    //              • If q_row_idx > 0: drive valid_q for DIMM_Q_WORDS cycles
    //                (Q row k, read from q_buffer at offset k*PACKED_NQ).
    //              • Wait for dimm_wsum_done_o (= Q row k entered WS_OUTPUT,
    //                meaning all 3 stages have completed for Q row k).
    //              • Fire all 3 *_next_q_row_trigger pulses in lockstep.
    //              • Increment q_row_idx; advance to compute next Q row.
    //              • After q_row_idx == N-1's wsum_done, transition to
    //                S_DRAIN_FINAL.
    // S_DRAIN_FINAL : drain margin (PHASE_DRAIN_CYC) for last Q row's wsum
    //                 to settle in out_sram before draining.
    // S_OUTPUT_DRAIN : assert valid_n for N_FC_OUT_WORDS cycles.
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state                  <= S_IDLE;
            in_count               <= 0;
            read_addr              <= 0;
            dimm_q_count           <= 0;
            dimm_k_count           <= 0;
            dimm_v_count           <= 0;
            drive_valid_q          <= 1'b0;
            drive_valid_k          <= 1'b0;
            drive_valid_v          <= 1'b0;
            q_row_idx              <= 0;
            ws_done_count          <= 0;
            ws_consumed_count      <= 0;
            phase_drain_count      <= 0;
            output_drain_count     <= 0;
        end else begin
            // Default: pulses low; states below override for one cycle.
            score_next_q_row_pulse   <= 1'b0;
            softmax_next_q_row_pulse <= 1'b0;
            wsum_next_q_row_pulse    <= 1'b0;

            // Track wsum_done_o pulses globally (independent of FSM state).
            // wsum_done_o pulses for 1 cycle on entry to WS_OUTPUT for each Q row.
            // Counting allows S_CASCADE to consume events that fired during
            // S_LOAD_KV (e.g. Q row 0's wsum finishes mid-K/V load).
            if (dimm_wsum_done_o) ws_done_count <= ws_done_count + 1;

            case (state)
                S_IDLE: begin
                    if (valid_x) state <= S_FEED_X;
                end
                S_FEED_X: begin
                    if (valid_x) in_count <= in_count + 1;
                    if (in_count + 1 == N_X_INPUT_WORDS) begin
                        state <= S_DRAIN_FC;
                    end
                end
                S_DRAIN_FC: begin
                    // Wait until all PACKED_NQ × N FC outputs are buffered.
                    if (fc_out_count >= N_FC_OUT_WORDS) begin
                        state         <= S_LOAD_KV;
                        read_addr     <= 0;       // Q row 0 starts at 0
                        drive_valid_q <= 1'b1;    // begin valid_q (Q row 0)
                        dimm_q_count  <= 0;
                        dimm_k_count  <= 0;
                        dimm_v_count  <= 0;
                        q_row_idx     <= 0;
                    end
                end
                S_LOAD_KV: begin
                    // Phase A: drive valid_q for DIMM_Q_WORDS cycles (Q row 0).
                    // Phase B: drive valid_k for DIMM_K_WORDS cycles (full K).
                    // Phase C: drive valid_v for DIMM_V_WORDS cycles (full V).
                    // After V completes, transition to S_CASCADE; q_row_idx=0
                    // (Q row 0's score is already being computed inside DIMM).
                    if (drive_valid_q) begin
                        dimm_q_count <= dimm_q_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin
                            drive_valid_q <= 1'b0;
                            drive_valid_k <= 1'b1;
                            read_addr     <= 0;
                        end
                    end else if (drive_valid_k) begin
                        dimm_k_count <= dimm_k_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_k_count + 1 == DIMM_K_WORDS) begin
                            drive_valid_k <= 1'b0;
                            drive_valid_v <= 1'b1;
                            read_addr     <= 0;
                        end
                    end else if (drive_valid_v) begin
                        dimm_v_count <= dimm_v_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_v_count + 1 == DIMM_V_WORDS) begin
                            drive_valid_v <= 1'b0;
                            // Q row 0 is being processed inside DIMM; advance to
                            // S_CASCADE FSM that handles all N Q rows.
                            state         <= S_CASCADE;
                            q_row_idx     <= 0;
                            phase_drain_count <= 0;
                        end
                    end
                end
                S_CASCADE: begin
                    // Drive valid_q for current Q row (k > 0).  For k = 0,
                    // valid_q already fired in S_LOAD_KV.  For each subsequent
                    // Q row we drive DIMM_Q_WORDS cycles after the previous Q
                    // row's wsum_done_o pulse fired.
                    if (drive_valid_q) begin
                        dimm_q_count <= dimm_q_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin
                            drive_valid_q <= 1'b0;
                        end
                    end
                    // Use cumulative ws_done_count (vs ws_consumed_count) so
                    // events that fired before S_CASCADE entry aren't lost.
                    // When a fresh wsum_done arrived (count > consumed) and we're
                    // not still driving valid_q for the current Q row, advance.
                    if (ws_done_count > ws_consumed_count && !drive_valid_q) begin
                        if (q_row_idx + 1 < N_SEQ) begin
                            // Advance to next Q row.  Fire all 3 triggers in
                            // lockstep — score recycles to S_LOAD_Q, softmax
                            // recycles to SM_IDLE, wsum recycles to WS_LOAD_A.
                            // Each FSM then waits for upstream's S_OUTPUT/
                            // SM_OUTPUT/etc. to provide data — natural cascade.
                            score_next_q_row_pulse   <= 1'b1;
                            softmax_next_q_row_pulse <= 1'b1;
                            wsum_next_q_row_pulse    <= 1'b1;
                            ws_consumed_count <= ws_consumed_count + 1;
                            q_row_idx     <= q_row_idx + 1;
                            // Drive valid_q for next Q row (k+1).
                            drive_valid_q <= 1'b1;
                            dimm_q_count  <= 0;
                            // Read addr starts at next Q row's word 0 in q_buffer.
                            read_addr     <= (q_row_idx + 1) * PACKED_NQ;
                        end else begin
                            // Last Q row done — no more triggers; advance to drain.
                            ws_consumed_count <= ws_consumed_count + 1;
                            state             <= S_DRAIN_FINAL;
                            phase_drain_count <= 0;
                        end
                    end
                end
                S_DRAIN_FINAL: begin
                    phase_drain_count <= phase_drain_count + 1;
                    if (phase_drain_count + 1 == PHASE_DRAIN_CYC) begin
                        state              <= S_OUTPUT_DRAIN;
                        output_drain_count <= 0;
                    end
                end
                S_OUTPUT_DRAIN: begin
                    // Stream all N × PACKED_NQ packed outputs to top-level valid_n.
                    // The TB only checks pulse count (N_FC_OUT_WORDS=1664) so the
                    // exact data ordering isn't validated here.
                    output_drain_count <= output_drain_count + 1;
                    if (output_drain_count + 1 == N_FC_OUT_WORDS)
                        state <= S_OUTPUT_DONE;
                end
                S_OUTPUT_DONE: begin
                    // Terminal — held forever (top-level has no rst path back).
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ─── Top-level handshake / outputs ─────────────────────────────
    // Accept new X words only while feeding the FCs.
    assign ready_x  = (state == S_FEED_X) && q_fc_ready && k_fc_ready && v_fc_ready;
    assign data_out = dimm_data_out;
    // valid_n asserts during S_OUTPUT_DRAIN for exactly N_FC_OUT_WORDS cycles.
    assign valid_n  = (state == S_OUTPUT_DRAIN);

endmodule
