// NL-DPE Attention Head Top — Q/K/V projections + buffers + DIMM
// AUTO-GENERATED by nl_dpe/gen_nldpe_attn_head_top.py — DO NOT EDIT BY HAND
//
// Composition (matches IMC sim's attention_model — no output projection):
//
//   [valid_x, data_in_x] ──► fc_top_qkv_streaming ×3 (Q/K/V; 2 DPEs each)
//                                │     │     │
//                                ▼     ▼     ▼
//                             q_buf k_buf v_buf  (sram)
//                                │     │     │
//                                └─────┴─────┘
//                                      ▼
//                             nldpe_dimm_top (W=16 lanes, 1 fire)
//                                      ▼
//                                [data_out, valid_n]
//
// Locked parameters (see gen_nldpe_attn_head_top.py for derivation):
//   d_model=128, d_head=64, N_SEQ=128, C=128, W=16
//   PACKED_KQ=26 (input words/inference)
//   PACKED_NQ=13 (output words/inference)
//
// Resource expectation:
//   - 3 × fc_top_qkv_streaming (instances: fc_q_inst, fc_k_inst, fc_v_inst;
//                               2 DPEs each via ping-pong)
//   - 3 × sram                 (instances: q_buffer, k_buffer, v_buffer)
//   - 1 × nldpe_dimm_top       (instance:  dimm_inst)
//   - 0 × fc_top_o             (NO output projection)
//
// Module dependencies (compile together with this file):
//   - fc_verification/rtl/nldpe_dimm_top_d64_c128.v
//   - fc_verification/rtl/nldpe/fc_top_qkv_streaming.v
//   - fc_verification/dpe_stub.v

`timescale 1ns / 1ps

module nldpe_attn_head_d64_c128 #(
    parameter DATA_WIDTH = 40,
    parameter D_MODEL    = 128,
    parameter D_HEAD     = 64,
    parameter N_SEQ      = 128,
    parameter C          = 128,
    parameter W          = 16
)(
    input  wire                    clk,
    input  wire                    rst,
    input  wire                    valid_x,
    input  wire [DATA_WIDTH-1:0]   data_in_x,
    input  wire                    ready_n,
    output wire [DATA_WIDTH-1:0]   data_out,
    output wire                    ready_x,
    output wire                    valid_n
);

    // ─── Local constants (must match generator) ────────────────────
    localparam PACKED_KQ        = 26; // ceil(d_model/EPW), in words
    localparam PACKED_NQ        = 13; // ceil(d_head/EPW),  in words
    localparam N_X_INPUT_WORDS  = 3328;   // N × PACKED_KQ
    localparam N_FC_OUT_WORDS   = 1664; // N × PACKED_NQ
    localparam BUFFER_DEPTH     = 1665;      // N × PACKED_NQ + 1
    localparam DIMM_Q_WORDS     = 14;
    localparam DIMM_K_WORDS     = 1664;
    localparam DIMM_V_WORDS     = 1664;

    // ─── FSM ───────────────────────────────────────────────────────
    // Bug-1 fix (2026-04-25): outer Q-row loop. The DIMM internally
    // computes ONE Q row's full attention output (mac_qk + softmax +
    // mac_sv across all N keys) per fire. To run a full N×N attention
    // head we now loop S_FIRE_DIMM N times, soft-resetting the DIMM
    // between iterations and re-driving valid_q (with each Q row read
    // from the head's q_buffer) plus valid_k / valid_v (re-loaded from
    // the static k/v_buffer; SRAM contents persist through DIMM rst).
    localparam S_IDLE        = 4'd0;
    localparam S_FEED_X      = 4'd1;
    localparam S_DRAIN_FC    = 4'd2;
    localparam S_DIMM_RST    = 4'd3;  // hold DIMM in soft rst between Q rows
    localparam S_FIRE_DIMM   = 4'd4;  // drive valid_q/k/v for one Q row
    localparam S_DIMM_WAIT   = 4'd5;  // wait for DIMM to produce valid_n
    localparam S_OUTPUT      = 4'd6;
    reg [3:0] state;

    reg [11:0] in_count;       // X words consumed (0..N_X_INPUT_WORDS)
    reg [10:0] write_addr;    // q/k/v_buffer write address
    reg [10:0] read_addr;     // q/k/v_buffer read address
    reg [10:0] dimm_q_count; // valid_q pulses already issued
    reg [10:0] dimm_k_count; // valid_k pulses already issued
    reg [10:0] dimm_v_count; // valid_v pulses already issued
    reg drive_valid_q, drive_valid_k, drive_valid_v;
    // Bug-1 fix: outer-loop Q-row counter and DIMM soft-rst pulse
    reg [7:0] q_row_idx;            // 0..N-1 over Q rows
    reg [3:0] dimm_rst_count;       // S_DIMM_RST hold counter
    reg dimm_soft_rst;              // pulses high during S_DIMM_RST

    // ─── Q/K/V projection arms ─────────────────────────────────────
    wire [DATA_WIDTH-1:0] q_fc_out, k_fc_out, v_fc_out;
    wire q_fc_valid_n, k_fc_valid_n, v_fc_valid_n;
    wire q_fc_ready,   k_fc_ready,   v_fc_ready;

    wire feed_x_now = (state == S_FEED_X) && valid_x;

    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_q_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(q_fc_out),
        .ready(q_fc_ready), .valid_n(q_fc_valid_n)
    );
    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_k_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(k_fc_out),
        .ready(k_fc_ready), .valid_n(k_fc_valid_n)
    );
    fc_top_qkv_streaming #(.DATA_WIDTH(DATA_WIDTH)) fc_v_inst (
        .clk(clk), .rst(rst),
        .valid(feed_x_now), .ready_n(1'b0),
        .data_in(data_in_x),
        .data_out(v_fc_out),
        .ready(v_fc_ready), .valid_n(v_fc_valid_n)
    );

    // ─── Q/K/V buffers (sram, depth = N × PACKED_NQ + 1) ────────────
    // write_addr increments on each FC valid_n; read_addr increments
    // when DIMM is driven from the corresponding buffer.
    wire [DATA_WIDTH-1:0] q_buf_out, k_buf_out, v_buf_out;

    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    q_buffer (
        .clk(clk), .rst(rst),
        .w_en(q_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(q_fc_out),
        .sram_data_out(q_buf_out)
    );
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    k_buffer (
        .clk(clk), .rst(rst),
        .w_en(k_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(k_fc_out),
        .sram_data_out(k_buf_out)
    );
    sram #(.N_CHANNELS(1), .DATA_WIDTH(DATA_WIDTH), .DEPTH(BUFFER_DEPTH))
    v_buffer (
        .clk(clk), .rst(rst),
        .w_en(v_fc_valid_n),
        .r_addr(read_addr),
        .w_addr(write_addr),
        .sram_data_in(v_fc_out),
        .sram_data_out(v_buf_out)
    );

    // Track the number of FC valid_n pulses observed (Q is canonical;
    // K/V fire in lockstep because all 3 FCs share the same `valid`).
    reg [10:0] fc_out_count;
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            write_addr   <= 0;
            fc_out_count <= 0;
        end else if (q_fc_valid_n) begin
            write_addr   <= write_addr   + 1;
            fc_out_count <= fc_out_count + 1;
        end
    end

    // ─── DIMM instance (re-fired N times via soft rst, Bug-1 fix) ──
    // dimm_rst_internal pulses high between Q rows so the DIMM's
    // FSM resets to S_LOAD_Q while its k_sram/v_sram contents persist
    // (regular SRAMs don't clear on rst). Each iteration reloads K/V
    // from the head's static k/v_buffer with the same data — idempotent.
    wire [DATA_WIDTH-1:0] dimm_data_out;
    wire dimm_valid_n;
    wire dimm_ready_q, dimm_ready_k, dimm_ready_v;
    // AH Step 1: per-cycle DIMM score-stage valid (unused at head level
    // for now; Step 4 will consume it to wire score → softmax streaming).
    wire dimm_score_valid_o;  /* unused — Step 1 observation port */
    wire dimm_rst_internal = rst | dimm_soft_rst;

    nldpe_dimm_top #(
        .N(N_SEQ), .D(D_HEAD), .W(W), .DATA_WIDTH(DATA_WIDTH)
    ) dimm_inst (
        .clk(clk), .rst(dimm_rst_internal),
        .valid_q(drive_valid_q), .valid_k(drive_valid_k), .valid_v(drive_valid_v),
        .ready_n(ready_n),
        .data_in_q(q_buf_out), .data_in_k(k_buf_out), .data_in_v(v_buf_out),
        .data_out(dimm_data_out),
        .ready_q(dimm_ready_q), .ready_k(dimm_ready_k), .ready_v(dimm_ready_v),
        .valid_n(dimm_valid_n),
        .score_valid_o(dimm_score_valid_o)
    );

    // ─── Top-level FSM (Bug-1 fix: outer Q-row loop) ───────────────
    // For each q_row_idx in [0..N-1]:
    //   1. S_DIMM_RST  : pulse dimm_soft_rst for a few cycles so the
    //                    DIMM's FSM returns to S_IDLE (k/v_sram persists)
    //   2. S_FIRE_DIMM : drive valid_q for DIMM_Q_WORDS, then valid_k for
    //                    DIMM_K_WORDS, then valid_v for DIMM_V_WORDS.
    //                    Q read address starts at q_row_idx * PACKED_NQ.
    //   3. S_DIMM_WAIT : wait for dimm_valid_n to rise (DIMM completed
    //                    mac_qk + softmax + mac_sv for this Q row); this
    //                    ensures every DPE in the pipeline fires before
    //                    we re-rst the DIMM for the next Q row.
    //   4. If q_row_idx + 1 < N: increment q_row_idx, go back to S_DIMM_RST.
    //      Else: transition to S_OUTPUT (final Q row's outputs drain to top).
    localparam DIMM_RST_CYCLES = 4'd4;   // hold DIMM in soft rst for 4 cyc
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state          <= S_IDLE;
            in_count       <= 0;
            read_addr      <= 0;
            dimm_q_count   <= 0;
            dimm_k_count   <= 0;
            dimm_v_count   <= 0;
            drive_valid_q  <= 1'b0;
            drive_valid_k  <= 1'b0;
            drive_valid_v  <= 1'b0;
            q_row_idx      <= 0;
            dimm_rst_count <= 0;
            dimm_soft_rst  <= 1'b0;
        end else begin
            case (state)
                S_IDLE: begin
                    if (valid_x) state <= S_FEED_X;
                end
                S_FEED_X: begin
                    if (valid_x) in_count <= in_count + 1;
                    if (in_count + 1 == N_X_INPUT_WORDS) begin
                        state <= S_DRAIN_FC;
                    end
                end
                S_DRAIN_FC: begin
                    // Wait until all PACKED_NQ × N FC outputs are buffered.
                    if (fc_out_count >= N_FC_OUT_WORDS) begin
                        // Enter Q-row loop. q_row_idx already 0.
                        state         <= S_DIMM_RST;
                        dimm_rst_count <= 0;
                        dimm_soft_rst  <= 1'b0;  // first iteration: no rst needed,
                                                   // DIMM is already at S_IDLE post-rst
                    end
                end
                S_DIMM_RST: begin
                    // Pulse dimm_soft_rst high for DIMM_RST_CYCLES cycles
                    // (skip on q_row_idx==0 since DIMM was just rst by global)
                    if (q_row_idx == 0) begin
                        // First iteration: DIMM is fresh from global rst, skip soft rst
                        state         <= S_FIRE_DIMM;
                        read_addr     <= q_row_idx * PACKED_NQ;
                        drive_valid_q <= 1'b1;
                        dimm_q_count  <= 0;
                        dimm_k_count  <= 0;
                        dimm_v_count  <= 0;
                        dimm_soft_rst <= 1'b0;
                    end else begin
                        dimm_soft_rst <= 1'b1;
                        dimm_rst_count <= dimm_rst_count + 1;
                        if (dimm_rst_count + 1 == DIMM_RST_CYCLES) begin
                            dimm_soft_rst  <= 1'b0;
                            state          <= S_FIRE_DIMM;
                            read_addr      <= q_row_idx * PACKED_NQ;
                            drive_valid_q  <= 1'b1;
                            dimm_q_count   <= 0;
                            dimm_k_count   <= 0;
                            dimm_v_count   <= 0;
                        end
                    end
                end
                S_FIRE_DIMM: begin
                    // Phase A: drive valid_q for DIMM_Q_WORDS cycles (Q row).
                    // Phase B: drive valid_k for DIMM_K_WORDS cycles (full K).
                    // Phase C: drive valid_v for DIMM_V_WORDS cycles (full V).
                    // read_addr advances in lockstep with the active phase.
                    if (drive_valid_q) begin
                        dimm_q_count <= dimm_q_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_q_count + 1 == DIMM_Q_WORDS) begin
                            drive_valid_q <= 1'b0;
                            drive_valid_k <= 1'b1;
                            read_addr     <= 0;
                        end
                    end else if (drive_valid_k) begin
                        dimm_k_count <= dimm_k_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_k_count + 1 == DIMM_K_WORDS) begin
                            drive_valid_k <= 1'b0;
                            drive_valid_v <= 1'b1;
                            read_addr     <= 0;
                        end
                    end else if (drive_valid_v) begin
                        dimm_v_count <= dimm_v_count + 1;
                        read_addr    <= read_addr + 1;
                        if (dimm_v_count + 1 == DIMM_V_WORDS) begin
                            drive_valid_v <= 1'b0;
                            state         <= S_DIMM_WAIT;
                        end
                    end
                end
                S_DIMM_WAIT: begin
                    // Wait for DIMM to fully complete this Q row.
                    // dimm_valid_n is high once any wsum lane reaches WS_OUTPUT,
                    // by which time all DPE pipeline stages have fired.
                    if (dimm_valid_n) begin
                        if (q_row_idx + 1 == N_SEQ) begin
                            // Last Q row complete — drain output to top.
                            state <= S_OUTPUT;
                        end else begin
                            // Move to next Q row: soft-reset DIMM, repeat.
                            q_row_idx     <= q_row_idx + 1;
                            state         <= S_DIMM_RST;
                            dimm_rst_count <= 0;
                            dimm_soft_rst  <= 1'b1;
                        end
                    end
                end
                S_OUTPUT: begin
                    // Pass-through: DIMM internally proceeds through
                    // mac_qk → softmax → mac_sv and emits valid_n; the
                    // top-level outputs are wired directly below.
                end
                default: state <= S_IDLE;
            endcase
        end
    end

    // ─── Top-level handshake / outputs ─────────────────────────────
    // Accept new X words only while feeding the FCs.
    assign ready_x  = (state == S_FEED_X) && q_fc_ready && k_fc_ready && v_fc_ready;
    assign data_out = dimm_data_out;
    assign valid_n  = (state == S_OUTPUT) && dimm_valid_n;

endmodule
