// NL-DPE Full DIMM Top — W=16, N=128, d=64, C=128
// Generated by gen_dimm_nldpe_top.py

// NL-DPE Full DIMM Top (W=16 parallel lanes)
// Per-head DPEs: 4 stages × 16 lanes = 64
// K_qkt=2 (dual-identity for C=128/d=64)
// K_sv=1

module nldpe_dimm_top #(
    parameter N = 128,
    parameter D = 64,
    parameter W = 16,
    parameter DATA_WIDTH = 40
)(
    input wire clk, rst,
    input wire valid_q, valid_k, valid_v, ready_n,
    input wire [DATA_WIDTH-1:0] data_in_q, data_in_k, data_in_v,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire ready_q, ready_k, ready_v, valid_n,
    // AH cycle alignment Step 1 (additive): per-cycle score-stage
    // valid pulse, OR-reduced across W lanes. Asserts every cycle a
    // lane's dimm_score_matrix produces a new score word into the
    // softmax SRAM. Step 4 will consume this to wire score → softmax
    // streaming directly. Today (Step 1) it is observable but unused.
    output wire score_valid_o
);

    // Per-lane valid/ready/data arrays
    wire [W-1:0] lane_valid_n;
    wire [W-1:0] lane_ready_q, lane_ready_k, lane_ready_v;
    wire [W-1:0] lane_score_valid;  // AH Step 1: per-lane score-stage valid
    wire [DATA_WIDTH-1:0] lane_data_out [0:W-1];

    // W parallel DIMM pipelines (each = score_matrix + softmax + weighted_sum)
    genvar lane;
    generate for (lane = 0; lane < W; lane = lane + 1) begin : dimm_lane
        wire [DATA_WIDTH-1:0] score_out, softmax_out;
        wire score_valid, softmax_valid;
        wire score_ready, softmax_ready;

        // Stage 1: dimm_score_matrix (mac_qk + softmax_exp fused)
        // LANE_IDX + W parameters make this lane handle keys {2*lane, 2*lane+1,
        // 2*lane+2W, 2*lane+2W+1, ...}, giving N/W=8 scores per lane at N=128, W=16.
        dimm_score_matrix #(.N(N), .d(D), .DATA_WIDTH(DATA_WIDTH),
                            .LANE_IDX(lane), .W(W)) score_inst (
            .clk(clk), .rst(rst),
            .valid_q(valid_q), .valid_k(valid_k),
            .ready_n(softmax_ready),
            .data_in_q(data_in_q), .data_in_k(data_in_k),
            .data_out(score_out),
            .ready_q(lane_ready_q[lane]), .ready_k(lane_ready_k[lane]),
            .valid_n(score_valid)
        );
        // AH Step 1: surface per-lane score_valid to top-level array
        assign lane_score_valid[lane] = score_valid;

        // Stage 2: softmax_approx (normalize) — per-lane over N/W=8 elements.
        // NOTE: sum is LOCAL (8 elements), not global. A cross-lane reduction
        // would be needed for mathematically correct softmax output. For Phase
        // J cycle alignment we accept local-only softmax; wsum outputs X here.
        softmax_approx #(.N(N), .d(D), .DATA_WIDTH(DATA_WIDTH),
                         .LANE_IDX(lane), .W(W)) softmax_inst (
            .clk(clk), .rst(rst),
            .valid(score_valid), .ready_n(1'b0),
            .data_in(score_out),
            .data_out(softmax_out),
            .ready(score_ready), .valid_n(softmax_valid)
        );
        assign softmax_ready = score_ready;

        // Stage 3: dimm_weighted_sum (wsum_log + mac_sv)
        // LANE_IDX + W make this lane handle output cols
        //   [LANE_IDX * d/W, (LANE_IDX+1) * d/W), giving d/W=4 cols per lane at d=64, W=16.
        dimm_weighted_sum #(.N(N), .d(D), .DATA_WIDTH(DATA_WIDTH),
                            .LANE_IDX(lane), .W(W)) wsum_inst (
            .clk(clk), .rst(rst),
            .valid_attn(softmax_valid), .valid_v(valid_v),
            .ready_n(1'b0),
            .data_in_attn(softmax_out), .data_in_v(data_in_v),
            .data_out(lane_data_out[lane]),
            .ready_attn(), .ready_v(lane_ready_v[lane]),
            .valid_n(lane_valid_n[lane])
        );
    end endgenerate

    // Output mux: round-robin across W lanes
    reg [$clog2(W)-1:0] out_lane_sel;
    wire any_valid = |lane_valid_n;
    always @(posedge clk or posedge rst) begin
        if (rst) out_lane_sel <= 0;
        else if (any_valid && !ready_n) out_lane_sel <= out_lane_sel + 1;
    end
    assign data_out = lane_data_out[out_lane_sel];
    assign valid_n = any_valid;

    assign ready_q = &lane_ready_q;
    assign ready_k = &lane_ready_k;
    assign ready_v = &lane_ready_v;

    // AH Step 1: top-level score-stage valid = OR-reduction of W lanes.
    // Cycle-by-cycle pulse, one bit per score word emitted by any lane's
    // dimm_score_matrix S_OUTPUT. Cycles unchanged vs pre-Step-1 (purely
    // additive observation port).
    assign score_valid_o = |lane_score_valid;

endmodule

// ════ Sub-modules ════

module dimm_score_matrix #(
    parameter N = 128,
    parameter d = 64,
    parameter DATA_WIDTH = 40,
    parameter ADDR_WIDTH = 11,
    parameter DEPTH = 1665,
    parameter LANE_IDX = 0,       // which key-lane this instance handles (0..W-1)
    parameter W = 1               // total number of parallel key-lanes at top
)(
    input wire clk, input wire rst,
    input wire valid_q, input wire valid_k,
    input wire ready_n,
    input wire [DATA_WIDTH-1:0] data_in_q,
    input wire [DATA_WIDTH-1:0] data_in_k,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire ready_q, output wire ready_k,
    output wire valid_n
);

    reg [ADDR_WIDTH-1:0] q_write_addr, q_read_addr;
    wire q_w_en = (state == S_LOAD_Q) && valid_q;
    wire [DATA_WIDTH-1:0] q_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(14))
    q_sram (.clk(clk),.rst(rst),.w_en(q_w_en),.r_addr(q_read_addr),
            .w_addr(q_write_addr),.sram_data_in(data_in_q),.sram_data_out(q_sram_out));

    reg [11-1:0] k_write_addr, k_read_addr_a;
    wire k_w_en = (state == S_LOAD_K) && valid_k;
    wire [DATA_WIDTH-1:0] k_sram_out_a;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(1665))
    k_sram_a (.clk(clk),.rst(rst),.w_en(k_w_en),.r_addr(k_read_addr_a[11-1:0]),
              .w_addr(k_write_addr[11-1:0]),.sram_data_in(data_in_k),.sram_data_out(k_sram_out_a));
    reg [11-1:0] k_read_addr_b;
    wire [DATA_WIDTH-1:0] k_sram_out_b;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(1665))
    k_sram_b (.clk(clk),.rst(rst),.w_en(k_w_en),.r_addr(k_read_addr_b[11-1:0]),
              .w_addr(k_write_addr[11-1:0]),.sram_data_in(data_in_k),.sram_data_out(k_sram_out_b));

    // CLB adder A: log_Q + log_K[j₁] (byte-wise, 5 lanes)
    wire [DATA_WIDTH-1:0] log_sum_a;
    genvar ga;
    generate for (ga = 0; ga < 5; ga = ga + 1) begin : add_a
        assign log_sum_a[ga*8 +: 8] = q_sram_out[ga*8 +: 8] + k_sram_out_a[ga*8 +: 8];
    end endgenerate
    // CLB adder B: log_Q + log_K[j₂] (byte-wise, 5 lanes)
    wire [DATA_WIDTH-1:0] log_sum_b;
    genvar gb;
    generate for (gb = 0; gb < 5; gb = gb + 1) begin : add_b
        assign log_sum_b[gb*8 +: 8] = q_sram_out[gb*8 +: 8] + k_sram_out_b[gb*8 +: 8];
    end endgenerate

    // DPE(I|exp) stage: dual-identity crossbar + ACAM=exp (KW=128)
    wire dimm_exp_valid, dimm_exp_ready_n, dimm_exp_ready, dimm_exp_valid_n;
    wire [DATA_WIDTH-1:0] dimm_exp_data_in, dimm_exp_data_out;
    // Inner DPE: KW_elems=128, KW_packed=26 (epw=5)
    // DPE direct instantiation (no conv_controller/SRAM wrapper)
    wire dimm_exp_dpe_done, dimm_exp_reg_full;
    wire dimm_exp_MSB_SA_Ready, dimm_exp_shift_add_done, dimm_exp_shift_add_bypass_ctrl;
    reg [1:0] dimm_exp_nl_dpe_control;
    reg dimm_exp_dpe_exec;
    // w_buf_en = valid (outer FSM feeds directly)
    wire dimm_exp_w_buf_en = dimm_exp_valid;
    // nl_dpe_control fires 1 cycle after reg_full
    always @(posedge clk) begin
        if (rst) begin dimm_exp_dpe_exec <= 0; dimm_exp_nl_dpe_control <= 0; end
        else begin
            dimm_exp_dpe_exec <= dimm_exp_reg_full;
            dimm_exp_nl_dpe_control <= dimm_exp_dpe_exec ? 2'b11 : 2'b00;
        end
    end
    // dpe instantiation — no #() params (arch XML model is parameterless)
    // Intended: KERNEL_WIDTH=128, NUM_COLS=128,
    //           ACAM_MODE=1, COMPUTE_CYCLES=3
    dpe dimm_exp (
        .clk(clk), .reset(rst),
        .data_in(dimm_exp_data_in),
        .nl_dpe_control(dimm_exp_nl_dpe_control),
        .shift_add_control(dimm_exp_MSB_SA_Ready),
        .w_buf_en(dimm_exp_w_buf_en),
        .shift_add_bypass(1'b0),
        .load_output_reg(dimm_exp_shift_add_done),
        .load_input_reg(1'b0),
        .MSB_SA_Ready(dimm_exp_MSB_SA_Ready),
        .data_out(dimm_exp_data_out),
        .dpe_done(dimm_exp_dpe_done),
        .reg_full(dimm_exp_reg_full),
        .shift_add_done(dimm_exp_shift_add_done),
        .shift_add_bypass_ctrl(dimm_exp_shift_add_bypass_ctrl)
        // Note: dpe_stub has weight_wen/weight_data/weight_row_addr/weight_col_addr
        // for TB preload; the arch-XML dpe hard block does NOT have those pins.
        // We leave them unconnected so VTR synthesis works; TB preloads weights
        // directly via hierarchical memory access (dut.X.dpe.weights[i][j]=...).
    );
    assign dimm_exp_valid_n = dimm_exp_dpe_done;

    // Dual-identity: feed vector A then vector B
    reg feed_phase;  // 0=vector A, 1=vector B
    assign dimm_exp_data_in = feed_phase ? log_sum_b : log_sum_a;
    assign dimm_exp_valid = (state == S_COMPUTE) && (mac_count >= 2) && (mac_count <= 14);  // 2-cycle SRAM latency
    assign dimm_exp_ready_n = 1'b1;

    reg acc_clear;
    reg [15:0] col_counter;
    // Dual accumulators: A for cols 0..63, B for cols 64..127
    reg [31:0] accumulator_a, accumulator_b;
    wire [31:0] masked_sum_a, masked_sum_b;
    assign masked_sum_a = ((col_counter + 0 >= 0 && col_counter + 0 < 64) ? {24'b0, dimm_exp_data_out[0*8 +: 8]} : 32'd0) + ((col_counter + 1 >= 0 && col_counter + 1 < 64) ? {24'b0, dimm_exp_data_out[1*8 +: 8]} : 32'd0) + ((col_counter + 2 >= 0 && col_counter + 2 < 64) ? {24'b0, dimm_exp_data_out[2*8 +: 8]} : 32'd0) + ((col_counter + 3 >= 0 && col_counter + 3 < 64) ? {24'b0, dimm_exp_data_out[3*8 +: 8]} : 32'd0) + ((col_counter + 4 >= 0 && col_counter + 4 < 64) ? {24'b0, dimm_exp_data_out[4*8 +: 8]} : 32'd0);
    assign masked_sum_b = ((col_counter + 0 >= 64 && col_counter + 0 < 128) ? {24'b0, dimm_exp_data_out[0*8 +: 8]} : 32'd0) + ((col_counter + 1 >= 64 && col_counter + 1 < 128) ? {24'b0, dimm_exp_data_out[1*8 +: 8]} : 32'd0) + ((col_counter + 2 >= 64 && col_counter + 2 < 128) ? {24'b0, dimm_exp_data_out[2*8 +: 8]} : 32'd0) + ((col_counter + 3 >= 64 && col_counter + 3 < 128) ? {24'b0, dimm_exp_data_out[3*8 +: 8]} : 32'd0) + ((col_counter + 4 >= 64 && col_counter + 4 < 128) ? {24'b0, dimm_exp_data_out[4*8 +: 8]} : 32'd0);
    always @(posedge clk) begin
        if (rst || acc_clear) begin accumulator_a <= 0; accumulator_b <= 0; col_counter <= 0; end
        else if (dimm_exp_valid_n) begin
            accumulator_a <= accumulator_a + masked_sum_a;
            accumulator_b <= accumulator_b + masked_sum_b;
            col_counter <= col_counter + 5;
        end
    end
    reg dpe_output_done;
    reg [15:0] dpe_out_count;
    always @(posedge clk) begin
        if (rst || acc_clear) begin dpe_out_count <= 0; dpe_output_done <= 0; end
        else if (dimm_exp_valid_n) begin
            dpe_out_count <= dpe_out_count + 1;
            if (dpe_out_count + 1 >= 26) dpe_output_done <= 1;
        end
    end

    reg [ADDR_WIDTH-1:0] score_write_addr, score_read_addr;
    reg score_w_en;
    reg [DATA_WIDTH-1:0] score_write_data;
    wire [DATA_WIDTH-1:0] score_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(129))
    score_sram (.clk(clk),.rst(rst),.w_en(score_w_en),.r_addr(score_read_addr),
                .w_addr(score_write_addr),.sram_data_in(score_write_data),.sram_data_out(score_sram_out));

    localparam S_IDLE = 4'd0, S_LOAD_Q = 4'd1, S_LOAD_K = 4'd2,
               S_COMPUTE = 4'd3, S_WAIT_DPE = 4'd4, S_WRITE_SCORE = 4'd5,
               S_OUTPUT = 4'd6;
    localparam S_WRITE_B = 4'd7;
    reg [3:0] state;
    reg [4-1:0] mac_count;  // packed word counter (0..12)
    reg [7-1:0] score_idx;  // score column index (element, 0..N-1)
    reg feed_half;  // 0=feeding vector A (d elements), 1=feeding vector B

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state <= S_IDLE;
            q_write_addr <= 0; q_read_addr <= 0;
            k_write_addr <= 0; k_read_addr_a <= 0;
            k_read_addr_b <= 0;
            feed_half <= 0; feed_phase <= 0;
            score_write_addr <= 0; score_read_addr <= 0; score_w_en <= 0;
            score_write_data <= 0;
            mac_count <= 0; score_idx <= LANE_IDX * 2; acc_clear <= 0;
        end else begin
            score_w_en <= 0; acc_clear <= 0;
            case (state)
                S_IDLE: if (valid_q || valid_k) state <= S_LOAD_Q;
                S_LOAD_Q: begin
                    if (valid_q) q_write_addr <= q_write_addr + 1;
                    if (q_write_addr == 13) state <= S_LOAD_K;  // written 13 words
                end
                S_LOAD_K: begin
                    if (valid_k) k_write_addr <= k_write_addr + 1;
                    if (k_write_addr == 1664) state <= S_COMPUTE;  // written 1664 words
                end
                S_COMPUTE: begin
                    // Feed phase: 13+2 cycles per half (2-cycle SRAM latency)
                    if (mac_count < 13) begin
                        q_read_addr <= mac_count;
                        if (!feed_half)
                            k_read_addr_a <= score_idx * 13 + mac_count;
                        else
                            k_read_addr_b <= (score_idx + 1) * 13 + mac_count;
                    end
                    mac_count <= mac_count + 1;
                    if (!feed_half) begin
                        feed_phase <= 0;
                        if (mac_count == 14) begin
                            mac_count <= 0;
                            feed_half <= 1;
                        end
                    end else begin
                        feed_phase <= 1;
                        if (mac_count == 14) begin
                            mac_count <= 0;
                            feed_half <= 0;
                            state <= S_WAIT_DPE;
                        end
                    end
                end
                S_WAIT_DPE: begin
                    // Wait for DPE to finish and return to idle
                    if (dpe_output_done && dimm_exp_MSB_SA_Ready) begin
                        // Write score A
                        score_write_data <= accumulator_a[7:0];
                        score_w_en <= 1;
                        score_write_addr <= score_idx;
                        state <= S_WRITE_B;
                    end
                end
                S_WRITE_B: begin
                    score_write_data <= accumulator_b[7:0];
                    score_w_en <= 1;
                    score_write_addr <= score_idx + 1;
                    acc_clear <= 1;
                    if (score_idx + W * 2 >= N) state <= S_OUTPUT;
                    else begin score_idx <= score_idx + W * 2; state <= S_COMPUTE; end
                end
                S_OUTPUT: if (ready_n) score_read_addr <= score_read_addr + 1;
            endcase
        end
    end

    assign data_out = score_sram_out;
    assign valid_n = (state == S_OUTPUT);
    assign ready_q = (state == S_LOAD_Q || state == S_IDLE);
    assign ready_k = (state == S_LOAD_K || state == S_IDLE);
endmodule

module softmax_approx #(
    parameter N = 128,
    parameter d = 64,
    parameter DATA_WIDTH = 40,
    parameter ADDR_WIDTH = 8,
    parameter DEPTH = 129,
    parameter LANE_IDX = 0,          // lane index (0..W-1)
    parameter W = 1,                 // total parallel lanes at top
    parameter N_PER_LANE = N / W     // attn elements this lane handles (= N/W)
)(
    input wire clk, input wire rst,
    input wire valid, input wire ready_n,
    input wire [DATA_WIDTH-1:0] data_in,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire ready, output wire valid_n
);

    reg [ADDR_WIDTH-1:0] in_write_addr, in_read_addr;
    reg in_w_en;
    wire [DATA_WIDTH-1:0] in_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(129))
    in_sram (.clk(clk),.rst(rst),.w_en(in_w_en),.r_addr(in_read_addr),
             .w_addr(in_write_addr),.sram_data_in(data_in),.sram_data_out(in_sram_out));

    wire sm_exp_valid, sm_exp_ready_n, sm_exp_ready, sm_exp_valid_n;
    wire [DATA_WIDTH-1:0] sm_exp_data_in, sm_exp_data_out;
    // DPE direct instantiation (no conv_controller/SRAM wrapper)
    wire sm_exp_dpe_done, sm_exp_reg_full;
    wire sm_exp_MSB_SA_Ready, sm_exp_shift_add_done, sm_exp_shift_add_bypass_ctrl;
    reg [1:0] sm_exp_nl_dpe_control;
    reg sm_exp_dpe_exec;
    // w_buf_en = valid (outer FSM feeds directly)
    wire sm_exp_w_buf_en = sm_exp_valid;
    // nl_dpe_control fires 1 cycle after reg_full
    always @(posedge clk) begin
        if (rst) begin sm_exp_dpe_exec <= 0; sm_exp_nl_dpe_control <= 0; end
        else begin
            sm_exp_dpe_exec <= sm_exp_reg_full;
            sm_exp_nl_dpe_control <= sm_exp_dpe_exec ? 2'b11 : 2'b00;
        end
    end
    // dpe instantiation — KW=1, NUM_COLS=1 override needed for
    // iverilog reg_full semantics (stub default KW=128 needs 26 strobes).
    // Other params (ACAM_MODE=1, COMPUTE_CYCLES=3) are
    // overridden via TB-level defparam where needed.
    dpe #(.KERNEL_WIDTH(1), .NUM_COLS(1)) sm_exp (
        .clk(clk), .reset(rst),
        .data_in(sm_exp_data_in),
        .nl_dpe_control(sm_exp_nl_dpe_control),
        .shift_add_control(sm_exp_MSB_SA_Ready),
        .w_buf_en(sm_exp_w_buf_en),
        .shift_add_bypass(1'b0),
        .load_output_reg(sm_exp_shift_add_done),
        .load_input_reg(1'b0),
        .MSB_SA_Ready(sm_exp_MSB_SA_Ready),
        .data_out(sm_exp_data_out),
        .dpe_done(sm_exp_dpe_done),
        .reg_full(sm_exp_reg_full),
        .shift_add_done(sm_exp_shift_add_done),
        .shift_add_bypass_ctrl(sm_exp_shift_add_bypass_ctrl)
        // Note: dpe_stub has weight_wen/weight_data/weight_row_addr/weight_col_addr
        // for TB preload; the arch-XML dpe hard block does NOT have those pins.
        // We leave them unconnected so VTR synthesis works; TB preloads weights
        // directly via hierarchical memory access (dut.X.dpe.weights[i][j]=...).
    );
    assign sm_exp_valid_n = sm_exp_dpe_done;

    assign sm_exp_data_in = in_sram_out;
    assign sm_exp_valid = (sm_state == SM_EXP);
    assign sm_exp_ready_n = 1'b0;

    reg [ADDR_WIDTH-1:0] exp_write_addr, exp_read_addr;
    reg exp_w_en;
    reg [DATA_WIDTH-1:0] exp_write_data;
    wire [DATA_WIDTH-1:0] exp_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(129))
    exp_sram (.clk(clk),.rst(rst),.w_en(exp_w_en),.r_addr(exp_read_addr),
              .w_addr(exp_write_addr),.sram_data_in(exp_write_data),.sram_data_out(exp_sram_out));
    reg [2*DATA_WIDTH-1:0] exp_sum;

    always @(posedge clk) begin
        if (rst) begin exp_w_en <= 0; exp_write_addr <= 0; exp_sum <= 0; end
        else if (sm_exp_valid_n) begin
            exp_write_data <= sm_exp_data_out;
            exp_w_en <= 1; exp_write_addr <= exp_write_addr + 1;
            exp_sum <= exp_sum + sm_exp_data_out;
        end else exp_w_en <= 0;
    end

    wire [DATA_WIDTH-1:0] exp_sum_upper = exp_sum[2*DATA_WIDTH-1:DATA_WIDTH];
    reg [DATA_WIDTH-1:0] recip_val;
    always @(*) begin
        casez (exp_sum_upper[15:0])
            16'b1???????????????: recip_val = 40'd2;
            16'b01??????????????: recip_val = 40'd32768;
            16'b001?????????????: recip_val = 40'd16384;
            16'b0001????????????: recip_val = 40'd8192;
            16'b00001???????????: recip_val = 40'd4096;
            16'b000001??????????: recip_val = 40'd2048;
            16'b0000001?????????: recip_val = 40'd1024;
            16'b00000001????????: recip_val = 40'd512;
            16'b000000001???????: recip_val = 40'd256;
            16'b0000000001??????: recip_val = 40'd128;
            16'b00000000001?????: recip_val = 40'd64;
            16'b000000000001????: recip_val = 40'd32;
            16'b0000000000001???: recip_val = 40'd16;
            16'b00000000000001??: recip_val = 40'd8;
            16'b000000000000001?: recip_val = 40'd4;
            16'b0000000000000001: recip_val = 40'd2;
            default: recip_val = 40'hFFFF;
        endcase
    end

    reg [DATA_WIDTH-1:0] inv_sum;
    reg [2*DATA_WIDTH-1:0] norm_product;
    reg [DATA_WIDTH-1:0] norm_val;

    reg [ADDR_WIDTH-1:0] out_write_addr, out_read_addr;
    reg out_w_en;
    wire [DATA_WIDTH-1:0] out_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(129))
    out_sram (.clk(clk),.rst(rst),.w_en(out_w_en),.r_addr(out_read_addr),
              .w_addr(out_write_addr),.sram_data_in(norm_val),.sram_data_out(out_sram_out));

    localparam SM_IDLE = 3'd0, SM_LOAD = 3'd1, SM_EXP = 3'd2,
               SM_NORMALIZE = 3'd3, SM_OUTPUT = 3'd4;
    reg [2:0] sm_state;
    reg [$clog2(N+2)-1:0] sm_count;  // needs to hold N+1 for SM_NORMALIZE exit check

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            sm_state <= SM_IDLE; sm_count <= 0;
            in_write_addr <= 0; in_read_addr <= 0; in_w_en <= 0;
            out_write_addr <= 0; out_read_addr <= 0; out_w_en <= 0;
            inv_sum <= 0; norm_product <= 0; norm_val <= 0;
        end else begin
            in_w_en <= 0; out_w_en <= 0;
            case (sm_state)
                SM_IDLE: if (valid) sm_state <= SM_LOAD;
                SM_LOAD: begin
                    if (valid) begin in_w_en <= 1; in_write_addr <= in_write_addr + 1; end
                    if (in_write_addr == N_PER_LANE - 1) sm_state <= SM_EXP;  // per-lane count
                end
                SM_EXP: begin
                    // DPE(I|exp) processes scores — output goes to exp_sram + sum
                    in_read_addr <= sm_count; sm_count <= sm_count + 1;
                    if (sm_count == N_PER_LANE - 1) begin
                        inv_sum <= recip_val; sm_count <= 0;
                        sm_state <= SM_NORMALIZE;
                    end
                end
                SM_NORMALIZE: begin
                    // CLB multiply: exp_val × inv_sum
                    exp_read_addr <= sm_count;
                    norm_product <= exp_sram_out * inv_sum;
                    norm_val <= norm_product[2*DATA_WIDTH-1:DATA_WIDTH];
                    out_w_en <= (sm_count > 1);
                    out_write_addr <= sm_count - 2;
                    sm_count <= sm_count + 1;
                    if (sm_count == N_PER_LANE + 1) sm_state <= SM_OUTPUT;
                end
                SM_OUTPUT: if (!ready_n) out_read_addr <= out_read_addr + 1;
            endcase
        end
    end

    assign data_out = out_sram_out;
    assign valid_n = (sm_state == SM_OUTPUT);
    assign ready = (sm_state == SM_LOAD || sm_state == SM_IDLE);
endmodule

module dimm_weighted_sum #(
    parameter N = 128,
    parameter d = 64,
    parameter DATA_WIDTH = 40,
    parameter ADDR_WIDTH = 11,
    parameter DEPTH = 1665,
    parameter LANE_IDX = 0,       // column-lane this instance owns (0..W-1)
    parameter W = 1,              // total parallel column-lanes at top
    parameter M_PER_LANE = d / W  // output cols per lane (= d/W)
)(
    input wire clk, input wire rst,
    input wire valid_attn, input wire valid_v,
    input wire ready_n,
    input wire [DATA_WIDTH-1:0] data_in_attn,
    input wire [DATA_WIDTH-1:0] data_in_v,
    output wire [DATA_WIDTH-1:0] data_out,
    output wire ready_attn, output wire ready_v,
    output wire valid_n
);

    localparam PACKED_N = 26;  // ceil(N/5) packed words for KW=128 feed

    reg [ADDR_WIDTH-1:0] attn_write_addr, attn_read_addr;
    reg attn_w_en;
    wire [DATA_WIDTH-1:0] attn_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(129))
    attn_sram (.clk(clk),.rst(rst),.w_en(attn_w_en),.r_addr(attn_read_addr),
               .w_addr(attn_write_addr),.sram_data_in(data_in_attn),.sram_data_out(attn_sram_out));

    reg [11-1:0] v_write_addr, v_read_addr;
    reg v_w_en;
    wire [DATA_WIDTH-1:0] v_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(1665))
    v_sram (.clk(clk),.rst(rst),.w_en(v_w_en),.r_addr(v_read_addr[11-1:0]),
            .w_addr(v_write_addr[11-1:0]),.sram_data_in(data_in_v),.sram_data_out(v_sram_out));

    wire ws_log_valid, ws_log_ready_n, ws_log_ready, ws_log_valid_n;
    wire [DATA_WIDTH-1:0] ws_log_data_in, ws_log_data_out;
    // ws_log: scalar 1×1 ACAM=log (unchanged from Phase 3).
    // DPE direct instantiation (no conv_controller/SRAM wrapper)
    wire ws_log_dpe_done, ws_log_reg_full;
    wire ws_log_MSB_SA_Ready, ws_log_shift_add_done, ws_log_shift_add_bypass_ctrl;
    reg [1:0] ws_log_nl_dpe_control;
    reg ws_log_dpe_exec;
    // w_buf_en = valid (outer FSM feeds directly)
    wire ws_log_w_buf_en = ws_log_valid;
    // nl_dpe_control fires 1 cycle after reg_full
    always @(posedge clk) begin
        if (rst) begin ws_log_dpe_exec <= 0; ws_log_nl_dpe_control <= 0; end
        else begin
            ws_log_dpe_exec <= ws_log_reg_full;
            ws_log_nl_dpe_control <= ws_log_dpe_exec ? 2'b11 : 2'b00;
        end
    end
    // dpe instantiation — KW=1, NUM_COLS=1 override needed for
    // iverilog reg_full semantics (stub default KW=128 needs 26 strobes).
    // Other params (ACAM_MODE=2, COMPUTE_CYCLES=3) are
    // overridden via TB-level defparam where needed.
    dpe #(.KERNEL_WIDTH(1), .NUM_COLS(1)) ws_log (
        .clk(clk), .reset(rst),
        .data_in(ws_log_data_in),
        .nl_dpe_control(ws_log_nl_dpe_control),
        .shift_add_control(ws_log_MSB_SA_Ready),
        .w_buf_en(ws_log_w_buf_en),
        .shift_add_bypass(1'b0),
        .load_output_reg(ws_log_shift_add_done),
        .load_input_reg(1'b0),
        .MSB_SA_Ready(ws_log_MSB_SA_Ready),
        .data_out(ws_log_data_out),
        .dpe_done(ws_log_dpe_done),
        .reg_full(ws_log_reg_full),
        .shift_add_done(ws_log_shift_add_done),
        .shift_add_bypass_ctrl(ws_log_shift_add_bypass_ctrl)
        // Note: dpe_stub has weight_wen/weight_data/weight_row_addr/weight_col_addr
        // for TB preload; the arch-XML dpe hard block does NOT have those pins.
        // We leave them unconnected so VTR synthesis works; TB preloads weights
        // directly via hierarchical memory access (dut.X.dpe.weights[i][j]=...).
    );
    assign ws_log_valid_n = ws_log_dpe_done;

    assign ws_log_data_in = attn_sram_out;
    assign ws_log_valid = (ws_state == WS_LOG_FEED) || 
                          ((ws_state == WS_LOAD_A) && (attn_write_addr != 0));
    assign ws_log_ready_n = 1'b0;

    reg [ADDR_WIDTH-1:0] log_attn_write_addr, log_attn_read_addr;
    reg log_attn_w_en;
    reg [DATA_WIDTH-1:0] log_attn_write_data;
    reg [5-1:0] log_byte_count;  // packing counter 0..4
    wire [DATA_WIDTH-1:0] log_attn_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(27))
    log_attn_sram (.clk(clk),.rst(rst),.w_en(log_attn_w_en),.r_addr(log_attn_read_addr),
                   .w_addr(log_attn_write_addr),.sram_data_in(log_attn_write_data),.sram_data_out(log_attn_sram_out));

    always @(posedge clk) begin
        if (rst) begin
            log_attn_w_en <= 0; log_attn_write_addr <= 0;
            log_attn_write_data <= 0; log_byte_count <= 0;
        end else begin
            log_attn_w_en <= 0;
            if (log_attn_w_en) log_attn_write_addr <= log_attn_write_addr + 1;
            if (ws_log_valid_n) begin
                log_attn_write_data[log_byte_count*8 +: 8] <= ws_log_data_out[7:0];
                if (log_byte_count == 4) begin
                    log_attn_w_en <= 1;
                    log_byte_count <= 0;
                end else begin
                    log_byte_count <= log_byte_count + 1;
                end
            end
        end
    end

    // CLB byte-wise adder (5 lanes): packed log_attn + packed V[*][m]
    wire [DATA_WIDTH-1:0] ws_log_sum;
    genvar gw;
    generate for (gw = 0; gw < 5; gw = gw + 1) begin : ws_add
        assign ws_log_sum[gw*8 +: 8] = log_attn_sram_out[gw*8 +: 8] + v_sram_out[gw*8 +: 8];
    end endgenerate

    wire ws_exp_valid, ws_exp_ready_n, ws_exp_ready, ws_exp_valid_n;
    wire [DATA_WIDTH-1:0] ws_exp_data_in, ws_exp_data_out;
    // Phase-4: widened to KW=128, NUM_COLS=128, ACAM=exp. One fire
    // per output column m (4 per lane); each fire ingests 128 packed
    // log-sum bytes and emits 128 exp() outputs to be summed.
    // DPE direct instantiation (no conv_controller/SRAM wrapper)
    wire ws_exp_dpe_done, ws_exp_reg_full;
    wire ws_exp_MSB_SA_Ready, ws_exp_shift_add_done, ws_exp_shift_add_bypass_ctrl;
    reg [1:0] ws_exp_nl_dpe_control;
    reg ws_exp_dpe_exec;
    // w_buf_en = valid (outer FSM feeds directly)
    wire ws_exp_w_buf_en = ws_exp_valid;
    // nl_dpe_control fires 1 cycle after reg_full
    always @(posedge clk) begin
        if (rst) begin ws_exp_dpe_exec <= 0; ws_exp_nl_dpe_control <= 0; end
        else begin
            ws_exp_dpe_exec <= ws_exp_reg_full;
            ws_exp_nl_dpe_control <= ws_exp_dpe_exec ? 2'b11 : 2'b00;
        end
    end
    // dpe instantiation — no #() params (arch XML model is parameterless)
    // Intended: KERNEL_WIDTH=128, NUM_COLS=128,
    //           ACAM_MODE=1, COMPUTE_CYCLES=3
    dpe ws_exp (
        .clk(clk), .reset(rst),
        .data_in(ws_exp_data_in),
        .nl_dpe_control(ws_exp_nl_dpe_control),
        .shift_add_control(ws_exp_MSB_SA_Ready),
        .w_buf_en(ws_exp_w_buf_en),
        .shift_add_bypass(1'b0),
        .load_output_reg(ws_exp_shift_add_done),
        .load_input_reg(1'b0),
        .MSB_SA_Ready(ws_exp_MSB_SA_Ready),
        .data_out(ws_exp_data_out),
        .dpe_done(ws_exp_dpe_done),
        .reg_full(ws_exp_reg_full),
        .shift_add_done(ws_exp_shift_add_done),
        .shift_add_bypass_ctrl(ws_exp_shift_add_bypass_ctrl)
        // Note: dpe_stub has weight_wen/weight_data/weight_row_addr/weight_col_addr
        // for TB preload; the arch-XML dpe hard block does NOT have those pins.
        // We leave them unconnected so VTR synthesis works; TB preloads weights
        // directly via hierarchical memory access (dut.X.dpe.weights[i][j]=...).
    );
    assign ws_exp_valid_n = ws_exp_dpe_done;

    assign ws_exp_data_in = ws_log_sum;  // packed log_attn + V
    assign ws_exp_valid = (ws_state == WS_EXP_FEED);
    assign ws_exp_ready_n = 1'b0;

    // Streaming reduction (7-level adder tree flattened over drain cycles)
    reg ws_acc_clear;
    reg [15:0] ws_col_counter;
    reg [31:0] ws_accumulator;
    wire [31:0] ws_masked_byte_sum;
    assign ws_masked_byte_sum = ((ws_col_counter + 0 < N) ? {24'b0, ws_exp_data_out[0*8 +: 8]} : 32'd0) + ((ws_col_counter + 1 < N) ? {24'b0, ws_exp_data_out[1*8 +: 8]} : 32'd0) + ((ws_col_counter + 2 < N) ? {24'b0, ws_exp_data_out[2*8 +: 8]} : 32'd0) + ((ws_col_counter + 3 < N) ? {24'b0, ws_exp_data_out[3*8 +: 8]} : 32'd0) + ((ws_col_counter + 4 < N) ? {24'b0, ws_exp_data_out[4*8 +: 8]} : 32'd0);
    always @(posedge clk) begin
        if (rst || ws_acc_clear) begin
            ws_accumulator <= 0; ws_col_counter <= 0;
        end else if (ws_exp_valid_n) begin
            ws_accumulator <= ws_accumulator + ws_masked_byte_sum;
            ws_col_counter <= ws_col_counter + 5;
        end
    end

    reg ws_dpe_output_done;
    reg [15:0] ws_dpe_out_count;
    always @(posedge clk) begin
        if (rst || ws_acc_clear) begin
            ws_dpe_out_count <= 0; ws_dpe_output_done <= 0;
        end else if (ws_exp_valid_n) begin
            ws_dpe_out_count <= ws_dpe_out_count + 1;
            if (ws_dpe_out_count + 1 >= PACKED_N) ws_dpe_output_done <= 1;
        end
    end

    reg [ADDR_WIDTH-1:0] out_write_addr, out_read_addr;
    reg out_w_en;
    reg [DATA_WIDTH-1:0] out_write_data;
    wire [DATA_WIDTH-1:0] out_sram_out;
    sram #(.N_CHANNELS(1),.DATA_WIDTH(DATA_WIDTH),.DEPTH(65))
    out_sram (.clk(clk),.rst(rst),.w_en(out_w_en),.r_addr(out_read_addr),
              .w_addr(out_write_addr),.sram_data_in(out_write_data),.sram_data_out(out_sram_out));

    localparam WS_IDLE       = 4'd0,
               WS_LOAD_A     = 4'd1,
               WS_LOAD_V     = 4'd2,
               WS_LOG_FEED   = 4'd3,
               WS_LOG_DRAIN  = 4'd4,
               WS_OUTPUT     = 4'd5,
               WS_EXP_FEED   = 4'd6,
               WS_EXP_DRAIN  = 4'd7,
               WS_WRITE      = 4'd8;
    reg [3:0] ws_state;
    reg [5-1:0] ws_feed_count;  // packed word counter (0..PACKED_N+1)
    reg [6-1:0]  ws_m;           // output column index

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            ws_state <= WS_IDLE; ws_feed_count <= 0;
            ws_m <= LANE_IDX * M_PER_LANE;
            attn_write_addr <= 0; attn_read_addr <= 0; attn_w_en <= 0;
            v_write_addr <= 0; v_read_addr <= 0; v_w_en <= 0;
            out_write_addr <= 0; out_read_addr <= 0; out_w_en <= 0;
            out_write_data <= 0;
            log_attn_read_addr <= 0;
            ws_acc_clear <= 0;
        end else begin
            attn_w_en <= 0; v_w_en <= 0; out_w_en <= 0;
            ws_acc_clear <= 0;
            case (ws_state)
                WS_IDLE: if (valid_attn || valid_v) ws_state <= WS_LOAD_A;
                WS_LOAD_A: begin
                    if (valid_attn) begin attn_w_en <= 1; attn_write_addr <= attn_write_addr + 1; end
                    if (attn_write_addr > 0) attn_read_addr <= attn_write_addr - 1;
                    if (attn_write_addr == (N/W) - 1) ws_state <= WS_LOAD_V;
                end
                WS_LOAD_V: begin
                    if (valid_v) begin v_w_en <= 1; v_write_addr <= v_write_addr + 1; end
                    if (v_write_addr == d*PACKED_N - 1) ws_state <= WS_LOG_FEED;
                end
                WS_LOG_FEED: begin
                    attn_read_addr <= (N/W) - 1;
                    ws_state <= WS_LOG_DRAIN;
                end
                WS_LOG_DRAIN: begin
                    ws_state <= WS_EXP_FEED;
                    ws_feed_count <= 0;
                end
                WS_EXP_FEED: begin
                    if (ws_feed_count < PACKED_N) begin
                        log_attn_read_addr <= ws_feed_count;
                        v_read_addr <= ws_m * PACKED_N + ws_feed_count;
                    end
                    ws_feed_count <= ws_feed_count + 1;
                    if (ws_feed_count == PACKED_N - 1) begin
                        ws_feed_count <= 0;
                        ws_state <= WS_EXP_DRAIN;
                    end
                end
                WS_EXP_DRAIN: begin
                    if (ws_dpe_output_done && ws_exp_MSB_SA_Ready) begin
                        out_write_data <= {32'b0, ws_accumulator[7:0]};
                        out_w_en <= 1; out_write_addr <= ws_m;
                        ws_acc_clear <= 1;
                        // Fused WS_WRITE: commit and advance m in the same cycle
                        if (ws_m == (LANE_IDX + 1) * M_PER_LANE - 1) begin
                            ws_state <= WS_OUTPUT;
                        end else begin
                            ws_m <= ws_m + 1;
                            ws_state <= WS_EXP_FEED;
                        end
                    end
                end
                WS_WRITE: begin  // vestigial — kept for 4-bit decoder completeness
                    ws_state <= WS_EXP_FEED;
                end
                WS_OUTPUT: if (ready_n) out_read_addr <= out_read_addr + 1;
            endcase
        end
    end

    assign data_out = out_sram_out;
    assign valid_n = (ws_state == WS_OUTPUT);
    assign ready_attn = (ws_state == WS_LOAD_A || ws_state == WS_IDLE);
    assign ready_v = (ws_state == WS_LOAD_V || ws_state == WS_IDLE);
endmodule

// ════ Supporting modules ════

module conv_layer_single_dpe #(
    parameter N_CHANNELS = 1,
    parameter ADDR_WIDTH = 9,
    parameter N_KERNELS = 1,
    parameter KERNEL_WIDTH = 5,
    parameter KERNEL_HEIGHT = 5,
    parameter W = 32,
    parameter H = 32,
    parameter S = 1,
    parameter DEPTH = 512,
    parameter DATA_WIDTH = 40

)(
    input wire clk,
    input wire rst,
    input wire valid,
    input wire ready_n,
    input wire [(N_CHANNELS*DATA_WIDTH)-1:0] data_in,
    output wire [(N_KERNELS*DATA_WIDTH)-1:0] data_out,
    output wire ready,
    output wire valid_n
);

    // Internal signals
    wire MSB_SA_Ready;
    wire dpe_done;
    wire reg_full;
    wire reg_empty;
    wire shift_add_done;
    wire shift_add_bypass_ctrl;
    wire [ADDR_WIDTH-1:0] read_address;
    wire [ADDR_WIDTH-1:0] write_address;
    wire w_buf_en;
    wire [1:0] nl_dpe_control;
    wire shift_add_control;
    wire shift_add_bypass;
    wire load_output_reg;
    wire w_en;
    wire load_input_reg;
    wire [DATA_WIDTH-1:0] sram_data_out;

    // Instantiate the SRAM module (DATA_WIDTH propagated from parent)
    sram #(
        .N_CHANNELS(1),
        .DEPTH(512),
        .DATA_WIDTH(DATA_WIDTH)
    ) sram_inst (
        .clk(clk),
		.rst(rst),
        .w_en(w_en),
        .r_addr(read_address),
        .w_addr(write_address),
        .sram_data_in(data_in),
        .sram_data_out(sram_data_out)
    );

    // Instantiate the DPE module (16-bit direct, no zero padding)
    dpe dpe_inst (
        .clk(clk),
        .reset(rst),
        .data_in(sram_data_out),
        .nl_dpe_control(nl_dpe_control),
        .shift_add_control(shift_add_control),
        .w_buf_en(w_buf_en),
        .shift_add_bypass(shift_add_bypass),
        .load_output_reg(load_output_reg),
        .load_input_reg(load_input_reg),
        .MSB_SA_Ready(MSB_SA_Ready),
        .data_out(data_out),
        .dpe_done(dpe_done),
        .reg_full(reg_full),
        .shift_add_done(shift_add_done),
        .shift_add_bypass_ctrl(shift_add_bypass_ctrl)
    );

    // Instantiate the Controller module
    conv_controller #(
        .N_CHANNELS(N_CHANNELS),
        .ADDR_WIDTH(ADDR_WIDTH),
        .N_KERNELS(N_KERNELS),
        .KERNEL_WIDTH(KERNEL_WIDTH),
        .KERNEL_HEIGHT(KERNEL_HEIGHT),
        .W(W),
        .H(H),
        .S(S)
    ) controller_inst (
        .clk(clk),
        .rst(rst),
        .MSB_SA_Ready(MSB_SA_Ready),
        .valid(valid),
        .ready_n(ready_n),
        .dpe_done(dpe_done),
        .reg_full(reg_full),
        .shift_add_done(shift_add_done),
        .shift_add_bypass_ctrl(shift_add_bypass_ctrl),
        .read_address(read_address),
        .write_address(write_address),
        .w_buf_en(w_buf_en),
        .nl_dpe_control(nl_dpe_control),
        .shift_add_control(shift_add_control),
        .shift_add_bypass(shift_add_bypass),
        .load_output_reg(load_output_reg),
        .w_en(w_en),
        .load_input_reg(load_input_reg),
        .ready(ready),
        .valid_n(valid_n)
    );

endmodule


module conv_controller #(
    parameter N_CHANNELS = 1,
    parameter ADDR_WIDTH = 9,
    parameter N_KERNELS = 1,
    parameter KERNEL_WIDTH = 5,
    parameter KERNEL_HEIGHT = 5,
    parameter W = 32,
    parameter H = 32,
    parameter S = 1,
    parameter B_ADDR_WIDTH = $clog2(KERNEL_WIDTH * KERNEL_HEIGHT),
    parameter S_BITWIDTH = S,
    parameter KW_BITWIDTH = $clog2(KERNEL_WIDTH),
    parameter KH_BITWIDTH = $clog2(KERNEL_HEIGHT)
)(
    input wire clk,
    input wire rst,
    input wire MSB_SA_Ready,
    input wire valid,
    input wire ready_n,
    input wire dpe_done,
    input wire reg_full,
    input wire shift_add_done,
    input wire shift_add_bypass_ctrl,
    output reg [ADDR_WIDTH-1:0] read_address,
    output reg [ADDR_WIDTH-1:0] write_address,
    output reg w_buf_en,
    output reg [1:0] nl_dpe_control,
    output reg shift_add_control,
    output reg shift_add_bypass,
    output reg load_output_reg,
    output reg w_en,
    output wire load_input_reg,
    output reg ready,
    output reg valid_n
);

    reg [ADDR_WIDTH-1:0] write_address_reg, read_address_reg;
    wire buf_load, busy;
    reg memory_flag;
    reg stall;
    reg memory_stall;
    reg dpe_exec_signal;
    reg [ADDR_WIDTH-1:0] next_address;

    reg [S_BITWIDTH-1:0] s, sv;
    reg [KW_BITWIDTH-1:0] n;
    reg [KH_BITWIDTH-1:0] m;
    reg [ADDR_WIDTH-1:0] pointer_offset;

    // always block for sram control
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            write_address_reg <= {ADDR_WIDTH{1'b0}};
            w_en <= 1'b0;
            w_buf_en <= 0;
            next_address <= {ADDR_WIDTH{1'b0}};
            pointer_offset <= 0;
            sv <= 0;
            s <= 0;
            n <= 0;
            m <= 0;
        end else begin
            if (valid && ~memory_stall) begin
                write_address_reg <= write_address_reg + 1;
                w_en <= 1'b1;
            end else begin
                w_en <= 1'b0;
            end

            if (~reg_full && ready_n && memory_flag) begin
                pointer_offset <= n + W * (m + sv) + s * S;
                if (n < KERNEL_WIDTH-1) begin
                    n <= n + 1;
                end else begin
                    n <= 0;
                    if (m < KERNEL_HEIGHT-1) begin
                        m <= m + 1;
                    end else begin
                        m <= 0;
                        if (s < W - KERNEL_WIDTH + S - 1) begin
                            s <= s + 1;
                        end else begin
                            s <= 0;
                            if (sv < H - KERNEL_HEIGHT + S - 1) begin
                                sv <= sv + 1;
                            end else begin
                                sv <= 0;
                            end
                        end
                    end
                end
                w_buf_en <= 1;
            end else begin
                w_buf_en <= 0;
            end
        end
    end

    always @* begin
        read_address_reg <= pointer_offset;
    end

    always @* begin
        if ((write_address_reg > read_address_reg) ||
            ((write_address_reg == {ADDR_WIDTH{1'b0}}) && (read_address_reg == {ADDR_WIDTH{1'b1}}))) begin
            memory_flag <= 1;
        end else begin
            memory_flag <= 0;
        end
    end

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            dpe_exec_signal <= 1'b0;
        end else begin
            if (reg_full) begin
                dpe_exec_signal <= 1'b1;
            end else begin
                dpe_exec_signal <= 1'b0;
            end
        end
    end

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            nl_dpe_control <= 2'b0;
        end else begin
            if (dpe_exec_signal) begin
                nl_dpe_control <= 2'b11;
            end else begin
                nl_dpe_control <= 2'b00;
            end
        end
    end

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            valid_n <= 1'b0;
            ready <= 1'b0;
            stall <= 0;
            memory_stall <= 0;
        end else begin
            if ((read_address_reg < write_address_reg - 2) && (write_address_reg == {ADDR_WIDTH{1'b1}})) begin
                memory_stall <= 1;
            end else begin
                memory_stall <= 0;
            end

            if (memory_stall) begin
                ready <= 1'b0;
            end else begin
                ready <= 1'b1;
            end

            if (dpe_done) begin
                valid_n <= 1;
            end else begin
                valid_n <= 0;
            end

            if (ready_n) begin
                stall <= 0;
            end else begin
                stall <= 1;
            end
        end
    end

    always @* begin
        read_address <= read_address_reg;
        write_address <= write_address_reg;
        shift_add_bypass <= shift_add_bypass_ctrl;
        shift_add_control <= MSB_SA_Ready;
        load_output_reg <= shift_add_done;
    end

    assign load_input_reg = reg_full;
    assign busy = ~MSB_SA_Ready;

endmodule


module sram #(
    parameter N_CHANNELS = 1,
    parameter DATA_WIDTH = 40*N_CHANNELS,  // Data width (default: 16 bits) 16 x number of channels
    parameter DEPTH = 512       // Memory depth (default: 512)

)(
    input wire clk,
    input wire w_en,
	input wire rst,
    input wire [$clog2(DEPTH)-1:0] r_addr,
    input wire [$clog2(DEPTH)-1:0] w_addr,
    input wire [DATA_WIDTH-1:0] sram_data_in,
    output reg [DATA_WIDTH-1:0] sram_data_out
);

    // Memory array with parameterized depth and width
    reg [DATA_WIDTH-1:0] mem [DEPTH-1:0];

    // Read/Write operations
    always @(posedge clk) begin
        if (rst) begin
            sram_data_out <= {DATA_WIDTH{1'b0}};
        end else begin
            sram_data_out <= mem[r_addr];
        end
    end
    always @(posedge clk) begin
            if (w_en) begin
                mem[w_addr] <= sram_data_in;
            end
    end

endmodule


module global_controller #(
    parameter N_Layers = 1
)(
    input wire clk,
    input wire rst,
    input wire ready_L1,
    input wire valid_Ln,
    input wire valid,
    output reg ready,
    output reg valid_L1,
    output reg ready_Ln
);

    wire busy;
    reg stall;

    // valid and ready control
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            stall <= 0;
        end else begin

            if (stall) begin
                ready_Ln <= 1'b0;
            end else begin
                ready_Ln <= 1'b1;
            end

            if(~valid) begin
                stall <= 0;
            end else begin
                stall <= 1;
            end
        end
    end

    always @* begin
        ready <= ready_L1;
        valid_L1 <= valid;
    end

endmodule


module controller_scalable #(
    parameter N_CHANNELS = 1,
    parameter N_BRAM_R = 4,
    parameter N_BRAM_W = 8,
    parameter N_DPE_V = 2,
    parameter N_DPE_H = 16,
    parameter ADDR_WIDTH = 10,
    parameter N_KERNELS = 6,
    parameter KERNEL_WIDTH = 5,
    parameter KERNEL_HEIGHT = 5,
    parameter W = 32,
    parameter H = 32,
    parameter S = 1,
    parameter B_ADDR_WIDTH = $clog2(KERNEL_WIDTH * KERNEL_HEIGHT),
    parameter S_BITWIDTH = S,
    parameter KW_BITWIDTH = $clog2(KERNEL_WIDTH),
    parameter KH_BITWIDTH = $clog2(KERNEL_HEIGHT)
)(
    // Clock and reset
    input wire clk,
    input wire rst,

    // Control inputs
    input wire MSB_SA_Ready,
    input wire valid,
    input wire ready_n,
    input wire dpe_done,
    input wire [N_DPE_V-1:0] reg_full,
    input wire [N_DPE_H-1:0] reg_empty,
    input wire shift_add_done,
    input wire shift_add_bypass_ctrl,
    input wire dpe_accum_done,

    // Memory interface
    output reg [ADDR_WIDTH-1:0] read_address,
    output reg [ADDR_WIDTH-1:0] write_address,
    output wire [(N_BRAM_W)-1:0] w_en_dec,

    // DPE control outputs
    output reg [N_DPE_V-1:0] w_buf_en,
    output reg [1:0] nl_dpe_control,
    output reg shift_add_control,
    output reg shift_add_bypass,
    output reg load_output_reg,
    output wire load_input_reg,
    output reg [$clog2(N_DPE_V)-1:0] dpe_sel,
    output reg [$clog2(N_DPE_H)-1:0] dpe_sel_h,

    // Status signals
    output reg ready,
    output reg valid_n,
    output reg dpe_accum_ready
);
    // Local parameters
    localparam VR_ADDR_WIDTH = $clog2(N_BRAM_R) + ADDR_WIDTH;
    localparam VW_ADDR_WIDTH = $clog2(N_BRAM_W) + ADDR_WIDTH;
    localparam N_DPE_SEL_V = (N_DPE_V > 1) ? $clog2(N_DPE_V) : 1;
    localparam N_DPE_SEL_H = $clog2(N_DPE_H);

    // Internal registers
    reg w_en;
    reg [VW_ADDR_WIDTH-1:0] write_address_reg;
    reg [VR_ADDR_WIDTH-1:0] read_address_reg;
    reg [$clog2(N_DPE_H)-1:0] dpe_h_count;
    reg [$clog2(N_DPE_V)-1:0] dpe_v_count;
    reg memory_flag;
    reg stall;
    reg memory_stall;
    reg dpe_exec_signal;
    reg [VW_ADDR_WIDTH-1:0] next_address;

    // Address generation registers
    reg [S_BITWIDTH-1:0] s, sv;
    reg [KW_BITWIDTH-1:0] n;
    reg [KH_BITWIDTH-1:0] m;
    reg [VR_ADDR_WIDTH-1:0] pointer_offset;

    // Bank select registers
    reg [N_BRAM_W-1:0] w_dec;
    reg [N_BRAM_R-1:0] r_dec;

    // Internal wires
    wire busy;

    // SRAM control logic
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            w_en <= 1'b0;
            w_buf_en <= 0;
            next_address <= {VW_ADDR_WIDTH{1'b0}};
            pointer_offset <= 0;
            sv <= 0;
            s <= 0;
            n <= 0;
            m <= 0;
        end else begin
            if (valid && ~memory_stall) begin
                next_address <= next_address + 1;
                w_en <= 1'b1;
            end else begin
                w_en <= 0;
            end

            if (~(&reg_full) && ready_n && memory_flag) begin
                pointer_offset <= n + W * (m + sv) + s * S;
                if (n < KERNEL_WIDTH-1) begin
                    n <= n + 1;
                end else begin
                    n <= 0;
                    if (m < KERNEL_HEIGHT-1) begin
                        m <= m + 1;
                    end else begin
                        m <= 0;
                        if (s < W - KERNEL_WIDTH + S - 1) begin
                            s <= s + 1;
                        end else begin
                            s <= 0;
                            if (sv < H - KERNEL_HEIGHT + S - 1) begin
                                sv <= sv + 1;
                            end else begin
                                sv <= 0;
                            end
                        end
                    end
                end
                w_buf_en <= 1<<dpe_v_count;
            end else begin
                w_buf_en <= 0;
            end
        end
    end

    // Address assignment
    always @* begin
        read_address_reg = pointer_offset;
        write_address_reg = next_address;
    end

    // Memory flag logic
    always @* begin
        if ((write_address_reg > read_address_reg) ||
            ((write_address_reg == {VW_ADDR_WIDTH{1'b0}}) && (read_address_reg == {VR_ADDR_WIDTH{1'b1}}))) begin
            memory_flag = 1;
        end else begin
            memory_flag = 0;
        end
    end

    // DPE execution control
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            dpe_exec_signal <= 1'b0;
        end else begin
            if (&reg_full) begin
                dpe_exec_signal <= 1'b1;
            end else begin
                dpe_exec_signal <= 1'b0;
            end
        end
    end

    // DPE control logic
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            nl_dpe_control <= 2'b0;
        end else begin
            if (dpe_exec_signal) begin
                nl_dpe_control <= 2'b11;
            end else begin
                nl_dpe_control <= 2'b00;
            end
        end
    end

    // Status control
    always @(posedge clk or posedge rst) begin
        if (rst) begin
            valid_n <= 1'b0;
            ready <= 1'b0;
            stall <= 0;
            memory_stall <= 0;
        end else begin
            if ((read_address_reg < write_address_reg - 2) && (write_address_reg == {VW_ADDR_WIDTH{1'b1}})) begin
                memory_stall <= 1;
            end else begin
                memory_stall <= 0;
            end

            if (memory_stall) begin
                ready <= 1'b0;
            end else begin
                ready <= 1'b1;
            end

            if (dpe_done) begin
                valid_n <= 1;
            end else begin
                valid_n <= 0;
            end

            if (ready_n) begin
                stall <= 0;
            end else begin
                stall <= 1;
            end
        end
    end

    // Priority encoder for reg_full
    integer v_bit;
    always @* begin
        dpe_v_count = {N_DPE_SEL_V{1'b0}};  // Default output is 0

        for (v_bit = N_DPE_V-1; v_bit >= 0; v_bit = v_bit - 1) begin
            if (reg_full[v_bit]) begin
                // Properly convert integer to the correct bit width
                dpe_v_count = v_bit + 1;
            end
        end
    end

    // Priority encoder for reg_empty
    integer h_bit;
    always @* begin
        dpe_h_count = {N_DPE_SEL_H{1'b0}};  // Default output is 0

        for (h_bit = 0; h_bit < N_DPE_H; h_bit = h_bit + 1) begin
            if (reg_empty[h_bit]) begin
                // Properly convert integer to the correct bit width
                dpe_h_count = h_bit + 1;
            end
        end
    end

    // Output assignments
    always @* begin
        read_address = read_address_reg[ADDR_WIDTH-1:0];
        write_address = write_address_reg[ADDR_WIDTH-1:0];
        dpe_sel = dpe_v_count;
        dpe_sel_h = dpe_h_count;
        shift_add_bypass = shift_add_bypass_ctrl;
        shift_add_control = MSB_SA_Ready;
        dpe_accum_ready = shift_add_done;
        load_output_reg = dpe_accum_done;

        // Fixed bank selection logic using proper bit ranges
        w_dec = {N_BRAM_W{1'b0}};
        r_dec = {N_BRAM_R{1'b0}};

        // Only perform shift if index is within valid range
        if (N_BRAM_W > 1) begin
            if (write_address_reg[VW_ADDR_WIDTH-1:ADDR_WIDTH] < N_BRAM_W) begin
                w_dec = 1'b1 << write_address_reg[VW_ADDR_WIDTH-1:ADDR_WIDTH];
            end
        end
        else begin
            w_dec = 1'b1 << write_address_reg[ADDR_WIDTH];
        end

        if (N_BRAM_R > 1) begin
            if (read_address_reg[VR_ADDR_WIDTH-1:ADDR_WIDTH] < N_BRAM_R) begin
                r_dec = 1'b1 << read_address_reg[VR_ADDR_WIDTH-1:ADDR_WIDTH];
            end
        end
        else begin
            r_dec = 1'b1 << write_address_reg[ADDR_WIDTH];
        end
    end

    // Output assignments
    assign w_en_dec = w_dec & {N_BRAM_W{w_en}};
    assign load_input_reg = reg_full;
    assign busy = ~MSB_SA_Ready;

endmodule


module xbar_ip_module #(
    parameter DATA_WIDTH = 40,
    parameter NUM_INPUTS = 1,
    parameter NUM_OUTPUTS = 4,
    // Derived parameters to handle special cases
    parameter IN_SEL_WIDTH = (NUM_INPUTS <= 1) ? 1 : $clog2(NUM_INPUTS),
    parameter OUT_SEL_WIDTH = (NUM_OUTPUTS <= 1) ? 1 : $clog2(NUM_OUTPUTS)
)(
    input  wire [NUM_INPUTS*DATA_WIDTH-1:0]  in_data,
    input  wire [IN_SEL_WIDTH-1:0]           in_sel,
    input  wire [OUT_SEL_WIDTH-1:0]          out_sel,
    output wire [NUM_OUTPUTS*DATA_WIDTH-1:0] out_data
);

    // Generate appropriate implementation based on parameters
    generate
        // Case 1: Both inputs and outputs > 1 (full crossbar)
        if (NUM_INPUTS > 1 && NUM_OUTPUTS > 1) begin : full_crossbar
            reg [NUM_OUTPUTS*DATA_WIDTH-1:0] out_data_reg;

            integer i, j;
            reg [DATA_WIDTH-1:0] in_data_arr [NUM_INPUTS-1:0];
            reg [DATA_WIDTH-1:0] out_data_arr [NUM_OUTPUTS-1:0];

            always @(*) begin
                // Unpack input data
                for (i = 0; i < NUM_INPUTS; i = i + 1) begin
                    in_data_arr[i] = in_data[i*DATA_WIDTH +: DATA_WIDTH];
                end

                // Default outputs to zero
                for (j = 0; j < NUM_OUTPUTS; j = j + 1) begin
                    out_data_arr[j] = {DATA_WIDTH{1'b0}};
                end

                // Route data based on selectors
                for (j = 0; j < NUM_OUTPUTS; j = j + 1) begin
                    for (i = 0; i < NUM_INPUTS; i = i + 1) begin
                        if ((in_sel == i) && (out_sel == j)) begin
                            out_data_arr[j] = in_data_arr[i];
                        end
                    end
                end

                // Pack output data
                for (j = 0; j < NUM_OUTPUTS; j = j + 1) begin
                    out_data_reg[j*DATA_WIDTH +: DATA_WIDTH] = out_data_arr[j];
                end
            end

            assign out_data = out_data_reg;
        end

        // Case 2: Single input, multiple outputs (fan-out)
        else if (NUM_INPUTS == 1 && NUM_OUTPUTS > 1) begin : single_input_multi_output
            wire [DATA_WIDTH-1:0] input_data = in_data[DATA_WIDTH-1:0];
            reg [NUM_OUTPUTS*DATA_WIDTH-1:0] out_data_reg;

            always @(*) begin
                // Default all outputs to 0
                out_data_reg = {NUM_OUTPUTS*DATA_WIDTH{1'b0}};

                // Send input data to selected output
                if (out_sel < NUM_OUTPUTS) begin
                    out_data_reg[out_sel*DATA_WIDTH +: DATA_WIDTH] = input_data;
                end
            end

            assign out_data = out_data_reg;
        end

        // Case 3: Multiple inputs, single output (multiplexer)
        else if (NUM_INPUTS > 1 && NUM_OUTPUTS == 1) begin : multi_input_single_output
            reg [DATA_WIDTH-1:0] out_data_reg;

            always @(*) begin
                // Default output to 0
                out_data_reg = {DATA_WIDTH{1'b0}};

                // Select from inputs
                if (in_sel < NUM_INPUTS) begin
                    out_data_reg = in_data[in_sel*DATA_WIDTH +: DATA_WIDTH];
                end
            end

            assign out_data = out_data_reg;
        end

        // Case 4: Single input, single output (direct connection)
        else begin : single_input_single_output
            // Just pass through - selectors are ignored
            assign out_data = in_data;
        end
    endgenerate

endmodule
